-- =====================================================================
-- 출고 웨이브 편성 반영 delta (PostgreSQL / Supabase)
--   원본: docs/migration-outb-wave.sql (Oracle DDL). 타입/문법만 변환한 파생 파일.
--   ddl-auto=validate 이므로 앱 부팅 전에 먼저 적용해야 한다.
--   기준 문서(docs/postgres/schema.sql)에는 이미 반영됨 — 이 파일은 기존 DB용 증분.
-- =====================================================================

-- 1) 출고번호 채번 시퀀스 (기존 스키마에 누락돼 있던 것 — OutbOrderService가 사용)
CREATE SEQUENCE outb_no_seq START WITH 1 INCREMENT BY 1;

-- 2) 출고 웨이브 테이블 + 채번 시퀀스
CREATE TABLE outb_wave (
    outb_wave_id BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wave_no      VARCHAR(30)    NOT NULL,
    status       VARCHAR(15)    NOT NULL,
    released_at  TIMESTAMP,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_wave_no UNIQUE (wave_no),
    CONSTRAINT ck_outb_wave_status CHECK (status IN ('PLANNED', 'RELEASED'))
);

CREATE SEQUENCE outb_wave_no_seq START WITH 1 INCREMENT BY 1;

-- 3) 출고 주문에 wave_id 추가 (nullable — 미편성 허용)
ALTER TABLE outb_order ADD COLUMN wave_id BIGINT;
ALTER TABLE outb_order ADD CONSTRAINT fk_outb_order_wave
    FOREIGN KEY (wave_id) REFERENCES outb_wave (outb_wave_id);
CREATE INDEX ix_outb_order_wave ON outb_order (wave_id);

-- 4) 출고 스테이징 로케이션 (피킹/확정 2단계 모델에서 사용 — 온도대는 플레이스홀더)
INSERT INTO loc (loc_cd, zone_cd, temp_zone, loc_type, pick_prty)
    VALUES ('SHIP-STAGE', 'SHIP-STAGE', 'DRY', 'STAGE', 0);

COMMIT;
