-- =====================================================================
-- 증분 마이그레이션: 전략 시스템 1차 — 검수 제약 · 적치 전략 테이블 6개 신설
--   대상: migration-catchup-to-schema.sql 까지 적용된 라이브 DB → docs/schema.sql 상태
--   근거: docs/st/전략_테이블설계서.md (컬럼 명세) · docs/st/전략_테이블설계안.md (결정 D1~D8)
--
--   재실행 안전: 모든 생성에 IF NOT EXISTS / 존재 확인을 건다.
--   BEGIN/COMMIT 없이 DO 블록 하나다 — DBeaver에서 실패 시 죽은 트랜잭션(25P02)이
--   연결에 남지 않게 하기 위함 (CLAUDE.md 「데이터베이스」).
--
--   시드 없음 — 전략은 관리자가 화면에서 만든다. 채번 규칙 없음 — 업무 번호 없는 대리키.
--   putaway_task 연결 컬럼은 1차 보류 (현행 코드가 putaway_task를 쓰지 않는다 —
--   docs/st/전략_테이블설계서.md 머리말).
-- =====================================================================

DO $mig$
BEGIN

    -- 1. 전략 리비전 (공용)
    CREATE TABLE IF NOT EXISTS stgy_rvsn (
        stgy_rvsn_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stgy_typ     VARCHAR(10)  NOT NULL,
        stgy_id      BIGINT       NOT NULL,
        rvsn_no      BIGINT       NOT NULL,
        snpsht       JSONB        NOT NULL,
        created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
        updated_at   TIMESTAMP,
        updated_by   VARCHAR(30),
        CONSTRAINT uq_stgy_rvsn UNIQUE (stgy_typ, stgy_id, rvsn_no),
        CONSTRAINT ck_stgy_rvsn_typ CHECK (stgy_typ IN ('INSP', 'PTAWY', 'WAV', 'ALOC')),
        CONSTRAINT ck_stgy_rvsn_no CHECK (rvsn_no >= 1)
    );

    -- 2. 전략 실행 로그 (공용)
    CREATE TABLE IF NOT EXISTS stgy_exec_log (
        stgy_exec_log_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stgy_typ         VARCHAR(10) NOT NULL,
        stgy_id          BIGINT      NOT NULL,
        rvsn_no          BIGINT      NOT NULL,
        trgr_typ         VARCHAR(10) NOT NULL,
        tgt_ref          VARCHAR(30),
        rslt_smry        VARCHAR(200),
        dcsn_trc         JSONB,
        created_at       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_by       VARCHAR(30) DEFAULT 'admin' NOT NULL,
        updated_at       TIMESTAMP,
        updated_by       VARCHAR(30),
        CONSTRAINT ck_stgy_exec_log_typ  CHECK (stgy_typ IN ('INSP', 'PTAWY', 'WAV', 'ALOC')),
        CONSTRAINT ck_stgy_exec_log_trgr CHECK (trgr_typ IN ('MANUAL', 'AUTO', 'PREVIEW'))
    );
    CREATE INDEX IF NOT EXISTS ix_stgy_exec_log_stgy ON stgy_exec_log (stgy_typ, stgy_id, created_at);
    CREATE INDEX IF NOT EXISTS ix_stgy_exec_log_ref  ON stgy_exec_log (tgt_ref);

    -- 3. 검수 정책 헤더 (전역 1행 — 서비스 검증, D8)
    CREATE TABLE IF NOT EXISTS insp_plcy (
        insp_plcy_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stgy_nm      VARCHAR(100) NOT NULL,
        last_rvsn_no BIGINT       DEFAULT 1 NOT NULL,
        created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
        updated_at   TIMESTAMP,
        updated_by   VARCHAR(30)
    );

    -- 4. 검수 규칙
    CREATE TABLE IF NOT EXISTS insp_plcy_rule (
        insp_plcy_rule_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        insp_plcy_id      BIGINT      NOT NULL,
        srt_seq           INTEGER     DEFAULT 0 NOT NULL,
        rule_cd           VARCHAR(30) NOT NULL,
        para              JSONB       DEFAULT '{}' NOT NULL,
        created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
        updated_at        TIMESTAMP,
        updated_by        VARCHAR(30),
        CONSTRAINT uq_insp_plcy_rule UNIQUE (insp_plcy_id, rule_cd)
    );
    CREATE INDEX IF NOT EXISTS ix_insp_plcy_rule ON insp_plcy_rule (insp_plcy_id);

    -- 5. 적치 전략 헤더
    CREATE TABLE IF NOT EXISTS ptawy_stgy (
        ptawy_stgy_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stgy_nm       VARCHAR(100) NOT NULL,
        prty          INTEGER      DEFAULT 0 NOT NULL,
        tgt_cond      JSONB        DEFAULT '[]' NOT NULL,
        unt_splt_yn   BOOLEAN      DEFAULT FALSE NOT NULL,
        loc_srt       JSONB        DEFAULT '[]' NOT NULL,
        last_rvsn_no  BIGINT       DEFAULT 1 NOT NULL,
        created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_by    VARCHAR(30)  DEFAULT 'admin' NOT NULL,
        updated_at    TIMESTAMP,
        updated_by    VARCHAR(30),
        CONSTRAINT ck_ptawy_stgy_prty CHECK (prty >= 0),
        CONSTRAINT ck_ptawy_stgy_tgt_cond CHECK (jsonb_typeof(tgt_cond) = 'array'),
        CONSTRAINT ck_ptawy_stgy_loc_srt  CHECK (jsonb_typeof(loc_srt) = 'array')
    );

    -- 6. 적치 단계
    CREATE TABLE IF NOT EXISTS ptawy_stgy_stg (
        ptawy_stgy_stg_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        ptawy_stgy_id     BIGINT      NOT NULL,
        srt_seq           INTEGER     NOT NULL,
        mthd_cd           VARCHAR(30) NOT NULL,
        mthd_para         JSONB       DEFAULT '{}' NOT NULL,
        line_cond         JSONB       DEFAULT '[]' NOT NULL,
        loc_cond          JSONB       DEFAULT '[]' NOT NULL,
        created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
        updated_at        TIMESTAMP,
        updated_by        VARCHAR(30),
        CONSTRAINT ck_ptawy_stg_line_cond CHECK (jsonb_typeof(line_cond) = 'array'),
        CONSTRAINT ck_ptawy_stg_loc_cond  CHECK (jsonb_typeof(loc_cond)  = 'array')
    );
    CREATE INDEX IF NOT EXISTS ix_ptawy_stgy_stg ON ptawy_stgy_stg (ptawy_stgy_id);

    -- 7. 코멘트 (재실행해도 무해 — 같은 값 덮어쓰기)
    COMMENT ON TABLE stgy_rvsn      IS '전략 리비전 스냅샷 (append-only). 전략 저장마다 1행 — created_*가 곧 저장 시각/저장자. 전략이 삭제돼도 남아 복원·감사의 근거가 된다';
    COMMENT ON TABLE stgy_exec_log  IS '전략 실행 로그. 검수 위반(=검수 저장 롤백) 시에도 남아야 하므로 기록은 REQUIRES_NEW 별도 트랜잭션. created_at = 실행 시각';
    COMMENT ON TABLE insp_plcy      IS '검수 정책 헤더 (전역 1행 — 서비스 검증). 검수 저장 직전 규칙 전부를 AND 평가, 위반 시 저장 전체 거부';
    COMMENT ON TABLE insp_plcy_rule IS '검수 규칙. 규칙 끄기 = 행 삭제 (D4 — 사용여부 컬럼 없음). 삭제 전 구성은 정책 리비전 스냅샷이 보유';
    COMMENT ON TABLE ptawy_stgy     IS '적치 전략 헤더. 1차에서 전략은 추천만 한다 — 실행은 기존 즉시 MOVE 흐름 유지 (docs/st/전략_프로세스정의서.md §3)';
    COMMENT ON TABLE ptawy_stgy_stg IS '적치 단계. srt_seq 순으로 시도, 잔여수량이 0이 되면 종료. "단계 0건 전략" 저장 거부는 서비스 검증(자식 행 존재는 CHECK 범위 밖)';

END
$mig$;
