-- =====================================================================
-- 자동발주 — 상품 거래처 마스터(발주점·상한·MOQ·리드타임) + 발주구분 ATO.
--
-- 현재 라이브 상태 → schema.sql 상태.
-- 근거: docs/design.md 「자동발주」. 매일 새벽 순재고가 발주점 아래인 상품을 벤더별로 묶어
--   작성(CREATED) 상태 입고주문으로 제안한다 — 확정(→ASN)은 사람이 누른다.
--   - prod_vndr: 상품×벤더. 발주점·발주 상한은 낱개(EA), 최소주문수량은 입고단위.
--   - ODR_DVSN에 ATO(자동발주) 추가 — 목록에서 사람이 낸 발주와 갈린다.
--
-- 실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--   - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--   - 재실행 안전 — 존재 확인을 걸어 이미 적용된 항목은 건너뛴다
-- =====================================================================
DO $mig$
BEGIN
    -- 1. prod_vndr ------------------------------------------------------------
    IF to_regclass('prod_vndr') IS NULL THEN
        CREATE TABLE prod_vndr (
            prod_vndr_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prod_id      BIGINT      NOT NULL,
            vendor_id    BIGINT      NOT NULL,
            min_qty      BIGINT      NOT NULL,
            max_qty      BIGINT      NOT NULL,
            min_odr_qty  BIGINT      DEFAULT 1 NOT NULL,
            lead_days    INTEGER     DEFAULT 1 NOT NULL,
            prty         INTEGER     DEFAULT 1 NOT NULL,
            created_at   TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by   VARCHAR(30) DEFAULT 'admin' NOT NULL,
            updated_at   TIMESTAMP,
            updated_by   VARCHAR(30),
            CONSTRAINT uq_prod_vndr UNIQUE (prod_id, vendor_id),
            CONSTRAINT ck_prod_vndr_qty CHECK (min_qty >= 0 AND max_qty >= 1 AND min_qty <= max_qty
                                               AND min_odr_qty >= 1 AND lead_days >= 0 AND prty >= 1)
        );

        COMMENT ON TABLE  prod_vndr IS '상품 거래처 마스터 (자동발주 기준)';
        COMMENT ON COLUMN prod_vndr.prod_id     IS '발주할 상품';
        COMMENT ON COLUMN prod_vndr.vendor_id   IS '공급 벤더';
        COMMENT ON COLUMN prod_vndr.min_qty     IS '발주점 (EA). 순재고가 이 아래면 발주 대상';
        COMMENT ON COLUMN prod_vndr.max_qty     IS '발주 상한 (EA). 여기까지 채우는 수량을 발주';
        COMMENT ON COLUMN prod_vndr.min_odr_qty IS '최소주문수량 (입고단위)';
        COMMENT ON COLUMN prod_vndr.lead_days   IS '리드타임 (일). 발주일 + 이 일수 = 입고 예정일';
        COMMENT ON COLUMN prod_vndr.prty        IS '대표 벤더 우선순위. 작을수록 우선';

        CREATE INDEX ix_prod_vndr_vendor ON prod_vndr (vendor_id);
        RAISE NOTICE 'prod_vndr 생성';
    ELSE
        RAISE NOTICE 'prod_vndr 이미 존재 — 건너뜀';
    END IF;

    -- 2. 발주구분 ATO ---------------------------------------------------------
    IF NOT EXISTS (SELECT 1 FROM code_detail WHERE grp_cd = 'ODR_DVSN' AND code_cd = 'ATO') THEN
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq)
        VALUES ('ODR_DVSN', 'ATO', '자동발주', 4);
        RAISE NOTICE 'ODR_DVSN/ATO 추가';
    ELSE
        RAISE NOTICE 'ODR_DVSN/ATO 이미 존재 — 건너뜀';
    END IF;

    RAISE NOTICE '자동발주 마이그레이션 완료';
END
$mig$;
