-- =====================================================================
-- 증분 마이그레이션: 전략 시스템 3차 — 출고 할당 전략
--   대상: migration-add-stgy-wave.sql 까지 적용된 라이브 DB → docs/schema.sql 상태
--
--   내용: ① aloc_stgy 신설  ② aloc_stgy_slot 신설  ③ outb_alloc에 전략 출처 2컬럼
--
--   재실행 안전: 모든 생성에 IF NOT EXISTS / 카탈로그 존재 확인을 건다.
--   BEGIN/COMMIT 없이 DO 블록 하나다 — DBeaver에서 실패 시 죽은 트랜잭션(25P02)이
--   연결에 남지 않게 하기 위함 (CLAUDE.md 「데이터베이스」).
--
--   stgy_rvsn·stgy_exec_log의 ck_*_typ는 1차에서 이미 'ALOC'을 포함하므로 손대지 않는다.
--   시드 없음 — 전략은 관리자가 화면에서 만든다. 채번 규칙도 없다(대리키 테이블).
--
--   기존 할당 행의 백필도 없다. outb_alloc의 두 컬럼이 NULL로 남는 것이 정확한 상태다 —
--   전략이 존재하지 않던 기간에 만들어진 할당이고, 「NULL = 전략 없이 만들어짐」이
--   수동할당과 같은 뜻이기 때문이다 (outb_order.wav_reg_typ을 MANUAL로 백필한 것과 다르다.
--   그쪽은 수동 편성이라는 사실이 확정적이었지만, 이쪽은 전략이 아예 없었다).
-- =====================================================================

DO $mig$
BEGIN

    -- 1. 할당 전략 헤더
    CREATE TABLE IF NOT EXISTS aloc_stgy (
        aloc_stgy_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stgy_nm      VARCHAR(100) NOT NULL,
        prty         INTEGER      DEFAULT 0 NOT NULL,
        tgt_cond     JSONB        DEFAULT '[]' NOT NULL,
        last_rvsn_no BIGINT       DEFAULT 1 NOT NULL,
        created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
        updated_at   TIMESTAMP,
        updated_by   VARCHAR(30),
        CONSTRAINT ck_aloc_stgy_prty     CHECK (prty >= 0),
        CONSTRAINT ck_aloc_stgy_tgt_cond CHECK (jsonb_typeof(tgt_cond) = 'array')
    );

    -- 2. 할당 슬롯 (적치 단계와 같은 판단으로 JSONB가 아니라 행)
    CREATE TABLE IF NOT EXISTS aloc_stgy_slot (
        aloc_stgy_slot_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        aloc_stgy_id      BIGINT      NOT NULL,
        slot_typ          VARCHAR(15) NOT NULL,
        srt_seq           INTEGER     DEFAULT 0 NOT NULL,
        cmpnt_cd          VARCHAR(30),
        para              JSONB       DEFAULT '{}' NOT NULL,
        cond              JSONB       DEFAULT '[]' NOT NULL,
        created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
        updated_at        TIMESTAMP,
        updated_by        VARCHAR(30),
        CONSTRAINT ck_aloc_slot_typ CHECK (
            slot_typ IN ('INVN_FLTR','RSTRCT','INVN_SRT','ODR_SRT','DSTRB')
        ),
        CONSTRAINT ck_aloc_slot_cmpnt CHECK (
            (slot_typ =  'INVN_FLTR' AND cmpnt_cd IS NULL)
         OR (slot_typ <> 'INVN_FLTR' AND cmpnt_cd IS NOT NULL)
        ),
        CONSTRAINT ck_aloc_slot_srt_seq CHECK (srt_seq >= 0),
        CONSTRAINT ck_aloc_slot_para    CHECK (jsonb_typeof(para) = 'object'),
        CONSTRAINT ck_aloc_slot_cond    CHECK (jsonb_typeof(cond) = 'array')
    );

    CREATE INDEX IF NOT EXISTS ix_aloc_stgy_slot ON aloc_stgy_slot (aloc_stgy_id);
    CREATE UNIQUE INDEX IF NOT EXISTS uq_aloc_stgy_slot_single ON aloc_stgy_slot (aloc_stgy_id, slot_typ)
        WHERE slot_typ IN ('INVN_SRT','ODR_SRT');

    -- 3. outb_alloc — 이 할당을 만든 전략·리비전. 둘 다 NULL = 수동할당 또는 전략 미설정
    ALTER TABLE outb_alloc ADD COLUMN IF NOT EXISTS aloc_stgy_id BIGINT;
    ALTER TABLE outb_alloc ADD COLUMN IF NOT EXISTS rvsn_no      BIGINT;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_outb_alloc_stgy') THEN
        ALTER TABLE outb_alloc ADD CONSTRAINT ck_outb_alloc_stgy
            CHECK ((aloc_stgy_id IS NULL) = (rvsn_no IS NULL));
    END IF;

    -- 4. 코멘트 (재실행해도 무해 — 같은 값 덮어쓰기)
    COMMENT ON TABLE  aloc_stgy IS '할당 전략. 자동할당이 어느 재고를 어떤 순서로 쓰고 모자라면 어떻게 나눌지를 정한다. 전략은 코드의 기본 동작을 슬롯 단위로 덮어쓰므로 필수 슬롯이 없고, 전략 0건이면 기본 동작(FEFO·점포 잔여수명·순차 소진)이 그대로 실행된다';
    COMMENT ON COLUMN aloc_stgy.stgy_nm      IS '전략명. 표시용 — 실행에 사용하지 않는다 (이름/정의 불일치는 미리보기가 보완)';
    COMMENT ON COLUMN aloc_stgy.prty         IS '선택 순서. 낮을수록 먼저 매칭 판정 — 실행 1회당 전략 1건이 확정된다. 동률은 aloc_stgy_id 순';
    COMMENT ON COLUMN aloc_stgy.tgt_cond     IS '적용대상 조건 [{fld,op,vals},…]. 원소끼리 AND, 빈 배열 = 전체 매칭 폴백. 대상 주문 "전부"가 만족해야 매칭이다. 필드: AlocTgtField enum — OUTB_TYP 출고유형 · VHCL_FLTNO 차량편수 (점포는 없다 — 한 웨이브에 여러 점포가 섞이는 것이 정상이라 전부-만족이 성립하지 않는다)';
    COMMENT ON COLUMN aloc_stgy.last_rvsn_no IS '마지막 저장 리비전';

    COMMENT ON TABLE  aloc_stgy_slot IS '할당 슬롯. 할당이 하는 일을 역할로 쪼갠 5종 — INVN_FLTR 재고위치(다중=계층) · RSTRCT 출고제약(다중) · INVN_SRT 재고정렬(단일) · ODR_SRT 주문순서(단일) · DSTRB 분배(다중=실행순서)';
    COMMENT ON COLUMN aloc_stgy_slot.aloc_stgy_id IS '할당 전략 헤더 (느슨한 참조, FK 없음)';
    COMMENT ON COLUMN aloc_stgy_slot.slot_typ     IS '슬롯 타입. 값 목록이 코드 구조 그 자체(AllocSlotTyp enum)라 공통코드가 아니라 CHECK로 고정한다 — status류와 같은 취급';
    COMMENT ON COLUMN aloc_stgy_slot.srt_seq      IS '다중 슬롯 안의 순서. INVN_FLTR은 후보 계층 순서(앞 계층부터 소진), DSTRB는 분배 실행 순서. 단일 슬롯에서는 무의미';
    COMMENT ON COLUMN aloc_stgy_slot.cmpnt_cd     IS '구현체 code (enum name — SHELF_LIFE_PCT · MULTI_SORT · SEQUENTIAL · RATIO · EQUAL). CHECK 없음: 구현체 추가로 DDL을 고치지 않기 위함이고 존재 검증은 저장 서비스가 한다. INVN_FLTR만 NULL';
    COMMENT ON COLUMN aloc_stgy_slot.para         IS '구현체 파라미터. MULTI_SORT는 {"criteria":[{"field","dir"},…]}, SHELF_LIFE_PCT는 {"basis":"STORE"} 또는 {"basis":"FIXED","minPct":40}';
    COMMENT ON COLUMN aloc_stgy_slot.cond         IS '조건 [{fld,op,vals},…] — 원소끼리 AND. INVN_FLTR은 계층 지정(존 업무유형 IN), DSTRB는 배분 대상 선별. 정렬·제약 슬롯은 쓰지 않는다. 마지막 DSTRB 슬롯의 조건이 비어 있어야 하는 검증은 저장 서비스 몫 — 조건 있는 슬롯으로 끝나면 어느 조건에도 안 걸린 라인이 재고를 두고도 0을 받는다';

    COMMENT ON COLUMN outb_alloc.aloc_stgy_id IS '이 할당을 만든 할당 전략 (느슨한 참조, FK 없음). NULL = 수동할당 또는 전략 미설정 기간의 기본 동작 할당. 같은 (라인,재고)에 합산될 때는 처음 값을 유지한다 — 나중 실행의 전략으로 덮어쓰면 이미 기록된 수량의 근거가 바뀐다';
    COMMENT ON COLUMN outb_alloc.rvsn_no      IS '할당에 사용된 전략 리비전. stgy_rvsn과 조합해 "그때의 정의"를 재구성한다 (P5)';

END
$mig$;
