-- =====================================================================
-- 재고 속성변경 도입 — lot_attr_chng(Lot 속성 정정 이력) + LOT_ATTR_RSN 공통코드.
--
-- 현재 라이브 상태(migration-inv-hld.sql·migration-inv-stktk.sql 적용) → schema.sql 상태.
-- 근거: docs/design.md 「Lot 속성 정정」 (2026-08-03 확정).
--   - 이 화면은 재고를 한 톨도 움직이지 않는다 — inv·inv_hist 무변경, 정정은 lot 행 UPDATE뿐.
--     따라서 이 마이그레이션은 기존 테이블을 하나도 건드리지 않는다(신규 테이블 + 코드 시드).
--   - 정정 대상은 lot.mfg_dt·expiry_dt 둘뿐. prod_id·lot_no·receipt_dt는 불변
--     (receipt_dt는 배치 재사용 키이자 lot_no의 근거라 바꾸면 번호와 어긋난다).
--   - 배치 재사용 키(상품+입고일자+제조일자) 충돌은 서비스가 막는다 —
--     uq_lot은 (prod_id, lot_no)에만 걸려 있어 DB가 잡아주지 않는다.
--   - 채번 없음: 어디서도 참조되지 않는 append-only 로그라 문서번호가 필요 없다.
--
-- 실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--   - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--   - 재실행 안전 — 존재 확인을 걸어 이미 적용된 항목은 건너뛴다
-- =====================================================================
DO $mig$
BEGIN
    -- 1. lot_attr_chng (Lot 속성 정정 이력) ---------------------------------
    IF to_regclass('lot_attr_chng') IS NULL THEN
        CREATE TABLE lot_attr_chng (
            lot_attr_chng_id BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            lot_id      BIGINT          NOT NULL,
            prod_id     BIGINT          NOT NULL,
            lot_no      VARCHAR(30)     NOT NULL,
            bfr_mfg_dt  DATE,
            aft_mfg_dt  DATE,
            bfr_expiry_dt DATE,
            aft_expiry_dt DATE,
            rsn_cd      VARCHAR(10)     NOT NULL,
            rsn_dscr    VARCHAR(200),
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT ck_lot_attr_chng_diff CHECK (
                bfr_mfg_dt IS DISTINCT FROM aft_mfg_dt OR bfr_expiry_dt IS DISTINCT FROM aft_expiry_dt
            ),
            CONSTRAINT ck_lot_attr_chng_dt CHECK (
                aft_mfg_dt IS NULL OR aft_expiry_dt IS NULL OR aft_expiry_dt >= aft_mfg_dt
            )
        );

        COMMENT ON TABLE  lot_attr_chng IS 'Lot 속성 정정 이력 (append-only 자기완결 로그). 재고 속성변경 화면이 남기는 유일한 원장 — 수량 변동이 없어 inv_hist에 실을 수 없다(보류 실적 테이블과 같은 예외 성격). 변경 이벤트당 1행이고 바뀌지 않은 필드도 전/후에 같은 값이 들어간다. 되돌리는 정정도 새 행이다(취소 경로 없음)';
        COMMENT ON COLUMN lot_attr_chng.lot_id        IS '정정 대상 Lot. lot 테이블 FK는 걸지 않는다 — inv_hist.ib_line_id와 같은 느슨한 참조';
        COMMENT ON COLUMN lot_attr_chng.prod_id       IS '대상 Lot의 상품. Lot이 상품을 함의하지만 단독 조회를 가능하게 담는다 (inv_hld·inv_mov_task와 같은 형태)';
        COMMENT ON COLUMN lot_attr_chng.lot_no        IS 'Lot 번호 스냅샷. lot_no는 정정 대상이 아니라 지금은 lot과 항상 같지만, 로그를 자기완결로 두는 원칙(보류 실적 선례)을 따른다';
        COMMENT ON COLUMN lot_attr_chng.bfr_mfg_dt    IS '제조일자 변경 전 값. 배치 재사용 키(상품+입고일자+제조일자)의 일부라 정정 시 다른 Lot과의 키 충돌을 서비스가 막는다 — uq_lot은 (prod_id, lot_no)에만 걸려 DB가 잡아주지 않는다';
        COMMENT ON COLUMN lot_attr_chng.aft_mfg_dt    IS '제조일자 변경 후 값. mfg_dt <= lot.receipt_dt 검증 대상 (검수의 「제조일자가 입고일자보다 미래일 수 없다」와 같은 규칙)';
        COMMENT ON COLUMN lot_attr_chng.bfr_expiry_dt IS '유통기한 변경 전 값';
        COMMENT ON COLUMN lot_attr_chng.aft_expiry_dt IS '유통기한 변경 후 값. 제조일자+shelf_life_days와 일치할 필요는 없다 — 벤더 인쇄값과 계산값이 다른 것이 이 화면의 주 사용처다. 정정 즉시 FEFO 정렬과 점포 잔여수명 필터에 반영되지만 이미 생성된 할당은 건드리지 않는다';
        COMMENT ON COLUMN lot_attr_chng.rsn_cd        IS '정정 사유 코드 (공통코드 LOT_ATTR_RSN). ETC(기타)일 때만 rsn_dscr 필수';
        COMMENT ON COLUMN lot_attr_chng.rsn_dscr      IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';

        CREATE INDEX ix_lot_attr_chng_lot ON lot_attr_chng (lot_id);
        CREATE INDEX ix_lot_attr_chng_prod_created ON lot_attr_chng (prod_id, created_at);

        RAISE NOTICE 'lot_attr_chng 테이블 생성';
    ELSE
        RAISE NOTICE 'lot_attr_chng 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 2. 공통코드 시드 (Lot 속성정정 사유) ------------------------------------
    IF NOT EXISTS (SELECT 1 FROM code_group WHERE grp_cd = 'LOT_ATTR_RSN') THEN
        INSERT INTO code_group (grp_cd, grp_nm, dscr)
        VALUES ('LOT_ATTR_RSN', 'Lot 속성정정 사유', 'Lot 속성(제조일자·유통기한) 정정 사유 (lot_attr_chng.rsn_cd). 정정 유형이 하나뿐이라 유형 선택 없이 단일 그룹이다. ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'ERR_REG', '검수 오등록', 1);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'LABEL', '실물표기 상이', 2);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'VNDR', '거래처 정정 통보', 3);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'ETC', '기타', 4);
        RAISE NOTICE '공통코드 LOT_ATTR_RSN 시드';
    ELSE
        RAISE NOTICE '공통코드 LOT_ATTR_RSN 이미 존재 — 건너뜀';
    END IF;
END
$mig$;

-- 확인:
--   SELECT to_regclass('lot_attr_chng');
--   SELECT * FROM code_detail WHERE grp_cd = 'LOT_ATTR_RSN' ORDER BY srt_seq;
