-- =====================================================================
-- 고정 로케이션 마스터(fxng_loc) 도입 — 피킹존 상품×로케이션 지정 + 보충 기준(min/max).
--
-- 현재 라이브 상태(migration-catchup-to-schema.sql 적용) → schema.sql 상태.
-- 근거: docs/design.md 「고정 로케이션 마스터 (피킹존)」.
--   - UNIQUE(loc_id): 한 로케이션 = 한 상품 전용. 상품 하나가 여러 로케이션은 허용.
--   - min/max는 보충(SPMT) 기준이며 보충 프로세스는 미구현 — 자리만 마련한다.
--   - FK 없음 (전 스키마 원칙). 존재·STORAGE·온도대 검증은 FxngLocService,
--     삭제 가드는 WmsProdRefChecker·LocRefQueryRepository.
--
-- 실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--   - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--   - 재실행 안전 — 존재 확인을 걸어 이미 적용된 항목은 건너뛴다
-- =====================================================================
DO $mig$
BEGIN
    -- 1. fxng_loc 테이블 ---------------------------------------------------
    IF to_regclass('fxng_loc') IS NULL THEN
        CREATE TABLE fxng_loc (
            fxng_loc_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prod_id     BIGINT      NOT NULL,
            loc_id      BIGINT      NOT NULL,
            min_qty     BIGINT      NOT NULL,
            max_qty     BIGINT      NOT NULL,
            created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30) DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT uq_fxng_loc UNIQUE (loc_id),
            CONSTRAINT ck_fxng_loc_qty CHECK (min_qty >= 0 AND max_qty >= 1 AND min_qty <= max_qty)
        );

        COMMENT ON TABLE  fxng_loc IS '고정 로케이션 마스터. 상품×로케이션 지정 (FK 없음 — 존재·STORAGE·온도대 검증은 FxngLocService, 삭제 가드는 WmsProdRefChecker·LocRefQueryRepository). 적치 FXNG_LOC 방식의 후보 원천이고, min/max는 보충(SPMT) 기준 — 보충 프로세스는 미구현';
        COMMENT ON COLUMN fxng_loc.prod_id IS '고정할 상품 (prod.prod_id). 한 상품이 여러 고정 로케이션을 가질 수 있다';
        COMMENT ON COLUMN fxng_loc.loc_id  IS '고정 로케이션 (loc.loc_id, STORAGE 전용 — STAGE는 적치·할당 후보 모집단 밖이라 지정해도 영영 쓰이지 않는다). UNIQUE — 한 로케이션은 한 상품 전용';
        COMMENT ON COLUMN fxng_loc.min_qty IS '재보충점. 이 로케이션의 재고가 이 아래로 내려가면 보충 대상 (보충 프로세스 구현 시 사용)';
        COMMENT ON COLUMN fxng_loc.max_qty IS '보충 목표 상한. loc.max_qty 이하 — 크로스 테이블이라 CHECK 불가, FxngLocService(등록)와 LocService(loc.max_qty 하향 가드)가 지킨다';

        CREATE INDEX ix_fxng_loc_prod ON fxng_loc (prod_id);

        RAISE NOTICE 'fxng_loc 테이블 생성';
    ELSE
        RAISE NOTICE 'fxng_loc 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 2. 적치 방식 주석 갱신 (FXNG_LOC 방식 추가 — 코드 레지스트리 PutawayMethod와 맞춤)
    COMMENT ON COLUMN ptawy_stgy_stg.mthd_cd IS '추천 방식 code (FXNG_LOC 고정 / SAME_PROD_LOC 적재 / EMPTY_LOC 빈 / ANY_LOC 전체 보관). CHECK 없음 — PutawayMethod enum이 소유';
END
$mig$;
