-- =====================================================================
-- 피킹지시(pikng_task) · 피킹실적(pikng_acrst) 도입 + ck_inv_mov_dvsn에서 PIKNG 제거.
--
-- 현재 라이브 상태 → schema.sql 상태.
-- 근거: docs/design.md 「피킹 · 출고확정」 + 피킹 분석설계 (2026-08-20 확정).
--   - pikng_task는 putaway_task(적치지시)·inv_mov_task(이동지시)와 동등한 위치의
--     작업지시 문서다 — 지시/완료 수량과 상태(DIRECTED/DONE/CANCELLED)를 스스로 갖는다.
--   - 웨이브 발행 시 outb_alloc과 1:1로 생성된다. 등록이 예약을 만들지 않는 점이
--     inv_mov_task와 다르다 — 예약은 할당이 이미 잡았고, 실행(PICK)이 그 예약을 소진한다.
--   - pikng_acrst는 실행 1회 = 1행의 append-only 실적 로그 (inv_hld_acrst와 같은 형태).
--     「실적 = inv_hist」 원칙의 두 번째 예외 — PICK 이력의 참조(rfn_doc_no = 출고번호)는
--     주문 단위라 실행 건을 지시 단위로 귀속시키지 못한다.
--   - 항등식: pikng_task.cmpl_qty = outb_alloc.pikng_qty = SUM(pikng_acrst.pikng_qty).
--   - InvMovDvsn.PIKNG은 이 결정으로 사용처가 없어 CHECK에서 제거한다 (P1 — 등록은 되는데
--     동작하지 않는 옵션 금지). PTAWY는 이번 결정 범위 밖이라 유지.
--
-- 실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--   - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--   - 재실행 안전 — 존재 확인을 걸어 이미 적용된 항목은 건너뛴다
-- =====================================================================
DO $mig$
BEGIN
    -- 1. pikng_task 테이블 --------------------------------------------------
    IF to_regclass('pikng_task') IS NULL THEN
        CREATE TABLE pikng_task (
            pikng_task_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            outb_wave_id  BIGINT      NOT NULL,
            outb_alloc_id BIGINT      NOT NULL,
            prod_id       BIGINT      NOT NULL,
            from_loc_id   BIGINT      NOT NULL,
            lot_id        BIGINT      NOT NULL,
            drct_qty      BIGINT      NOT NULL,
            cmpl_qty      BIGINT      DEFAULT 0 NOT NULL,
            status        VARCHAR(15) NOT NULL,
            srt_seq       INT         NOT NULL,
            cmpl_dt       TIMESTAMP,
            created_at    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by    VARCHAR(30) DEFAULT 'admin' NOT NULL,
            updated_at    TIMESTAMP,
            updated_by    VARCHAR(30),
            CONSTRAINT ck_pikng_task_status CHECK (status IN ('DIRECTED', 'DONE', 'CANCELLED')),
            CONSTRAINT ck_pikng_task_qty CHECK (drct_qty > 0 AND cmpl_qty >= 0 AND cmpl_qty <= drct_qty)
        );

        COMMENT ON TABLE  pikng_task IS '피킹 지시. putaway_task·inv_mov_task와 동등한 위치의 작업지시 문서 — 웨이브 발행 시 outb_alloc과 1:1로 생성된다(상품별 집약 없음). 등록은 예약을 만들지 않는다 — 예약은 할당이 이미 잡았고 실행(PICK)이 소진한다. 발행·취소는 웨이브 단위(웨이브가 발행 문서)';
        COMMENT ON COLUMN pikng_task.outb_wave_id  IS '발행 웨이브 (느슨한 참조, FK 없음). 발행·취소·피킹 화면의 조회 단위';
        COMMENT ON COLUMN pikng_task.outb_alloc_id IS '지시의 근거 할당 — 1:1 (uq_pikng_task_alloc). 주문 도메인 카운터(outb_alloc.pikng_qty)·할당해제 가드가 이 참조를 지난다';
        COMMENT ON COLUMN pikng_task.prod_id       IS '재고 키 스냅샷. alloc → inv 조인으로도 얻지만 inv 행은 수량 0이 되면 삭제된다 — 완료된 지시의 표시를 위해 직접 담는다 (inv_hist·inv_mov_task와 같은 형태)';
        COMMENT ON COLUMN pikng_task.from_loc_id   IS '집품 로케이션 = 할당된 재고의 로케이션 스냅샷. TO는 SHIP-STAGE 고정이라 컬럼으로 두지 않는다 (putaway_task가 FROM을 두지 않는 것의 거울상)';
        COMMENT ON COLUMN pikng_task.lot_id        IS '집품 Lot 스냅샷 (Lot 행은 삭제되지 않는다)';
        COMMENT ON COLUMN pikng_task.drct_qty      IS '지시 수량 = 발행 시점의 aloc_qty. 발행 후 재할당·해제가 막혀 항등식 drct_qty = aloc_qty가 유지된다';
        COMMENT ON COLUMN pikng_task.cmpl_qty      IS '실행(PICK) 완료 수량 누계. 부분 피킹 허용 — drct_qty에 도달하면 DONE. 항등식: cmpl_qty = outb_alloc.pikng_qty = SUM(pikng_acrst.pikng_qty)';
        COMMENT ON COLUMN pikng_task.status        IS 'DIRECTED 지시(부분 실행 포함) / DONE 완료 / CANCELLED 취소(웨이브 단위 지시취소, cmpl_qty=0일 때만). 「진행」 같은 부분 상태는 두지 않는다 — 진행도는 수량 파생';
        COMMENT ON COLUMN pikng_task.srt_seq       IS '집품 순서 (웨이브 내 1..N). 발행 시점에 loc.pikng_prty → loc_cd → outb_alloc_id 순으로 고정한 스냅샷 — 작업 중 마스터가 바뀌어도 리스트 순서가 흔들리지 않는다';
        COMMENT ON COLUMN pikng_task.cmpl_dt       IS '지시 완료 시각 (DONE 전이 시점)';

        -- 지시 = 할당 1:1의 물리적 강제. 취소(CANCELLED) 행은 이력으로 남으므로 살아 있는 행만 센다
        CREATE UNIQUE INDEX uq_pikng_task_alloc ON pikng_task (outb_alloc_id) WHERE status <> 'CANCELLED';
        CREATE INDEX ix_pikng_task_wave ON pikng_task (outb_wave_id);

        RAISE NOTICE 'pikng_task 테이블 생성';
    ELSE
        RAISE NOTICE 'pikng_task 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 2. pikng_acrst 테이블 -------------------------------------------------
    IF to_regclass('pikng_acrst') IS NULL THEN
        CREATE TABLE pikng_acrst (
            pikng_acrst_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            pikng_task_id  BIGINT      NOT NULL,
            prod_id        BIGINT      NOT NULL,
            from_loc_id    BIGINT      NOT NULL,
            lot_id         BIGINT      NOT NULL,
            pikng_qty      BIGINT      NOT NULL,
            created_at     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by     VARCHAR(30) DEFAULT 'admin' NOT NULL,
            updated_at     TIMESTAMP,
            updated_by     VARCHAR(30),
            CONSTRAINT ck_pikng_acrst_qty CHECK (pikng_qty > 0)
        );

        COMMENT ON TABLE  pikng_acrst IS '피킹 실적 (실행 append-only 로그). 수정·삭제하지 않는다 — 부분 피킹이 N번이면 N행. inv_hld_acrst와 같은 형태로, 「실적 = inv_hist」 원칙의 두 번째 예외다 — PICK 이력의 참조(출고번호)는 주문 단위라 실행 건을 지시 단위로 귀속시키지 못한다. 실적 취소(백로그)가 도입되면 취소 단위가 이 행이다';
        COMMENT ON COLUMN pikng_acrst.pikng_task_id IS '실행한 피킹지시 (느슨한 참조, FK 없음)';
        COMMENT ON COLUMN pikng_acrst.pikng_qty     IS '이번 실행의 피킹 수량. SUM = pikng_task.cmpl_qty (대사 축)';

        CREATE INDEX ix_pikng_acrst_task ON pikng_acrst (pikng_task_id);

        RAISE NOTICE 'pikng_acrst 테이블 생성';
    ELSE
        RAISE NOTICE 'pikng_acrst 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 3. ck_inv_mov_dvsn에서 PIKNG 제거 --------------------------------------
    --    피킹지시가 별도 pikng_task로 확정되어 PIKNG 값을 쓰는 코드가 없다.
    IF EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'ck_inv_mov_dvsn'
          AND pg_get_constraintdef(oid) LIKE '%PIKNG%'
    ) THEN
        ALTER TABLE inv_mov_task DROP CONSTRAINT ck_inv_mov_dvsn;
        ALTER TABLE inv_mov_task ADD CONSTRAINT ck_inv_mov_dvsn CHECK (mov_dvsn IN ('INV_MOV', 'PTAWY'));
        RAISE NOTICE 'ck_inv_mov_dvsn 재정의 (PIKNG 제거)';
    ELSE
        RAISE NOTICE 'ck_inv_mov_dvsn 이미 PIKNG 없음 — 건너뜀';
    END IF;

    -- 4. 코멘트 갱신 (COMMENT ON은 덮어쓰기라 재실행 안전) --------------------
    COMMENT ON COLUMN inv_mov_task.mov_dvsn IS '이동구분 — INV_MOV 재고이동 / PTAWY 적치. 재고이동 화면의 등록은 INV_MOV 고정이고, 그 화면의 확정·취소도 INV_MOV만 허용한다. 적치는 별도 putaway_task 유지로 확정(2026-08-04), 피킹도 별도 pikng_task로 확정(2026-08-20)되어 PIKNG 값은 제거했다';
    COMMENT ON COLUMN outb_alloc.pikng_qty IS '피킹 완료 수량. 피킹 시 보관→SHIP-STAGE MOVE(tx PICK)와 함께 누적되고, 이때 보관 inv.aloc_qty도 소진된다(실물 반출). 항등식: pikng_qty = pikng_task.cmpl_qty = SUM(pikng_acrst.pikng_qty) — 주문 도메인의 진행 / 지시 문서의 진행 / 실행 원장이 같은 사실의 세 관점이다';
    COMMENT ON COLUMN outb_wave.issued_dt IS '피킹지시 발행 시각. 미발행이면 NULL — 지시취소(실적 0일 때만)가 다시 NULL로 되돌린다';
END $mig$;
