-- =====================================================================
-- 이동지시(inv_mov_task) 도입 — 보관 ↔ 보관 2단계 이동 (지시=예약 → 확정=실물 MOVE).
--
-- 현재 라이브 상태(migration-catchup-to-schema.sql 적용) → schema.sql 상태.
-- 근거: docs/sg/wms-st-화면프로세스정의서.md 4절 (2단계 예약 모델).
--   - 등록 시 FROM 재고의 inv.aloc_qty를 선점(예약)한다 — aloc_qty는 출고 할당 전용이
--     아니라 예약수량 일반이라는 의미 확정에 따름 (전용 예약 컬럼을 만들지 않는다).
--   - 실적 테이블은 없다. 실적의 실체는 inv_hist의 MOVE 2행 (rfn_doc_no = inv_mov_no).
--   - 상태 집합은 putaway_task와 동일 (DIRECTED / DONE / CANCELLED).
--
-- 실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--   - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--   - 재실행 안전 — 존재 확인을 걸어 이미 적용된 항목은 건너뛴다
-- =====================================================================
DO $mig$
BEGIN
    -- 1. inv_mov_task 테이블 -----------------------------------------------
    IF to_regclass('inv_mov_task') IS NULL THEN
        CREATE TABLE inv_mov_task (
            inv_mov_task_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            inv_mov_no      VARCHAR(30) NOT NULL,
            mov_dvsn        VARCHAR(10) NOT NULL,
            prod_id         BIGINT      NOT NULL,
            lot_id          BIGINT      NOT NULL,
            from_loc_id     BIGINT      NOT NULL,
            to_loc_id       BIGINT      NOT NULL,
            drct_qty        BIGINT      NOT NULL,
            cmpl_qty        BIGINT      DEFAULT 0 NOT NULL,
            status          VARCHAR(15) NOT NULL,
            cmpl_dt         TIMESTAMP,
            created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by      VARCHAR(30) DEFAULT 'admin' NOT NULL,
            updated_at      TIMESTAMP,
            updated_by      VARCHAR(30),
            CONSTRAINT uq_inv_mov_no UNIQUE (inv_mov_no),
            CONSTRAINT ck_inv_mov_dvsn CHECK (mov_dvsn IN ('INV_MOV', 'PTAWY', 'PIKNG')),
            CONSTRAINT ck_inv_mov_status CHECK (status IN ('DIRECTED', 'DONE', 'CANCELLED')),
            CONSTRAINT ck_inv_mov_qty CHECK (drct_qty > 0 AND cmpl_qty >= 0 AND cmpl_qty <= drct_qty),
            CONSTRAINT ck_inv_mov_loc CHECK (from_loc_id <> to_loc_id)
        );

        COMMENT ON TABLE  inv_mov_task IS '이동지시 (보관↔보관 2단계: 지시=예약 → 확정=실물 MOVE). 지시는 권고가 아니라 명령 — 지시 TO와 다른 로케이션으로 확정할 수 없고, 다른 곳에 두려면 잔량 취소 후 재지시한다. 실적은 별도 테이블 없이 inv_hist의 MOVE 2행(rfn_doc_no = inv_mov_no)';
        COMMENT ON COLUMN inv_mov_task.inv_mov_no  IS '이동지시 번호 (건당 유일 — 라인 구조 없음). inv_hist 실적이 rfn_doc_no만으로 지시와 정확히 매칭되게 하는 전제. nbr_rule INV_MOV_NO 채번';
        COMMENT ON COLUMN inv_mov_task.mov_dvsn    IS '이동구분 — INV_MOV 재고이동 / PTAWY 적치 / PIKNG 피킹. 재고이동 화면의 등록은 INV_MOV 고정이고, 그 화면의 확정·취소도 INV_MOV만 허용한다(적치·피킹 유형은 각자의 경로 전용 — 레거시의 「재고업무 유형만 확정 가능, 입고적치 차단」 대응). 적치·피킹 지시를 이 테이블로 통합할지(별도 putaway_task 유지 여부)는 각 지시 구현 시 결정';
        COMMENT ON COLUMN inv_mov_task.prod_id     IS '이동 대상 상품. Lot이 상품을 함의하지만 재고 키(상품+Loc+Lot) 그대로 담아 단독 조회를 가능하게 한다 (inv_hist와 같은 형태)';
        COMMENT ON COLUMN inv_mov_task.from_loc_id IS '출발 보관 로케이션. 등록 시 이 로케이션 재고의 aloc_qty를 잔여수량만큼 선점(예약)한다';
        COMMENT ON COLUMN inv_mov_task.to_loc_id   IS '도착 보관 로케이션. 온도대 일치 + 적재가능수량(max_qty − 현재고 − 미완료 지시 유입 잔량) 검증 대상';
        COMMENT ON COLUMN inv_mov_task.drct_qty    IS '지시 수량. 부분확정 후 잔량 취소 시 완료수량으로 차감된다';
        COMMENT ON COLUMN inv_mov_task.cmpl_qty    IS '확정(실물 MOVE) 완료 수량 누계. 부분확정 허용 — drct_qty에 도달하면 DONE';
        COMMENT ON COLUMN inv_mov_task.status      IS 'DIRECTED 지시(부분확정 포함) / DONE 완료 / CANCELLED 취소(cmpl_qty=0 전량 취소 시. 부분확정 후 잔량 취소는 drct_qty 차감 후 DONE). 「진행」 같은 부분 상태는 두지 않는다 — 진행도는 수량 파생';
        COMMENT ON COLUMN inv_mov_task.cmpl_dt     IS '지시 완료 시각 (DONE 전이 시점)';

        CREATE INDEX ix_inv_mov_prod ON inv_mov_task (prod_id);
        CREATE INDEX ix_inv_mov_open_to ON inv_mov_task (to_loc_id) WHERE status = 'DIRECTED';

        RAISE NOTICE 'inv_mov_task 테이블 생성';
    ELSE
        RAISE NOTICE 'inv_mov_task 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 2. 채번 규칙 시드 -----------------------------------------------------
    IF NOT EXISTS (SELECT 1 FROM nbr_rule WHERE rule_cd = 'INV_MOV_NO') THEN
        INSERT INTO nbr_rule (rule_cd, rule_nm, prfx, prfx_dlmt, de_dlmt, seq_dgt, dync_ky_typ)
        VALUES ('INV_MOV_NO', '이동지시 번호', 'MV', '-', '-', 3, 'DAY');
        RAISE NOTICE 'nbr_rule INV_MOV_NO 시드';
    ELSE
        RAISE NOTICE 'nbr_rule INV_MOV_NO 이미 존재 — 건너뜀';
    END IF;

    -- 3. 코멘트 갱신 (COMMENT ON은 덮어쓰기라 재실행 안전) --------------------
    COMMENT ON COLUMN inv.aloc_qty IS '예약 수량 — 출고 할당 전용이 아니라 예약수량 일반. 출고 할당(outb_alloc)과 이동지시(inv_mov_task)가 같은 컬럼으로 선점하고, 실행(피킹/이동확정)이 on_hand와 함께 소진. 물리 이동이 아니므로 이력에 기록하지 않음. 항등식: aloc_qty = 원천별 미소진 잔량 합 (대사 대상)';
    COMMENT ON COLUMN inv_hist.rfn_doc_typ IS '참조 문서 유형 (INBOUND / OUTBOUND / INV_MOV 이동지시 / 수동조정 시 NULL)';
    RAISE NOTICE 'inv.aloc_qty / inv_hist.rfn_doc_typ 코멘트 갱신';
END
$mig$;

-- 확인:
--   SELECT to_regclass('inv_mov_task');
--   SELECT * FROM nbr_rule WHERE rule_cd = 'INV_MOV_NO';
