-- =====================================================================
-- 재고조정 도입 — inv_adj(자기완결 append-only 로그) 1테이블.
--
-- 현재 라이브 상태(migration-inv-lot-chng.sql 적용) → schema.sql 상태.
-- 근거: docs/design.md 「재고조정」.
--   - 재고조사와 갈리는 지점은 「실물이 그 자리에 있느냐」 하나다. 조사는 장부와 실물이
--     어긋났을 때 장부를 실물에 맞추고(조정수량은 실사수량에서 파생), 조정은 둘이 맞는 상태에서
--     함께 줄이거나 늘린다(조정수량은 입력값). 불량 반품 폐기를 실사수량 0으로 적으면
--     「세어보니 없었다」는 거짓 기록이 되므로 경로를 나눈다.
--   - 조정 라인은 두 종류다. 가용 라인(재고 행 지목, ±)과 보류 라인(보류 건 지목, − 전용).
--     보류 라인은 hld_qty 소진 + on_hand 감소를 한 트랜잭션에 묶어, 보류를 먼저 풀 때 생기는
--     「폐기 대기분이 가용으로 뜨는 창」을 없앤다.
--   - 보류 「건」을 지목하는 이유: 같은 재고 행에 사유가 다른 미해제 보류가 여러 건 병존해서
--     (2026-08-09 확정), 재고 행만 지목하면 어느 건에서 빠지는지 정해지지 않는다.
--     건을 지목하면 항등식 inv.hld_qty = SUM(미해제 잔량)도 해제 실적이 그대로 지킨다.
--   - 실적 테이블 없음 — 재고 실체는 inv_hist의 ADJUST 1행(부호 있음,
--     rfn_doc_typ=INV_ADJ, rfn_doc_no=adj_no). 번호가 건당 유일이라 실적↔이력이 1:1이다.
--   - 취소 경로 없음 — 되돌리는 것도 새 조정 1건(사유 ERR_ADJ)이다. (+) 방향을 여는 이유가 이것이다.
--
-- 실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--   - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--   - 재실행 안전 — 존재 확인을 걸어 이미 적용된 항목은 건너뛴다
-- =====================================================================
DO $mig$
BEGIN
    -- 1. inv_adj ------------------------------------------------------------
    IF to_regclass('inv_adj') IS NULL THEN
        CREATE TABLE inv_adj (
            inv_adj_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            adj_no      VARCHAR(30)     NOT NULL,
            prod_id     BIGINT          NOT NULL,
            loc_id      BIGINT          NOT NULL,
            lot_id      BIGINT          NOT NULL,
            adj_bfr_qty BIGINT          NOT NULL,
            adj_qty     BIGINT          NOT NULL,
            hld_no      VARCHAR(30),
            rsn_cd      VARCHAR(10)     NOT NULL,
            rsn_dscr    VARCHAR(200),
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT uq_inv_adj_no UNIQUE (adj_no),
            CONSTRAINT ck_inv_adj_qty CHECK (adj_qty <> 0 AND adj_bfr_qty >= 0 AND adj_bfr_qty + adj_qty >= 0),
            CONSTRAINT ck_inv_adj_hld CHECK (hld_no IS NULL OR adj_qty < 0)
        );

        COMMENT ON TABLE  inv_adj IS '재고조정 원장 (append-only 자기완결 로그). 취소 경로 없음 — 되돌리는 것도 새 조정 1건(사유 ERR_ADJ)이다';
        COMMENT ON COLUMN inv_adj.adj_no      IS '재고조정 번호 (nbr_rule INV_ADJ_NO, 건당 유일 — 라인 구조 없음). inv_hist.rfn_doc_no로 실려 실적 ↔ 이력이 1:1로 매칭된다';
        COMMENT ON COLUMN inv_adj.prod_id     IS '조정 대상 상품';
        COMMENT ON COLUMN inv_adj.loc_id      IS '조정 대상 보관 로케이션 (스테이징은 대상이 아니다 — 보류·이동·조사와 같은 경계)';
        COMMENT ON COLUMN inv_adj.lot_id      IS '조정 대상 Lot';
        COMMENT ON COLUMN inv_adj.adj_bfr_qty IS '조정전수량 — 화면 입력값이 아니라 재고 행 락을 걸고 다시 읽은 on_hand_qty다 (재고조사 cfm_sys_qty와 같은 성격). 조정후수량은 adj_bfr_qty + adj_qty로 파생되므로 담지 않는다';
        COMMENT ON COLUMN inv_adj.adj_qty     IS '조정수량 (부호 있음 — 양수 증가 / 음수 감소). 0은 금지';
        COMMENT ON COLUMN inv_adj.hld_no      IS '소진한 보류 건 (보류 라인). NULL이면 가용 라인 — 라인 종류의 유일한 판별자라 별도 구분 컬럼을 두지 않는다. 보류 라인은 이 조정이 inv_hld_rlz_acrst 해제 실적(사유 ADJ)을 함께 남긴다';
        COMMENT ON COLUMN inv_adj.rsn_cd      IS '조정사유 코드 (공통코드 INV_ADJ_RSN). ETC(기타)일 때만 rsn_dscr 필수';
        COMMENT ON COLUMN inv_adj.rsn_dscr    IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';

        CREATE INDEX ix_inv_adj_prod_created ON inv_adj (prod_id, created_at);
        CREATE INDEX ix_inv_adj_hld ON inv_adj (hld_no) WHERE hld_no IS NOT NULL;

        RAISE NOTICE 'inv_adj 테이블 생성';
    ELSE
        RAISE NOTICE 'inv_adj 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 2. inv_hist.rfn_doc_typ 코멘트 (CHECK 없는 컬럼이라 DDL 변경은 없다) -------
    COMMENT ON COLUMN inv_hist.rfn_doc_typ IS '참조 문서 유형. RefDocTyp enum (INBOUND / OUTBOUND / INV_MOV 이동지시 / INV_STKTK 재고조사 / INV_ADJ 재고조정 / LOT_CHNG 재고 로트변경). NULL = 참조 문서 없음. ADJUST 이력은 rfn_doc_typ이 조사·조정·로트변경 중 무엇인지를 가른다 — tx_typ만으로는 구분되지 않는다';
    RAISE NOTICE 'inv_hist.rfn_doc_typ 코멘트에 INV_ADJ 추가';

    -- 3. inv_stktk 코멘트 — 「건별 수동 조정 화면을 두지 않는다」 번복 ------------
    COMMENT ON TABLE  inv_stktk IS '재고조사(실사) 헤더. 장부와 실물이 어긋났을 때 장부를 실물에 맞춘다 — 실물을 그대로 둔 채 장부만 줄이는 처분(폐기·견본출고)은 재고조정(inv_adj)의 몫이다. 상태는 워크플로 단계만(작성 → 확정) — 「부분확정」은 두지 않는다. 확정 후 재정정은 조사를 되열지 않고 새 조사를 만든다(append-only). 확정이 남기는 것은 inv_hist의 ADJUST 행(rfn_doc_typ=INV_STKTK, rfn_doc_no=stktk_no)';
    RAISE NOTICE 'inv_stktk 코멘트 갱신 (재고조정과의 경계)';

    -- 4. 공통코드 — 조정사유 그룹 신설 + 조사사유 그룹명 정정 ---------------------
    -- 기존 ADJ_RSN은 이름이 「재고조정 사유」인데 내용은 조사 전용이다. 그룹코드를 맞바꾸지 않는
    -- 이유: code_detail의 PK가 (grp_cd, code_cd)라 grp_cd 변경은 PK 이관이고 inv_stktk_ln.rsn_cd가
    -- 참조 중인 라이브 데이터가 걸린다. 이름 한 줄로 끝나는 문제에 데이터 이관을 붙이지 않는다.
    UPDATE code_group
       SET grp_nm = '재고조사 조정사유',
           dscr   = '재고조사 확정 시 차이 라인의 조정 사유 (inv_stktk_ln.rsn_cd). 차이가 0이 아닌 라인만 필수이며, ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다. 재고조정(inv_adj)의 사유는 별개 그룹 INV_ADJ_RSN이다 — 조사는 「장부가 틀렸다」의 정정이고 조정은 「이만큼 처분했다」의 기록이라 사유 집합이 겹치지 않는다'
     WHERE grp_cd = 'ADJ_RSN';
    RAISE NOTICE '공통코드 ADJ_RSN 그룹명 정정 (재고조사 조정사유)';

    IF NOT EXISTS (SELECT 1 FROM code_group WHERE grp_cd = 'INV_ADJ_RSN') THEN
        INSERT INTO code_group (grp_cd, grp_nm, dscr)
        VALUES ('INV_ADJ_RSN', '재고조정 사유', '재고조정 라인의 사유 (inv_adj.rsn_cd). 장부와 실물을 함께 증감시키는 처분의 근거다. ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
        -- 기초재고·발견재고를 넣지 않는다 — 「장부에 없던 것을 올린다」는 장부/실물 차이의 정정이라 조사 소관이다
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('INV_ADJ_RSN', 'SCRP', '폐기', 1);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('INV_ADJ_RSN', 'SMPL', '견본출고', 2);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('INV_ADJ_RSN', 'ERR_ADJ', '조정오류 정정', 3);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('INV_ADJ_RSN', 'ETC', '기타', 4);
        RAISE NOTICE '공통코드 INV_ADJ_RSN 시드';
    ELSE
        RAISE NOTICE '공통코드 INV_ADJ_RSN 이미 존재 — 건너뜀';
    END IF;

    -- 5. 해제사유에 ADJ 추가 (보류 라인이 남기는 해제 실적의 사유) -----------------
    -- 트랜잭션이 넣는 값이라 보류 해제 화면 콤보에서는 빼고, 서버(InvHldService.release)도
    -- 수동 해제 요청에 이 코드가 오면 거부한다
    IF NOT EXISTS (SELECT 1 FROM code_detail WHERE grp_cd = 'HLD_RLZ_RSN' AND code_cd = 'ADJ') THEN
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'ADJ', '재고조정', 4);
        RAISE NOTICE '공통코드 HLD_RLZ_RSN.ADJ 시드';
    ELSE
        RAISE NOTICE '공통코드 HLD_RLZ_RSN.ADJ 이미 존재 — 건너뜀';
    END IF;

    -- 6. 채번 규칙 시드 -----------------------------------------------------
    IF NOT EXISTS (SELECT 1 FROM nbr_rule WHERE rule_cd = 'INV_ADJ_NO') THEN
        INSERT INTO nbr_rule (rule_cd, rule_nm, prfx, prfx_dlmt, de_dlmt, seq_dgt, dync_ky_typ)
        VALUES ('INV_ADJ_NO', '재고조정 번호', 'AJ', '-', '-', 3, 'DAY');
        RAISE NOTICE 'nbr_rule INV_ADJ_NO 시드';
    ELSE
        RAISE NOTICE 'nbr_rule INV_ADJ_NO 이미 존재 — 건너뜀';
    END IF;
END
$mig$;

-- 확인:
--   SELECT to_regclass('inv_adj');
--   SELECT * FROM nbr_rule WHERE rule_cd = 'INV_ADJ_NO';
--   SELECT * FROM code_detail WHERE grp_cd = 'INV_ADJ_RSN' ORDER BY srt_seq;
--   SELECT grp_cd, grp_nm FROM code_group WHERE grp_cd IN ('ADJ_RSN', 'INV_ADJ_RSN');
--   -- 조정이 남긴 이력
--   SELECT * FROM inv_hist WHERE rfn_doc_typ = 'INV_ADJ' ORDER BY inv_hist_id DESC;
--   -- 보류 라인 대사: 조정 ↔ 해제 실적 (같은 hld_no로 이어진다)
--   SELECT a.adj_no, a.adj_qty, a.hld_no, r.rlz_qty, r.rsn_cd
--     FROM inv_adj a JOIN inv_hld_rlz_acrst r ON r.hld_no = a.hld_no
--    WHERE a.hld_no IS NOT NULL ORDER BY a.inv_adj_id DESC;
