-- =====================================================================
-- 재고 로트변경 도입 — inv_lot_chng(로트변경 원장) 1테이블 + 채번 규칙 + 코멘트 갱신.
--
-- 현재 라이브 상태(migration-inv-stktk.sql 적용) → schema.sql 상태.
-- 근거: 재고 로트변경 분석설계 (2026-08-13 확정).
--   - 「이 로케이션의 이 재고 중 N개는 제조일자가 X였다」 — 원 Lot에서 N개를 빼
--     (상품+입고일자+X) 배치의 Lot으로 넣는다(있으면 병합, 없으면 채번=분할).
--   - lot_attr_chng(전량·무이동 정정)에 얹지 않는다 — 그쪽은 「한 Lot의 전/후」(bfr_*/aft_*),
--     여기는 「두 Lot 사이」(from_*/to_*)라 모양이 다르고, 무채번 vs 채번 필수로 정책도 충돌한다.
--   - 재고 실체는 inv_hist의 ADJUST 2행(원 Lot −N / 새 Lot +N,
--     rfn_doc_typ=LOT_CHNG, rfn_doc_no=lot_chng_no). 「이력 합계 = 스냅샷」 불변식 유지.
--   - TxTyp 추가 없음(ADJUST 재사용 — ck_invh_tx_typ 변경 없음), RefDocTyp만 LOT_CHNG 추가
--     (rfn_doc_typ VARCHAR(10)이라 INV_LOT_CHNG 12자는 들어가지 않는다 — 컬럼 확장 대신 이름을 줄였다).
--   - 사유 코드는 LOT_ATTR_RSN 재사용 (성격이 속성 정정과 같다) — code_detail 시드 추가 없음.
--
-- 실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--   - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--   - 재실행 안전 — 존재 확인을 걸어 이미 적용된 항목은 건너뛴다
-- =====================================================================
DO $mig$
BEGIN
    -- 1. inv_lot_chng (로트변경 원장) ----------------------------------------
    IF to_regclass('inv_lot_chng') IS NULL THEN
        CREATE TABLE inv_lot_chng (
            inv_lot_chng_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            lot_chng_no VARCHAR(30)     NOT NULL,
            prod_id     BIGINT          NOT NULL,
            loc_id      BIGINT          NOT NULL,
            from_lot_id BIGINT          NOT NULL,
            from_lot_no VARCHAR(30)     NOT NULL,
            from_mfg_dt DATE            NOT NULL,
            from_expiry_dt DATE         NOT NULL,
            to_lot_id   BIGINT          NOT NULL,
            to_lot_no   VARCHAR(30)     NOT NULL,
            to_mfg_dt   DATE            NOT NULL,
            to_expiry_dt DATE           NOT NULL,
            chng_qty    BIGINT          NOT NULL,
            to_lot_new_yn BOOLEAN       DEFAULT FALSE NOT NULL,
            rsn_cd      VARCHAR(10)     NOT NULL,
            rsn_dscr    VARCHAR(200),
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT uq_inv_lot_chng_no UNIQUE (lot_chng_no),
            CONSTRAINT ck_inv_lot_chng_qty CHECK (chng_qty >= 1),
            CONSTRAINT ck_inv_lot_chng_lot CHECK (from_lot_id <> to_lot_id),
            CONSTRAINT ck_inv_lot_chng_dt  CHECK (to_expiry_dt >= to_mfg_dt)
        );

        COMMENT ON TABLE  inv_lot_chng IS '재고 로트변경 원장 (append-only 자기완결 로그). 「이 로케이션의 이 재고 중 N개는 제조일자가 X였다」 — 원 Lot에서 N개를 빼 (상품+입고일자+X) 배치의 Lot으로 넣는다(그 키의 Lot이 있으면 병합, 없으면 채번=분할). 취소 경로 없음 — 되돌리는 것도 새 로트변경 1건. 재고 실체는 inv_hist의 ADJUST 2행(rfn_doc_typ=LOT_CHNG, rfn_doc_no=lot_chng_no)';
        COMMENT ON COLUMN inv_lot_chng.lot_chng_no    IS '로트변경 번호 (건당 유일 — 라인 구조 없음). nbr_rule LOT_CHNG_NO 채번. inv_hist.rfn_doc_no로 실려 실적 ↔ 이력이 매칭된다 — lot_attr_chng가 무채번인 것과 갈리는 지점(그쪽은 아무도 참조하지 않는 로그다)';
        COMMENT ON COLUMN inv_lot_chng.prod_id        IS '대상 상품. 재고 키(상품+Loc+Lot) 그대로 담는다 (inv_hld·inv_mov_task와 같은 형태)';
        COMMENT ON COLUMN inv_lot_chng.loc_id         IS '대상 보관 로케이션. 로케이션은 바뀌지 않는다 — 같은 로케이션 안에서 Lot만 바뀌는 장부 이동이라 inv_hist의 from/to_loc_id도 NULL';
        COMMENT ON COLUMN inv_lot_chng.from_lot_id    IS '원 Lot. lot 테이블 FK는 걸지 않는다 — lot_attr_chng.lot_id와 같은 느슨한 참조';
        COMMENT ON COLUMN inv_lot_chng.from_lot_no    IS '원 Lot 번호 스냅샷 — 자기완결 로그 원칙 (lot_attr_chng.lot_no·보류 실적 선례)';
        COMMENT ON COLUMN inv_lot_chng.from_mfg_dt    IS '원 Lot 제조일자 스냅샷. NOT NULL — 대상이 유통기한 관리 상품뿐이라 값이 항상 있다 (lot_attr_chng이 nullable로 둔 것을 따르지 않는 이유: 새 테이블에서 같은 느슨함을 복제할 이유가 없다)';
        COMMENT ON COLUMN inv_lot_chng.from_expiry_dt IS '원 Lot 유통기한 스냅샷';
        COMMENT ON COLUMN inv_lot_chng.to_lot_id      IS '목적지 Lot — (원 Lot의 상품+입고일자, 요청 제조일자) 배치 키의 findOrCreate 결과. 있으면 재사용(병합), 없으면 채번(분할) — 배치 키 충돌이 구조적으로 없다';
        COMMENT ON COLUMN inv_lot_chng.to_lot_no      IS '목적지 Lot 번호 스냅샷. 새 번호가 발생하므로 현품 라벨은 재출력 대상 — 라벨을 유지해야 하는 정정은 기존 재고 속성변경(전량)이 맡는다';
        COMMENT ON COLUMN inv_lot_chng.to_mfg_dt      IS '정정된 제조일자. 원 Lot과 반드시 다르다(같으면 목적지 = 원 Lot이라 무의미 — 서비스 검증) — 그래서 목적지 배치 키가 원 Lot과 언제나 다르다';
        COMMENT ON COLUMN inv_lot_chng.to_expiry_dt   IS '정정된 유통기한 — 화면 입력값(벤더 인쇄값 정정이 주 사용처, 계산 강제 없음). 목적지 Lot이 기존이고 그 유통기한이 이 값과 다르면 거부한다(작업자 입력과 다른 값의 조용한 저장 금지)';
        COMMENT ON COLUMN inv_lot_chng.chng_qty       IS '변경 수량. 원 재고 행의 가용수량(on_hand - aloc - hld) 이내 — 예약(outb_alloc·inv_mov_task)·보류(inv_hld)가 가리키는 재고를 침범할 수 없다';
        COMMENT ON COLUMN inv_lot_chng.to_lot_new_yn  IS '목적지 Lot을 이번에 채번했는가 — true 분할(새 Lot) / false 병합(기존 Lot 합류). 실적 조회에서 둘을 구분할 유일한 근거';
        COMMENT ON COLUMN inv_lot_chng.rsn_cd         IS '변경 사유 코드 (공통코드 LOT_ATTR_RSN 재사용 — 사유 성격이 속성 정정과 같다). ETC(기타)일 때만 rsn_dscr 필수';
        COMMENT ON COLUMN inv_lot_chng.rsn_dscr       IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';

        CREATE INDEX ix_inv_lot_chng_from_lot     ON inv_lot_chng (from_lot_id);
        CREATE INDEX ix_inv_lot_chng_prod_created ON inv_lot_chng (prod_id, created_at);

        RAISE NOTICE 'inv_lot_chng 테이블 생성';
    ELSE
        RAISE NOTICE 'inv_lot_chng 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 2. inv_hist.rfn_doc_typ 코멘트 (CHECK 없는 컬럼이라 DDL 변경은 없다) -------
    COMMENT ON COLUMN inv_hist.rfn_doc_typ IS '참조 문서 유형 (INBOUND / OUTBOUND / INV_MOV 이동지시 / INV_STKTK 재고조사 / LOT_CHNG 재고 로트변경 / 수동조정 시 NULL)';
    RAISE NOTICE 'inv_hist.rfn_doc_typ 코멘트에 LOT_CHNG 추가';

    -- 3. 공통코드 그룹 설명 갱신 (사유 그룹 재사용 — code_detail 시드 추가 없음) ---
    UPDATE code_group
       SET dscr = 'Lot 속성(제조일자·유통기한) 정정 사유 (lot_attr_chng.rsn_cd · inv_lot_chng.rsn_cd — 재고 로트변경도 사유 성격이 같아 그룹을 재사용한다). ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다'
     WHERE grp_cd = 'LOT_ATTR_RSN';
    RAISE NOTICE '공통코드 LOT_ATTR_RSN 설명에 inv_lot_chng 사용처 추가';

    -- 4. 채번 규칙 시드 -----------------------------------------------------
    -- LC-20260813-001 형식 — 보류(HD)·조사(ST)와 같은 형식이고 LC는 기존 접두어와 겹치지 않는다
    IF NOT EXISTS (SELECT 1 FROM nbr_rule WHERE rule_cd = 'LOT_CHNG_NO') THEN
        INSERT INTO nbr_rule (rule_cd, rule_nm, prfx, prfx_dlmt, de_dlmt, seq_dgt, dync_ky_typ)
        VALUES ('LOT_CHNG_NO', '재고 로트변경 번호', 'LC', '-', '-', 3, 'DAY');
        RAISE NOTICE 'nbr_rule LOT_CHNG_NO 시드';
    ELSE
        RAISE NOTICE 'nbr_rule LOT_CHNG_NO 이미 존재 — 건너뜀';
    END IF;
END
$mig$;

-- 확인:
--   SELECT to_regclass('inv_lot_chng');
--   SELECT * FROM nbr_rule WHERE rule_cd = 'LOT_CHNG_NO';
--   -- 로트변경이 남긴 이력 (구현 후)
--   SELECT * FROM inv_hist WHERE rfn_doc_typ = 'LOT_CHNG' ORDER BY inv_hist_id DESC;
--
-- 참고 — 배치 재사용 조회의 null 버그(LotIssuer 도입으로 수정)가 이미 만들어 둔
-- 미관리 상품의 중복 배치 키 현황 확인(있어도 막지 않는다 — 최소 lot_id 재사용으로 흡수, 규모 파악용):
--   SELECT prod_id, receipt_dt, COUNT(*) FROM lot
--    WHERE mfg_dt IS NULL GROUP BY prod_id, receipt_dt HAVING COUNT(*) > 1;
