-- =====================================================================
-- OMS 출고주문(oms_outb_order · oms_outb_line) 신설 + WMS 출고주문을 그 하위로 묶기
--   전제: docs/migration-catchup-to-schema.sql 까지 적용된 DB (= 현재 라이브 상태).
--
--   배경 —
--   입고는 「OMS 입고주문 확정 → WMS 입고예정(ASN) 생성」 한 방향뿐인데, 출고는 WMS
--   outb_order 를 직접 등록하는 경로밖에 없었다. 주문 원장이 없으니 수정·확정·확정취소가
--   설 자리도 없고, 「누가 언제 무엇을 주문했나」가 창고 작업문서와 한 행에 뭉개져 있었다.
--   입고와 같은 2계층으로 맞춘다 — 원장은 OMS, 작업문서는 WMS.
--
--   ▣ 컬럼 이름은 표준 단어 사전(docs/naming-dictionary.md)을 따른다 —
--     납품처는 점포 마스터 참조라 FK 규칙대로 store_id(사전의 DLVPLC 는 화면 라벨로만 쓴다),
--     출고유형 outb_typ, 편수 vhcl_fltno(차량 VHCL + 편수 FLTNO), 출고예정일자 expct_de.
--
--   ▣ outb_order 는 이제 확정으로만 생긴다. oms_outb_order_id 가 NOT NULL 이라
--     주문 없는 창고 출고주문은 존재할 수 없다 (ib_order 와 같은 형태). 기존 행에는
--     이 마이그레이션이 상위 주문(CONFIRMED)을 만들어 붙인다 — 지우지 않는다.
--
--   ▣ 출고예정일(expct_de)을 새로 둔다. 기존 행은 주문일(odr_de)을 그대로 복사한다 —
--     지금까지 odr_de 하나가 「들어온 날」과 「나갈 날」을 겸했기 때문에 그게 사실에 가장 가깝다.
--     앞으로 웨이브 편성 대상 기간은 expct_de 를 본다 (같은 날 나갈 주문을 묶는 것이 웨이브다).
--
--   ▣ 전체가 DO 블록 하나다 (BEGIN;/COMMIT; 을 쓰지 않는다) — CLAUDE.md 규칙.
--     전 구간에 존재 확인이 걸려 있어 몇 번을 돌려도 안전하다.
--
--   실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--     - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
-- =====================================================================

DO $oms_outb$
DECLARE
    n int;
BEGIN
    -- 1. 채번 규칙 -------------------------------------------------------
    -- 접두 SO(Sales Order). PO/IB/OB/WV 가 이미 쓰이고 있어 겹치지 않는 두 글자를 골랐다.
    INSERT INTO nbr_rule (rule_cd, rule_nm, prfx, prfx_dlmt, de_dlmt, seq_dgt, dync_ky_typ)
    VALUES ('OMS_OUTB_NO', '출고주문 번호', 'SO', '-', '-', 3, 'DAY')
    ON CONFLICT (rule_cd) DO NOTHING;

    RAISE NOTICE '채번 규칙 OMS_OUTB_NO 반영 (SO-yyyyMMdd-NNN)';

    -- 2. 출고주문 헤더 ---------------------------------------------------
    IF to_regclass('public.oms_outb_order') IS NULL THEN
        CREATE TABLE oms_outb_order (
            oms_outb_order_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            oms_outb_no  VARCHAR(30)    NOT NULL,
            status       VARCHAR(15)    NOT NULL,
            store_id     BIGINT         NOT NULL,
            outb_typ     VARCHAR(10)    DEFAULT 'NRML' NOT NULL,
            vhcl_fltno   VARCHAR(10),
            expct_de     DATE           NOT NULL,
            pic_nm       VARCHAR(30),
            rmk          VARCHAR(200),
            cfm_dt       TIMESTAMP,
            created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
            updated_at   TIMESTAMP,
            updated_by   VARCHAR(30),
            CONSTRAINT uq_oms_outb_no UNIQUE (oms_outb_no),
            CONSTRAINT ck_oms_outb_order_status CHECK (status IN ('CREATED', 'CONFIRMED'))
        );
        CREATE INDEX ix_oms_outb_order_store ON oms_outb_order (store_id);
        RAISE NOTICE 'oms_outb_order 생성';
    ELSE
        RAISE NOTICE 'oms_outb_order 이미 존재 — 건너뜀';
    END IF;

    COMMENT ON TABLE  oms_outb_order IS '출고주문(점포 수주) 헤더. 확정 시 outb_order(WMS 출고주문)를 생성하는 상위 원장. WMS 출고주문의 생성·소멸은 전적으로 여기서 주관한다';
    COMMENT ON COLUMN oms_outb_order.oms_outb_no IS '출고주문 번호 (업무 식별자, 예: SO-20260803-001). 확정 후 생기는 출고번호(OB-)와는 별개의 채번';
    COMMENT ON COLUMN oms_outb_order.status      IS 'CREATED 작성 / CONFIRMED 확정(=WMS 출고주문 생성됨). 확정취소하면 CREATED로 돌아와 재확정할 수 있다. 취소 상태는 두지 않는다 — 없앨 주문은 삭제한다(확정 전만)';
    COMMENT ON COLUMN oms_outb_order.store_id    IS '납품처 점포 (store 참조). 확정 시 WMS 출고주문이 같은 점포를 이어받는다 — 할당 때 이 점포의 잔여수명 허용률로 Lot을 거른다. 이름은 조인으로 얻는다';
    COMMENT ON COLUMN oms_outb_order.outb_typ    IS '출고유형 (공통코드 OUTB_TYP — NRML 일반출고 / RTNGS 반품출고). 확정 시 그대로 복사된다 — 웨이브 편성 조건의 기준값이라 주문 시점에 정해져야 한다. CHECK 없음 — 값 목록은 공통코드가 소유하고 존재 검증은 서비스가 한다';
    COMMENT ON COLUMN oms_outb_order.vhcl_fltno  IS '차량편수 (공통코드 VHCL_FLTNO — 1편·2편…). NULL = 배차 미정. 확정 시 그대로 복사된다 — 같은 차수에 실릴 주문만 함께 묶기 위한 웨이브 편성 조건';
    COMMENT ON COLUMN oms_outb_order.expct_de    IS '출고 예정일. WMS 출고주문의 출고번호 채번(OB-YYYYMMDD-NNN) 기준일이자 웨이브 편성 대상 기간의 기준이다 — 「같은 날 나갈 주문을 묶는다」가 웨이브의 정의라서다';
    COMMENT ON COLUMN oms_outb_order.pic_nm      IS '수주 담당자명. 감사 컬럼 created_by(로그인 계정)와는 별개다 — 인증이 없어 created_by가 admin 고정이기도 하고, 대신 등록한 경우 실제 담당자가 다를 수 있다';
    COMMENT ON COLUMN oms_outb_order.rmk         IS '비고. 점포 전달사항 등 자유 입력. 확정 시 WMS로 넘기지 않는다 — 수주 시점의 메모라 창고 작업 지시와 성격이 다르다';
    COMMENT ON COLUMN oms_outb_order.cfm_dt      IS '확정(WMS 출고주문 생성) 시각. 확정취소하면 다시 NULL이 된다';

    -- 3. 출고주문 라인 ---------------------------------------------------
    IF to_regclass('public.oms_outb_line') IS NULL THEN
        CREATE TABLE oms_outb_line (
            oms_outb_line_id  BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            oms_outb_order_id BIGINT    NOT NULL,
            prod_id           BIGINT    NOT NULL,
            odr_qty           BIGINT    NOT NULL,
            created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
            updated_at        TIMESTAMP,
            updated_by        VARCHAR(30),
            CONSTRAINT ck_oms_outb_line_qty CHECK (odr_qty > 0)
        );
        CREATE INDEX ix_oms_outb_line_order ON oms_outb_line (oms_outb_order_id);
        RAISE NOTICE 'oms_outb_line 생성';
    ELSE
        RAISE NOTICE 'oms_outb_line 이미 존재 — 건너뜀';
    END IF;

    COMMENT ON TABLE  oms_outb_line IS '출고주문 라인. 확정 시 outb_line으로 1:1 복사된다 (환산 없음)';
    COMMENT ON COLUMN oms_outb_line.odr_qty IS '주문 수량. <<출고단위(prod.outb_uom_cd) 기준>> — 입고주문(oms_ib_line.odr_qty)과 달리 환산하지 않는다. 출고는 재고를 그대로 덜어내는 일이라 저장 단위와 주문 단위가 갈릴 이유가 없다';

    -- 4. outb_order 컬럼 2종 (일단 NULL 허용으로 추가 — 백필 뒤 제약을 건다) ----
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'outb_order' AND column_name = 'oms_outb_order_id') THEN
        ALTER TABLE outb_order ADD COLUMN oms_outb_order_id BIGINT;
        RAISE NOTICE 'outb_order.oms_outb_order_id 추가';
    ELSE
        RAISE NOTICE 'outb_order.oms_outb_order_id 이미 존재 — 건너뜀';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'outb_order' AND column_name = 'expct_de') THEN
        ALTER TABLE outb_order ADD COLUMN expct_de DATE;
        RAISE NOTICE 'outb_order.expct_de 추가';
    ELSE
        RAISE NOTICE 'outb_order.expct_de 이미 존재 — 건너뜀';
    END IF;

    -- 5. 기존 출고주문에 상위 주문 백필 ------------------------------------
    -- 이미 창고로 넘어간 문서라 상위 주문은 CONFIRMED 로 만든다. 번호는 주문일 기준으로
    -- 같은 규칙(SO-yyyyMMdd-NNN)을 재현하고, 확정시각은 원본 생성시각을 그대로 쓴다.
    WITH src AS (
        SELECT o.outb_order_id, o.store_id, o.outb_typ, o.vhcl_fltno, o.odr_de,
               o.created_at, o.created_by,
               'SO-' || to_char(o.odr_de, 'YYYYMMDD') || '-' ||
               lpad((row_number() OVER (PARTITION BY o.odr_de ORDER BY o.outb_order_id))::text, 3, '0')
                   AS oms_outb_no
          FROM outb_order o
         WHERE o.oms_outb_order_id IS NULL
    ), ins AS (
        INSERT INTO oms_outb_order (oms_outb_no, status, store_id, outb_typ, vhcl_fltno,
                                    expct_de, cfm_dt, created_at, created_by)
        SELECT src.oms_outb_no, 'CONFIRMED', src.store_id, src.outb_typ, src.vhcl_fltno,
               src.odr_de, src.created_at, src.created_at, src.created_by
          FROM src
        RETURNING oms_outb_order_id, oms_outb_no
    )
    UPDATE outb_order o
       SET oms_outb_order_id = ins.oms_outb_order_id
      FROM ins
      JOIN src ON src.oms_outb_no = ins.oms_outb_no
     WHERE o.outb_order_id = src.outb_order_id;

    GET DIAGNOSTICS n = ROW_COUNT;
    RAISE NOTICE '기존 출고주문 % 건에 상위 OMS 주문 생성·연결', n;

    -- 라인도 그대로 복사한다 (수량 단위가 같아 환산 없음). 이미 라인이 있는 주문은 건너뛴다.
    INSERT INTO oms_outb_line (oms_outb_order_id, prod_id, odr_qty, created_at, created_by)
    SELECT o.oms_outb_order_id, l.prod_id, l.odr_qty, l.created_at, l.created_by
      FROM outb_order o
      JOIN outb_line l ON l.outb_order_id = o.outb_order_id
     WHERE o.oms_outb_order_id IS NOT NULL
       AND NOT EXISTS (SELECT 1 FROM oms_outb_line ol
                        WHERE ol.oms_outb_order_id = o.oms_outb_order_id);

    GET DIAGNOSTICS n = ROW_COUNT;
    RAISE NOTICE '출고주문 라인 % 건 복사', n;

    -- 출고예정일은 주문일을 그대로 쓴다 — 지금까지 odr_de 하나가 두 뜻을 겸했다
    UPDATE outb_order SET expct_de = odr_de WHERE expct_de IS NULL;
    GET DIAGNOSTICS n = ROW_COUNT;
    RAISE NOTICE 'outb_order.expct_de % 건 백필 (odr_de 복사)', n;

    -- 6. 제약 -------------------------------------------------------------
    -- SET NOT NULL 은 이미 NOT NULL 인 컬럼에 다시 걸어도 아무 일도 하지 않는다(재실행 안전).
    -- 남은 NULL 이 있으면 여기서 터지는 게 맞다 — 백필이 빠진 행을 조용히 넘기면 안 된다.
    ALTER TABLE outb_order ALTER COLUMN oms_outb_order_id SET NOT NULL;
    ALTER TABLE outb_order ALTER COLUMN expct_de SET NOT NULL;

    -- 주문 하나가 붙들 수 있는 WMS 출고주문은 하나 (동시 확정의 최후 방어선)
    IF NOT EXISTS (SELECT 1 FROM pg_indexes
                    WHERE tablename = 'outb_order' AND indexname = 'uq_outb_order_oms') THEN
        CREATE UNIQUE INDEX uq_outb_order_oms ON outb_order (oms_outb_order_id);
        RAISE NOTICE 'uq_outb_order_oms 생성';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_indexes
                    WHERE tablename = 'outb_order' AND indexname = 'ix_outb_order_oms') THEN
        CREATE INDEX ix_outb_order_oms ON outb_order (oms_outb_order_id);
        RAISE NOTICE 'ix_outb_order_oms 생성';
    END IF;

    COMMENT ON COLUMN outb_order.oms_outb_order_id IS '이 출고주문을 발생시킨 OMS 출고주문. NOT NULL — 주문 없는 창고 출고주문은 존재할 수 없다(무결성은 애플리케이션이 보증, FK 없음). JPA는 연관관계가 아닌 스칼라로 매핑한다(패키지 의존을 omsback → wmsback 한 방향으로 유지)';
    COMMENT ON COLUMN outb_order.odr_de   IS '주문일 = 상위 OMS 출고주문이 등록된 날. 확정 시 복사되며 이후 바뀌지 않는다 — 「언제 들어온 주문인가」를 보는 값이다';
    COMMENT ON COLUMN outb_order.expct_de IS '출고 예정일. 출고번호 채번(OB-YYYYMMDD-NNN) 기준일이자 웨이브 편성 대상 기간의 기준이다 — 웨이브는 「같은 날 나갈 주문」을 묶는 단위라 주문일이 아니라 이쪽을 본다';

    -- 7. 채번 카운터 맞추기 ------------------------------------------------
    -- 백필로 이미 SO 번호를 써버렸으므로 카운터를 그 최대값까지 올려둔다.
    -- 그러지 않으면 다음 발급이 001부터 시작해 uq_oms_outb_no 에 부딪힌다.
    INSERT INTO nbr_seq (rule_cd, dync_ky, seq)
    SELECT 'OMS_OUTB_NO', split_part(oms_outb_no, '-', 2),
           MAX(split_part(oms_outb_no, '-', 3)::bigint)
      FROM oms_outb_order
     GROUP BY split_part(oms_outb_no, '-', 2)
    ON CONFLICT (rule_cd, dync_ky) DO UPDATE
        SET seq = GREATEST(nbr_seq.seq, EXCLUDED.seq);

    -- 8. 검증 -------------------------------------------------------------
    SELECT count(*) INTO n FROM outb_order o
     WHERE NOT EXISTS (SELECT 1 FROM oms_outb_order m
                        WHERE m.oms_outb_order_id = o.oms_outb_order_id);
    IF n > 0 THEN
        RAISE EXCEPTION '상위 주문이 없는 출고주문이 % 건 있다', n;
    END IF;

    SELECT count(*) INTO n
      FROM outb_order o
     WHERE (SELECT count(*) FROM outb_line l WHERE l.outb_order_id = o.outb_order_id)
        <> (SELECT count(*) FROM oms_outb_line ol WHERE ol.oms_outb_order_id = o.oms_outb_order_id);
    IF n > 0 THEN
        RAISE EXCEPTION '상위 주문과 라인 건수가 다른 출고주문이 % 건 있다', n;
    END IF;

    RAISE NOTICE 'OMS 출고주문 도입 완료';
END
$oms_outb$;

-- =====================================================================
-- 적용 후 확인
--   SELECT m.oms_outb_no, m.status, m.expct_de, o.outb_no, o.status
--     FROM oms_outb_order m LEFT JOIN outb_order o ON o.oms_outb_order_id = m.oms_outb_order_id
--    ORDER BY m.oms_outb_no;
--   SELECT rule_cd, dync_ky, seq FROM nbr_seq WHERE rule_cd = 'OMS_OUTB_NO' ORDER BY dync_ky;
-- =====================================================================
