-- =====================================================================
-- 입고 보완 delta — 입고제약 + 적치지시/로케이션 용량 (PostgreSQL / Supabase)
--   근거: docs/design.md 「입고 제약 (검수 관문)」 / 「적치 지시 (putaway_task)」
--
--   현재 DB 상태(= docs/schema.sql)에서 보완 설계가 기대하는 상태로 올린다:
--     (A) 입고 잔여수명 하한 기준 — sku.ib_life_rate
--     (B) 로케이션 용량 상한   — loc.max_qty
--     (C) 적치 지시            — putaway_task
--
--   먼저 적용해도 앱은 뜬다. validate는 "엔티티가 기대하는 것이 DB에 있는가"만 보므로,
--   아직 엔티티가 없는 테이블/컬럼이 DB에 더 있는 것은 문제가 되지 않는다.
--   (반대 순서 — 코드 먼저 —는 부팅이 깨진다)
--
--   실행: Supabase 대시보드 › SQL Editor 에 붙여넣고 Run
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- (A) 입고 잔여수명 하한 — 상품이 갖는 기준
--     store.outb_life_rate(출고: 납품처가 요구하는 기준)와 주체가 다르므로 별도 컬럼.
--     NOT NULL DEFAULT를 주지 않는다 — 기본값이 있으면 "미적용"을 표현할 수 없다.
-- ---------------------------------------------------------------------

ALTER TABLE sku ADD COLUMN ib_life_rate SMALLINT;
ALTER TABLE sku ADD CONSTRAINT ck_sku_ib_life_rate
    CHECK (ib_life_rate IS NULL OR ib_life_rate BETWEEN 0 AND 100);

COMMENT ON COLUMN sku.ib_life_rate IS
    '입고 허용 잔여수명 비율(%). 검수 시 (유통기한-입고일자)/shelf_life_days 가 이 비율 미만이면 차단. NULL = 미적용(유통기한 미관리 SKU 포함)';

-- 유통기한 관리 SKU에만 기본 기준을 넣는다. 출고 기준(40%)보다 높게 잡는 것이 정상이다 —
-- 받을 때 이미 40%면 점포에 내보낼 수 있는 창이 남지 않는다.
UPDATE sku SET ib_life_rate = 70 WHERE shelf_life_days IS NOT NULL;

-- ---------------------------------------------------------------------
-- (B) 로케이션 용량 상한
--     NULL = 무제한. 스테이징(RCV-STAGE/SHIP-STAGE)은 받는 대로 쌓이는 곳이라 상한이 없다.
--     보관(STORAGE)은 적치 전략의 전제이므로 값이 반드시 있어야 한다 —
--     기존 행을 채운 뒤에야 그 제약을 걸 수 있다.
-- ---------------------------------------------------------------------

ALTER TABLE loc ADD COLUMN max_qty BIGINT;

UPDATE loc SET max_qty = 1000 WHERE loc_type = 'STORAGE';

ALTER TABLE loc ADD CONSTRAINT ck_loc_max_qty
    CHECK (max_qty IS NULL OR max_qty > 0);
ALTER TABLE loc ADD CONSTRAINT ck_loc_storage_capacity
    CHECK (loc_type <> 'STORAGE' OR max_qty IS NOT NULL);

COMMENT ON COLUMN loc.max_qty IS
    '최대 적재 수량. 적재가능수량 = max_qty - 현재고 - 미완료 지시 잔량. NULL = 무제한(스테이징 전용), STORAGE는 NOT NULL 강제';

-- ---------------------------------------------------------------------
-- (C) 적치 지시
--     지시(전략이 정한 배정)와 실행(실물 MOVE)의 분리. 실적의 실체는 inv_hist의 MOVE 2행이므로
--     LODIS처럼 지시/실적을 두 테이블로 나누지 않고 지시 한 테이블 + cmpl_qty로 둔다.
--     from_loc는 항상 RCV-STAGE라 컬럼으로 두지 않는다.
-- ---------------------------------------------------------------------

CREATE TABLE putaway_task (
    putaway_task_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ib_line_id      BIGINT      NOT NULL,
    lot_id          BIGINT      NOT NULL,
    to_loc_id       BIGINT      NOT NULL,
    drct_qty        BIGINT      NOT NULL,
    cmpl_qty        BIGINT      DEFAULT 0 NOT NULL,
    status          VARCHAR(15) NOT NULL,
    completed_at    TIMESTAMP,
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT ck_ptwy_task_status CHECK (status IN ('DIRECTED', 'DONE', 'CANCELLED')),
    -- 지시 초과 실행을 DB가 거부한다 (용량 계산의 전제)
    CONSTRAINT ck_ptwy_task_qty CHECK (drct_qty > 0 AND cmpl_qty >= 0 AND cmpl_qty <= drct_qty)
);

COMMENT ON TABLE  putaway_task IS
    '적치 지시. 전략이 정한 (라인, Lot, 대상 로케이션, 수량) 배정 결과. 지시는 권고가 아니라 명령이며, 다른 로케이션에 두려면 취소 후 재지시한다';
COMMENT ON COLUMN putaway_task.ib_line_id   IS '적치 대상 입고 라인. 지시 단위가 (라인, Lot) 배치인 이유는 한 라인의 검수분이 여러 Lot에 걸칠 수 있기 때문';
COMMENT ON COLUMN putaway_task.lot_id       IS '적치 대상 Lot. 이 Lot의 스테이징 잔량이 지시 수량의 상한';
COMMENT ON COLUMN putaway_task.to_loc_id    IS '지시된 보관 로케이션. 용량이 모자라면 한 배치가 여러 로케이션으로 1:N 분할된다';
COMMENT ON COLUMN putaway_task.drct_qty     IS '지시 수량';
COMMENT ON COLUMN putaway_task.cmpl_qty     IS '실행(실물 MOVE) 완료 수량 누계. 부분 실행 허용 — drct_qty에 도달하면 DONE';
COMMENT ON COLUMN putaway_task.status       IS 'DIRECTED 지시(부분 실행 포함) / DONE 완료 / CANCELLED 취소(cmpl_qty=0일 때만 가능)';
COMMENT ON COLUMN putaway_task.completed_at IS '지시 완료 시각 (DONE 전이 시점)';

CREATE INDEX ix_ptwy_task_line ON putaway_task (ib_line_id);
-- 적재가능수량 계산: 로케이션별 미완료 지시 잔량 SUM(drct_qty - cmpl_qty).
-- 지시는 대부분 금방 DONE이 되므로 DIRECTED만 담는 부분 인덱스로 좁게 유지한다.
CREATE INDEX ix_ptwy_task_open_loc ON putaway_task (to_loc_id) WHERE status = 'DIRECTED';

COMMIT;

-- 검증
--   1) 보관 로케이션에 용량이 다 찼는지 (0건이어야 한다)
--      SELECT COUNT(*) FROM loc WHERE loc_type = 'STORAGE' AND max_qty IS NULL;
--   2) 유통기한 관리 SKU에 입고 기준이 붙었는지 (0건이어야 한다)
--      SELECT COUNT(*) FROM sku WHERE shelf_life_days IS NOT NULL AND ib_life_rate IS NULL;
--   3) 로케이션별 적재가능수량 (지시 도입 전이라 세 번째 항은 아직 0)
--      SELECT l.loc_cd, l.max_qty,
--             COALESCE(SUM(i.on_hand_qty), 0)                          AS on_hand,
--             l.max_qty - COALESCE(SUM(i.on_hand_qty), 0)              AS free_qty
--        FROM loc l LEFT JOIN inv i ON i.loc_id = l.loc_id
--       WHERE l.loc_type = 'STORAGE'
--       GROUP BY l.loc_cd, l.max_qty
--       ORDER BY l.loc_cd;
