-- =====================================================================
-- 존(zon) 마스터 추가
--   전제: docs/migration-catchup-to-schema.sql 까지 적용된 DB (loc.zon_cd · loc.tmp_zon 상태).
--
--   배경 —
--   존은 지금까지 마스터가 없고 loc.zon_cd 문자열과 프론트 상수에만 존재했다.
--   존을 마스터로 승격시켜 온도구분 · 보관유형 · 업무구분을 데이터로 갖게 하고,
--   하위 로케이션이 없을 때만 삭제 가능하게 한다.
--
--   ▣ 전체가 DO 블록 하나다 (BEGIN;/COMMIT; 을 쓰지 않는다) — CLAUDE.md 규칙.
--     전 구간에 존재 확인이 걸려 있어 몇 번을 돌려도 안전하다.
--
--   FK는 걸지 않는다 (FK 0건 정책 유지). loc.zon_cd -> zon.zon_cd 존재 검증은 LocService가 한다.
--   tmp_zon / strg_typ / biz_dvsn 은 공통코드에서 관리하므로 CHECK를 걸지 않는다.
--
--   실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--     - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
-- =====================================================================

DO $zon$
DECLARE
    n int;
BEGIN
    -- 1. 테이블 -------------------------------------------------------
    IF to_regclass('zon') IS NULL THEN
        CREATE TABLE zon (
            zon_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            zon_cd      VARCHAR(20)     NOT NULL,
            zon_nm      VARCHAR(100)    NOT NULL,
            tmp_zon     VARCHAR(10)     NOT NULL,
            strg_typ    VARCHAR(10)     NOT NULL,
            biz_dvsn    VARCHAR(10)     NOT NULL,
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT uq_zon_cd UNIQUE (zon_cd)
        );

        COMMENT ON TABLE  zon IS '존 마스터. 로케이션의 상위 그룹 (loc.zon_cd가 zon.zon_cd를 느슨하게 참조)';
        COMMENT ON COLUMN zon.zon_cd   IS '존 코드 (업무 식별자, 예: DRY, RCV-STAGE). 하위 로케이션이 문자열로 참조하므로 등록 후 변경 금지';
        COMMENT ON COLUMN zon.zon_nm   IS '존 명 (화면 표시용)';
        COMMENT ON COLUMN zon.tmp_zon  IS '온도구분. 공통코드 TEMP_ZONE (DRY 상온 / CHL 냉장 / FRZ 냉동). 보관 로케이션은 이 값과 loc.tmp_zon이 일치해야 한다';
        COMMENT ON COLUMN zon.strg_typ IS '보관유형. 공통코드 STRG_TYP (RACK 랙 / FLAT 평치 / VRTL 가상)';
        COMMENT ON COLUMN zon.biz_dvsn IS '업무구분. 공통코드 BIZ_DVSN (INB 입고작업 / OUTB 출고작업 / STRG 보관 / PIKNG 피킹 / RTNGS 반품 / WRK 작업)';

        RAISE NOTICE 'zon 테이블 생성';
    ELSE
        RAISE NOTICE 'zon 테이블 이미 존재 — 건너뜀';
    END IF;

    COMMENT ON COLUMN loc.zon_cd IS '존 코드. zon.zon_cd를 참조하지만 FK는 없다 — 존재 검증은 LocService가 한다';

    -- 2. 공통코드 (화면 드롭다운과 엑셀 코드표가 이걸 읽는다) -----------
    INSERT INTO code_group (grp_cd, grp_nm, description) VALUES
        ('STRG_TYP', '보관유형', '존의 물리 보관 형태'),
        ('BIZ_DVSN', '업무구분', '존이 담당하는 업무')
    ON CONFLICT (grp_cd) DO NOTHING;

    INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES
        ('STRG_TYP', 'RACK',  '랙',       1),
        ('STRG_TYP', 'FLAT',  '평치',     2),
        ('STRG_TYP', 'VRTL',  '가상',     3),
        ('BIZ_DVSN', 'INB',   '입고작업', 1),
        ('BIZ_DVSN', 'OUTB',  '출고작업', 2),
        ('BIZ_DVSN', 'STRG',  '보관',     3),
        ('BIZ_DVSN', 'PIKNG', '피킹',     4),
        ('BIZ_DVSN', 'RTNGS', '반품',     5),
        ('BIZ_DVSN', 'WRK',   '작업',     6)
    ON CONFLICT (grp_cd, code_cd) DO NOTHING;

    RAISE NOTICE '공통코드 STRG_TYP · BIZ_DVSN 반영';

    -- 3. 백필 ---------------------------------------------------------
    -- 기존 loc 행들이 이미 이 존 코드들을 참조하고 있다.
    -- 백필하지 않으면 적용 직후 모든 로케이션 저장이 "존재하지 않는 존입니다"로 실패한다.
    INSERT INTO zon (zon_cd, zon_nm, tmp_zon, strg_typ, biz_dvsn) VALUES
        ('RCV-STAGE',  '입고 스테이징', 'DRY', 'VRTL', 'INB'),
        ('SHIP-STAGE', '출고 스테이징', 'DRY', 'VRTL', 'OUTB'),
        ('DRY',        '상온 보관존',   'DRY', 'RACK', 'STRG'),
        ('CHL',        '냉장 보관존',   'CHL', 'RACK', 'STRG'),
        ('FRZ',        '냉동 보관존',   'FRZ', 'RACK', 'STRG')
    ON CONFLICT (zon_cd) DO NOTHING;

    -- 4. 검증 ---------------------------------------------------------
    -- 위 5건으로 커버되지 않는 존 코드가 loc 에 남아 있으면 애플리케이션이 저장을 거부한다.
    SELECT count(*) INTO n
      FROM loc l WHERE NOT EXISTS (SELECT 1 FROM zon z WHERE z.zon_cd = l.zon_cd);
    IF n > 0 THEN
        RAISE EXCEPTION '존 마스터에 없는 zon_cd 를 쓰는 로케이션이 % 건 있다. '
                        '해당 존을 zon 에 추가한 뒤 다시 실행할 것: %',
            n, (SELECT string_agg(DISTINCT l.zon_cd, ', ')
                  FROM loc l WHERE NOT EXISTS (SELECT 1 FROM zon z WHERE z.zon_cd = l.zon_cd));
    END IF;

    -- 보관 로케이션의 온도대가 존 온도대와 어긋난 행 (LocService 신규 규칙에 걸릴 데이터).
    -- 막지는 않고 알리기만 한다 — 기존 데이터를 어떻게 정리할지는 업무 판단이다.
    SELECT count(*) INTO n
      FROM loc l JOIN zon z ON z.zon_cd = l.zon_cd
     WHERE l.loc_typ = 'STORAGE' AND l.tmp_zon <> z.tmp_zon;
    IF n > 0 THEN
        RAISE WARNING '보관 로케이션 % 건의 온도대가 존 온도대와 다르다. '
                      '로케이션 화면에서 저장하려 하면 거부된다.', n;
    END IF;

    RAISE NOTICE '존 마스터 마이그레이션 완료';
END
$zon$;

-- =====================================================================
-- 적용 후 확인
--   1) 존 5건
--      SELECT * FROM zon ORDER BY zon_cd;
--   2) 고아 로케이션 0건 (위 DO 블록이 이미 막지만 재확인용)
--      SELECT DISTINCT l.zon_cd FROM loc l
--       WHERE NOT EXISTS (SELECT 1 FROM zon z WHERE z.zon_cd = l.zon_cd);
--   3) 공통코드 9건
--      SELECT * FROM code_detail WHERE grp_cd IN ('STRG_TYP','BIZ_DVSN') ORDER BY grp_cd, srt_seq;
-- =====================================================================
