-- =====================================================================
-- 재고조사(실사) 도입 — inv_stktk(조사 헤더) / inv_stktk_ln(조사 라인) 2테이블.
--
-- 현재 라이브 상태(migration-inv-hld.sql 적용) → schema.sql 상태.
-- 근거: docs/design.md 「재고조사(실사)」 (2026-08-03 확정).
--   - 건별 즉시 조정 화면을 두지 않는다 — 재고 수량 정정의 유일한 경로가 조사(실사)다.
--     특정 재고 하나의 정정도 범위를 좁게 잡은 조사로 수행한다(입고 확정 후 수량 정정 포함).
--   - 실적 테이블 없음 — 실적의 실체는 inv_hist의 ADJUST 행(rfn_doc_typ=INV_STKTK, rfn_doc_no=조사번호).
--     「이력 합계 = 스냅샷」 불변식은 확정 트랜잭션이 그대로 지킨다.
--   - 조정수량 = 실사수량(stktk_qty) - 확정시점 전산수량(cfm_sys_qty). 확정 시 재고 행 락을 걸고
--     전산수량을 다시 읽으므로 확정 후 on_hand_qty는 실사수량과 정확히 일치한다.
--     조사 생성 시점 스냅샷(sys_qty)은 「조사 시작 때는 얼마였나」의 기록으로만 남는다.
--   - 차이 0 라인은 ADJUST를 남기지 않는다(ck_invh_qty가 변동 0 금지). 사유도 필요 없다.
--
-- 실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--   - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--   - 재실행 안전 — 존재 확인을 걸어 이미 적용된 항목은 건너뛴다
-- =====================================================================
DO $mig$
BEGIN
    -- 1. inv_stktk (조사 헤더) ----------------------------------------------
    IF to_regclass('inv_stktk') IS NULL THEN
        CREATE TABLE inv_stktk (
            inv_stktk_id BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            stktk_no    VARCHAR(30)     NOT NULL,
            zon_cd      VARCHAR(20),
            loc_id      BIGINT,
            prod_id     BIGINT,
            status      VARCHAR(15)     NOT NULL,
            cfm_dt      TIMESTAMP,
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT uq_inv_stktk_no UNIQUE (stktk_no),
            CONSTRAINT ck_inv_stktk_status CHECK (status IN ('CREATED', 'CONFIRMED', 'CANCELLED'))
        );

        COMMENT ON TABLE  inv_stktk IS '재고조사(실사) 헤더. 상태는 워크플로 단계만(작성 → 확정) — 「부분확정」은 두지 않는다. 확정 후 재정정은 조사를 되열지 않고 새 조사를 만든다(append-only). 확정이 남기는 것은 inv_hist의 ADJUST 행(rfn_doc_typ=INV_STKTK, rfn_doc_no=stktk_no)';
        COMMENT ON COLUMN inv_stktk.stktk_no IS '재고조사 번호 (건당 유일 — 라인은 inv_stktk_ln). nbr_rule STKTK_NO 채번. inv_hist.rfn_doc_no로 실려 조사 ↔ 조정 이력이 매칭된다';
        COMMENT ON COLUMN inv_stktk.zon_cd   IS '조사 범위 — 존 코드. NULL이면 존 조건 없음. 라인 생성에 쓴 조건을 그대로 보존해 「무엇을 조사했나」를 남긴다';
        COMMENT ON COLUMN inv_stktk.loc_id   IS '조사 범위 — 로케이션. NULL이면 로케이션 조건 없음. 범위 3필드가 모두 NULL이면 전 보관 로케이션 조사';
        COMMENT ON COLUMN inv_stktk.prod_id  IS '조사 범위 — 상품. NULL이면 상품 조건 없음';
        COMMENT ON COLUMN inv_stktk.status   IS 'CREATED 작성(실사수량 입력 중) / CONFIRMED 확정(ADJUST 반영 완료) / CANCELLED 취소(확정 전 폐기 — 라인 보존, putaway_task 선례)';
        COMMENT ON COLUMN inv_stktk.cfm_dt   IS '확정 시각 (CONFIRMED 전이 시점)';

        CREATE INDEX ix_inv_stktk_status ON inv_stktk (status);

        RAISE NOTICE 'inv_stktk 테이블 생성';
    ELSE
        RAISE NOTICE 'inv_stktk 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 2. inv_stktk_ln (조사 라인) -------------------------------------------
    IF to_regclass('inv_stktk_ln') IS NULL THEN
        CREATE TABLE inv_stktk_ln (
            inv_stktk_ln_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            inv_stktk_id BIGINT         NOT NULL,
            prod_id     BIGINT          NOT NULL,
            loc_id      BIGINT          NOT NULL,
            lot_id      BIGINT          NOT NULL,
            sys_qty     BIGINT          NOT NULL,
            stktk_qty   BIGINT,
            cfm_sys_qty BIGINT,
            rsn_cd      VARCHAR(10),
            rsn_dscr    VARCHAR(200),
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT uq_inv_stktk_ln UNIQUE (inv_stktk_id, prod_id, loc_id, lot_id),
            CONSTRAINT ck_inv_stktk_ln_qty CHECK (
                sys_qty >= 0
                AND (stktk_qty IS NULL OR stktk_qty >= 0)
                AND (cfm_sys_qty IS NULL OR cfm_sys_qty >= 0)
            )
        );

        COMMENT ON TABLE  inv_stktk_ln IS '재고조사 라인. 재고 키 단위. 조정수량 = stktk_qty - cfm_sys_qty (파생, 컬럼 아님). 실사수량 미입력(NULL) 라인은 「미조사」로 확정에서 건너뛴다 — 0(실물 없음)과 구분된다';
        COMMENT ON COLUMN inv_stktk_ln.sys_qty     IS '조사 생성 시점의 전산수량 스냅샷 (on_hand_qty). 조정 계산의 기준이 아니라 「조사 시작 때는 얼마였나」의 기록 — 확정 기준은 cfm_sys_qty다';
        COMMENT ON COLUMN inv_stktk_ln.stktk_qty   IS '실사수량 (실물을 센 값). NULL = 미조사(확정 시 건너뜀), 0 = 실물 없음(전량 차감). 출고단위 기준';
        COMMENT ON COLUMN inv_stktk_ln.cfm_sys_qty IS '확정 시점에 재고 행 락을 걸고 다시 읽은 전산수량(= 조정전수량). 조정수량 = stktk_qty - cfm_sys_qty이므로 확정 후 on_hand_qty는 실사수량과 정확히 일치한다. 조사 중 다른 업무로 재고가 변해도 실사값이 이긴다 (2026-08-03 결정 — 확정시점 기준). 확정 전에는 NULL';
        COMMENT ON COLUMN inv_stktk_ln.rsn_cd      IS '조정사유 코드 (공통코드 ADJ_RSN). 차이가 0이 아닌 라인만 필수 — 차이 0 라인은 ADJUST 자체가 없으므로 사유도 없다. ETC(기타)일 때만 rsn_dscr 필수';
        COMMENT ON COLUMN inv_stktk_ln.rsn_dscr    IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';

        CREATE INDEX ix_inv_stktk_ln_stktk ON inv_stktk_ln (inv_stktk_id);
        CREATE INDEX ix_inv_stktk_ln_prod ON inv_stktk_ln (prod_id);

        RAISE NOTICE 'inv_stktk_ln 테이블 생성';
    ELSE
        RAISE NOTICE 'inv_stktk_ln 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 3. inv_hist.rfn_doc_typ 코멘트 (CHECK 없는 컬럼이라 DDL 변경은 없다) -------
    COMMENT ON COLUMN inv_hist.rfn_doc_typ IS '참조 문서 유형 (INBOUND / OUTBOUND / INV_MOV 이동지시 / INV_STKTK 재고조사 / 수동조정 시 NULL)';
    RAISE NOTICE 'inv_hist.rfn_doc_typ 코멘트에 INV_STKTK 추가';

    -- 4. 공통코드 시드 (조정사유) ---------------------------------------------
    -- 조정사유에는 조사 전용 사유만 담는다 — 세트화·단위대체 같은 타 업무 사유를 섞으면
    -- 화면이 매번 걸러내야 한다.
    IF NOT EXISTS (SELECT 1 FROM code_group WHERE grp_cd = 'ADJ_RSN') THEN
        INSERT INTO code_group (grp_cd, grp_nm, dscr)
        VALUES ('ADJ_RSN', '재고조정 사유', '재고조사 확정 시 차이 라인의 조정 사유 (inv_stktk_ln.rsn_cd). 차이가 0이 아닌 라인만 필수이며, ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'DAMG', '파손', 1);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'LOSS', '분실', 2);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'ERR_WRK', '작업오류', 3);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'INIT', '기초재고', 4);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'ETC', '기타', 5);
        RAISE NOTICE '공통코드 ADJ_RSN 시드';
    ELSE
        RAISE NOTICE '공통코드 ADJ_RSN 이미 존재 — 건너뜀';
    END IF;

    -- 5. 채번 규칙 시드 -----------------------------------------------------
    IF NOT EXISTS (SELECT 1 FROM nbr_rule WHERE rule_cd = 'STKTK_NO') THEN
        INSERT INTO nbr_rule (rule_cd, rule_nm, prfx, prfx_dlmt, de_dlmt, seq_dgt, dync_ky_typ)
        VALUES ('STKTK_NO', '재고조사 번호', 'ST', '-', '-', 3, 'DAY');
        RAISE NOTICE 'nbr_rule STKTK_NO 시드';
    ELSE
        RAISE NOTICE 'nbr_rule STKTK_NO 이미 존재 — 건너뜀';
    END IF;
END
$mig$;

-- 확인:
--   SELECT to_regclass('inv_stktk'), to_regclass('inv_stktk_ln');
--   SELECT * FROM nbr_rule WHERE rule_cd = 'STKTK_NO';
--   SELECT * FROM code_detail WHERE grp_cd = 'ADJ_RSN' ORDER BY srt_seq;
--   -- 확정 후 대사: 조사가 남긴 조정 이력
--   SELECT * FROM inv_hist WHERE rfn_doc_typ = 'INV_STKTK' ORDER BY inv_hist_id DESC;
