-- =====================================================================
-- 재고 보류 도입 — inv.hld_qty(보류수량) + 보류 3테이블(inv_hld / inv_hld_acrst / inv_hld_rlz_acrst).
--
-- 현재 라이브 상태(migration-inv-mov-task.sql·migration-inv-mov-dvsn.sql 적용) → schema.sql 상태.
-- 근거: docs/design.md 「재고 보류」 (2026-08-03 확정).
--   - 보류는 상태가 아니라 수량 — 재고상태 컬럼 없이 inv.hld_qty가 가용재고에서 뺀다.
--   - 재고수량(on_hand) = 가용 + 예약(aloc) + 보류(hld). 예약과 보류는 배타(보류는 가용에서만).
--     ck_inv_qty가 aloc_qty + hld_qty <= on_hand_qty로 확장된다.
--   - 보류/해제는 물리 이동이 아니라 inv_hist에 기록하지 않는다. 원장은 전용 실적 2테이블 —
--     「물리 변동 실적 테이블 없음」 원칙의 유일한 예외 (사유 히스토리 보존 요구).
--   - 항등식: inv.hld_qty = SUM(HELD 건의 hld_qty - rlz_qty) — aloc_qty 항등식과 별도 대사 축.
--
-- 실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--   - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--   - 재실행 안전 — 존재 확인을 걸어 이미 적용된 항목은 건너뛴다
-- =====================================================================
DO $mig$
BEGIN
    -- 1. inv.hld_qty 컬럼 + ck_inv_qty 확장 ---------------------------------
    ALTER TABLE inv ADD COLUMN IF NOT EXISTS hld_qty BIGINT DEFAULT 0 NOT NULL;

    -- CHECK 교체 (DROP + ADD — 재실행하면 같은 정의로 다시 걸린다)
    ALTER TABLE inv DROP CONSTRAINT IF EXISTS ck_inv_qty;
    ALTER TABLE inv ADD CONSTRAINT ck_inv_qty
        CHECK (on_hand_qty >= 0 AND aloc_qty >= 0 AND hld_qty >= 0 AND aloc_qty + hld_qty <= on_hand_qty);

    COMMENT ON TABLE  inv IS '현재고 스냅샷. 키: 상품+Loc+Lot. 재고수량(on_hand) = 가용 + 예약(aloc) + 보류(hld). 가용재고 = on_hand - aloc - hld (파생값, 컬럼 아님)';
    COMMENT ON COLUMN inv.hld_qty IS '보류 수량 — 가용재고에서 뺀다(예약과 배타: 가용에서만 잡고, 예약분은 보류 불가). 물리 이동이 아니므로 이력에 기록하지 않고, 원장은 inv_hld/inv_hld_acrst/inv_hld_rlz_acrst가 담당. 항등식: hld_qty = SUM(HELD 건의 hld_qty - rlz_qty) (대사 대상)';
    RAISE NOTICE 'inv.hld_qty 컬럼 + ck_inv_qty 확장';

    -- 2. inv_hld (보류 건) --------------------------------------------------
    IF to_regclass('inv_hld') IS NULL THEN
        CREATE TABLE inv_hld (
            inv_hld_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            hld_no      VARCHAR(30)     NOT NULL,
            prod_id     BIGINT          NOT NULL,
            loc_id      BIGINT          NOT NULL,
            lot_id      BIGINT          NOT NULL,
            hld_qty     BIGINT          NOT NULL,
            rlz_qty     BIGINT          DEFAULT 0 NOT NULL,
            rsn_cd      VARCHAR(10)     NOT NULL,
            rsn_dscr    VARCHAR(200),
            status      VARCHAR(15)     NOT NULL,
            rlz_dt      TIMESTAMP,
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT uq_inv_hld_no UNIQUE (hld_no),
            CONSTRAINT ck_inv_hld_status CHECK (status IN ('HELD', 'RELEASED')),
            CONSTRAINT ck_inv_hld_qty CHECK (hld_qty > 0 AND rlz_qty >= 0 AND rlz_qty <= hld_qty)
        );

        COMMENT ON TABLE  inv_hld IS '재고 보류 건. 등록 즉시 발효(지시→확정 2단계 아님) — inv.hld_qty 증가와 한 트랜잭션. 잔량 = hld_qty - rlz_qty 파생. 전량 해제돼도 행 보존(RELEASED 전이) — putaway_task 선례. 항등식: inv.hld_qty = SUM(HELD 건의 잔량)';
        COMMENT ON COLUMN inv_hld.hld_no   IS '보류 번호 (건당 유일 — 라인 구조 없음). nbr_rule HLD_NO 채번';
        COMMENT ON COLUMN inv_hld.prod_id  IS '보류 대상 상품. 재고 키(상품+Loc+Lot) 그대로 담는다 (inv_mov_task와 같은 형태)';
        COMMENT ON COLUMN inv_hld.hld_qty  IS '보류 수량. 등록 시점 가용재고(on_hand - aloc - hld) 이내 — 예약분은 보류 불가(배타)';
        COMMENT ON COLUMN inv_hld.rlz_qty  IS '해제 완료 수량 누계. 부분 해제 허용 — hld_qty에 도달하면 RELEASED';
        COMMENT ON COLUMN inv_hld.rsn_cd   IS '보류 사유 코드 (공통코드 HLD_RSN). ETC(기타)일 때만 rsn_dscr 필수';
        COMMENT ON COLUMN inv_hld.rsn_dscr IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';
        COMMENT ON COLUMN inv_hld.status   IS 'HELD 보류중(부분 해제 포함) / RELEASED 전량 해제. 취소 상태 없음 — 오등록도 해제(사유: 오등록)로 흡수한다(등록 즉시 발효라 실행 전 취소 구간이 없다)';
        COMMENT ON COLUMN inv_hld.rlz_dt   IS '전량 해제 시각 (RELEASED 전이 시점)';

        CREATE UNIQUE INDEX uq_inv_hld_open_rsn ON inv_hld (prod_id, loc_id, lot_id, rsn_cd) WHERE status = 'HELD';
        CREATE INDEX ix_inv_hld_prod ON inv_hld (prod_id);

        RAISE NOTICE 'inv_hld 테이블 생성';
    ELSE
        RAISE NOTICE 'inv_hld 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 3. inv_hld_acrst (보류 실적) ------------------------------------------
    IF to_regclass('inv_hld_acrst') IS NULL THEN
        CREATE TABLE inv_hld_acrst (
            inv_hld_acrst_id BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            hld_no      VARCHAR(30)     NOT NULL,
            prod_id     BIGINT          NOT NULL,
            loc_id      BIGINT          NOT NULL,
            lot_id      BIGINT          NOT NULL,
            hld_qty     BIGINT          NOT NULL,
            rsn_cd      VARCHAR(10)     NOT NULL,
            rsn_dscr    VARCHAR(200),
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT ck_inv_hld_acrst_qty CHECK (hld_qty > 0)
        );

        COMMENT ON TABLE inv_hld_acrst IS '보류 실적 (등록 append-only 로그). 수정·삭제하지 않는다. hld_no는 inv_hld를 느슨하게 참조 (FK 없음)';

        CREATE INDEX ix_inv_hld_acrst_no ON inv_hld_acrst (hld_no);

        RAISE NOTICE 'inv_hld_acrst 테이블 생성';
    ELSE
        RAISE NOTICE 'inv_hld_acrst 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 4. inv_hld_rlz_acrst (해제 실적) --------------------------------------
    IF to_regclass('inv_hld_rlz_acrst') IS NULL THEN
        CREATE TABLE inv_hld_rlz_acrst (
            inv_hld_rlz_acrst_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            hld_no      VARCHAR(30)     NOT NULL,
            prod_id     BIGINT          NOT NULL,
            loc_id      BIGINT          NOT NULL,
            lot_id      BIGINT          NOT NULL,
            rlz_qty     BIGINT          NOT NULL,
            rsn_cd      VARCHAR(10)     NOT NULL,
            rsn_dscr    VARCHAR(200),
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT ck_inv_hld_rlz_acrst_qty CHECK (rlz_qty > 0)
        );

        COMMENT ON TABLE inv_hld_rlz_acrst IS '보류 해제 실적 (append-only 로그). 해제는 특정 보류 건(hld_no)을 지목하며 부분 해제 허용 — N번 해제면 N행. rsn_cd는 공통코드 HLD_RLZ_RSN, ETC일 때만 rsn_dscr 필수';

        CREATE INDEX ix_inv_hld_rlz_acrst_no ON inv_hld_rlz_acrst (hld_no);

        RAISE NOTICE 'inv_hld_rlz_acrst 테이블 생성';
    ELSE
        RAISE NOTICE 'inv_hld_rlz_acrst 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 5. 공통코드 시드 (보류사유·해제사유) ------------------------------------
    IF NOT EXISTS (SELECT 1 FROM code_group WHERE grp_cd = 'HLD_RSN') THEN
        INSERT INTO code_group (grp_cd, grp_nm, description)
        VALUES ('HLD_RSN', '보류사유', '재고 보류 등록 사유 (inv_hld.rsn_cd). ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'QLTY', '품질이상', 1);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'DAMG', '파손', 2);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'EXPIRY', '유통기한', 3);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'ETC', '기타', 4);
        RAISE NOTICE '공통코드 HLD_RSN 시드';
    ELSE
        RAISE NOTICE '공통코드 HLD_RSN 이미 존재 — 건너뜀';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM code_group WHERE grp_cd = 'HLD_RLZ_RSN') THEN
        INSERT INTO code_group (grp_cd, grp_nm, description)
        VALUES ('HLD_RLZ_RSN', '보류 해제사유', '재고 보류 해제 사유 (inv_hld_rlz_acrst.rsn_cd). 등록 사유와 별개 그룹 — 「왜 묶었나」와 「왜 풀었나」는 다른 질문이다. ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'NRML', '정상 확인', 1);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'ERR_REG', '오등록', 2);
        INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'ETC', '기타', 3);
        RAISE NOTICE '공통코드 HLD_RLZ_RSN 시드';
    ELSE
        RAISE NOTICE '공통코드 HLD_RLZ_RSN 이미 존재 — 건너뜀';
    END IF;

    -- 6. 채번 규칙 시드 -----------------------------------------------------
    IF NOT EXISTS (SELECT 1 FROM nbr_rule WHERE rule_cd = 'HLD_NO') THEN
        INSERT INTO nbr_rule (rule_cd, rule_nm, prfx, prfx_dlmt, de_dlmt, seq_dgt, dync_ky_typ)
        VALUES ('HLD_NO', '보류 번호', 'HD', '-', '-', 3, 'DAY');
        RAISE NOTICE 'nbr_rule HLD_NO 시드';
    ELSE
        RAISE NOTICE 'nbr_rule HLD_NO 이미 존재 — 건너뜀';
    END IF;
END
$mig$;

-- 확인:
--   SELECT column_name FROM information_schema.columns WHERE table_name = 'inv' AND column_name = 'hld_qty';
--   SELECT to_regclass('inv_hld'), to_regclass('inv_hld_acrst'), to_regclass('inv_hld_rlz_acrst');
--   SELECT * FROM nbr_rule WHERE rule_cd = 'HLD_NO';
--   SELECT * FROM code_detail WHERE grp_cd IN ('HLD_RSN', 'HLD_RLZ_RSN') ORDER BY grp_cd, srt_seq;
