-- =====================================================================
-- OMS 입고주문 + 벤더 마스터 도입 delta (PostgreSQL / Supabase)
--   ddl-auto=validate 이므로 앱 부팅 전에 먼저 적용해야 한다.
--
--   현재 DB 상태(= docs/schema.sql)에서 엔티티가 기대하는 상태로 올린다:
--     (A) 벤더를 텍스트(ib_order.vndr_nm)에서 마스터(vendor) + FK로 승격
--     (B) OMS 입고주문(oms_ib_order/oms_ib_line) 도입
--     (C) 주문:유효 ASN = 1:1 을 DB가 강제
--
--   순서가 핵심이다. NOT NULL은 기존 행을 채운 뒤에야 걸 수 있다.
--     1) vendor 생성 → 2) 기존 vndr_nm distinct 값으로 벤더 backfill
--     3) ib_order.vendor_id 채우고 NOT NULL → 4) oms_* 생성
--     5) 기존 ASN에 상위 주문 backfill → 6) oms_ib_order_id NOT NULL
--     7) vndr_nm 제거 (backfill이 매칭 키로 쓰므로 가장 마지막)
--
--   ※ 별도 파일이던 "확정→변환" 전환(confirmed_at → converted_at)은 여기에 흡수돼 있다.
--
--   실행: Supabase 대시보드 › SQL Editor 에 붙여넣고 Run
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- (A) 벤더 마스터
-- ---------------------------------------------------------------------

CREATE TABLE vendor (
    vendor_id   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vndr_cd     VARCHAR(30)     NOT NULL,
    vndr_nm     VARCHAR(100)    NOT NULL,
    mgr_nm      VARCHAR(50),
    tel_no      VARCHAR(30),
    use_yn      CHAR(1)         DEFAULT 'Y' NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_vndr_cd UNIQUE (vndr_cd),
    CONSTRAINT ck_vendor_use_yn CHECK (use_yn IN ('Y', 'N'))
);

COMMENT ON TABLE  vendor IS '벤더(납품처) 마스터. 입고주문·입고예정의 거래처. 거래 종료는 삭제가 아니라 use_yn=N';
COMMENT ON COLUMN vendor.vndr_cd IS '벤더 코드 (업무 식별자, 예: VD-0001). 서버가 시퀀스로 채번';
COMMENT ON COLUMN vendor.use_yn  IS '사용 여부. N이면 신규 주문에서 선택 불가 — 과거 주문의 참조는 그대로 유지된다';

CREATE SEQUENCE vndr_cd_seq START WITH 1 INCREMENT BY 1;

-- 기존 ib_order.vndr_nm의 distinct 값으로 벤더 소급 생성.
-- 표기가 흔들린 값도 그대로 한 건씩 올라온다 — 이게 정확히 텍스트 보관의 문제였으므로
-- 적용 후 벤더 관리 화면에서 use_yn='N'으로 정리할 것.
-- (ib_order가 비어 있으면 아무것도 생성되지 않는다 — 그때는 seed로 벤더를 넣어야 한다)
INSERT INTO vendor (vndr_cd, vndr_nm)
SELECT 'VD-' || LPAD(nextval('vndr_cd_seq')::text, 4, '0'), t.vndr_nm
FROM (SELECT DISTINCT vndr_nm FROM ib_order ORDER BY vndr_nm) t;

ALTER TABLE ib_order ADD COLUMN vendor_id BIGINT;

UPDATE ib_order i
SET vendor_id = v.vendor_id
FROM vendor v
WHERE v.vndr_nm = i.vndr_nm;

ALTER TABLE ib_order ALTER COLUMN vendor_id SET NOT NULL;
CREATE INDEX ix_ib_order_vendor ON ib_order (vendor_id);

COMMENT ON COLUMN ib_order.vendor_id IS '납품 벤더 (vendor 참조). 주문에서 그대로 이어받는다 — 확정 시점의 스냅샷이 아니라 같은 마스터를 가리킨다';

-- ---------------------------------------------------------------------
-- (B) OMS 입고주문
-- ---------------------------------------------------------------------

CREATE TABLE oms_ib_order (
    oms_ib_order_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_ib_no    VARCHAR(30)    NOT NULL,
    status       VARCHAR(15)    NOT NULL,
    vendor_id    BIGINT         NOT NULL,
    expct_dt     DATE           NOT NULL,
    converted_at TIMESTAMP,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_oms_ib_no UNIQUE (oms_ib_no),
    CONSTRAINT ck_oms_ib_order_status CHECK (status IN ('CREATED', 'CONVERTED', 'CANCELLED'))
);

COMMENT ON TABLE  oms_ib_order IS '입고주문(벤더 발주) 헤더. 변환 시 ib_order(ASN)를 자동 생성하는 상위 원장';
COMMENT ON COLUMN oms_ib_order.oms_ib_no    IS '입고주문 번호 (업무 식별자, 예: PO-20260723-001). 변환 후 생기는 입고번호(IB-)와는 별개의 채번';
COMMENT ON COLUMN oms_ib_order.status       IS 'CREATED 작성 / CONVERTED 변환완료(=ASN 생성됨) / CANCELLED 취소(변환 전만)';
COMMENT ON COLUMN oms_ib_order.vendor_id    IS '납품 벤더 (vendor 참조). 변환 시 ASN으로 같은 벤더가 복사된다. 이름은 조인으로 얻는다';
COMMENT ON COLUMN oms_ib_order.converted_at IS '변환(ASN 생성) 시각. 변환취소하면 다시 NULL이 된다';

CREATE SEQUENCE oms_ib_no_seq START WITH 1 INCREMENT BY 1;
CREATE INDEX ix_oms_ib_order_vendor ON oms_ib_order (vendor_id);

CREATE TABLE oms_ib_line (
    oms_ib_line_id  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_ib_order_id BIGINT      NOT NULL,
    sku_id          BIGINT      NOT NULL,
    order_qty       BIGINT      NOT NULL,
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT ck_oms_ib_line_qty CHECK (order_qty > 0)
);

COMMENT ON TABLE  oms_ib_line IS '입고주문 라인. 변환 시 ib_line으로 1:1 복사된다 (order_qty → expct_qty)';

CREATE INDEX ix_oms_ib_line_order ON oms_ib_line (oms_ib_order_id);

ALTER TABLE ib_order ADD COLUMN oms_ib_order_id BIGINT;

-- 기존 ASN → 상위 입고주문 소급 생성.
-- 이미 창고로 나간 예정이므로 주문 상태는 CONVERTED로 만든다.
-- 취소된 ASN도 "주문은 변환됐고 이후 창고에서 취소된" 이력이라 동일하게 CONVERTED.
DO $$
DECLARE
    r        RECORD;
    v_oms_id BIGINT;
BEGIN
    FOR r IN SELECT ib_order_id, vendor_id, expct_dt, created_at FROM ib_order ORDER BY ib_order_id LOOP
        INSERT INTO oms_ib_order (oms_ib_no, status, vendor_id, expct_dt, converted_at)
            VALUES ('PO-' || TO_CHAR(r.expct_dt, 'YYYYMMDD') || '-' || LPAD(nextval('oms_ib_no_seq')::text, 3, '0'),
                    'CONVERTED', r.vendor_id, r.expct_dt, r.created_at)
            RETURNING oms_ib_order_id INTO v_oms_id;

        INSERT INTO oms_ib_line (oms_ib_order_id, sku_id, order_qty)
            SELECT v_oms_id, sku_id, expct_qty FROM ib_line WHERE ib_order_id = r.ib_order_id;

        UPDATE ib_order SET oms_ib_order_id = v_oms_id WHERE ib_order_id = r.ib_order_id;
    END LOOP;
END $$;

ALTER TABLE ib_order ALTER COLUMN oms_ib_order_id SET NOT NULL;

COMMENT ON COLUMN ib_order.oms_ib_order_id IS '이 ASN을 발생시킨 입고주문. NOT NULL — 주문 없는 입고예정은 존재할 수 없다(무결성은 애플리케이션이 보증, FK 없음). JPA는 연관관계가 아닌 스칼라로 매핑한다(패키지 의존을 omsback → wmsback 한 방향으로 유지)';

-- ---------------------------------------------------------------------
-- (C) 주문 하나에 유효한 ASN은 하나
-- ---------------------------------------------------------------------

-- 변환취소는 ASN 행을 지우지 않고 status='CANCELLED'로 남긴다 (언제 왜 물렸는지 추적용).
-- 그래서 통짜 UNIQUE는 못 쓴다 — 재변환하면 같은 주문에 행이 하나 더 생기기 때문이다.
-- 취소분을 제외한 부분 유니크 인덱스가 정확히 "유효한 ASN은 하나"를 표현한다.
--
-- 이게 없으면 같은 주문에 변환 요청이 동시에 들어올 때 두 트랜잭션이 모두 CREATED를 읽고
-- 통과해 ASN이 2건 생긴다 (입고 예정수량이 2배가 된다).
CREATE UNIQUE INDEX uq_ib_order_oms_active
    ON ib_order (oms_ib_order_id)
    WHERE status <> 'CANCELLED';

-- 취소분까지 포함한 역추적(주문의 ASN 이력 전체)은 여전히 필요하므로 일반 인덱스도 남긴다
CREATE INDEX ix_ib_order_oms ON ib_order (oms_ib_order_id);

-- ---------------------------------------------------------------------
-- (D) 텍스트 벤더명 제거 — 위 backfill들이 매칭 키로 쓰므로 가장 마지막
-- ---------------------------------------------------------------------

ALTER TABLE ib_order DROP COLUMN vndr_nm;

COMMIT;

-- 검증: 아래 쿼리가 모두 0건이어야 한다
--   SELECT COUNT(*) FROM ib_order WHERE oms_ib_order_id IS NULL;
--   SELECT COUNT(*) FROM ib_order WHERE vendor_id IS NULL;
--   SELECT COUNT(*) FROM ib_order i WHERE NOT EXISTS
--       (SELECT 1 FROM oms_ib_order o WHERE o.oms_ib_order_id = i.oms_ib_order_id);
-- 승격된 벤더 확인:
--   SELECT vndr_cd, vndr_nm FROM vendor ORDER BY vendor_id;
