-- =====================================================================
-- 증분 마이그레이션: 전략 시스템 2차 — 출고 웨이브 전략
--   대상: migration-add-stgy-inspection-putaway.sql 까지 적용된 라이브 DB → docs/schema.sql 상태
--
--   내용: ① wav_stgy 신설  ② outb_wave에 전략 출처 2컬럼  ③ outb_order에 편입 출처 1컬럼
--         ④ outb_order에 웨이브 조건 기준값 2컬럼(출고유형·차량편수) + 공통코드 2그룹
--
--   재실행 안전: 모든 생성에 IF NOT EXISTS / 카탈로그 존재 확인을 건다.
--   BEGIN/COMMIT 없이 DO 블록 하나다 — DBeaver에서 실패 시 죽은 트랜잭션(25P02)이
--   연결에 남지 않게 하기 위함 (CLAUDE.md 「데이터베이스」).
--
--   stgy_rvsn·stgy_exec_log의 ck_*_typ는 1차에서 이미 'WAV'를 포함하므로 손대지 않는다.
--   시드 없음 — 전략은 관리자가 화면에서 만든다. 채번 규칙도 없다(대리키 테이블).
-- =====================================================================

DO $mig$
BEGIN

    -- 1. 웨이브 전략 (테이블 1개로 종결 — 조건그룹은 JSONB)
    CREATE TABLE IF NOT EXISTS wav_stgy (
        wav_stgy_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        stgy_nm      VARCHAR(100) NOT NULL,
        prty         INTEGER      DEFAULT 0 NOT NULL,
        cond_grp     JSONB        NOT NULL,
        last_rvsn_no BIGINT       DEFAULT 1 NOT NULL,
        created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
        updated_at   TIMESTAMP,
        updated_by   VARCHAR(30),
        CONSTRAINT ck_wav_stgy_prty CHECK (prty >= 0),
        CONSTRAINT ck_wav_stgy_cond_grp CHECK (
            jsonb_typeof(cond_grp) = 'array' AND jsonb_array_length(cond_grp) > 0
        )
    );

    -- 2. outb_wave — 이 웨이브를 만든 전략·리비전. 둘 다 NULL = 화면에서 수동 생성
    ALTER TABLE outb_wave ADD COLUMN IF NOT EXISTS wav_stgy_id BIGINT;
    ALTER TABLE outb_wave ADD COLUMN IF NOT EXISTS rvsn_no     BIGINT;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_outb_wave_stgy') THEN
        ALTER TABLE outb_wave ADD CONSTRAINT ck_outb_wave_stgy
            CHECK ((wav_stgy_id IS NULL) = (rvsn_no IS NULL));
    END IF;

    -- 3. outb_order — 웨이브 편입 출처. 기존 편성분은 수동 편성이므로 MANUAL로 채운다
    ALTER TABLE outb_order ADD COLUMN IF NOT EXISTS wav_reg_typ VARCHAR(10);

    UPDATE outb_order
       SET wav_reg_typ = 'MANUAL'
     WHERE wav_id IS NOT NULL
       AND wav_reg_typ IS NULL;

    -- 편성 해제·주문 취소 시 wav_id와 함께 비워지는 컬럼이라 짝을 CHECK로 고정한다
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_outb_order_wav_reg') THEN
        ALTER TABLE outb_order ADD CONSTRAINT ck_outb_order_wav_reg
            CHECK ((wav_id IS NULL AND wav_reg_typ IS NULL)
                   OR (wav_id IS NOT NULL AND wav_reg_typ IN ('STGY', 'MANUAL')));
    END IF;

    -- 4. outb_order — 웨이브 편성 조건의 기준값. 기존 행은 DEFAULT로 일반출고가 되고 배차는 미정(NULL)
    ALTER TABLE outb_order ADD COLUMN IF NOT EXISTS outb_typ   VARCHAR(10) DEFAULT 'NRML' NOT NULL;
    ALTER TABLE outb_order ADD COLUMN IF NOT EXISTS vhcl_fltno VARCHAR(10);

    -- 5. 공통코드 (값 목록의 주인은 코드관리 화면 — 컬럼에 CHECK를 걸지 않는 이유)
    INSERT INTO code_group (grp_cd, grp_nm, dscr)
        SELECT 'OUTB_TYP', '출고유형', '출고주문의 성격 (outb_order.outb_typ). 웨이브 편성 조건의 기준값'
         WHERE NOT EXISTS (SELECT 1 FROM code_group WHERE grp_cd = 'OUTB_TYP');
    INSERT INTO code_group (grp_cd, grp_nm, dscr)
        SELECT 'VHCL_FLTNO', '차량편수', '출고 배차 차수 (outb_order.vhcl_fltno). 웨이브 편성 조건의 기준값 — 같은 차수에 실릴 주문만 함께 묶는다'
         WHERE NOT EXISTS (SELECT 1 FROM code_group WHERE grp_cd = 'VHCL_FLTNO');

    INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq)
        SELECT v.grp_cd, v.code_cd, v.code_nm, v.srt_seq
          FROM (VALUES
                    ('OUTB_TYP',   'NRML',  '일반출고', 1),
                    ('OUTB_TYP',   'RTNGS', '반품출고', 2),
                    ('VHCL_FLTNO', '1',     '1편',     1),
                    ('VHCL_FLTNO', '2',     '2편',     2),
                    ('VHCL_FLTNO', '3',     '3편',     3)
               ) AS v(grp_cd, code_cd, code_nm, srt_seq)
         WHERE NOT EXISTS (
                   SELECT 1 FROM code_detail d
                    WHERE d.grp_cd = v.grp_cd AND d.code_cd = v.code_cd);

    -- 6. 코멘트 (재실행해도 무해 — 같은 값 덮어쓰기)
    COMMENT ON TABLE  wav_stgy IS '웨이브 전략. 실행 시 전략마다 웨이브를 1개 만들고 조건에 맞는 미편성 주문을 편입한다. 적치와 달리 "적용대상 1개 선택"이 아니라 전 전략을 prty 순으로 순회하는 유형이라 우선순위 컬럼이 있다';
    COMMENT ON COLUMN wav_stgy.stgy_nm      IS '전략명. 표시용 — 실행에 사용하지 않는다 (이름/조건 불일치는 미리보기가 보완)';
    COMMENT ON COLUMN wav_stgy.prty         IS '실행 순서. 낮을수록 먼저 — 주문은 먼저 실행된 전략이 선점한다(한 주문은 웨이브 1개). 동률은 wav_stgy_id 순으로 결정적이게 처리';
    COMMENT ON COLUMN wav_stgy.cond_grp     IS '조건그룹 [[{fld,op,vals},…],…]. 그룹끼리 OR, 그룹 안 AND. 필드: WaveOrderField enum — STORE 점포 · ODR_DE 주문일';
    COMMENT ON COLUMN wav_stgy.last_rvsn_no IS '마지막 저장 리비전';

    COMMENT ON COLUMN outb_wave.wav_stgy_id  IS '이 웨이브를 만든 웨이브 전략 (느슨한 참조, FK 없음). NULL = 화면에서 수동 생성';
    COMMENT ON COLUMN outb_wave.rvsn_no      IS '생성에 사용된 전략 리비전. stgy_rvsn과 조합해 "그때의 조건"을 재구성한다 (P5)';
    COMMENT ON COLUMN outb_order.wav_reg_typ IS '웨이브 편입 출처. STGY 전략 실행 / MANUAL 화면 수동 편성. NULL = 미편성. 수동 편성을 금지하지 않고 가시화한다 — 전략 조건과 안 맞는 주문이 웨이브에 있는 상황을 화면이 구분 표시';
    COMMENT ON COLUMN outb_order.outb_typ    IS '출고유형 (공통코드 OUTB_TYP — NRML 일반출고 / RTNGS 반품출고). 웨이브 편성 조건의 기준값. CHECK 없음 — 값 목록은 공통코드가 소유하고 존재 검증은 서비스가 한다';
    COMMENT ON COLUMN outb_order.vhcl_fltno  IS '차량편수 (공통코드 VHCL_FLTNO — 1편·2편…). NULL = 배차 미정. 같은 차수에 실릴 주문만 함께 묶기 위한 웨이브 편성 조건';

END
$mig$;
