-- =====================================================================
-- 계량단위(공통코드 UOM 그룹) + 상품 포장(prod_uom) 추가
--   (겸 상품 마스터 정리 — 죽은 컬럼 prod.ib_life_rate 삭제)
--   전제: docs/migration-catchup-to-schema.sql · migration-zon.sql 까지 적용된 DB.
--
--   배경 —
--   지금까지 단위 개념이 스키마에 전혀 없었다. 모든 수량이 단위 없는 BIGINT이고
--   입수량은 상품명 문자열에 갇혀 있었다 ('코카콜라 350ml (24입)').
--   단위를 데이터로 승격시키고, 박스로 받아 낱개로 내보내는 환산을 도입한다.
--
--   ▣ 단위 규약 (이걸 어기면 재고가 조용히 틀어진다)
--     - prod.inb_uom_cd  : 벤더 발주·납품 단위. 이 단위를 쓰는 곳은 oms_ib_line.odr_qty 하나뿐.
--     - prod.outb_uom_cd : 재고 저장 단위. inv · inv_hist · ib_line · putaway_task ·
--                          outb_line · outb_alloc 의 모든 수량 컬럼이 이 단위.
--     - prod_uom.ea_qty  : 그 단위 1개 = 낱개 몇 개. 환산은 이 둘로 파생한다 —
--                          odr_qty × ea_qty(입고단위) / ea_qty(출고단위).
--     환산은 애플리케이션의 한 곳에서만 한다 — OmsIbOrderService.convert() (발주 → ASN).
--     ASN 이후의 검수 · 적치 · 재고 · 출고는 전부 출고단위로만 계산한다.
--
--   ▣ 환산수량을 상품에 한 칸(cnvr_qty)으로 두지 않는 이유는 docs/design.md 「계량단위와 환산」.
--     요약: 한 칸이면 「입고→출고」 한 쌍만 표현되고, 중량(wgt)을 둘 자리가 없어진다.
--
--   ▣ 이 스크립트는 기존 데이터의 의미를 바꾸지 않는다.
--     단위가 없던 상품은 ib=EA / outb=EA / ea_qty=1 로 백필되므로 환산이 항등이다.
--     실제 박스 입고를 쓰려면 적용 후 상품 화면에서 포장을 추가하고 단위를 바꾼다.
--
--   ▣ 전체가 DO 블록 하나다 (BEGIN;/COMMIT; 을 쓰지 않는다) — CLAUDE.md 규칙.
--     전 구간에 존재 확인이 걸려 있어 몇 번을 돌려도 안전하다.
--
--   FK는 걸지 않는다 (FK 0건 정책 유지).
--   prod.inb_uom_cd / outb_uom_cd / prod_uom.uom_cd -> code_detail(grp_cd='UOM'),
--   prod_uom.prod_id -> prod.prod_id. 존재 검증은 ProdService 가 한다.
--   단위 값 목록의 주인이 공통코드라 CHECK 도 걸지 않는다 (코드 추가마다 DDL을 고치지 않기 위함).
--
--   실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--     - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
-- =====================================================================

DO $uom$
DECLARE
    n int;
BEGIN
    -- 1. 단위 목록 = 공통코드 UOM 그룹 -----------------------------------
    -- 전용 마스터(uom 테이블)를 두지 않는다. 화면에서 행 추가 시 단위를 콤보박스로 고르는데,
    -- 그 목록을 다른 코드성 컬럼(온도대·보관유형 등)과 다른 경로로 받을 이유가 없다.
    -- 조회 API 도 기존 것을 그대로 쓴다 — GET /master/codes/UOM.
    INSERT INTO code_group (grp_cd, grp_nm, description)
    VALUES ('UOM', '계량단위', '상품 포장의 단위 (prod_uom.uom_cd · prod.inb_uom_cd · outb_uom_cd)')
    ON CONFLICT (grp_cd) DO NOTHING;

    -- EA(낱개)는 prod.inb_uom_cd · outb_uom_cd 의 DEFAULT 이고 prod_uom.ea_qty 가 세는 기준
    -- 단위이기도 하다 — 다른 코드와 달리 존재가 구조적 전제이므로 지우면 안 된다.
    --
    -- 포장 단위만 둔다 (KG · L 같은 계량 단위는 넣지 않는다). prod_uom.ea_qty 가 「이 단위 1개 =
    -- 낱개 몇 개」인데 kg · 리터에는 그 값이 성립하지 않아서, 목록에 있으면 채울 수 없는 칸이 생긴다.
    -- 중량은 이미 prod_uom.wgt 가 kg 고정으로 들고 있어 단위를 데이터로 둘 이유도 없다.
    -- 정렬순서는 등록 순서일 뿐이라 화면에서 바꿔도 된다. ON CONFLICT DO NOTHING 이므로
    -- 이미 들어간 코드의 이름·순서를 여기서 덮어쓰지 않는다 (화면에서 고친 값이 살아남는다).
    INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES
        ('UOM', 'EA',   '낱개',   1),
        ('UOM', 'BOX',  '박스',   2),
        ('UOM', 'PACK', '팩',     3),
        ('UOM', 'CS',   '케이스', 4),
        ('UOM', 'PLT',  '파렛트', 5),
        ('UOM', 'BAG',  '봉지',   6),
        ('UOM', 'TRAY', '트레이', 7),
        ('UOM', 'SET',  '세트',   8),
        ('UOM', 'DZ',   '다스',   9),
        ('UOM', 'BDL',  '번들',  10),
        ('UOM', 'CTN',  '카톤',  11),
        ('UOM', 'ROLL', '롤',    12)
    ON CONFLICT (grp_cd, code_cd) DO NOTHING;

    RAISE NOTICE '공통코드 UOM 그룹 + 포장 단위 12건 반영';

    -- 2. 상품의 입고/출고단위 -------------------------------------------
    -- 백필을 먼저 하지 않으면 기존 상품 행 때문에 SET NOT NULL 이 실패한다.
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'prod' AND column_name = 'inb_uom_cd') THEN
        ALTER TABLE prod ADD COLUMN inb_uom_cd VARCHAR(20);
        UPDATE prod SET inb_uom_cd = 'EA' WHERE inb_uom_cd IS NULL;
        ALTER TABLE prod ALTER COLUMN inb_uom_cd SET DEFAULT 'EA';
        ALTER TABLE prod ALTER COLUMN inb_uom_cd SET NOT NULL;
        RAISE NOTICE 'prod.inb_uom_cd 추가 (전 상품 EA 백필)';
    ELSE
        RAISE NOTICE 'prod.inb_uom_cd 이미 존재 — 건너뜀';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'prod' AND column_name = 'outb_uom_cd') THEN
        ALTER TABLE prod ADD COLUMN outb_uom_cd VARCHAR(20);
        UPDATE prod SET outb_uom_cd = 'EA' WHERE outb_uom_cd IS NULL;
        ALTER TABLE prod ALTER COLUMN outb_uom_cd SET DEFAULT 'EA';
        ALTER TABLE prod ALTER COLUMN outb_uom_cd SET NOT NULL;
        RAISE NOTICE 'prod.outb_uom_cd 추가 (전 상품 EA 백필)';
    ELSE
        RAISE NOTICE 'prod.outb_uom_cd 이미 존재 — 건너뜀';
    END IF;

    -- 3. 상품 포장 -----------------------------------------------------
    -- (상품, 단위) 한 조합이 한 행. 낱개수량과 중량이 포장마다 다르므로 상품에 칸으로 둘 수 없다.
    IF to_regclass('prod_uom') IS NULL THEN
        CREATE TABLE prod_uom (
            prod_uom_id BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            prod_id     BIGINT          NOT NULL,
            uom_cd      VARCHAR(20)     NOT NULL,
            ea_qty      BIGINT          NOT NULL,
            wgt         NUMERIC(12, 3),
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT uq_prod_uom UNIQUE (prod_id, uom_cd),
            -- 0이나 음수면 환산이 수량을 0으로 만들거나 부호를 뒤집는다. 단위 관련 유일한 DB 방어선이다
            CONSTRAINT ck_prod_uom_ea_qty CHECK (ea_qty >= 1),
            -- NULL은 미측정. 값이 있는데 0 이하면 실측값일 수 없다
            CONSTRAINT ck_prod_uom_wgt CHECK (wgt IS NULL OR wgt > 0)
        );

        COMMENT ON TABLE  prod_uom IS '상품 포장. (상품, 단위) 한 조합이 한 행 — 낱개수량과 중량을 포장마다 갖는다. 입고→출고단위 환산이 여기서 파생된다';
        COMMENT ON COLUMN prod_uom.uom_cd IS '단위 코드. 공통코드 UOM 그룹(code_detail) 참조, FK 없음 — 존재 검증은 ProdService';
        COMMENT ON COLUMN prod_uom.ea_qty IS '이 단위 1개가 낱개 몇 개인가 (예: BOX 1개 = 24). 낱개 그 자체면 1. 환산은 OmsIbOrderService.convert(발주→ASN) 한 곳에서만 일어나고 — odr_qty × ea_qty(입고단위) / ea_qty(출고단위) — ASN 이후의 검수·적치·재고·출고는 전부 출고단위로만 계산한다';
        COMMENT ON COLUMN prod_uom.wgt    IS '이 단위 1개의 중량(kg). 포장재 무게(tare)를 포함한 실측값이며 미측정이면 NULL. 낱개중량 × 낱개수량으로 파생시키지 않는 이유가 tare다';

        RAISE NOTICE 'prod_uom 테이블 생성';
    ELSE
        RAISE NOTICE 'prod_uom 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 백필. Prod.eaQtyOf() 는 지정 단위의 포장 행이 없으면 IllegalStateException 을 던진다 —
    -- 여기서 채우지 않으면 상품 조회도 발주 변환도 전부 그 예외로 죽는다.
    --
    -- 낱개수량이 전부 1이라 환산이 항등이다. 3단계가 기존 상품을 모두 inb=outb=EA 로
    -- 백필하므로 두 번째 갈래는 실제로 0건이고, 입고/출고단위가 이미 갈라진 DB에만 걸린다.
    -- 실제 입수량(BOX 24 등)은 적용 후 상품 화면에서 넣는다.
    INSERT INTO prod_uom (prod_id, uom_cd, ea_qty)
    SELECT p.prod_id, p.outb_uom_cd, 1 FROM prod p
    UNION ALL
    SELECT p.prod_id, p.inb_uom_cd, 1 FROM prod p WHERE p.inb_uom_cd <> p.outb_uom_cd
    ON CONFLICT (prod_id, uom_cd) DO NOTHING;

    GET DIAGNOSTICS n = ROW_COUNT;
    RAISE NOTICE '포장 % 건 추가 — 낱개수량 1 (환산 항등, 기존 행은 건드리지 않음)', n;

    -- 4. 옛 uom 마스터 제거 ---------------------------------------------
    -- 이 스크립트의 이전 버전이 만들었던 전용 테이블. 값 목록이 공통코드와 두 벌이 되므로 지운다.
    -- 코드값(EA/BOX/…)은 1단계에서 그대로 재현했고, 상품이 참조하는 건 문자열이라 영향이 없다.
    --
    -- 막아야 하는 건 "쓰이고 있는데 공통코드에 없는" 단위뿐이다. 옛 시드가 넣은 KG · L 처럼
    -- 아무 상품도 안 쓰는 코드는 그냥 사라져도 된다 — 계량 단위는 의도적으로 뺐다(1단계 주석).
    -- 상품 참조를 보려면 prod_uom 이 있어야 해서 이 검사가 3단계 뒤에 온다.
    IF to_regclass('uom') IS NOT NULL THEN
        SELECT count(*) INTO n FROM uom u
         WHERE NOT EXISTS (SELECT 1 FROM code_detail c
                            WHERE c.grp_cd = 'UOM' AND c.code_cd = u.uom_cd)
           AND (EXISTS (SELECT 1 FROM prod p
                         WHERE p.inb_uom_cd = u.uom_cd OR p.outb_uom_cd = u.uom_cd)
             OR EXISTS (SELECT 1 FROM prod_uom pu WHERE pu.uom_cd = u.uom_cd));
        IF n > 0 THEN
            RAISE EXCEPTION '상품이 쓰고 있는데 공통코드 UOM 그룹에 없는 단위가 % 건 있다. 먼저 옮긴 뒤 다시 실행할 것: '
                            'INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) '
                            'SELECT ''UOM'', uom_cd, uom_nm, 99 FROM uom u WHERE NOT EXISTS '
                            '(SELECT 1 FROM code_detail c WHERE c.grp_cd = ''UOM'' AND c.code_cd = u.uom_cd);', n;
        END IF;

        SELECT count(*) INTO n FROM uom u
         WHERE NOT EXISTS (SELECT 1 FROM code_detail c
                            WHERE c.grp_cd = 'UOM' AND c.code_cd = u.uom_cd);
        DROP TABLE uom;
        RAISE NOTICE 'uom 테이블 삭제 (단위는 공통코드 UOM 그룹으로 일원화). 공통코드에 없는 미사용 코드 % 건은 함께 버려짐', n;
    ELSE
        RAISE NOTICE 'uom 테이블 없음 — 건너뜀';
    END IF;

    -- 5. 죽은 컬럼 제거 — prod.ib_life_rate ------------------------------
    -- 입고 검수 관문(잔여수명 하한)의 기준값으로 만들어졌지만 읽는 코드가 한 줄도 없다:
    -- Prod 엔티티에 필드가 없고 ReceivingService에 검증도 없다. 시드가 70을 넣기만 하는
    -- write-only 데이터라 유지할 이유가 없다.
    --
    -- 검수 관문을 실제로 구현할 때는 이 컬럼을 되살리지 않는다 — 전역 기본값을 두고
    -- 상품에는 예외(override)만 두는 형태로 간다 (docs/design.md 「입고 제약」 참고).
    -- 그때 이름은 사전대로 짓는다 (「비율」·「잔여」가 아직 사전에 없어 등재가 선행).
    IF EXISTS (SELECT 1 FROM information_schema.columns
                WHERE table_name = 'prod' AND column_name = 'ib_life_rate') THEN
        SELECT count(*) INTO n FROM prod WHERE ib_life_rate IS NOT NULL;
        RAISE NOTICE 'prod.ib_life_rate 삭제 — 값이 있던 % 건은 버려진다 (읽는 코드가 없어 무해)', n;
        ALTER TABLE prod DROP COLUMN ib_life_rate;   -- CHECK 제약도 함께 사라진다
    ELSE
        RAISE NOTICE 'prod.ib_life_rate 이미 없음 — 건너뜀';
    END IF;

    -- 6. 검증 ---------------------------------------------------------
    -- 공통코드 UOM 그룹에 없는 코드를 쓰는 곳이 없어야 한다 (ProdService 가 지키는 규칙)
    SELECT count(*) INTO n
      FROM prod p WHERE NOT EXISTS (SELECT 1 FROM code_detail c
                                     WHERE c.grp_cd = 'UOM' AND c.code_cd = p.inb_uom_cd)
                     OR NOT EXISTS (SELECT 1 FROM code_detail c
                                     WHERE c.grp_cd = 'UOM' AND c.code_cd = p.outb_uom_cd);
    IF n > 0 THEN
        RAISE EXCEPTION '공통코드 UOM 그룹에 없는 단위를 쓰는 상품이 % 건 있다. '
                        '해당 단위를 code_detail 에 추가한 뒤 다시 실행할 것.', n;
    END IF;

    SELECT count(*) INTO n
      FROM prod_uom pu WHERE NOT EXISTS (SELECT 1 FROM code_detail c
                                          WHERE c.grp_cd = 'UOM' AND c.code_cd = pu.uom_cd);
    IF n > 0 THEN
        RAISE EXCEPTION '공통코드 UOM 그룹에 없는 단위를 쓰는 포장이 % 건 있다.', n;
    END IF;

    -- 입고/출고단위는 반드시 그 상품의 포장 목록 안에 있어야 한다 (ProdService 가 지키는 규칙)
    SELECT count(*) INTO n
      FROM prod p WHERE NOT EXISTS (SELECT 1 FROM prod_uom pu
                                     WHERE pu.prod_id = p.prod_id AND pu.uom_cd = p.inb_uom_cd)
                     OR NOT EXISTS (SELECT 1 FROM prod_uom pu
                                     WHERE pu.prod_id = p.prod_id AND pu.uom_cd = p.outb_uom_cd);
    IF n > 0 THEN
        RAISE EXCEPTION '입고/출고단위가 포장 목록에 없는 상품이 % 건 있다.', n;
    END IF;

    -- 환산이 정수로 떨어지지 않으면 toOutbQty 의 정수 나눗셈이 수량을 조용히 깎는다
    SELECT count(*) INTO n
      FROM prod p
      JOIN prod_uom i ON i.prod_id = p.prod_id AND i.uom_cd = p.inb_uom_cd
      JOIN prod_uom o ON o.prod_id = p.prod_id AND o.uom_cd = p.outb_uom_cd
     WHERE i.ea_qty % o.ea_qty <> 0;
    IF n > 0 THEN
        RAISE EXCEPTION '입고단위 낱개수량이 출고단위 낱개수량의 배수가 아닌 상품이 % 건 있다.', n;
    END IF;

    RAISE NOTICE '계량단위 마이그레이션 완료';
END
$uom$;

-- =====================================================================
-- 적용 후 확인
--   1) 포장 단위 5건 (화면 콤보박스가 받는 것과 같은 목록 — GET /master/codes/UOM)
--      SELECT code_cd, code_nm, srt_seq FROM code_detail WHERE grp_cd = 'UOM' ORDER BY srt_seq;
--      -- 옛 uom 테이블은 사라져 있어야 한다 (NULL 이면 정상)
--      SELECT to_regclass('uom');
--   2) 포장 없는 상품 0건
--      SELECT p.prod_cd, p.prod_nm FROM prod p
--       WHERE NOT EXISTS (SELECT 1 FROM prod_uom pu WHERE pu.prod_id = p.prod_id);
--   3) 상품별 포장·환산 한눈에
--      SELECT p.prod_cd, p.prod_nm, p.inb_uom_cd, p.outb_uom_cd,
--             i.ea_qty AS inb_ea, o.ea_qty AS outb_ea, i.ea_qty / o.ea_qty AS cnvr
--        FROM prod p
--        JOIN prod_uom i ON i.prod_id = p.prod_id AND i.uom_cd = p.inb_uom_cd
--        JOIN prod_uom o ON o.prod_id = p.prod_id AND o.uom_cd = p.outb_uom_cd
--       ORDER BY p.prod_cd;
--
-- 박스 입고를 시험해보려면 (예: 코카콜라 24입 — 낱개로 재고를 잡고 박스로 받는다)
--   INSERT INTO prod_uom (prod_id, uom_cd, ea_qty, wgt)
--   SELECT prod_id, 'BOX', 24, 9.120 FROM prod WHERE prod_nm LIKE '코카콜라%'
--   ON CONFLICT (prod_id, uom_cd) DO UPDATE SET ea_qty = EXCLUDED.ea_qty;
--   UPDATE prod SET inb_uom_cd = 'BOX', outb_uom_cd = 'EA' WHERE prod_nm LIKE '코카콜라%';
--   이후 이 상품으로 발주 10(박스)을 넣고 ASN 변환하면 예정수량이 240(낱개)으로 잡힌다.
--   검수·재고는 그 240을 그대로 쓴다 (검수 입력도 낱개 — 환산은 변환 시점 한 번뿐).
-- =====================================================================
