-- =====================================================================
-- 인증·역할 도입 — 사용자 마스터(usr)와 사용자 역할(usr_role)을 만든다.
--   전제: docs/migration-catchup-to-schema.sql 까지 적용된 DB.
--
--   ▣ 전체가 DO 블록 하나다 (BEGIN;/COMMIT; 을 쓰지 않는다) — CLAUDE.md 규칙.
--     전 구간에 존재 확인이 걸려 있어 몇 번을 돌려도 안전하다.
--
--   FK는 걸지 않는다 (usr_role.usr_id 포함). 참조 무결성은 애플리케이션 책임이다.
--
--   역할 목록은 CHECK 제약과 코드(Role enum) 두 곳에 있다. 역할을 늘리려면 둘을 함께
--   고쳐야 한다 — 역할이 곧 URL 접두(업무 구역)라 데이터로만 늘려도 그 접두를 아는
--   코드가 따라 바뀌어야 하고, 그러면 두 벌을 맞추는 일만 남기 때문에 마스터로 빼지 않았다.
--
--   시드 8명의 비밀번호는 전부 1234의 BCrypt 해시다. 운영 DB에 적용한다면 이 블록의
--   사용자 시드를 지우거나, 적용 직후 화면에서 비밀번호를 바꿀 것.
--
--   실행(DBeaver): 이 파일을 열고 Alt+X (Execute script).
--     - NOTICE 는 결과 패널의 Server Output 탭에서 볼 것
--     - 이 스크립트를 적용하는 배포에는 애플리케이션 코드 변경(SecurityConfig 규칙,
--       JwtAuthFilter, AuditorAware)도 같이 나가야 한다. 반대로 코드가 먼저 나가면
--       로그인 자체가 불가능해 전 화면이 401이 된다.
-- =====================================================================

DO $usr$
BEGIN
    -- 1. 테이블 -------------------------------------------------------
    IF to_regclass('usr') IS NULL THEN
        CREATE TABLE usr (
            usr_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            login_id    VARCHAR(30)     NOT NULL,
            usr_nm      VARCHAR(50)     NOT NULL,
            pwd         VARCHAR(100)    NOT NULL,
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT uq_usr_login_id UNIQUE (login_id)
        );
        COMMENT ON TABLE  usr IS '사용자 마스터 (로그인 계정)';
        COMMENT ON COLUMN usr.login_id IS '로그인 아이디. _id는 PK/FK 관례와 겹치지만 사람이 「아이디」라 부르는 값이 이것이다';
        COMMENT ON COLUMN usr.pwd      IS 'BCrypt 해시';
        RAISE NOTICE 'usr 테이블 생성';
    ELSE
        RAISE NOTICE 'usr 테이블 이미 존재 — 건너뜀';
    END IF;

    IF to_regclass('usr_role') IS NULL THEN
        CREATE TABLE usr_role (
            usr_id      BIGINT          NOT NULL,
            role        VARCHAR(20)     NOT NULL,
            created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
            created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
            updated_at  TIMESTAMP,
            updated_by  VARCHAR(30),
            CONSTRAINT pk_usr_role PRIMARY KEY (usr_id, role),
            CONSTRAINT ck_usr_role CHECK (role IN ('ADMR', 'CENT_ADMR', 'ODR_PIC', 'IB_PIC', 'INV_PIC', 'OUTB_PIC', 'INQ'))
        );
        COMMENT ON TABLE  usr_role IS '사용자 역할 (사용자당 다건)';
        COMMENT ON COLUMN usr_role.role IS 'ADMR 시스템관리자 / CENT_ADMR 센터관리자 / *_PIC 업무담당 / INQ 조회';
        RAISE NOTICE 'usr_role 테이블 생성';
    ELSE
        RAISE NOTICE 'usr_role 테이블 이미 존재 — 건너뜀';
    END IF;

    -- 2. 사용자 시드 (비밀번호는 전부 1234) --------------------------------
    INSERT INTO usr (login_id, usr_nm, pwd) VALUES
        ('admin',    '시스템관리자', '$2a$10$ndeRZj62lK2QZkSiUQYXl.WwdmHIAXLu8OBmy3D6DMqw2UaWLdBSq'),
        ('center',   '센터관리자',   '$2a$10$ndeRZj62lK2QZkSiUQYXl.WwdmHIAXLu8OBmy3D6DMqw2UaWLdBSq'),
        ('order',    '주문담당',     '$2a$10$ndeRZj62lK2QZkSiUQYXl.WwdmHIAXLu8OBmy3D6DMqw2UaWLdBSq'),
        ('inbound',  '입고담당',     '$2a$10$ndeRZj62lK2QZkSiUQYXl.WwdmHIAXLu8OBmy3D6DMqw2UaWLdBSq'),
        ('stock',    '재고담당',     '$2a$10$ndeRZj62lK2QZkSiUQYXl.WwdmHIAXLu8OBmy3D6DMqw2UaWLdBSq'),
        ('outbound', '출고담당',     '$2a$10$ndeRZj62lK2QZkSiUQYXl.WwdmHIAXLu8OBmy3D6DMqw2UaWLdBSq'),
        ('manager',  '입고재고겸직', '$2a$10$ndeRZj62lK2QZkSiUQYXl.WwdmHIAXLu8OBmy3D6DMqw2UaWLdBSq'),
        ('viewer',   '조회전용',     '$2a$10$ndeRZj62lK2QZkSiUQYXl.WwdmHIAXLu8OBmy3D6DMqw2UaWLdBSq')
    ON CONFLICT (login_id) DO NOTHING;

    INSERT INTO usr_role (usr_id, role)
    SELECT u.usr_id, r.role
    FROM usr u
    JOIN (VALUES
        ('admin',    'ADMR'),
        ('center',   'CENT_ADMR'),
        ('order',    'ODR_PIC'),
        ('inbound',  'IB_PIC'),
        ('stock',    'INV_PIC'),
        ('outbound', 'OUTB_PIC'),
        ('manager',  'IB_PIC'),
        ('manager',  'INV_PIC'),
        ('viewer',   'INQ')
    ) AS r(login_id, role) ON r.login_id = u.login_id
    ON CONFLICT (usr_id, role) DO NOTHING;

    RAISE NOTICE '사용자 8명 · 역할 9건 반영';

    RAISE NOTICE '인증·역할 마이그레이션 완료';
END
$usr$;

-- =====================================================================
-- 적용 후 확인
--   1) 사용자 8명과 역할
--      SELECT u.login_id, u.usr_nm, string_agg(r.role, ',' ORDER BY r.role) AS roles
--        FROM usr u LEFT JOIN usr_role r ON r.usr_id = u.usr_id
--       GROUP BY 1, 2 ORDER BY 1;
--      -- manager 는 IB_PIC,INV_PIC 두 개여야 한다 (다중 역할 확인).
--   2) 역할 CHECK 가 걸려 있는지
--      INSERT INTO usr_role (usr_id, role)
--      SELECT usr_id, 'NOPE' FROM usr WHERE login_id = 'viewer';
--      -- ck_usr_role 위반으로 실패해야 한다 (성공하면 CHECK 가 안 붙은 것).
--   3) FK 는 여전히 0건
--      SELECT COUNT(*) FROM pg_constraint WHERE contype = 'f';
-- =====================================================================
