-- =====================================================================
-- WMS 스키마 DDL (Oracle)
--
-- 설계 근거: docs/design.md
--  - 재고 키: SKU + Location + Lot
--  - 헤더 상태는 워크플로 단계만 표현, 부분 여부는 라인 수량에서 파생
--  - 재고 이력 합계 = 현재고 스냅샷 (불변식)
--  - 도메인: 식품/음료 유통센터 → 온도대 제약, 납품기한 출고 제한
--
-- 네이밍 규칙
--  - 접두: 입고 IB_* / 출고 OUTB_* / 재고 INV* / 마스터는 무접두
--  - PK는 {테이블명}_id, FK는 참조 테이블 PK명 그대로
--  - 약어 사전 (새 컬럼도 반드시 이 사전을 따른다):
--      expected→expct  received→rcvd  rejected→rjct  putaway→ptwy
--      allocated/allocation→alloc  location→loc  history→hist
--      code→cd  name→nm  date→dt  vendor→vndr  priority→prty
--  - 공통 감사 컬럼: 모든 테이블에 created_at/created_by/updated_at/updated_by.
--    작성자는 JPA Auditing(AuditorAware)이 채운다 (인증 도입 전까지 'admin' 고정)
--
-- 참고: 개발 중에는 JPA ddl-auto=update로 생성하므로 이 파일은
--       "테이블 설계 기준 문서"다. 엔티티는 이 DDL에 맞춰 작성한다.
-- =====================================================================


-- =====================================================================
-- 1. 마스터
-- =====================================================================

-- 상품 마스터. 온도대/유통기한 정책 등 "상품이 갖는 규칙"을 보유한다.
CREATE TABLE sku (
    sku_id          NUMBER(19)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sku_cd          VARCHAR2(30)    NOT NULL,
    sku_nm          VARCHAR2(100)   NOT NULL,
    temp_zone       VARCHAR2(10)    NOT NULL,
    shelf_life_days NUMBER(5),
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR2(30),
    CONSTRAINT uq_sku_cd UNIQUE (sku_cd),
    CONSTRAINT ck_sku_temp_zone CHECK (temp_zone IN ('DRY', 'CHL', 'FRZ'))
);

COMMENT ON TABLE  sku IS '상품 마스터. 보관 규칙(온도대)과 유통기한 정책을 상품 단위로 정의';
COMMENT ON COLUMN sku.sku_cd          IS '상품 코드 (업무 식별자, 예: SKU-0001)';
COMMENT ON COLUMN sku.temp_zone       IS '보관 온도대 (DRY 상온 / CHL 냉장 / FRZ 냉동). 적치·이동 시 로케이션 온도대와 일치 검증';
COMMENT ON COLUMN sku.shelf_life_days IS '제조일 기준 총 유통기한(일). NULL = 유통기한 미관리(공산품 등). 시더가 Lot 유통기한 생성 시 사용';

-- SKU 코드 채번 시퀀스 (SKU-0001 형식의 업무 코드 전용, PK identity와 분리 운용).
-- MAX(sku_cd)+1 방식은 동시 INSERT 시 같은 값을 읽어 중복 채번되므로 시퀀스로 발급한다.
-- 이미 seed 데이터가 있다면 START WITH를 (기존 최대 채번값 + 1)로 맞출 것.
CREATE SEQUENCE sku_cd_seq START WITH 1 INCREMENT BY 1;

-- 로케이션 마스터. 입고 스테이징(RCV-STAGE)과 온도대별 보관존으로 구성.
CREATE TABLE loc (
    loc_id          NUMBER(19)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    loc_cd          VARCHAR2(30)    NOT NULL,
    zone_cd         VARCHAR2(20)    NOT NULL,
    temp_zone       VARCHAR2(10)    NOT NULL,
    loc_type        VARCHAR2(10)    NOT NULL,
    pick_prty       NUMBER(5)       DEFAULT 0 NOT NULL,
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR2(30),
    CONSTRAINT uq_loc_cd UNIQUE (loc_cd),
    CONSTRAINT ck_loc_temp_zone CHECK (temp_zone IN ('DRY', 'CHL', 'FRZ')),
    CONSTRAINT ck_loc_type CHECK (loc_type IN ('STAGE', 'STORAGE'))
);

COMMENT ON TABLE  loc IS '로케이션 마스터. 재고가 놓이는 물리 위치 (스테이징/보관존)';
COMMENT ON COLUMN loc.loc_cd    IS '로케이션 코드 (예: DRY-A-01-01, RCV-STAGE)';
COMMENT ON COLUMN loc.zone_cd   IS '존 코드 (RCV-STAGE / DRY / CHL / FRZ)';
COMMENT ON COLUMN loc.temp_zone IS '존 온도대. SKU 온도대와 불일치하면 적치·이동 차단 (스테이징은 예외적으로 전 온도대 허용할지 서비스에서 판단)';
COMMENT ON COLUMN loc.loc_type  IS 'STAGE: 스테이징(RCV-STAGE 적치 대기 / SHIP-STAGE 반출 대기) / STORAGE: 보관(할당 대상)';
COMMENT ON COLUMN loc.pick_prty IS '할당 시 동일 유통기한(FEFO 동순위) 간 로케이션 우선순위. 낮을수록 먼저 할당';

-- Lot. 입고 처리 시점에 생성되며 유통기한을 보유한다 (FEFO 기준값).
CREATE TABLE lot (
    lot_id      NUMBER(19)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sku_id      NUMBER(19)      NOT NULL,
    lot_no      VARCHAR2(30)    NOT NULL,
    receipt_dt  DATE,
    mfg_dt      DATE,
    expiry_dt   DATE,
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by  VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR2(30),
    CONSTRAINT fk_lot_sku FOREIGN KEY (sku_id) REFERENCES sku (sku_id),
    CONSTRAINT uq_lot UNIQUE (sku_id, lot_no)
);

COMMENT ON TABLE  lot IS 'Lot(입고 단위 묶음). 입고 처리 시 생성. 유통기한이 FEFO 할당과 납품기한 필터의 기준';
COMMENT ON COLUMN lot.lot_no    IS 'Lot 번호 (SKU 내 유일). 입고일 기준 SKU별 일자 리셋 채번(LOT-YYMMDD-NNN). 유통기한 미관리 SKU도 동일 형식이며 입고일자만으로 구분됨';
COMMENT ON COLUMN lot.receipt_dt IS '입고일자 (소급 등록 가능). SKU+입고일자+제조일자가 같으면 기존 Lot을 재사용 (증분 검수 시 배치 중복 생성 방지). 유통기한 미관리 SKU는 제조일자가 항상 NULL이라 사실상 SKU+입고일자로만 구분';
COMMENT ON COLUMN lot.mfg_dt    IS '제조일자. 유통기한 미관리 SKU의 Lot은 NULL';
COMMENT ON COLUMN lot.expiry_dt IS '유통기한. 생성 시점의 SKU.shelf_life_days로 계산해 저장한 스냅샷 (이후 SKU 마스터 변경에 소급 영향 없음). NULL = 미관리 SKU의 Lot (FEFO 맨 뒤 정렬, 잔여수명 필터 대상 아님)';

CREATE INDEX ix_lot_expiry ON lot (sku_id, expiry_dt);
-- Lot 재사용 조회(SKU+입고일자+제조일자) 및 일자별 채번 카운트에 사용
CREATE INDEX ix_lot_sku_receipt ON lot (sku_id, receipt_dt);

-- Lot 번호는 더 이상 DB 시퀀스로 채번하지 않는다.
-- SKU 로우 락(SELECT ... FOR UPDATE) 하에 해당 SKU+입고일자의 기존 Lot 건수를 세어 다음 번호를 매긴다 (SKU별 일자 리셋).

-- 점포 마스터. 납품 기준(잔여수명 허용률)은 상품이 아니라 납품처가 정한다.
CREATE TABLE store (
    store_id        NUMBER(19)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    store_cd        VARCHAR2(30)    NOT NULL,
    store_nm        VARCHAR2(100)   NOT NULL,
    outb_life_rate  NUMBER(3)       DEFAULT 40 NOT NULL,
    created_at      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR2(30),
    CONSTRAINT uq_store_cd UNIQUE (store_cd),
    CONSTRAINT ck_store_life_rate CHECK (outb_life_rate BETWEEN 0 AND 100)
);

COMMENT ON TABLE  store IS '점포(납품처) 마스터. 납품 허용 잔여수명 기준을 점포 단위로 관리';
COMMENT ON COLUMN store.store_cd       IS '점포 코드 (업무 식별자, 예: ST-0001)';
COMMENT ON COLUMN store.outb_life_rate IS '납품 허용 잔여수명 비율(%). 이 점포 출고 시 잔여 유통기한이 이 비율 미만인 Lot은 할당 제외 (FEFO 앞단 필터)';

-- 공통코드 그룹. 관리 화면은 추후 추가 예정, 당분간 시드 데이터로만 운용.
-- 코드성 테이블이라 PK는 {테이블명}_id 규칙 대신 자연키를 쓴다 (조회가 항상 코드 기준).
CREATE TABLE code_group (
    group_cd    VARCHAR2(30)    NOT NULL,
    group_nm    VARCHAR2(100)   NOT NULL,
    description VARCHAR2(200),
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by  VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR2(30),
    CONSTRAINT pk_code_group PRIMARY KEY (group_cd)
);

COMMENT ON TABLE  code_group IS '공통코드 그룹. 로직 분기에 쓰이는 enum성 코드의 기준 목록 (표시 스타일은 프론트 상수가 보유)';
COMMENT ON COLUMN code_group.group_cd IS '코드 그룹 코드 (예: TEMP_ZONE)';

-- 공통코드 상세. group_cd는 code_group 참조지만 FK는 걸지 않는다
-- (변경이 시드/관리화면으로만 일어나는 코드성 테이블 — 그룹 존재 검증은 관리 화면 추가 시 서비스에서).
CREATE TABLE code_detail (
    group_cd    VARCHAR2(30)    NOT NULL,
    code_cd     VARCHAR2(30)    NOT NULL,
    code_nm     VARCHAR2(100)   NOT NULL,
    sort_ord    NUMBER(5)       DEFAULT 0 NOT NULL,
    use_yn      CHAR(1)         DEFAULT 'Y' NOT NULL,
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by  VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR2(30),
    CONSTRAINT pk_code_detail PRIMARY KEY (group_cd, code_cd),
    CONSTRAINT ck_code_use_yn CHECK (use_yn IN ('Y', 'N'))
);

COMMENT ON TABLE  code_detail IS '공통코드 상세. 그룹 내 개별 코드와 표시명/정렬 순서';
COMMENT ON COLUMN code_detail.code_cd  IS '코드 값 (예: DRY). 로직에서 리터럴로 참조하므로 변경 금지, 폐기는 use_yn=N';
COMMENT ON COLUMN code_detail.use_yn   IS '사용 여부. 과거 데이터가 참조하므로 삭제 대신 N 처리';
COMMENT ON COLUMN code_detail.sort_ord IS '화면 표시 정렬 순서';

-- 공통코드 시드 (참조 데이터 — 테이블 정의와 한 몸이므로 여기서 함께 관리)
INSERT INTO code_group (group_cd, group_nm, description) VALUES
    ('TEMP_ZONE', '온도대', '보관 온도 구분 (SKU/로케이션 공용)');
INSERT INTO code_group (group_cd, group_nm, description) VALUES
    ('LOC_TYPE', '로케이션 유형', '스테이징/보관 구분');

INSERT INTO code_detail (group_cd, code_cd, code_nm, sort_ord) VALUES ('TEMP_ZONE', 'DRY', '상온', 1);
INSERT INTO code_detail (group_cd, code_cd, code_nm, sort_ord) VALUES ('TEMP_ZONE', 'CHL', '냉장', 2);
INSERT INTO code_detail (group_cd, code_cd, code_nm, sort_ord) VALUES ('TEMP_ZONE', 'FRZ', '냉동', 3);
INSERT INTO code_detail (group_cd, code_cd, code_nm, sort_ord) VALUES ('LOC_TYPE', 'STAGE', '스테이징', 1);
INSERT INTO code_detail (group_cd, code_cd, code_nm, sort_ord) VALUES ('LOC_TYPE', 'STORAGE', '보관', 2);
COMMIT;


-- =====================================================================
-- 2. 입고 IB_* (SCHEDULED → RECEIVING → RECEIVED → COMPLETED / CANCELLED)
-- =====================================================================

-- 입고예정(ASN) 헤더. 상태는 워크플로 단계만 표현한다 (부분입고 상태 없음).
CREATE TABLE ib_order (
    ib_order_id NUMBER(19)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ib_no       VARCHAR2(30)    NOT NULL,
    status      VARCHAR2(15)    NOT NULL,
    vndr_nm     VARCHAR2(100)   NOT NULL,
    expct_dt    DATE            NOT NULL,
    closed_at   TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by  VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR2(30),
    CONSTRAINT uq_ib_no UNIQUE (ib_no),
    CONSTRAINT ck_ib_order_status CHECK (status IN ('SCHEDULED', 'RECEIVING', 'RECEIVED', 'COMPLETED', 'CANCELLED'))
);

COMMENT ON TABLE  ib_order IS '입고예정(ASN) 헤더. 부분입고 여부는 상태가 아니라 라인 수량(expct vs rcvd)에서 파생';
COMMENT ON COLUMN ib_order.ib_no     IS '입고 번호 (업무 식별자, 예: IB-20260714-001)';
COMMENT ON COLUMN ib_order.status    IS 'SCHEDULED 예정 / RECEIVING 입고중 / RECEIVED 마감 / COMPLETED 적치완료 / CANCELLED 취소(검수 시작 전만)';
COMMENT ON COLUMN ib_order.vndr_nm   IS '납품 벤더명 (v1은 벤더 마스터 없이 텍스트 보관)';
COMMENT ON COLUMN ib_order.expct_dt  IS '입고 예정일';
COMMENT ON COLUMN ib_order.closed_at IS '입고 마감(close) 시각. 마감은 미입고 잔량을 확정하는 명시적 액션';

-- 입고번호 채번 시퀀스 (IB-YYYYMMDD-NNN 형식. 시퀀스는 전역이라 일자별로 리셋되지 않는다 — 유일성만 보장)
CREATE SEQUENCE ib_no_seq START WITH 1 INCREMENT BY 1;

-- 입고 라인. 부분입고/검수/적치 진행률을 수량으로만 표현한다.
CREATE TABLE ib_line (
    ib_line_id  NUMBER(19)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ib_order_id NUMBER(19)      NOT NULL,
    sku_id      NUMBER(19)      NOT NULL,
    expct_qty   NUMBER(12)      NOT NULL,
    rcvd_qty    NUMBER(12)      DEFAULT 0 NOT NULL,
    ptwy_qty    NUMBER(12)      DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by  VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR2(30),
    CONSTRAINT fk_ib_line_order FOREIGN KEY (ib_order_id) REFERENCES ib_order (ib_order_id),
    CONSTRAINT fk_ib_line_sku FOREIGN KEY (sku_id) REFERENCES sku (sku_id),
    CONSTRAINT ck_ib_line_qty CHECK (
        expct_qty > 0 AND rcvd_qty >= 0
        AND ptwy_qty >= 0 AND ptwy_qty <= rcvd_qty
    )
);

COMMENT ON TABLE  ib_line IS '입고 라인. Lot은 라인이 아니라 입고 처리(재고 이력) 단위로 기록되므로 여기엔 두지 않는다';
COMMENT ON COLUMN ib_line.expct_qty IS '입고 예정 수량';
COMMENT ON COLUMN ib_line.rcvd_qty  IS '검수(개수 확인) 완료된 실제 입고(스테이징 입) 수량 누계. 실무 검수는 개수 대조 수준이라 불합격 수량은 관리하지 않는다';
COMMENT ON COLUMN ib_line.ptwy_qty  IS '적치 완료 수량 누계 (스테이징 → 보관 MOVE 반영분)';

CREATE INDEX ix_ib_line_order ON ib_line (ib_order_id);


-- =====================================================================
-- 3. 재고 INV*
-- =====================================================================

-- 현재고 스냅샷. 할당 시 락을 거는 지점 (비관적/낙관적 락 비교 대상).
CREATE TABLE inv (
    inv_id      NUMBER(19)      GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    sku_id      NUMBER(19)      NOT NULL,
    loc_id      NUMBER(19)      NOT NULL,
    lot_id      NUMBER(19)      NOT NULL,
    on_hand_qty NUMBER(12)      DEFAULT 0 NOT NULL,
    alloc_qty   NUMBER(12)      DEFAULT 0 NOT NULL,
    version     NUMBER(19)      DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by  VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR2(30),
    CONSTRAINT fk_inv_sku FOREIGN KEY (sku_id) REFERENCES sku (sku_id),
    CONSTRAINT fk_inv_loc FOREIGN KEY (loc_id) REFERENCES loc (loc_id),
    CONSTRAINT fk_inv_lot FOREIGN KEY (lot_id) REFERENCES lot (lot_id),
    CONSTRAINT uq_inv UNIQUE (sku_id, loc_id, lot_id),
    -- 동시성 실험의 최후 방어선: 애플리케이션 락이 실패해도 DB가 음수/과할당을 거부
    CONSTRAINT ck_inv_qty CHECK (on_hand_qty >= 0 AND alloc_qty >= 0 AND alloc_qty <= on_hand_qty)
);

COMMENT ON TABLE  inv IS '현재고 스냅샷. 키: SKU+Loc+Lot. 가용재고 = on_hand - alloc (파생값, 컬럼 아님)';
COMMENT ON COLUMN inv.on_hand_qty IS '실물 보유 수량. 물리 변동(RECEIVE/MOVE/ADJUST/PICK 등) 시에만 증감';
COMMENT ON COLUMN inv.alloc_qty   IS '할당(예약) 수량. 물리 이동이 아니므로 이력에 기록하지 않음';
COMMENT ON COLUMN inv.version     IS '낙관적 락 버전 (@Version). 비관적 락과의 비교 실험 대상';

CREATE INDEX ix_inv_sku ON inv (sku_id);
CREATE INDEX ix_inv_loc ON inv (loc_id);

-- 재고 이력 (append-only 원장). 이력 합계 = 스냅샷 불변식의 근거 데이터.
CREATE TABLE inv_hist (
    inv_hist_id  NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    tx_type      VARCHAR2(10)   NOT NULL,
    sku_id       NUMBER(19)     NOT NULL,
    loc_id       NUMBER(19)     NOT NULL,
    lot_id       NUMBER(19)     NOT NULL,
    qty          NUMBER(12)     NOT NULL,
    ref_doc_type VARCHAR2(10),
    ref_doc_no   VARCHAR2(30),
    ib_line_id   NUMBER(19),
    from_loc_id  NUMBER(19),
    to_loc_id    NUMBER(19),
    cancels_inv_hist_id NUMBER(19),
    created_at   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    created_by   VARCHAR2(30)   DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR2(30),
    CONSTRAINT fk_invh_sku FOREIGN KEY (sku_id) REFERENCES sku (sku_id),
    CONSTRAINT fk_invh_loc FOREIGN KEY (loc_id) REFERENCES loc (loc_id),
    CONSTRAINT fk_invh_lot FOREIGN KEY (lot_id) REFERENCES lot (lot_id),
    CONSTRAINT ck_invh_tx_type CHECK (tx_type IN ('RECEIVE', 'MOVE', 'ADJUST', 'PICK', 'SHIP')),
    CONSTRAINT ck_invh_qty CHECK (qty <> 0)
);

COMMENT ON TABLE  inv_hist IS '재고 이력 (append-only 원장). 모든 물리 변동을 ±수량으로 기록. 스냅샷과 한 트랜잭션에서 갱신. MOVE는 출발지(-)/도착지(+) 2건으로 기록';
COMMENT ON COLUMN inv_hist.tx_type      IS 'RECEIVE 입고 / MOVE 이동(적치 포함) / ADJUST 조정 / PICK 피킹 / SHIP 출고확정';
COMMENT ON COLUMN inv_hist.qty          IS '변동 수량 (증가 +, 감소 -). 0 금지';
COMMENT ON COLUMN inv_hist.ref_doc_type IS '참조 문서 유형 (INBOUND / OUTBOUND / 수동조정 시 NULL)';
COMMENT ON COLUMN inv_hist.ref_doc_no   IS '참조 문서 번호 (입고번호/출고번호). 이력 → 원인 문서 추적용';
COMMENT ON COLUMN inv_hist.ib_line_id   IS '입고 라인 ID. RECEIVE(및 그 취소 ADJUST) 건에만 채워짐. ref_doc_no(주문 단위)와 달리 라인 단위 역추적용 (적치 시 FEFO 소진 대상 Lot 조회, 검수 취소 대상 조회). ib_line 테이블 FK는 걸지 않는다 — ref_doc_no와 같은 느슨한 참조 컬럼';
COMMENT ON COLUMN inv_hist.from_loc_id  IS 'MOVE의 출발지. 도착지(+)/출발지(-) 두 행 모두 동일한 값을 가져서, 한 행만 봐도 상대 조인 없이 "출발지→도착지"를 알 수 있다. 재고 키/불변식은 loc_id·qty가 그대로 담당하고 이건 표시 전용. MOVE가 아니면 NULL. loc 테이블 FK는 걸지 않는다 — ib_line_id/ref_doc_no와 같은 느슨한 참조 컬럼';
COMMENT ON COLUMN inv_hist.to_loc_id    IS 'MOVE의 도착지. from_loc_id와 동일한 성격 — 표시 전용, FK 없음, MOVE가 아니면 NULL';
COMMENT ON COLUMN inv_hist.cancels_inv_hist_id IS '검수 취소(ADJUST) 건이 되돌리는 원본 RECEIVE 건의 inv_hist_id. 이게 있어야 화면이 "이미 취소된 RECEIVE"를 구분해 취소 버튼을 다시 못 누르게 막을 수 있다. FK 없음. ADJUST가 아니면 NULL';

CREATE INDEX ix_invh_sku_created ON inv_hist (sku_id, created_at);
CREATE INDEX ix_invh_ref_doc ON inv_hist (ref_doc_no);
CREATE INDEX ix_invh_ib_line ON inv_hist (ib_line_id);
-- 대사(reconciliation) 배치: 키별 SUM(qty) vs inv.on_hand_qty 비교용
CREATE INDEX ix_invh_inv_key ON inv_hist (sku_id, loc_id, lot_id);


-- =====================================================================
-- 4. 출고 OUTB_* (CREATED → ALLOCATED → PICKING → PICKED → SHIPPED / CANCELLED)
--    할당은 오직 웨이브 릴리즈로만 일어난다 (웨이브 = 할당 단위). 피킹/확정은 주문 단위.
--    물리 재고는 2단계: PICK(보관→SHIP-STAGE) → SHIP(SHIP-STAGE 반출). 입고의 거울상.
-- =====================================================================

-- 출고 웨이브. 여러 출고 주문을 묶어 한 번에 할당하는 단위 (동시성 실험의 경합 지점).
CREATE TABLE outb_wave (
    outb_wave_id NUMBER(19)     GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    wave_no      VARCHAR2(30)   NOT NULL,
    status       VARCHAR2(15)   NOT NULL,
    released_at  TIMESTAMP,
    created_at   TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    created_by   VARCHAR2(30)   DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR2(30),
    CONSTRAINT uq_wave_no UNIQUE (wave_no),
    CONSTRAINT ck_outb_wave_status CHECK (status IN ('PLANNED', 'RELEASED'))
);

COMMENT ON TABLE  outb_wave IS '출고 웨이브. 재고 할당의 단위 — 릴리즈 시 소속 주문 전체를 한 트랜잭션에서 FEFO 할당. 릴리즈 이후 진행(피킹/확정)은 주문 단위라 웨이브는 여기서 역할이 끝난다';
COMMENT ON COLUMN outb_wave.wave_no     IS '웨이브 번호 (업무 식별자, 예: WV-20260718-001)';
COMMENT ON COLUMN outb_wave.status      IS 'PLANNED 편성중(주문 담기 가능) / RELEASED 릴리즈 완료(=할당 실행됨)';
COMMENT ON COLUMN outb_wave.released_at IS '릴리즈(할당 실행) 시각';

-- 웨이브 번호 채번 시퀀스 (WV-YYYYMMDD-NNN 형식. 전역 유일성만 보장, 일자 리셋 없음)
CREATE SEQUENCE outb_wave_no_seq START WITH 1 INCREMENT BY 1;

-- 출고 주문 헤더. 부분할당 여부는 상태가 아니라 라인/할당 수량에서 파생.
CREATE TABLE outb_order (
    outb_order_id NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    outb_no     VARCHAR2(30)    NOT NULL,
    status      VARCHAR2(15)    NOT NULL,
    store_id    NUMBER(19)      NOT NULL,
    wave_id     NUMBER(19),
    order_dt    DATE            NOT NULL,
    shipped_at  TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    created_by  VARCHAR2(30)    DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR2(30),
    CONSTRAINT uq_outb_no UNIQUE (outb_no),
    CONSTRAINT fk_outb_order_store FOREIGN KEY (store_id) REFERENCES store (store_id),
    CONSTRAINT fk_outb_order_wave FOREIGN KEY (wave_id) REFERENCES outb_wave (outb_wave_id),
    CONSTRAINT ck_outb_order_status CHECK (status IN ('CREATED', 'ALLOCATED', 'PICKING', 'PICKED', 'SHIPPED', 'CANCELLED'))
);

COMMENT ON TABLE  outb_order IS '출고 주문 헤더 (B2B 점포 출고). 피킹 시작 이후 취소는 v1 미지원';
COMMENT ON COLUMN outb_order.outb_no  IS '출고 번호 (업무 식별자, 예: OB-20260714-001)';
COMMENT ON COLUMN outb_order.status   IS 'CREATED 생성 / ALLOCATED 할당 / PICKING 피킹중 / PICKED 피킹완료 / SHIPPED 출고확정 / CANCELLED 취소';
COMMENT ON COLUMN outb_order.store_id IS '출고처 점포. 할당 시 이 점포의 잔여수명 허용률로 Lot 필터';
COMMENT ON COLUMN outb_order.wave_id  IS '편성된 출고 웨이브. NULL = 아직 미편성. 할당은 이 웨이브의 릴리즈로만 일어난다';
COMMENT ON COLUMN outb_order.order_dt IS '주문일';

CREATE INDEX ix_outb_order_wave ON outb_order (wave_id);

-- 출고번호 채번 시퀀스 (OB-YYYYMMDD-NNN 형식. 전역 유일성만 보장, 일자 리셋 없음)
CREATE SEQUENCE outb_no_seq START WITH 1 INCREMENT BY 1;

-- 출고 라인. 주문 수량만 보유하고, 할당/피킹 진행은 outb_alloc에서 집계 파생.
CREATE TABLE outb_line (
    outb_line_id  NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    outb_order_id NUMBER(19)    NOT NULL,
    sku_id        NUMBER(19)    NOT NULL,
    order_qty     NUMBER(12)    NOT NULL,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    created_by    VARCHAR2(30)  DEFAULT 'admin' NOT NULL,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR2(30),
    CONSTRAINT fk_outb_line_order FOREIGN KEY (outb_order_id) REFERENCES outb_order (outb_order_id),
    CONSTRAINT fk_outb_line_sku FOREIGN KEY (sku_id) REFERENCES sku (sku_id),
    CONSTRAINT ck_outb_line_qty CHECK (order_qty > 0)
);

COMMENT ON TABLE  outb_line IS '출고 주문 라인. 할당/피킹 수량은 컬럼으로 두지 않고 outb_alloc 집계로 파생 (수량-상태 불일치 원천 차단)';
COMMENT ON COLUMN outb_line.order_qty IS '주문 수량';

CREATE INDEX ix_outb_line_order ON outb_line (outb_order_id);

-- 할당. 주문라인 ↔ 재고(SKU+Loc+Lot) 매핑. FEFO(+ 납품기한 필터) 결과가 기록된다.
CREATE TABLE outb_alloc (
    outb_alloc_id NUMBER(19)    GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    outb_line_id  NUMBER(19)    NOT NULL,
    inv_id        NUMBER(19)    NOT NULL,
    alloc_qty     NUMBER(12)    NOT NULL,
    picked_qty    NUMBER(12)    DEFAULT 0 NOT NULL,
    created_at    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    created_by    VARCHAR2(30)  DEFAULT 'admin' NOT NULL,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR2(30),
    CONSTRAINT fk_alloc_line FOREIGN KEY (outb_line_id) REFERENCES outb_line (outb_line_id),
    CONSTRAINT fk_alloc_inv FOREIGN KEY (inv_id) REFERENCES inv (inv_id),
    CONSTRAINT ck_alloc_qty CHECK (alloc_qty > 0 AND picked_qty >= 0 AND picked_qty <= alloc_qty)
);

COMMENT ON TABLE  outb_alloc IS '재고 할당 레코드. 어떤 주문라인이 어떤 재고(SKU+Loc+Lot)를 몇 개 예약했는지. 할당 취소 시 삭제 + inv.alloc_qty 복원';
COMMENT ON COLUMN outb_alloc.alloc_qty  IS '할당 수량 (부분할당 허용: 라인 order_qty보다 합계가 작을 수 있음)';
COMMENT ON COLUMN outb_alloc.picked_qty IS '피킹 완료 수량. 피킹 리스트는 outb_alloc을 loc.pick_prty 순으로 정렬한 뷰. 피킹 시 보관→SHIP-STAGE MOVE(tx PICK)와 함께 누적되고, 이때 보관 inv.alloc_qty도 소진된다(실물 반출)';

CREATE INDEX ix_alloc_line ON outb_alloc (outb_line_id);
CREATE INDEX ix_alloc_inv ON outb_alloc (inv_id);
