-- =====================================================================
-- WMS 스키마 DDL (PostgreSQL / Supabase) — 현행 기준 문서
--   스키마의 주인은 이 파일이다. 엔티티는 여기에 맞춰 작성한다.
--   신규 DB는 이 파일 전체를 적용하고, 기존 DB는 docs/migration-*.sql 증분만 적용한다.
--   (Oracle 시절 원본은 접었다 — 이력이 필요하면 커밋 히스토리를 본다)
--
-- 설계 근거: docs/design.md
--  - 재고 키: 상품 + Location + Lot
--  - 헤더 상태는 워크플로 단계만 표현, 부분 여부는 라인 수량에서 파생
--  - 재고 이력 합계 = 현재고 스냅샷 (불변식)
--  - 도메인: 식품/음료 유통센터 → 온도대 제약, 납품기한 출고 제한
--  - FK 제약은 걸지 않는다 — 참조 무결성은 애플리케이션이 보증. 서비스/DB 분리 시
--    스키마를 자유롭게 쪼갤 수 있어야 하고, 마이그레이션 순서 제약을 줄이기 위함
--
-- 네이밍 규칙
--  - 접두: 주문 OMS_* / 입고 IB_* / 출고 OUTB_* / 재고 INV* / 마스터는 무접두
--          전략은 유형별 도메인 접두(INSP_* 검수 / PTAWY_* 적치 / WAV_* 웨이브 / ALOC_* 할당) + 공용 STGY_*
--  - PK는 {테이블명}_id, FK는 참조 테이블 PK명 그대로
--  - 약어 사전의 주인은 docs/naming-dictionary.md 하나다. 아래는 이 파일에서 자주 보이는
--    것만 추린 발췌이며, 새 이름은 반드시 사전에서 단어를 찾아 조합한다:
--      expected→expct  received→rcvd  rejected→rjct  putaway→ptawy
--      allocated/allocation→aloc  location→loc  history→hist  zone→zon
--      code→cd  name→nm  vendor→vndr  priority→prty  temperature→tmp
--      date→de(일자)  datetime→dt(일시)   ← 둘을 구분한다
--  - 공통 감사 컬럼: 모든 테이블에 created_at/created_by/updated_at/updated_by.
--    작성자는 JPA Auditing(AuditorAware)이 채운다 (인증 도입 전까지 'admin' 고정)
--
-- 참고: ddl-auto=none이므로 Hibernate는 테이블을 만들지도, 엔티티와 대조하지도 않는다.
--       엔티티가 없는 컬럼을 가리켜도 기동 시점에는 조용하고 조회할 때 터진다.
--       스키마 변경은 항상 이 파일(+증분 마이그레이션)을 DB에 먼저 적용한 뒤 엔티티를 고친다.
-- =====================================================================


-- =====================================================================
-- 1. 마스터
-- =====================================================================

-- 계량단위(UOM)는 전용 마스터 테이블을 두지 않고 공통코드 UOM 그룹으로 관리한다.
-- 정의와 시드는 아래 「공통코드」 절에 있다 (code_group 'UOM' + code_detail).
-- 화면 콤보박스도 다른 코드성 컬럼과 똑같이 /master/codes/UOM 하나로 받는다.

-- 상품 마스터. 온도대/유통기한 정책 등 "상품이 갖는 규칙"을 보유한다.
CREATE TABLE prod (
    prod_id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_cd          VARCHAR(30)     NOT NULL,
    prod_nm          VARCHAR(100)    NOT NULL,
    tmp_zon       VARCHAR(10)     NOT NULL,
    inb_uom_cd      VARCHAR(20)     DEFAULT 'EA' NOT NULL,
    outb_uom_cd     VARCHAR(20)     DEFAULT 'EA' NOT NULL,
    shelf_life_days INTEGER,
    img_url         VARCHAR(500),
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT uq_prod_cd UNIQUE (prod_cd),
    CONSTRAINT ck_prod_tmp_zon CHECK (tmp_zon IN ('DRY', 'CHL', 'FRZ'))
    -- 환산수량 컬럼을 두지 않는다. 포장단위 → 낱개(EA) 환산은 prod_uom.ea_qty(낱개수량)로
    -- 파생시킨다 (아래 prod_uom 주석 참고). 두 벌로 두면 서로 어긋날 수 있는 값이 생긴다.
);

COMMENT ON TABLE  prod IS '상품 마스터';
COMMENT ON COLUMN prod.prod_cd          IS '상품 코드';
COMMENT ON COLUMN prod.tmp_zon       IS '보관 온도대. TmpZon enum';
COMMENT ON COLUMN prod.inb_uom_cd      IS '입고단위';
COMMENT ON COLUMN prod.outb_uom_cd     IS '출고단위';
COMMENT ON COLUMN prod.shelf_life_days IS '제조일 기준 총 유통기한. NULL = 유통기한 미관리';
COMMENT ON COLUMN prod.img_url         IS '상품 이미지 — emoji:🥛 아이콘(화면이 넣는 유일한 형태) / /prod-img/… 시더 전용 그림 / https:// 절대주소. NULL = 이미지 없음';

-- 상품 코드(PROD-0001)는 채번 모듈이 발급한다 — nbr_rule 'PROD_CD' + nbr_seq.
-- 전용 시퀀스(prod_cd_seq)를 두던 방식은 폐기했다. 규칙이 테이블 데이터라 화면에서 바꿀 수 있고,
-- 일자 리셋 같은 패턴도 DDL 없이 표현된다 (아래 「채번」 절 참고).

-- 상품 포장. (상품, 단위) 한 조합이 한 행이다 — 한 상품이 낱개·박스·파렛트를 동시에 갖고,
-- 낱개수량과 중량은 그 조합마다 다르다.
--
-- 환산수량 컬럼(prod.cnvr_qty) 대신 이 테이블을 두는 이유 —
--   ① 상품당 한 칸이면 "입고단위 → 출고단위" 한 쌍만 표현된다. 박스·파렛트를 함께 다루려면
--      쌍마다 컬럼이 늘어난다. 낱개수량을 단위마다 두면 어떤 두 단위든 낱개를 매개로 환산된다
--      (BOX→EA = ea_qty(BOX) / ea_qty(EA)).
--   ② 중량을 둘 자리가 여기 말고 없다. prod에 두면 그 값이 어느 포장 기준인지 이름에 드러나지 않고,
--      박스 중량을 「낱개중량 × 낱개수량」으로 파생하게 되어 포장재 무게(tare)가 사라진다.
--      파렛트처럼 tare가 큰 단위에서 무시할 수 없는 오차다.
--
-- PK는 규칙대로 prod_uom_id 대리키이고, 실제 grain은 uq_prod_uom이 강제한다.
-- prod_id는 FK가 아니다 (FK 0건 정책) — 상품 삭제 시 포장 정리는 ProdService(cascade)가 한다.
CREATE TABLE prod_uom (
    prod_uom_id BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_id     BIGINT          NOT NULL,
    uom_cd      VARCHAR(20)     NOT NULL,
    ea_qty      BIGINT          NOT NULL,
    wgt         NUMERIC(12, 3),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_prod_uom UNIQUE (prod_id, uom_cd),
    -- 0이나 음수면 환산이 수량을 0으로 만들거나 부호를 뒤집는다. 단위 관련 유일한 DB 방어선이다
    CONSTRAINT ck_prod_uom_ea_qty CHECK (ea_qty >= 1),
    -- NULL은 미측정. 값이 있는데 0 이하면 실측값일 수 없다
    CONSTRAINT ck_prod_uom_wgt CHECK (wgt IS NULL OR wgt > 0)
);

COMMENT ON TABLE  prod_uom IS '상품 포장 (단위별 낱개수량·중량)';
COMMENT ON COLUMN prod_uom.uom_cd IS '단위 코드';
COMMENT ON COLUMN prod_uom.ea_qty IS '이 단위 1개가 낱개 몇 개인가';
COMMENT ON COLUMN prod_uom.wgt    IS '이 단위 1개의 중량(kg). NULL = 미측정';

-- 존 마스터. 로케이션의 상위 그룹 (온도 · 보관형태 · 담당업무 단위).
-- tmp_zon은 loc.tmp_zon · prod.tmp_zon과 같은 값 도메인이다 (공통코드 TEMP_ZONE, Java TempZone enum 공용).
-- tmp_zon / strg_typ / biz_dvsn은 공통코드에서 관리하므로 CHECK를 걸지 않는다 —
-- 코드를 추가할 때마다 DDL을 고치지 않기 위함이고, 값 검증은 서비스단 enum이 맡는다.
-- (loc·prod는 CHECK를 갖고 있어 존만 방식이 다르다. 근거는 docs/design.md 「존 마스터」)
CREATE TABLE zon (
    zon_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zon_cd      VARCHAR(20)     NOT NULL,
    zon_nm      VARCHAR(100)    NOT NULL,
    tmp_zon     VARCHAR(10)     NOT NULL,
    strg_typ    VARCHAR(10)     NOT NULL,
    biz_dvsn    VARCHAR(10)     NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_zon_cd UNIQUE (zon_cd)
);

COMMENT ON TABLE  zon IS '존 마스터 (로케이션의 상위 그룹)';
COMMENT ON COLUMN zon.zon_cd   IS '존 코드';
COMMENT ON COLUMN zon.zon_nm   IS '존 명';
COMMENT ON COLUMN zon.tmp_zon  IS '온도대. TmpZon enum';
COMMENT ON COLUMN zon.strg_typ IS '보관유형. StrgTyp enum';
COMMENT ON COLUMN zon.biz_dvsn IS '업무구분. BizDvsn enum';

-- 로케이션 마스터. 존(zon)의 하위 물리 위치. 입고 스테이징(RCV-STAGE)과 온도대별 보관존으로 구성.
CREATE TABLE loc (
    loc_id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loc_cd          VARCHAR(30)     NOT NULL,
    zon_id          BIGINT          NOT NULL,
    tmp_zon       VARCHAR(10)     NOT NULL,
    loc_typ        VARCHAR(10)     NOT NULL,
    pikng_prty       INTEGER         DEFAULT 0 NOT NULL,
    ptawy_prty      INTEGER         DEFAULT 0 NOT NULL,
    max_qty         BIGINT,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT uq_loc_cd UNIQUE (loc_cd),
    CONSTRAINT ck_loc_tmp_zon CHECK (tmp_zon IN ('DRY', 'CHL', 'FRZ')),
    CONSTRAINT ck_loc_typ CHECK (loc_typ IN ('STAGE', 'STORAGE')),
    CONSTRAINT ck_loc_max_qty CHECK (max_qty IS NULL OR max_qty > 0),
    -- 용량은 적치 전략의 전제다. 보관 로케이션에 상한이 없으면 후보가 "온도대 일치 전부"라
    -- 전략이 정렬 순서밖에 바꾸지 못한다 — 그래서 STORAGE에만 NOT NULL을 강제한다.
    CONSTRAINT ck_loc_storage_capacity CHECK (loc_typ <> 'STORAGE' OR max_qty IS NOT NULL)
);

COMMENT ON TABLE  loc IS '로케이션 마스터 (재고가 놓이는 물리 위치)';
COMMENT ON COLUMN loc.loc_cd    IS '로케이션 코드';
COMMENT ON COLUMN loc.zon_id   IS '소속 존';
COMMENT ON COLUMN loc.tmp_zon IS '온도대. TmpZon enum';
COMMENT ON COLUMN loc.loc_typ  IS '로케이션 유형. LocTyp enum';
COMMENT ON COLUMN loc.pikng_prty IS '할당 시 동일 유통기한';
COMMENT ON COLUMN loc.ptawy_prty IS '적치 우선순위';
COMMENT ON COLUMN loc.max_qty   IS '최대 적재 수량. NULL = 무제한';

-- 고정 로케이션 마스터. 상품×로케이션 지정 — 피킹존 운영의 근거 테이블.
-- 존이 아니라 로케이션 단위인 이유: "이 상품은 항상 이 자리"가 고정의 뜻이고, 보충 기준(min/max)도
-- 자리마다 다르다. UNIQUE(loc_id)로 한 로케이션 = 한 상품 전용 — 상품 하나가 여러 로케이션을
-- 갖는 것은 허용한다(회전 빠른 상품은 피킹 페이스가 여럿). PIKNG 존 강제는 하지 않는다 —
-- biz_dvsn 값 목록의 주인은 공통코드라(zon과 같은 이유) 서비스가 특정 값에 결합하지 않는다.
CREATE TABLE fxng_loc (
    fxng_loc_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_id     BIGINT      NOT NULL,
    loc_id      BIGINT      NOT NULL,
    min_qty     BIGINT      NOT NULL,
    max_qty     BIGINT      NOT NULL,
    created_at  TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_fxng_loc UNIQUE (loc_id),
    CONSTRAINT ck_fxng_loc_qty CHECK (min_qty >= 0 AND max_qty >= 1 AND min_qty <= max_qty)
);

COMMENT ON TABLE  fxng_loc IS '고정 로케이션 마스터 (상품 전용 자리)';
COMMENT ON COLUMN fxng_loc.prod_id IS '고정할 상품';
COMMENT ON COLUMN fxng_loc.loc_id  IS '고정 로케이션';
COMMENT ON COLUMN fxng_loc.min_qty IS '재보충점';
COMMENT ON COLUMN fxng_loc.max_qty IS '보충 목표 상한';

CREATE INDEX ix_fxng_loc_prod ON fxng_loc (prod_id); -- 상품→고정 로케이션 조회 (적치 추천 join · 상품 삭제 가드)

-- Lot. 입고 처리 시점에 생성되며 유통기한을 보유한다 (FEFO 기준값).
CREATE TABLE lot (
    lot_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_id      BIGINT          NOT NULL,
    lot_no      VARCHAR(30)     NOT NULL,
    receipt_dt  DATE,
    mfg_dt      DATE,
    expiry_dt   DATE,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_lot UNIQUE (prod_id, lot_no)
);

COMMENT ON TABLE  lot IS 'Lot 마스터 (입고 단위 묶음)';
COMMENT ON COLUMN lot.lot_no    IS 'Lot 번호';
COMMENT ON COLUMN lot.receipt_dt IS '입고일자 (소급 등록 가능)';
COMMENT ON COLUMN lot.mfg_dt    IS '제조일자. NULL = 유통기한 미관리 상품';
COMMENT ON COLUMN lot.expiry_dt IS '유통기한. NULL = 미관리 상품의 Lot';

CREATE INDEX ix_lot_expiry ON lot (prod_id, expiry_dt);
-- Lot 재사용 조회(상품+입고일자+제조일자) 및 일자별 채번 카운트에 사용
CREATE INDEX ix_lot_prod_receipt ON lot (prod_id, receipt_dt);

-- Lot 번호는 더 이상 DB 시퀀스로 채번하지 않는다.
-- 상품 로우 락(SELECT ... FOR UPDATE) 하에 해당 상품+입고일자의 기존 Lot 건수를 세어 다음 번호를 매긴다 (상품별 일자 리셋).

-- 점포 마스터. 납품 기준(잔여수명 허용률)은 상품이 아니라 납품처가 정한다.
CREATE TABLE store (
    store_id        BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_cd        VARCHAR(30)     NOT NULL,
    store_nm        VARCHAR(100)    NOT NULL,
    store_grp       VARCHAR(10),
    store_typ       VARCHAR(10),
    outb_life_rate  SMALLINT        DEFAULT 40 NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT uq_store_cd UNIQUE (store_cd),
    CONSTRAINT ck_store_life_rate CHECK (outb_life_rate BETWEEN 0 AND 100)
);

COMMENT ON TABLE  store IS '점포 마스터 (출고처)';
COMMENT ON COLUMN store.store_cd       IS '점포 코드';
COMMENT ON COLUMN store.store_grp      IS '점포그룹. NULL = 미지정';
COMMENT ON COLUMN store.store_typ      IS '점포유형. NULL = 미지정';
COMMENT ON COLUMN store.outb_life_rate IS '납품 허용 잔여수명 비율';

-- 벤더(납품처) 마스터. 입고주문·입고예정이 참조한다.
-- 점포(store)가 출고의 거래처이듯 벤더는 입고의 거래처 — 둘 다 마스터로 두어 대칭을 맞춘다.
-- 이름을 주문에 텍스트로 박지 않는 이유: 같은 벤더의 표기 흔들림("대한물류"/"(주)대한물류")을
-- 묶을 수 없고, 벤더 단위 기준정보(리드타임·검수기준 등)를 붙일 자리가 사라진다.
--
-- 사용여부(us_yn)를 두지 않는다 — 이 프로젝트의 어느 테이블에도 두지 않는다. 마스터는
-- 물리삭제로 운용한다. "지운 것도 아니고 쓰는 것도 아닌" 중간 상태를 만들면 모든 조회에
-- 그 필터가 따라붙어야 하고, 한 군데라도 빠지면 폐기한 값이 화면에 되살아난다.
CREATE TABLE vendor (
    vendor_id   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vndr_cd     VARCHAR(30)     NOT NULL,
    vndr_nm     VARCHAR(100)    NOT NULL,
    pic_nm      VARCHAR(50),
    tel_no      VARCHAR(30),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_vndr_cd UNIQUE (vndr_cd)
);

COMMENT ON TABLE  vendor IS '벤더 마스터 (매입처)';
COMMENT ON COLUMN vendor.vndr_cd IS '벤더 코드';

-- 공통코드 그룹. 관리 화면은 추후 추가 예정, 당분간 시드 데이터로만 운용.
-- 코드성 테이블이라 PK는 {테이블명}_id 규칙 대신 자연키를 쓴다 (조회가 항상 코드 기준).
CREATE TABLE code_group (
    grp_cd    VARCHAR(30)     NOT NULL,
    grp_nm    VARCHAR(100)    NOT NULL,
    dscr      VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT pk_code_group PRIMARY KEY (grp_cd)
);

COMMENT ON TABLE  code_group IS '공통코드 그룹';
COMMENT ON COLUMN code_group.grp_cd IS '코드 그룹 코드';
COMMENT ON COLUMN code_group.dscr   IS '그룹 설명';

-- 공통코드 상세. group_cd는 code_group 참조지만 FK는 걸지 않는다
-- (변경이 시드/관리화면으로만 일어나는 코드성 테이블 — 그룹 존재 검증은 관리 화면 추가 시 서비스에서).
CREATE TABLE code_detail (
    grp_cd    VARCHAR(30)     NOT NULL,
    code_cd     VARCHAR(30)     NOT NULL,
    code_nm     VARCHAR(100)    NOT NULL,
    srt_seq    INTEGER         DEFAULT 0 NOT NULL,
    ref1        VARCHAR(100),
    ref2        VARCHAR(100),
    ref3        VARCHAR(100),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT pk_code_detail PRIMARY KEY (grp_cd, code_cd)
);

-- 사용여부(us_yn)를 두지 않는다 (vendor와 같은 이유). 안 쓰는 코드는 지우고, 하위가 참조
-- 중이면 CodeService가 삭제를 거부한다 — UOM 그룹이 그 가드를 갖는 유일한 그룹이다.
COMMENT ON TABLE  code_detail IS '공통코드 상세';
COMMENT ON COLUMN code_detail.code_cd  IS '코드 값';
COMMENT ON COLUMN code_detail.srt_seq IS '화면 표시 정렬 순서';
-- 참조값 3칸. 코드마다 딸린 자잘한 속성을 새 컬럼 없이 얹는 자리다 (공통코드의 관행).
-- 뜻이 그룹마다 다르므로 컬럼 이름으로는 알 수 없다 — 무엇을 담았는지는 그 값을 읽는 쪽과
-- code_group.dscr 에 남긴다. 표시 스타일(뱃지 색 등)은 여기 담지 않는다:
-- 그건 프론트 상수가 갖기로 이미 정한 사항이다 (code_group 테이블 주석 참고).
COMMENT ON COLUMN code_detail.ref1    IS '참조값1. 뜻은 그룹마다 다르다 (해당 그룹의 dscr 참고)';
COMMENT ON COLUMN code_detail.ref2    IS '참조값2';
COMMENT ON COLUMN code_detail.ref3    IS '참조값3';

-- 채번 규칙. code_group과 같은 자연키 코드 테이블 — 항상 코드로 조회한다.
CREATE TABLE nbr_rule (
    rule_cd     VARCHAR(30)     NOT NULL,
    rule_nm     VARCHAR(100)    NOT NULL,
    prfx        VARCHAR(20)     NOT NULL,
    prfx_dlmt   VARCHAR(1)      NOT NULL,
    de_dlmt     VARCHAR(1)      NOT NULL,
    seq_dgt     SMALLINT        NOT NULL,
    dync_ky_typ VARCHAR(10)     NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT pk_nbr_rule PRIMARY KEY (rule_cd),
    CONSTRAINT ck_nbr_rule_prfx_dlmt CHECK (prfx_dlmt IN ('-', '_', '')),
    CONSTRAINT ck_nbr_rule_de_dlmt CHECK (de_dlmt IN ('-', '_', '')),
    CONSTRAINT ck_nbr_rule_seq_dgt CHECK (seq_dgt BETWEEN 1 AND 9),
    CONSTRAINT ck_nbr_rule_dync_ky_typ CHECK (dync_ky_typ IN ('NONE', 'YEAR', 'MONTH', 'DAY'))
);

COMMENT ON TABLE  nbr_rule IS '채번 규칙';
COMMENT ON COLUMN nbr_rule.rule_cd     IS '채번 규칙 코드';
COMMENT ON COLUMN nbr_rule.prfx        IS '접두어 리터럴';
COMMENT ON COLUMN nbr_rule.prfx_dlmt   IS '접두어 뒤 구분자';
COMMENT ON COLUMN nbr_rule.de_dlmt     IS '날짜 뒤 구분자';
COMMENT ON COLUMN nbr_rule.seq_dgt     IS 'SEQ 자릿수';
COMMENT ON COLUMN nbr_rule.dync_ky_typ IS '동적키 유형. DyncKyTyp enum';

-- 채번 카운터. rule_cd+dync_ky 조합별 현재 발급값. 관리자가 만들지 않고 최초 발급 시 자동 생성된다.
CREATE TABLE nbr_seq (
    rule_cd     VARCHAR(30)     NOT NULL,
    dync_ky     VARCHAR(30)     NOT NULL,
    seq         BIGINT          DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT pk_nbr_seq PRIMARY KEY (rule_cd, dync_ky)
);

COMMENT ON TABLE  nbr_seq IS '채번 카운터';
COMMENT ON COLUMN nbr_seq.dync_ky IS '동적키 값';
COMMENT ON COLUMN nbr_seq.seq     IS '현재 발급값';

-- 공통코드 시드 (참조 데이터 — 테이블 정의와 한 몸이므로 여기서 함께 관리)
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('TEMP_ZONE', '온도대', '보관 온도 구분 (상품/로케이션 공용)');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('LOC_TYPE', '로케이션 유형', '스테이징/보관 구분');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('STRG_TYP', '보관유형', '존의 물리 보관 형태');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('BIZ_DVSN', '업무구분', '존이 담당하는 업무');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('ODR_DVSN', '발주구분', '입고주문의 성격 (oms_ib_order.odr_dvsn)');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('UOM', '계량단위', '상품 포장의 단위 (prod_uom.uom_cd · prod.inb_uom_cd · outb_uom_cd)');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('HLD_RSN', '보류사유', '재고 보류 등록 사유 (inv_hld.rsn_cd). ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('RTNGS_RSN', '반품사유', '반품입고 라인의 반품 사유 (oms_ib_line.rsn_cd). ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('SHOTGE_RSN', '결품사유', '피킹 결품 종결 사유 (pikng_task.shotge_rsn_cd). 시킨 만큼 실물이 없어 잔량을 포기할 때의 근거다. ETC(기타)일 때만 자유 텍스트 shotge_rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('HLD_RLZ_RSN', '보류 해제사유', '재고 보류 해제 사유 (inv_hld_rlz_acrst.rsn_cd). 등록 사유와 별개 그룹 — 「왜 묶었나」와 「왜 풀었나」는 다른 질문이다. ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('ADJ_RSN', '재고조사 조정사유', '재고조사 확정 시 차이 라인의 조정 사유 (inv_stktk_ln.rsn_cd). 차이가 0이 아닌 라인만 필수이며, ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다. 재고조정(inv_adj)의 사유는 별개 그룹 INV_ADJ_RSN이다 — 조사는 「장부가 틀렸다」의 정정이고 조정은 「이만큼 처분했다」의 기록이라 사유 집합이 겹치지 않는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('INV_ADJ_RSN', '재고조정 사유', '재고조정 라인의 사유 (inv_adj.rsn_cd). 장부와 실물을 함께 증감시키는 처분의 근거다. ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('LOT_ATTR_RSN', 'Lot 속성정정 사유', 'Lot 속성(제조일자·유통기한) 정정 사유 (lot_attr_chng.rsn_cd · inv_lot_chng.rsn_cd — 재고 로트변경도 사유 성격이 같아 그룹을 재사용한다). ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('OUTB_TYP', '출고유형', '출고주문의 성격 (oms_outb_order.outb_typ → outb_order.outb_typ). 주문 등록 시 정해져 확정 때 창고로 복사된다. 웨이브 편성 조건의 기준값');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('VHCL_FLTNO', '차량편수', '출고 배차 차수 (oms_outb_order.vhcl_fltno → outb_order.vhcl_fltno). 웨이브 편성 조건의 기준값 — 같은 차수에 실릴 주문만 함께 묶는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('STORE_GRP', '점포그룹', '점포의 체인·계열 묶음 (store.store_grp). 웨이브 편성 조건 「납품처그룹」과 할당 분배 대상 선별의 기준값');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('STORE_TYP', '점포유형', '점포의 업태 (store.store_typ — 편의점·마트·급식). 웨이브 편성 조건 「납품처유형」과 할당 분배 대상 선별의 기준값');

INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('TEMP_ZONE', 'DRY', '상온', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('TEMP_ZONE', 'CHL', '냉장', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('TEMP_ZONE', 'FRZ', '냉동', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOC_TYPE', 'STAGE', '스테이징', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOC_TYPE', 'STORAGE', '보관', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STRG_TYP', 'RACK', '랙', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STRG_TYP', 'FLAT', '평치', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STRG_TYP', 'VRTL', '가상', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'INB', '입고작업', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'OUTB', '출고작업', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'STRG', '보관', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'PIKNG', '피킹', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'RTNGS', '반품', 5);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'WRK', '작업', 6);
-- 계량단위. EA(낱개)는 prod.inb_uom_cd · outb_uom_cd의 DEFAULT이고 prod_uom.ea_qty가 세는 기준
-- 단위이기도 해서, 다른 코드와 달리 존재가 구조적 전제다 — 지우지 말 것.
--
-- 포장 단위만 둔다 (KG · L 같은 계량 단위는 넣지 않는다). prod_uom.ea_qty가 「이 단위 1개 =
-- 낱개 몇 개」인데 kg·리터에는 그 값이 성립하지 않아서, 목록에 있으면 채울 수 없는 칸이 생긴다.
-- 중량은 이미 prod_uom.wgt가 kg 고정으로 들고 있어 단위를 데이터로 둘 이유도 없다.
-- 중량 기반 재고(수량 컬럼이 BIGINT가 아니게 되는 변경)가 필요해지면 그때 단위에 유형 속성을
-- 붙여야 하고, 그건 공통코드로 표현할 수 없으므로 전용 마스터를 다시 세우는 결정이 선행한다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'EA', '낱개', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'BOX', '박스', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'PACK', '팩', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'CS', '케이스', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'PLT', '파렛트', 5);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'BAG', '봉지', 6);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'TRAY', '트레이', 7);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'SET', '세트', 8);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'DZ', '다스', 9);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'BDL', '번들', 10);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'CTN', '카톤', 11);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'ROLL', '롤', 12);

-- 발주구분. 기본값 NRML은 prod.inb_uom_cd의 'EA'처럼 컬럼 DEFAULT가 가리키는 값이라 지우면 안 된다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ODR_DVSN', 'NRML', '정상', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ODR_DVSN', 'URGT', '긴급', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ODR_DVSN', 'RTNGS', '반품입고', 3);

-- 출고유형. NRML은 outb_order.outb_typ의 컬럼 DEFAULT가 가리키는 값이라 지우면 안 된다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('OUTB_TYP', 'NRML', '일반출고', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('OUTB_TYP', 'RTNGS', '반품출고', 2);

-- 차량편수. 코드값이 곧 차수 숫자다. 편수가 늘면 코드관리 화면에서 추가하면 되고 컬럼·코드 변경은 없다.
-- 조건 비교가 문자열이라 대소 연산자는 허용하지 않는다(10편이 2편보다 앞서게 된다) — EQ/IN 계열만 쓴다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('VHCL_FLTNO', '1', '1편', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('VHCL_FLTNO', '2', '2편', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('VHCL_FLTNO', '3', '3편', 3);

-- 점포그룹·점포유형. 시드 점포 5건이 실제로 쓰는 값들 — 그룹은 체인 계열, 유형은 업태다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_GRP', 'CNU', '씨앤유', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_GRP', 'HANMAUM', '한마음', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_GRP', 'HAENGBOK', '행복', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_TYP', 'CVS', '편의점', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_TYP', 'MART', '마트', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_TYP', 'FDSVC', '급식', 3);

-- 보류사유·해제사유. ETC(기타)는 「코드가 기타면 자유 텍스트 입력」 규칙이 걸리는 값이라 지우면 안 된다.
-- 코드는 분류 축일 뿐 병존 단위가 아니다 — 같은 재고 행에 같은 사유의 미해제 보류가 여러 건 있을 수 있다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('SHOTGE_RSN', 'NOSTOCK', '재고없음', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('SHOTGE_RSN', 'DAMG', '파손', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('SHOTGE_RSN', 'MISLOC', '위치오류', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('SHOTGE_RSN', 'ETC', '기타', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'QLTY', '품질이상', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'DAMG', '파손', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'EXPIRY', '유통기한', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'ETC', '기타', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('RTNGS_RSN', 'MISDLV', '오배송', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('RTNGS_RSN', 'DAMG', '파손', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('RTNGS_RSN', 'EXPIRY', '유통기한임박', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('RTNGS_RSN', 'UNSOLD', '미판매', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('RTNGS_RSN', 'ETC', '기타', 5);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'NRML', '정상 확인', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'ERR_REG', '오등록', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'ETC', '기타', 3);
-- 재고조정이 보류분을 폐기할 때 남기는 해제 실적의 사유. 트랜잭션이 넣는 값이라 화면 콤보에서는
-- 빼고 서버(InvHldService.release)도 수동 해제 요청에 이 코드가 오면 거부한다 —
-- 고르면 조정 없이 사유만 조정인 해제가 되어, 「등록은 되는데 동작하지 않는 옵션」이 된다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'ADJ', '재고조정', 4);

-- 재고조사 조정사유 (조사 확정 시 차이 라인). 여기도 ETC가 자유 텍스트 규칙의 트리거라 지우면 안 된다.
-- 세트화·단위대체 같은 타 업무 사유는 넣지 않는다 — 조사 전용만 담아 화면이 거를 필요가 없게 한다.
-- 조사의 사유는 「어디로 갔는지 모른다」 계열이다 — 누가 버렸는지 아는 수량은 재고조정(INV_ADJ_RSN)이 맡는다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'DAMG', '파손', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'LOSS', '분실', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'ERR_WRK', '작업오류', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'INIT', '기초재고', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'ETC', '기타', 5);

-- 재고조정 사유. 장부와 실물이 맞는 상태에서 둘을 함께 움직이는 처분의 근거라 조사와 값이 겹치지 않는다.
-- 기초재고·발견재고를 넣지 않는 이유: 「장부에 없던 것을 올린다」는 장부/실물 차이의 정정이라 조사 소관이다.
-- (+) 조정의 주 용도는 ERR_ADJ — append-only라 취소 경로가 없어 반대 부호 조정이 유일한 복구다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('INV_ADJ_RSN', 'SCRP', '폐기', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('INV_ADJ_RSN', 'SMPL', '견본출고', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('INV_ADJ_RSN', 'ERR_ADJ', '조정오류 정정', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('INV_ADJ_RSN', 'ETC', '기타', 4);

-- Lot 속성정정 사유 (재고 속성변경). 여기도 ETC가 자유 텍스트 규칙의 트리거라 지우면 안 된다.
-- 「왜 날짜가 틀렸나」의 출처를 나누는 값들이다 — 검수 입력 오류 / 실물 표기와 상이 / 거래처 통보.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'ERR_REG', '검수 오등록', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'LABEL', '실물표기 상이', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'VNDR', '거래처 정정 통보', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'ETC', '기타', 4);

-- 채번 규칙. 상품·벤더·점포 코드와 주문/입고/출고 번호를 여기서 발급한다 (전용 시퀀스 폐기).
-- STORE_CD의 접두어 ST는 STKTK_NO와 같지만 형식이 다르다(ST-0001 vs ST-20260814-001) —
-- prfx는 UNIQUE가 아니고, 시드가 이미 ST-0001 형식을 쓰고 있어 접두어를 바꿀 수 없다.
INSERT INTO nbr_rule (rule_cd, rule_nm, prfx, prfx_dlmt, de_dlmt, seq_dgt, dync_ky_typ) VALUES
    ('PROD_CD',     '상품 코드',        'PROD', '-', '-', 4, 'NONE'),
    ('VNDR_CD',     '벤더 코드',        'VD',   '-', '-', 4, 'NONE'),
    ('STORE_CD',    '점포 코드',        'ST',   '-', '-', 4, 'NONE'),
    ('OMS_IB_NO',   '입고주문 번호',    'PO',   '-', '-', 3, 'DAY'),
    ('OMS_OUTB_NO', '출고주문 번호',    'SO',   '-', '-', 3, 'DAY'),
    ('IB_NO',       '입고 번호',        'IB',   '-', '-', 3, 'DAY'),
    ('OUTB_NO',     '출고 번호',        'OB',   '-', '-', 3, 'DAY'),
    ('OUTB_WAV_NO', '출고 웨이브 번호', 'WV',   '-', '-', 3, 'DAY'),
    ('INV_MOV_NO',  '이동지시 번호',    'MV',   '-', '-', 3, 'DAY'),
    ('SPMT_NO',     '보충지시 번호',    'SP',   '-', '-', 3, 'DAY'),
    ('HLD_NO',      '보류 번호',        'HD',   '-', '-', 3, 'DAY'),
    ('STKTK_NO',    '재고조사 번호',    'ST',   '-', '-', 3, 'DAY'),
    ('LOT_CHNG_NO', '재고 로트변경 번호', 'LC', '-', '-', 3, 'DAY'),
    ('INV_ADJ_NO',  '재고조정 번호',    'AJ',   '-', '-', 3, 'DAY');
COMMIT;


-- =====================================================================
-- 2. OMS 주문 OMS_* (CREATED ↔ CONFIRMED)
--    주문 원장. WMS 작업문서(입고예정 ASN · 출고주문)의 유일한 발생지다.
--    확정(confirm) 시 같은 트랜잭션에서 ib_order / outb_order를 생성한다 —
--    WMS 쪽에 직접 등록 경로는 없다.
--    확정취소하면 작업문서는 삭제되고 주문은 CREATED로 돌아와 재확정할 수 있다.
--
--    취소 상태를 두지 않는다. 없앨 주문은 지운다 — 확정 전이면 바로, 확정 뒤면 확정취소로
--    되돌린 뒤에. "지운 것도 아니고 쓰는 것도 아닌" 상태를 두면 목록·집계마다 그 상태를 빼는
--    필터가 따라붙고, 화면에서 삭제와 취소 중 무엇을 눌러야 하는지가 매번 애매해진다.
--    (마스터에서 us_yn을 걷어낸 것과 같은 판단 — 위 「vendor」 참고)
--    ASN 쪽도 취소 상태를 두지 않는다: 확정취소는 ASN 행을 삭제한다 — 검수 전의 예정은
--    아직 아무 일도 안 한 문서라 흔적 가치가 없다 (재확정하면 새 번호로 새 행이 생긴다).
-- =====================================================================

-- 입고주문(벤더 발주) 헤더. 창고 작업 진행은 여기서 표현하지 않는다 (ASN의 status가 담당).
CREATE TABLE oms_ib_order (
    oms_ib_order_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_ib_no    VARCHAR(30)    NOT NULL,
    status       VARCHAR(15)    NOT NULL,
    vendor_id    BIGINT,
    store_id     BIGINT,
    ref_outb_no  VARCHAR(30),
    expct_de     DATE           NOT NULL,
    odr_dvsn     VARCHAR(10)    DEFAULT 'NRML' NOT NULL,
    pic_nm       VARCHAR(30),
    rmk          VARCHAR(200),
    cfm_dt       TIMESTAMP,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_oms_ib_no UNIQUE (oms_ib_no),
    CONSTRAINT ck_oms_ib_order_status CHECK (status IN ('CREATED', 'CONFIRMED')),
    CONSTRAINT ck_oms_ib_order_vndr_store CHECK ((vendor_id IS NOT NULL) <> (store_id IS NOT NULL))
);

COMMENT ON TABLE  oms_ib_order IS '입고주문 헤더 (벤더 발주)';
COMMENT ON COLUMN oms_ib_order.oms_ib_no    IS '입고주문 번호';
COMMENT ON COLUMN oms_ib_order.status       IS '입고주문 상태. OmsIbStatus enum';
COMMENT ON COLUMN oms_ib_order.vendor_id    IS '납품 벤더. 반품입고(odr_dvsn=RTNGS)는 NULL';
COMMENT ON COLUMN oms_ib_order.store_id     IS '반품 점포. 반품입고만, 벤더와 둘 중 하나';
COMMENT ON COLUMN oms_ib_order.ref_outb_no  IS '원 출고번호. 반품입고만, 선택 (느슨한 참조)';
COMMENT ON COLUMN oms_ib_order.expct_de     IS '입고 예정일';
COMMENT ON COLUMN oms_ib_order.odr_dvsn     IS '발주구분';
COMMENT ON COLUMN oms_ib_order.pic_nm       IS '발주 담당자명';
COMMENT ON COLUMN oms_ib_order.rmk          IS '비고';
COMMENT ON COLUMN oms_ib_order.cfm_dt       IS '확정(ASN 생성) 시각. NULL = 미확정';

-- 입고주문 라인. 발주 수량만 보유한다 (검수/적치 진행 수량은 ASN 라인이 갖는다).
CREATE TABLE oms_ib_line (
    oms_ib_line_id  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_ib_order_id BIGINT      NOT NULL,
    prod_id          BIGINT      NOT NULL,
    odr_qty       BIGINT      NOT NULL,
    rsn_cd          VARCHAR(10),
    rsn_dscr        VARCHAR(200),
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT ck_oms_ib_line_qty CHECK (odr_qty > 0)
);

COMMENT ON TABLE  oms_ib_line IS '입고주문 라인';
COMMENT ON COLUMN oms_ib_line.odr_qty  IS '발주 수량 (정상 입고단위 · 반품 출고단위)';
COMMENT ON COLUMN oms_ib_line.rsn_cd   IS '반품사유. RTNGS_RSN. 반품 라인만';
COMMENT ON COLUMN oms_ib_line.rsn_dscr IS '반품사유 상세. ETC일 때만';

CREATE INDEX ix_oms_ib_line_order ON oms_ib_line (oms_ib_order_id);
CREATE INDEX ix_oms_ib_order_vendor ON oms_ib_order (vendor_id);
CREATE INDEX ix_oms_ib_order_store ON oms_ib_order (store_id);


-- 출고주문(점포 수주) 헤더. 창고 작업 진행은 여기서 표현하지 않는다 (outb_order의 status가 담당).
-- 입고주문과 같은 구조다 — 다른 것은 상대가 벤더가 아니라 납품처(점포)라는 점과,
-- 확정 시 넘기는 값이 하나가 아니라 셋(납품처 · 출고유형 · 편수)이라는 점뿐이다.
CREATE TABLE oms_outb_order (
    oms_outb_order_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_outb_no  VARCHAR(30)    NOT NULL,
    status       VARCHAR(15)    NOT NULL,
    store_id     BIGINT         NOT NULL,
    outb_typ     VARCHAR(10)    DEFAULT 'NRML' NOT NULL,
    vhcl_fltno   VARCHAR(10),
    expct_de     DATE           NOT NULL,
    pic_nm       VARCHAR(30),
    rmk          VARCHAR(200),
    cfm_dt       TIMESTAMP,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_oms_outb_no UNIQUE (oms_outb_no),
    CONSTRAINT ck_oms_outb_order_status CHECK (status IN ('CREATED', 'CONFIRMED'))
);

COMMENT ON TABLE  oms_outb_order IS '출고주문 헤더 (점포 수주)';
COMMENT ON COLUMN oms_outb_order.oms_outb_no IS '출고주문 번호';
COMMENT ON COLUMN oms_outb_order.status      IS '출고주문 상태. OmsOutbStatus enum';
COMMENT ON COLUMN oms_outb_order.store_id    IS '납품처 점포';
COMMENT ON COLUMN oms_outb_order.outb_typ    IS '출고유형';
COMMENT ON COLUMN oms_outb_order.vhcl_fltno  IS '차량편수. NULL = 배차 미정';
COMMENT ON COLUMN oms_outb_order.expct_de    IS '출고 예정일';
COMMENT ON COLUMN oms_outb_order.pic_nm      IS '수주 담당자명';
COMMENT ON COLUMN oms_outb_order.rmk         IS '비고';
COMMENT ON COLUMN oms_outb_order.cfm_dt      IS '확정 시각. NULL = 미확정';

-- 출고주문 라인. 주문 수량만 보유한다 (할당/피킹 진행은 WMS 쪽이 갖는다).
CREATE TABLE oms_outb_line (
    oms_outb_line_id  BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_outb_order_id BIGINT    NOT NULL,
    prod_id           BIGINT    NOT NULL,
    odr_qty           BIGINT    NOT NULL,
    created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR(30),
    CONSTRAINT ck_oms_outb_line_qty CHECK (odr_qty > 0)
);

COMMENT ON TABLE  oms_outb_line IS '출고주문 라인';
COMMENT ON COLUMN oms_outb_line.odr_qty IS '주문 수량 (출고단위)';

CREATE INDEX ix_oms_outb_line_order ON oms_outb_line (oms_outb_order_id);
CREATE INDEX ix_oms_outb_order_store ON oms_outb_order (store_id);


-- =====================================================================
-- 3. 입고 IB_* (SCHEDULED → RECEIVING → CONFIRMED)
--    자동 전이 없음 — 종결은 입고확정 버튼뿐 (전제: 검수분 전량 적치).
--    검수·적치의 진행 단계(적치지시/적치완료)는 저장하지 않고 수량·지시에서 파생한다.
--    취소 상태 없음 — 확정취소는 행을 삭제한다 (검수 시작 전만 가능)
-- =====================================================================

-- 입고예정(ASN) 헤더. 상태는 워크플로 단계만 표현한다 (부분입고 상태 없음).
-- OMS 입고주문 확정으로만 생성된다 (등록·취소 엔드포인트가 WMS에 없다).
CREATE TABLE ib_order (
    ib_order_id BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ib_no       VARCHAR(30)     NOT NULL,
    oms_ib_order_id BIGINT      NOT NULL,
    status      VARCHAR(15)     NOT NULL,
    vendor_id   BIGINT,
    store_id    BIGINT,
    expct_de    DATE            NOT NULL,
    odr_dvsn    VARCHAR(10)     DEFAULT 'NRML' NOT NULL,
    cfm_dt      TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_ib_no UNIQUE (ib_no),
    CONSTRAINT ck_ib_order_status CHECK (status IN ('SCHEDULED', 'RECEIVING', 'CONFIRMED')),
    CONSTRAINT ck_ib_order_vndr_store CHECK ((vendor_id IS NOT NULL) <> (store_id IS NOT NULL))
);

COMMENT ON TABLE  ib_order IS '입고예정(ASN) 헤더';
COMMENT ON COLUMN ib_order.ib_no     IS '입고 번호';
COMMENT ON COLUMN ib_order.oms_ib_order_id IS '이 ASN을 발생시킨 OMS 입고주문';
COMMENT ON COLUMN ib_order.status    IS '입고예정 상태. IbStatus enum';
COMMENT ON COLUMN ib_order.vendor_id IS '납품 벤더. 반품입고는 NULL';
COMMENT ON COLUMN ib_order.store_id  IS '반품 점포. 반품입고만';
COMMENT ON COLUMN ib_order.expct_de  IS '입고 예정일';
COMMENT ON COLUMN ib_order.odr_dvsn  IS '발주구분';
COMMENT ON COLUMN ib_order.cfm_dt   IS '입고확정 시각';

-- 입고 라인. 부분입고/검수/적치 진행률을 수량으로만 표현한다.
CREATE TABLE ib_line (
    ib_line_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ib_order_id BIGINT          NOT NULL,
    prod_id      BIGINT          NOT NULL,
    expct_qty   BIGINT          NOT NULL,
    rcvd_qty    BIGINT          DEFAULT 0 NOT NULL,
    ptawy_qty    BIGINT          DEFAULT 0 NOT NULL,
    rjct_qty    BIGINT          DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT ck_ib_line_qty CHECK (
        expct_qty > 0 AND rcvd_qty >= 0 AND rjct_qty >= 0
        AND ptawy_qty >= 0 AND ptawy_qty <= rcvd_qty
    )
);

COMMENT ON TABLE  ib_line IS '입고예정(ASN) 라인';
COMMENT ON COLUMN ib_line.expct_qty IS '입고 예정 수량';
COMMENT ON COLUMN ib_line.rcvd_qty  IS '검수 양품 수량 누계 (스테이징 입)';
COMMENT ON COLUMN ib_line.rjct_qty  IS '검수 불량 수량 누계 (반품존 입). 반품입고만';
COMMENT ON COLUMN ib_line.ptawy_qty  IS '적치 완료 수량 누계';

CREATE INDEX ix_ib_line_order ON ib_line (ib_order_id);
-- 주문 → ASN 역추적 (입고주문 관리 화면이 주문별 ASN 진행상태를 붙여 보여준다)
CREATE INDEX ix_ib_order_oms ON ib_order (oms_ib_order_id);
-- 주문 하나가 붙들 수 있는 ASN은 하나. 확정취소가 행을 삭제하므로 평범한 유니크로 충분하다
-- (예전에는 CANCELLED를 남겨 부분 유니크였다 — migration-drop-asn-cancelled.sql로 전환).
-- 동시 확정 요청 시 두 트랜잭션이 모두 CREATED를 읽고 통과하는 구간을 DB가 막는 최후 방어선.
CREATE UNIQUE INDEX uq_ib_order_oms_active ON ib_order (oms_ib_order_id);
CREATE INDEX ix_ib_order_vendor ON ib_order (vendor_id);
CREATE INDEX ix_ib_order_store ON ib_order (store_id);

-- 적치 지시. 전략이 정한 배정 결과(어느 Lot을 어느 로케이션에 몇 개)를 담는다.
-- 지시 생성(전략 적용)과 지시 실행(실물 MOVE)을 분리해 지시 대비 실적을 추적한다.
-- 실적의 실체는 inv_hist의 MOVE 2행이므로 실적 테이블을 따로 두지 않고 cmpl_qty로 갈음한다.
CREATE TABLE putaway_task (
    putaway_task_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ib_line_id      BIGINT      NOT NULL,
    lot_id          BIGINT      NOT NULL,
    to_loc_id       BIGINT      NOT NULL,
    drct_qty        BIGINT      NOT NULL,
    cmpl_qty        BIGINT      DEFAULT 0 NOT NULL,
    status          VARCHAR(15) NOT NULL,
    cmpl_dt    TIMESTAMP,
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT ck_ptawy_task_status CHECK (status IN ('DIRECTED', 'DONE', 'CANCELLED')),
    -- 지시 초과 실행을 DB가 거부한다 (로케이션 적재가능수량 계산의 전제)
    CONSTRAINT ck_ptawy_task_qty CHECK (drct_qty > 0 AND cmpl_qty >= 0 AND cmpl_qty <= drct_qty)
);

COMMENT ON TABLE  putaway_task IS '적치 지시';
COMMENT ON COLUMN putaway_task.ib_line_id   IS '적치 대상 입고 라인';
COMMENT ON COLUMN putaway_task.lot_id       IS '적치 대상 Lot';
COMMENT ON COLUMN putaway_task.to_loc_id    IS '지시된 보관 로케이션';
COMMENT ON COLUMN putaway_task.drct_qty     IS '지시 수량';
COMMENT ON COLUMN putaway_task.cmpl_qty     IS '실행';
COMMENT ON COLUMN putaway_task.status       IS '적치지시 상태. PutawayTaskStatus enum';
COMMENT ON COLUMN putaway_task.cmpl_dt IS '지시 완료 시각';

CREATE INDEX ix_ptawy_task_line ON putaway_task (ib_line_id);
-- 적재가능수량 계산: 로케이션별 미완료 지시 잔량 SUM(drct_qty - cmpl_qty).
-- 지시는 대부분 금방 DONE이 되므로 DIRECTED만 담는 부분 인덱스로 좁게 유지한다.
CREATE INDEX ix_ptawy_task_open_loc ON putaway_task (to_loc_id) WHERE status = 'DIRECTED';


-- =====================================================================
-- 4. 재고 INV*
-- =====================================================================

-- 현재고 스냅샷. 할당 시 락을 거는 지점 (비관적/낙관적 락 비교 대상).
CREATE TABLE inv (
    inv_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_id      BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    on_hand_qty BIGINT          DEFAULT 0 NOT NULL,
    aloc_qty   BIGINT          DEFAULT 0 NOT NULL,
    hld_qty     BIGINT          DEFAULT 0 NOT NULL,
    version     BIGINT          DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_inv UNIQUE (prod_id, loc_id, lot_id),
    -- 동시성 실험의 최후 방어선: 애플리케이션 락이 실패해도 DB가 음수/과할당/과보류를 거부.
    -- 예약과 보류는 배타(각각 가용에서만 잡는다)라 합산 상한 하나로 표현된다.
    CONSTRAINT ck_inv_qty CHECK (on_hand_qty >= 0 AND aloc_qty >= 0 AND hld_qty >= 0 AND aloc_qty + hld_qty <= on_hand_qty)
);

COMMENT ON TABLE  inv IS '현재고 스냅샷 (키: 상품+Loc+Lot)';
COMMENT ON COLUMN inv.on_hand_qty IS '실물 보유 수량';
COMMENT ON COLUMN inv.aloc_qty   IS '예약 수량';
COMMENT ON COLUMN inv.hld_qty     IS '보류 수량';
COMMENT ON COLUMN inv.version     IS '낙관적 락 버전';

CREATE INDEX ix_inv_prod ON inv (prod_id);
CREATE INDEX ix_inv_loc ON inv (loc_id);

-- 재고 이력 (append-only 원장). 이력 합계 = 스냅샷 불변식의 근거 데이터.
CREATE TABLE inv_hist (
    inv_hist_id  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_typ      VARCHAR(10)    NOT NULL,
    prod_id       BIGINT         NOT NULL,
    loc_id       BIGINT         NOT NULL,
    lot_id       BIGINT         NOT NULL,
    qty          BIGINT         NOT NULL,
    rfn_doc_typ VARCHAR(10),
    rfn_doc_no   VARCHAR(30),
    ib_line_id   BIGINT,
    from_loc_id  BIGINT,
    to_loc_id    BIGINT,
    cncl_inv_hist_id BIGINT,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT ck_invh_tx_typ CHECK (tx_typ IN ('RECEIVE', 'MOVE', 'ADJUST', 'PICK', 'SHIP', 'RPLN')),
    CONSTRAINT ck_invh_qty CHECK (qty <> 0)
);

COMMENT ON TABLE  inv_hist IS '재고 이력 (append-only 원장)';
COMMENT ON COLUMN inv_hist.tx_typ      IS '거래유형. TxTyp enum';
COMMENT ON COLUMN inv_hist.qty          IS '변동 수량';
COMMENT ON COLUMN inv_hist.rfn_doc_typ IS '참조 문서 유형. RefDocTyp enum (INBOUND / OUTBOUND / INV_MOV 이동지시 / INV_STKTK 재고조사 / INV_ADJ 재고조정 / LOT_CHNG 재고 로트변경). NULL = 참조 문서 없음. ADJUST 이력은 rfn_doc_typ이 조사·조정·로트변경 중 무엇인지를 가른다 — tx_typ만으로는 구분되지 않는다';
COMMENT ON COLUMN inv_hist.rfn_doc_no   IS '참조 문서 번호';
COMMENT ON COLUMN inv_hist.ib_line_id   IS '입고 라인 ID';
COMMENT ON COLUMN inv_hist.from_loc_id  IS 'MOVE의 출발지. MOVE가 아니면 NULL';
COMMENT ON COLUMN inv_hist.to_loc_id    IS 'MOVE의 도착지. MOVE가 아니면 NULL';
COMMENT ON COLUMN inv_hist.cncl_inv_hist_id IS '검수 취소가 되돌리는 원본 RECEIVE 건. ADJUST가 아니면 NULL';

CREATE INDEX ix_invh_prod_created ON inv_hist (prod_id, created_at);
CREATE INDEX ix_invh_rfn_doc ON inv_hist (rfn_doc_no);
-- 입고 라인 역추적. tx_typ·created_at까지 담아 커버링으로 둔다 — 입고예정 목록의 최종 검수일시가
-- RECEIVE 행의 max(created_at) 파생이라, 세 컬럼이 인덱스에 있어야 테이블을 읽지 않는다
CREATE INDEX ix_invh_ib_line_typ_created ON inv_hist (ib_line_id, tx_typ, created_at);
-- 대사(reconciliation) 배치: 키별 SUM(qty) vs inv.on_hand_qty 비교용
CREATE INDEX ix_invh_inv_key ON inv_hist (prod_id, loc_id, lot_id);

-- 이동지시 (보관 ↔ 보관 2단계 이동: 지시=예약 → 확정=실물 MOVE).
-- 등록 시 FROM 재고의 aloc_qty를 선점하고, 확정이 inv_hist MOVE 2행을 남기며 예약을 소진한다.
-- 실적 테이블은 따로 없다 — 실적의 실체는 inv_hist의 MOVE 2행이고, 분할확정은 확정 횟수만큼
-- 2행이 쌓이는 것이다 (putaway_task가 지시/실적 분리를 접은 것과 같은 판단).
CREATE TABLE inv_mov_task (
    inv_mov_task_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_mov_no      VARCHAR(30) NOT NULL,
    mov_dvsn        VARCHAR(10) NOT NULL,
    prod_id         BIGINT      NOT NULL,
    lot_id          BIGINT      NOT NULL,
    from_loc_id     BIGINT      NOT NULL,
    to_loc_id       BIGINT      NOT NULL,
    drct_qty        BIGINT      NOT NULL,
    cmpl_qty        BIGINT      DEFAULT 0 NOT NULL,
    status          VARCHAR(15) NOT NULL,
    cmpl_dt         TIMESTAMP,
    pikng_task_id   BIGINT,
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT uq_inv_mov_no UNIQUE (inv_mov_no),
    CONSTRAINT ck_inv_mov_dvsn CHECK (mov_dvsn IN ('INV_MOV', 'RPLN', 'SPMT')),
    CONSTRAINT ck_inv_mov_status CHECK (status IN ('DIRECTED', 'DONE', 'CANCELLED')),
    -- 지시 초과 확정을 DB가 거부한다 (putaway_task의 ck_ptawy_task_qty와 같은 방어)
    CONSTRAINT ck_inv_mov_qty CHECK (drct_qty > 0 AND cmpl_qty >= 0 AND cmpl_qty <= drct_qty),
    CONSTRAINT ck_inv_mov_loc CHECK (from_loc_id <> to_loc_id)
);

COMMENT ON TABLE  inv_mov_task IS '이동지시 (보관↔보관)';
COMMENT ON COLUMN inv_mov_task.inv_mov_no  IS '이동지시 번호';
COMMENT ON COLUMN inv_mov_task.mov_dvsn    IS '이동구분. InvMovDvsn enum';
COMMENT ON COLUMN inv_mov_task.prod_id     IS '이동 대상 상품';
COMMENT ON COLUMN inv_mov_task.from_loc_id IS '출발 보관 로케이션';
COMMENT ON COLUMN inv_mov_task.to_loc_id   IS '도착 보관 로케이션';
COMMENT ON COLUMN inv_mov_task.drct_qty    IS '지시 수량';
COMMENT ON COLUMN inv_mov_task.cmpl_qty    IS '확정';
COMMENT ON COLUMN inv_mov_task.status      IS '이동지시 상태. InvMovStatus enum';
COMMENT ON COLUMN inv_mov_task.cmpl_dt     IS '지시 완료 시각';
COMMENT ON COLUMN inv_mov_task.pikng_task_id IS '짝 피킹지시';

-- 피킹지시 하나에 살아 있는 보충지시는 하나. 취소된 것은 다시 낼 수 있어 부분 유니크
CREATE UNIQUE INDEX uq_inv_mov_rpln_task ON inv_mov_task (pikng_task_id) WHERE status <> 'CANCELLED';

CREATE INDEX ix_inv_mov_prod ON inv_mov_task (prod_id);
-- 적재가능수량 계산: TO 로케이션별 미완료 지시 유입 잔량 SUM(drct_qty - cmpl_qty).
-- putaway_task의 ix_ptawy_task_open_loc와 같은 이유로 DIRECTED만 담는 부분 인덱스.
CREATE INDEX ix_inv_mov_open_to ON inv_mov_task (to_loc_id) WHERE status = 'DIRECTED';

-- 재고 보류 (수량 방식: 등록이 inv.hld_qty를 늘려 가용재고에서 뺀다. 재고상태 컬럼 없음).
-- 보류/해제는 물리 이동이 아니라 inv_hist(수량 원장)에 실을 수 없는데 등록·해제 각각의
-- 사유 히스토리를 보존해야 하므로, 「물리 변동 실적 테이블 없음」 원칙의 유일한 예외로
-- 전용 실적 테이블 2벌(inv_hld_acrst / inv_hld_rlz_acrst)을 둔다.
-- v1 보류 대상은 보관(STORAGE) 로케이션 재고만 — 스테이징 허용은 적치·출고확정 파급을 수반.
CREATE TABLE inv_hld (
    inv_hld_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hld_no      VARCHAR(30)     NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    hld_qty     BIGINT          NOT NULL,
    rlz_qty     BIGINT          DEFAULT 0 NOT NULL,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    status      VARCHAR(15)     NOT NULL,
    rlz_dt      TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_inv_hld_no UNIQUE (hld_no),
    CONSTRAINT ck_inv_hld_status CHECK (status IN ('HELD', 'RELEASED')),
    -- 과해제를 DB가 거부한다 (inv_mov_task의 ck_inv_mov_qty와 같은 방어)
    CONSTRAINT ck_inv_hld_qty CHECK (hld_qty > 0 AND rlz_qty >= 0 AND rlz_qty <= hld_qty)
);

COMMENT ON TABLE  inv_hld IS '재고 보류 건';
COMMENT ON COLUMN inv_hld.hld_no   IS '보류 번호';
COMMENT ON COLUMN inv_hld.prod_id  IS '보류 대상 상품';
COMMENT ON COLUMN inv_hld.hld_qty  IS '보류 수량';
COMMENT ON COLUMN inv_hld.rlz_qty  IS '해제 완료 수량 누계';
COMMENT ON COLUMN inv_hld.rsn_cd   IS '보류 사유 코드';
COMMENT ON COLUMN inv_hld.rsn_dscr IS '기타 사유 텍스트';
COMMENT ON COLUMN inv_hld.status   IS '보류 상태. InvHldStatus enum';
COMMENT ON COLUMN inv_hld.rlz_dt   IS '전량 해제 시각';

-- 항등식 대사(재고 키별 HELD 잔량 SUM vs inv.hld_qty) + 재고 행의 미해제 보류 조회.
-- 유니크가 아니다 — 같은 재고 행에는 사유가 같든 다르든 미해제 보류가 여러 건 병존한다.
CREATE INDEX ix_inv_hld_open ON inv_hld (prod_id, loc_id, lot_id) WHERE status = 'HELD';
-- 상태를 가리지 않는 상품별 조회 (위 부분 인덱스는 HELD만 담아 대신하지 못한다)
CREATE INDEX ix_inv_hld_prod ON inv_hld (prod_id);

-- 보류 실적 (등록의 append-only 로그). 보류 건과 1:1이지만 자기완결로 둔다 —
-- 건이 갱신(해제누계·상태 전이)돼도 등록 시점의 기록이 그대로 보존된다. 실적 시각 = created_at.
CREATE TABLE inv_hld_acrst (
    inv_hld_acrst_id BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hld_no      VARCHAR(30)     NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    hld_qty     BIGINT          NOT NULL,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT ck_inv_hld_acrst_qty CHECK (hld_qty > 0)
);

COMMENT ON TABLE  inv_hld_acrst IS '보류 등록 실적 (append-only)';

CREATE INDEX ix_inv_hld_acrst_no ON inv_hld_acrst (hld_no);

-- 해제 실적 (해제의 append-only 로그). 부분 해제가 N번이면 N행. 해제 사유는 등록 사유와
-- 별개의 코드 그룹(HLD_RLZ_RSN)이다 — 「왜 묶었나」와 「왜 풀었나」는 다른 질문이다.
CREATE TABLE inv_hld_rlz_acrst (
    inv_hld_rlz_acrst_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hld_no      VARCHAR(30)     NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    rlz_qty     BIGINT          NOT NULL,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT ck_inv_hld_rlz_acrst_qty CHECK (rlz_qty > 0)
);

COMMENT ON TABLE  inv_hld_rlz_acrst IS '보류 해제 실적 (append-only)';

CREATE INDEX ix_inv_hld_rlz_acrst_no ON inv_hld_rlz_acrst (hld_no);

-- 재고조사(실사). 조사 범위를 잡아 라인을 만들고(전산수량 스냅샷), 실사수량을 입력한 뒤
-- 확정 시점에 차이를 ADJUST로 보정한다. 장부와 실물이 어긋났을 때 장부를 실물에 맞추는 경로이고,
-- 조정수량은 실사수량에서 파생된다 — 실물을 그대로 둔 채 장부만 줄이는 처분(폐기·견본출고)은
-- 재고조정(inv_adj)의 몫이다. 특정 재고 하나의 차이 정정도 범위를 좁게 잡은 조사로 수행한다
-- (입고 확정 후 수량 정정 포함).
-- 실적 테이블은 없다 — 실적의 실체는 inv_hist의 ADJUST 행(rfn_doc_no = 조사번호)이다
-- (inv_mov_task와 같은 판단. 「실적 테이블 없음」의 예외는 보류와 피킹 둘이다 — pikng_acrst 참고).
CREATE TABLE inv_stktk (
    inv_stktk_id BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stktk_no    VARCHAR(30)     NOT NULL,
    zon_cd      VARCHAR(20),
    loc_id      BIGINT,
    prod_id     BIGINT,
    status      VARCHAR(15)     NOT NULL,
    cfm_dt      TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_inv_stktk_no UNIQUE (stktk_no),
    CONSTRAINT ck_inv_stktk_status CHECK (status IN ('CREATED', 'CONFIRMED', 'CANCELLED'))
);

COMMENT ON TABLE  inv_stktk IS '재고조사(실사) 헤더. 장부와 실물이 어긋났을 때 장부를 실물에 맞춘다 — 실물을 그대로 둔 채 장부만 줄이는 처분(폐기·견본출고)은 재고조정(inv_adj)의 몫이다. 상태는 워크플로 단계만(작성 → 확정) — 「부분확정」은 두지 않는다. 확정 후 재정정은 조사를 되열지 않고 새 조사를 만든다(append-only). 확정이 남기는 것은 inv_hist의 ADJUST 행(rfn_doc_typ=INV_STKTK, rfn_doc_no=stktk_no)';
COMMENT ON COLUMN inv_stktk.stktk_no IS '재고조사 번호';
COMMENT ON COLUMN inv_stktk.zon_cd   IS '조사 범위 — 존 코드. NULL = 조건 없음';
COMMENT ON COLUMN inv_stktk.loc_id   IS '조사 범위 — 로케이션. NULL = 조건 없음';
COMMENT ON COLUMN inv_stktk.prod_id  IS '조사 범위 — 상품. NULL = 조건 없음';
COMMENT ON COLUMN inv_stktk.status   IS '재고조사 상태. InvStktkStatus enum';
COMMENT ON COLUMN inv_stktk.cfm_dt   IS '확정 시각';

CREATE INDEX ix_inv_stktk_status ON inv_stktk (status);

-- 재고조사 라인. 재고 키(상품+Loc+Lot) 단위로 전산수량과 실사수량을 나란히 든다.
-- 조정수량(차이)은 stktk_qty - cfm_sys_qty 파생이라 컬럼을 두지 않는다.
CREATE TABLE inv_stktk_ln (
    inv_stktk_ln_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_stktk_id BIGINT         NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    sys_qty     BIGINT          NOT NULL,
    stktk_qty   BIGINT,
    cfm_sys_qty BIGINT,
    rsn_cd      VARCHAR(10),
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    -- 한 조사 안에서 같은 재고를 두 번 세지 않는다 (서비스 검증이 아니라 DB가 막는다)
    CONSTRAINT uq_inv_stktk_ln UNIQUE (inv_stktk_id, prod_id, loc_id, lot_id),
    CONSTRAINT ck_inv_stktk_ln_qty CHECK (
        sys_qty >= 0
        AND (stktk_qty IS NULL OR stktk_qty >= 0)
        AND (cfm_sys_qty IS NULL OR cfm_sys_qty >= 0)
    )
);

COMMENT ON TABLE  inv_stktk_ln IS '재고조사 라인 (재고 키 단위)';
COMMENT ON COLUMN inv_stktk_ln.sys_qty     IS '조사 생성 시점의 전산수량 스냅샷';
COMMENT ON COLUMN inv_stktk_ln.stktk_qty   IS '실사수량. NULL = 미조사';
COMMENT ON COLUMN inv_stktk_ln.cfm_sys_qty IS '확정 시점 전산수량(= 조정전수량). NULL = 확정 전';
COMMENT ON COLUMN inv_stktk_ln.rsn_cd      IS '조정사유 코드';
COMMENT ON COLUMN inv_stktk_ln.rsn_dscr    IS '기타 사유 텍스트';

CREATE INDEX ix_inv_stktk_ln_stktk ON inv_stktk_ln (inv_stktk_id);
CREATE INDEX ix_inv_stktk_ln_prod ON inv_stktk_ln (prod_id);

-- Lot 속성 정정 이력 (재고 속성변경 화면). 대상은 lot 행이라 INV* 접두를 쓰지 않지만,
-- 이 정정을 수행하는 업무가 재고 화면군이라 재고 절에 둔다 (Lot 생성이 검수의 소관인 것과 같은 갈래).
-- 이 화면은 재고를 한 톨도 움직이지 않는다 — inv·inv_hist 모두 무변경이고, 정정의 원장은 이 테이블 하나다.
-- 채번하지 않는다: 어디서도 참조되지 않는 append-only 로그라 문서번호가 필요 없다
-- (보류의 hld_no는 해제가 지목해야 해서, 조사의 stktk_no는 inv_hist.rfn_doc_no가 물어서 있는 것이다).
CREATE TABLE lot_attr_chng (
    lot_attr_chng_id BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id      BIGINT          NOT NULL,
    prod_id     BIGINT          NOT NULL,
    lot_no      VARCHAR(30)     NOT NULL,
    bfr_mfg_dt  DATE,
    aft_mfg_dt  DATE,
    bfr_expiry_dt DATE,
    aft_expiry_dt DATE,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    -- 변동 0 금지. ck_invh_qty(수량 변동 0 금지)와 같은 성격의 최후 방어 —
    -- 두 필드가 모두 그대로인 「정정」은 로그만 늘린다.
    CONSTRAINT ck_lot_attr_chng_diff CHECK (
        bfr_mfg_dt IS DISTINCT FROM aft_mfg_dt OR bfr_expiry_dt IS DISTINCT FROM aft_expiry_dt
    ),
    CONSTRAINT ck_lot_attr_chng_dt CHECK (
        aft_mfg_dt IS NULL OR aft_expiry_dt IS NULL OR aft_expiry_dt >= aft_mfg_dt
    )
);

COMMENT ON TABLE  lot_attr_chng IS 'Lot 속성 정정 이력 (수량 변동 없음)';
COMMENT ON COLUMN lot_attr_chng.lot_id        IS '정정 대상 Lot';
COMMENT ON COLUMN lot_attr_chng.prod_id       IS '대상 Lot의 상품';
COMMENT ON COLUMN lot_attr_chng.lot_no        IS 'Lot 번호 스냅샷';
COMMENT ON COLUMN lot_attr_chng.bfr_mfg_dt    IS '제조일자 변경 전 값';
COMMENT ON COLUMN lot_attr_chng.aft_mfg_dt    IS '제조일자 변경 후 값';
COMMENT ON COLUMN lot_attr_chng.bfr_expiry_dt IS '유통기한 변경 전 값';
COMMENT ON COLUMN lot_attr_chng.aft_expiry_dt IS '유통기한 변경 후 값';
COMMENT ON COLUMN lot_attr_chng.rsn_cd        IS '정정 사유 코드';
COMMENT ON COLUMN lot_attr_chng.rsn_dscr      IS '기타 사유 텍스트';

CREATE INDEX ix_lot_attr_chng_lot ON lot_attr_chng (lot_id);
CREATE INDEX ix_lot_attr_chng_prod_created ON lot_attr_chng (prod_id, created_at);

-- 재고 로트변경 (수량을 지정한 Lot 속성정정) 원장. lot_attr_chng(전량·무이동 정정)와 별개 테이블 —
-- 그쪽은 「한 Lot의 변경 전/후」(bfr_*/aft_*)이고 여기는 「두 Lot 사이」(from_*/to_*)라 모양이 다르고
-- (로트변경에서 원 Lot의 속성은 바뀌지 않는다), 무채번(그쪽) vs 채번 필수(여기)로 정책도 정면 충돌한다.
-- 재고 실체는 inv_hist의 ADJUST 2행(원 Lot −N / 새 Lot +N, rfn_doc_typ=LOT_CHNG, rfn_doc_no=lot_chng_no) —
-- 「이력 합계 = 스냅샷」 불변식은 Lot별로 그대로 유지된다. 이 테이블은 조작 단위의 자기완결 로그다(보류 실적 선례).
-- 대상은 보관(STORAGE) 로케이션의 유통기한 관리 상품 재고만 — 스테이징은 적치 잔량 집계(ib_line_id 기반)가
-- 깨져 제외한다(적치 전 제조일자 오류는 검수 취소 후 재검수가 정답).
CREATE TABLE inv_lot_chng (
    inv_lot_chng_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_chng_no VARCHAR(30)     NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    from_lot_id BIGINT          NOT NULL,
    from_lot_no VARCHAR(30)     NOT NULL,
    from_mfg_dt DATE            NOT NULL,
    from_expiry_dt DATE         NOT NULL,
    to_lot_id   BIGINT          NOT NULL,
    to_lot_no   VARCHAR(30)     NOT NULL,
    to_mfg_dt   DATE            NOT NULL,
    to_expiry_dt DATE           NOT NULL,
    chng_qty    BIGINT          NOT NULL,
    to_lot_new_yn BOOLEAN       DEFAULT FALSE NOT NULL,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_inv_lot_chng_no UNIQUE (lot_chng_no),
    CONSTRAINT ck_inv_lot_chng_qty CHECK (chng_qty >= 1),
    -- 같은 Lot으로의 「변경」 금지 — 제조일자가 같으면 목적지 = 원 Lot이라 조작 자체가 무의미하다
    CONSTRAINT ck_inv_lot_chng_lot CHECK (from_lot_id <> to_lot_id),
    -- 날짜 4컬럼이 NOT NULL이라(대상이 관리 상품뿐) lot_attr_chng의 null 분기 없이 곧장 비교한다
    CONSTRAINT ck_inv_lot_chng_dt  CHECK (to_expiry_dt >= to_mfg_dt)
);

COMMENT ON TABLE  inv_lot_chng IS '재고 로트변경 이력 (재고를 다른 Lot으로 이동)';
COMMENT ON COLUMN inv_lot_chng.lot_chng_no    IS '로트변경 번호';
COMMENT ON COLUMN inv_lot_chng.prod_id        IS '대상 상품';
COMMENT ON COLUMN inv_lot_chng.loc_id         IS '대상 보관 로케이션';
COMMENT ON COLUMN inv_lot_chng.from_lot_id    IS '원 Lot';
COMMENT ON COLUMN inv_lot_chng.from_lot_no    IS '원 Lot 번호 스냅샷';
COMMENT ON COLUMN inv_lot_chng.from_mfg_dt    IS '원 Lot 제조일자 스냅샷';
COMMENT ON COLUMN inv_lot_chng.from_expiry_dt IS '원 Lot 유통기한 스냅샷';
COMMENT ON COLUMN inv_lot_chng.to_lot_id      IS '목적지 Lot';
COMMENT ON COLUMN inv_lot_chng.to_lot_no      IS '목적지 Lot 번호 스냅샷';
COMMENT ON COLUMN inv_lot_chng.to_mfg_dt      IS '정정된 제조일자';
COMMENT ON COLUMN inv_lot_chng.to_expiry_dt   IS '정정된 유통기한';
COMMENT ON COLUMN inv_lot_chng.chng_qty       IS '변경 수량';
COMMENT ON COLUMN inv_lot_chng.to_lot_new_yn  IS '목적지 Lot을 이번에 채번했는가';
COMMENT ON COLUMN inv_lot_chng.rsn_cd         IS '변경 사유 코드';
COMMENT ON COLUMN inv_lot_chng.rsn_dscr       IS '기타 사유 텍스트';

CREATE INDEX ix_inv_lot_chng_from_lot     ON inv_lot_chng (from_lot_id);
CREATE INDEX ix_inv_lot_chng_prod_created ON inv_lot_chng (prod_id, created_at);


-- 재고조정. 장부와 실물이 맞는 상태에서 둘을 함께 증감시키는 의도된 처분(폐기·견본출고)의 기록이다.
-- 재고조사와 갈리는 지점은 「실물이 그 자리에 있느냐」 하나다 — 조사는 어긋난 것을 실물에 맞추고
-- (조정수량이 실사수량에서 파생), 조정은 맞는 것을 함께 줄인다(조정수량이 입력값). 불량 반품을
-- 폐기하는데 실사수량 0으로 적으면 「세어보니 없었다」는 거짓 기록이 되므로 경로를 나눈다.
-- 실적 테이블을 따로 두지 않는 자기완결 로그다 (inv_lot_chng과 같은 형태, append-only · 취소 없음).
-- 재고 실체는 inv_hist의 ADJUST 1행(부호 있음, rfn_doc_typ=INV_ADJ, rfn_doc_no=adj_no).
CREATE TABLE inv_adj (
    inv_adj_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adj_no      VARCHAR(30)     NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    adj_bfr_qty BIGINT          NOT NULL,
    adj_qty     BIGINT          NOT NULL,
    hld_no      VARCHAR(30),
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_inv_adj_no UNIQUE (adj_no),
    -- 조정후수량이 음수가 될 수 없다. ck_invh_qty(변동 0 금지)와 짝을 이루는 최후 방어 —
    -- 서비스가 가용·보류 잔량으로 이미 막지만 DB도 스스로 성립한다
    CONSTRAINT ck_inv_adj_qty CHECK (adj_qty <> 0 AND adj_bfr_qty >= 0 AND adj_bfr_qty + adj_qty >= 0),
    -- 보류 라인은 감소 전용 — 보류를 늘리는 조정은 없다(그건 재고 보류 등록이다)
    CONSTRAINT ck_inv_adj_hld CHECK (hld_no IS NULL OR adj_qty < 0)
);

COMMENT ON TABLE  inv_adj IS '재고조정 원장 (append-only 자기완결 로그). 취소 경로 없음 — 되돌리는 것도 새 조정 1건(사유 ERR_ADJ)이다';
COMMENT ON COLUMN inv_adj.adj_no      IS '재고조정 번호 (nbr_rule INV_ADJ_NO, 건당 유일 — 라인 구조 없음). inv_hist.rfn_doc_no로 실려 실적 ↔ 이력이 1:1로 매칭된다';
COMMENT ON COLUMN inv_adj.prod_id     IS '조정 대상 상품';
COMMENT ON COLUMN inv_adj.loc_id      IS '조정 대상 보관 로케이션 (스테이징은 대상이 아니다 — 보류·이동·조사와 같은 경계)';
COMMENT ON COLUMN inv_adj.lot_id      IS '조정 대상 Lot';
COMMENT ON COLUMN inv_adj.adj_bfr_qty IS '조정전수량 — 화면 입력값이 아니라 재고 행 락을 걸고 다시 읽은 on_hand_qty다 (재고조사 cfm_sys_qty와 같은 성격). 조정후수량은 adj_bfr_qty + adj_qty로 파생되므로 담지 않는다';
COMMENT ON COLUMN inv_adj.adj_qty     IS '조정수량 (부호 있음 — 양수 증가 / 음수 감소). 0은 금지';
COMMENT ON COLUMN inv_adj.hld_no      IS '소진한 보류 건 (보류 라인). NULL이면 가용 라인 — 라인 종류의 유일한 판별자라 별도 구분 컬럼을 두지 않는다. 보류 라인은 이 조정이 inv_hld_rlz_acrst 해제 실적(사유 ADJ)을 함께 남긴다';
COMMENT ON COLUMN inv_adj.rsn_cd      IS '조정사유 코드 (공통코드 INV_ADJ_RSN). ETC(기타)일 때만 rsn_dscr 필수';
COMMENT ON COLUMN inv_adj.rsn_dscr    IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';

CREATE INDEX ix_inv_adj_prod_created ON inv_adj (prod_id, created_at);
-- 보류 건에서 「무엇으로 소진됐나」를 찾는 역방향 추적. 해제 실적(inv_hld_rlz_acrst)에는
-- 조정번호를 실을 컬럼이 없어(보류의 원장이다) 조정이 자기 로그에 상대를 적는 쪽으로 잇는다
CREATE INDEX ix_inv_adj_hld ON inv_adj (hld_no) WHERE hld_no IS NOT NULL;


-- =====================================================================
-- 5. 출고 OUTB_* (CREATED → ALLOCATED → PICKING → PICKED → SHIPPED)
--    취소 상태 없음 — 확정취소(OMS 출고주문)가 행을 삭제한다 (웨이브 편성 전만). ASN과 같은 방식
--    할당은 웨이브를 대상으로 실행하되 계산·결과는 출고주문 라인 단위다 (outb_alloc).
--    웨이브 상태는 할당으로 바뀌지 않는다 — 「릴리즈(=웨이브가 할당 상태를 갖는 것)」는 없다.
--    피킹/확정도 주문 단위.
--    물리 재고는 2단계: PICK(보관→SHIP-STAGE) → SHIP(SHIP-STAGE 반출). 입고의 거울상.
-- =====================================================================

-- 출고 웨이브. 피킹지시의 발행 단위이자 할당의 실행 단위 (동시성 실험의 경합 지점).
CREATE TABLE outb_wave (
    outb_wave_id BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wav_no      VARCHAR(30)    NOT NULL,
    status       VARCHAR(15)    NOT NULL,
    issued_dt    TIMESTAMP,
    clos_dt      TIMESTAMP,
    wav_stgy_id  BIGINT,
    rvsn_no      BIGINT,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_wav_no UNIQUE (wav_no),
    CONSTRAINT ck_outb_wave_status CHECK (status IN ('PLANNED', 'ISSUED', 'CLOSED')),
    -- 전략 컬럼은 전략이 실제로 실행해 만든 행에만 채운다 — "전략 id 있음 = 전략이 실행함"이 성립해야 한다
    CONSTRAINT ck_outb_wave_stgy CHECK ((wav_stgy_id IS NULL) = (rvsn_no IS NULL))
);

COMMENT ON TABLE  outb_wave IS '출고 웨이브 (피킹지시 발행 단위)';
COMMENT ON COLUMN outb_wave.wav_no     IS '웨이브 번호';
COMMENT ON COLUMN outb_wave.status      IS '웨이브 상태. WaveStatus enum';
COMMENT ON COLUMN outb_wave.issued_dt   IS '피킹지시 발행 시각. NULL = 미발행';
COMMENT ON COLUMN outb_wave.clos_dt     IS '종료 시각';
COMMENT ON COLUMN outb_wave.wav_stgy_id IS '이 웨이브를 만든 웨이브 전략. NULL = 화면에서 수동 생성';
COMMENT ON COLUMN outb_wave.rvsn_no     IS '생성에 사용된 전략 리비전';

-- 출고 주문 헤더. 부분할당 여부는 상태가 아니라 라인/할당 수량에서 파생.
-- OMS 출고주문 확정으로만 생성된다 (등록·취소 엔드포인트가 WMS에 없다 — ASN과 같은 구조).
CREATE TABLE outb_order (
    outb_order_id BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outb_no     VARCHAR(30)     NOT NULL,
    oms_outb_order_id BIGINT    NOT NULL,
    status      VARCHAR(15)     NOT NULL,
    outb_typ    VARCHAR(10)     DEFAULT 'NRML' NOT NULL,
    vhcl_fltno  VARCHAR(10),
    store_id    BIGINT          NOT NULL,
    wav_id     BIGINT,
    wav_reg_typ VARCHAR(10),
    odr_de    DATE            NOT NULL,
    expct_de  DATE            NOT NULL,
    shmt_dt  TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_outb_no UNIQUE (outb_no),
    CONSTRAINT ck_outb_order_status CHECK (status IN ('CREATED', 'ALLOCATED', 'PICKING', 'PICKED', 'SHIPPED')),
    -- 편성 출처는 편성돼 있을 때만 존재한다. 편성 해제·주문 취소는 wav_id와 함께 이 컬럼도 비워야 한다
    CONSTRAINT ck_outb_order_wav_reg CHECK (
        (wav_id IS NULL AND wav_reg_typ IS NULL)
        OR (wav_id IS NOT NULL AND wav_reg_typ IN ('STGY', 'MANUAL'))
    )
);

COMMENT ON TABLE  outb_order IS '출고주문 헤더 (WMS)';
COMMENT ON COLUMN outb_order.outb_no  IS '출고 번호';
COMMENT ON COLUMN outb_order.oms_outb_order_id IS '이 출고주문을 발생시킨 OMS 출고주문';
COMMENT ON COLUMN outb_order.status   IS '출고 상태. OutbStatus enum';
COMMENT ON COLUMN outb_order.outb_typ   IS '출고유형';
COMMENT ON COLUMN outb_order.vhcl_fltno IS '차량편수. NULL = 배차 미정';
COMMENT ON COLUMN outb_order.store_id IS '출고처 점포';
COMMENT ON COLUMN outb_order.wav_id  IS '편성된 출고 웨이브. NULL = 아직 미편성';
COMMENT ON COLUMN outb_order.wav_reg_typ IS '웨이브 편입 출처. WavRegTyp enum. NULL = 미편성';
COMMENT ON COLUMN outb_order.odr_de IS '주문일 = 상위 OMS 출고주문이 등록된 날';
COMMENT ON COLUMN outb_order.shmt_dt  IS '출고 확정 시각';
COMMENT ON COLUMN outb_order.expct_de IS '출고 예정일';

CREATE INDEX ix_outb_order_wav ON outb_order (wav_id);
-- 주문 → WMS 출고주문 역추적 (출고주문 관리 화면이 주문별 창고 진행상태를 붙여 보여준다)
CREATE INDEX ix_outb_order_oms ON outb_order (oms_outb_order_id);
-- 주문 하나가 붙들 수 있는 WMS 출고주문은 하나. 확정취소가 행을 삭제하므로 평범한 유니크로 충분하다.
-- 동시 확정 요청 시 두 트랜잭션이 모두 CREATED를 읽고 통과하는 구간을 DB가 막는 최후 방어선
-- (ib_order의 uq_ib_order_oms_active와 같은 역할).
CREATE UNIQUE INDEX uq_outb_order_oms ON outb_order (oms_outb_order_id);

-- 출고 라인. 주문 수량만 보유하고, 할당/피킹 진행은 outb_alloc에서 집계 파생.
CREATE TABLE outb_line (
    outb_line_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outb_order_id BIGINT        NOT NULL,
    prod_id        BIGINT        NOT NULL,
    odr_qty     BIGINT        NOT NULL,
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    VARCHAR(30)   DEFAULT 'admin' NOT NULL,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(30),
    CONSTRAINT ck_outb_line_qty CHECK (odr_qty > 0)
);

COMMENT ON TABLE  outb_line IS '출고주문 라인 (WMS)';
COMMENT ON COLUMN outb_line.odr_qty IS '주문 수량';

CREATE INDEX ix_outb_line_order ON outb_line (outb_order_id);

-- 할당. 주문라인 ↔ 재고(상품+Loc+Lot) 매핑. FEFO(+ 납품기한 필터) 결과가 기록된다.
CREATE TABLE outb_alloc (
    outb_alloc_id BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outb_line_id  BIGINT        NOT NULL,
    inv_id        BIGINT        NOT NULL,
    aloc_qty     BIGINT        NOT NULL,
    pikng_qty    BIGINT        DEFAULT 0 NOT NULL,
    -- 이 할당을 만든 전략·리비전. 전략이 실제로 실행해 만든 행에만 채운다 —
    -- 수동할당분에까지 채우면 "전략 id 있음 ≠ 전략 실행됨"이 되어 추적이 무의미해진다
    aloc_stgy_id  BIGINT,
    rvsn_no       BIGINT,
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    VARCHAR(30)   DEFAULT 'admin' NOT NULL,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(30),
    CONSTRAINT ck_aloc_qty CHECK (aloc_qty > 0 AND pikng_qty >= 0 AND pikng_qty <= aloc_qty),
    CONSTRAINT ck_outb_alloc_stgy CHECK ((aloc_stgy_id IS NULL) = (rvsn_no IS NULL))
);

COMMENT ON TABLE  outb_alloc IS '재고 할당 레코드';
COMMENT ON COLUMN outb_alloc.aloc_qty  IS '할당 수량';
COMMENT ON COLUMN outb_alloc.aloc_stgy_id IS '이 할당을 만든 할당 전략. NULL = 수동할당 또는 전략 미설정 기간의 기본 동작';
COMMENT ON COLUMN outb_alloc.rvsn_no      IS '할당에 사용된 전략 리비전';
COMMENT ON COLUMN outb_alloc.pikng_qty IS '피킹 완료 수량';

CREATE INDEX ix_alloc_line ON outb_alloc (outb_line_id);
CREATE INDEX ix_alloc_inv ON outb_alloc (inv_id);

-- 피킹 지시. putaway_task·inv_mov_task와 동등한 위치의 세 번째 작업지시 문서 (2026-08-20 확정).
-- 웨이브 발행 시 outb_alloc과 1:1로 생성된다 — 상품별 집약(배치 피킹) 없음.
-- 등록이 예약을 만들지 않는 점이 inv_mov_task와 다르다 — 예약은 할당이 이미 잡았고,
-- 실행(PICK)이 그 예약을 소진한다. 발행·취소는 웨이브 단위다 (웨이브가 발행 문서).
CREATE TABLE pikng_task (
    pikng_task_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outb_wave_id  BIGINT      NOT NULL,
    outb_alloc_id BIGINT      NOT NULL,
    prod_id       BIGINT      NOT NULL,
    from_loc_id   BIGINT      NOT NULL,
    lot_id        BIGINT      NOT NULL,
    drct_qty      BIGINT      NOT NULL,
    cmpl_qty      BIGINT      DEFAULT 0 NOT NULL,
    status        VARCHAR(15) NOT NULL,
    srt_seq       INT         NOT NULL,
    cmpl_dt       TIMESTAMP,
    shotge_qty      BIGINT,
    shotge_rsn_cd   VARCHAR(10),
    shotge_rsn_dscr VARCHAR(200),
    created_at    TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(30),
    CONSTRAINT ck_pikng_task_status CHECK (status IN ('DIRECTED', 'DONE', 'CANCELLED')),
    -- 지시 초과 실행을 DB가 거부한다 (ck_ptawy_task_qty·ck_inv_mov_qty와 같은 방어)
    CONSTRAINT ck_pikng_task_qty CHECK (drct_qty > 0 AND cmpl_qty >= 0 AND cmpl_qty <= drct_qty),
    -- 결품 수량과 사유는 짝으로만 존재한다 — 한쪽만 있으면 「왜 사라졌나」와 「얼마나 사라졌나」 중 하나를 잃는다
    CONSTRAINT ck_pikng_task_shotge CHECK ((shotge_qty IS NULL) = (shotge_rsn_cd IS NULL)
                                           AND (shotge_qty IS NULL OR shotge_qty > 0))
);

COMMENT ON TABLE  pikng_task IS '피킹 지시';
COMMENT ON COLUMN pikng_task.outb_wave_id  IS '발행 웨이브';
COMMENT ON COLUMN pikng_task.outb_alloc_id IS '지시의 근거 할당';
COMMENT ON COLUMN pikng_task.prod_id       IS '재고 키 스냅샷';
COMMENT ON COLUMN pikng_task.from_loc_id   IS '집품 로케이션 = 할당된 재고의 로케이션 스냅샷';
COMMENT ON COLUMN pikng_task.lot_id        IS '집품 Lot 스냅샷';
COMMENT ON COLUMN pikng_task.drct_qty      IS '지시 수량 = 발행 시점의 aloc_qty';
COMMENT ON COLUMN pikng_task.cmpl_qty      IS '실행';
COMMENT ON COLUMN pikng_task.status        IS '피킹지시 상태. PikngTaskStatus enum';
COMMENT ON COLUMN pikng_task.srt_seq       IS '집품 순서';
COMMENT ON COLUMN pikng_task.cmpl_dt       IS '지시 완료 시각';
COMMENT ON COLUMN pikng_task.shotge_qty      IS '결품 수량';
COMMENT ON COLUMN pikng_task.shotge_rsn_cd   IS '결품 사유 코드. NULL = 결품 아님';
COMMENT ON COLUMN pikng_task.shotge_rsn_dscr IS '기타 결품사유 텍스트';

-- 지시 = 할당 1:1의 물리적 강제. 취소(CANCELLED) 행은 이력으로 남으므로 살아 있는 행만 센다 —
-- 취소 후 재발행이 같은 할당에 새 지시를 만드는 경로를 열어두면서 이중 발행은 거부한다
CREATE UNIQUE INDEX uq_pikng_task_alloc ON pikng_task (outb_alloc_id) WHERE status <> 'CANCELLED';
CREATE INDEX ix_pikng_task_wave ON pikng_task (outb_wave_id);

-- 피킹 실적 (실행 append-only 로그). 수정·삭제하지 않는다 — 부분 피킹이 N번이면 N행.
-- 「실적 = inv_hist」 원칙의 두 번째 예외 (첫째는 보류) — PICK 이력의 참조(rfn_doc_no = 출고번호)는
-- 주문 단위라 실행 건을 지시 단위로 귀속시키지 못한다. 실적 취소(백로그) 도입 시 취소 단위가 이 행이다.
CREATE TABLE pikng_acrst (
    pikng_acrst_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pikng_task_id  BIGINT      NOT NULL,
    prod_id        BIGINT      NOT NULL,
    from_loc_id    BIGINT      NOT NULL,
    lot_id         BIGINT      NOT NULL,
    pikng_qty      BIGINT      NOT NULL,
    created_at     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by     VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at     TIMESTAMP,
    updated_by     VARCHAR(30),
    CONSTRAINT ck_pikng_acrst_qty CHECK (pikng_qty > 0)
);

COMMENT ON TABLE  pikng_acrst IS '피킹 실적 (append-only)';
COMMENT ON COLUMN pikng_acrst.pikng_task_id IS '실행한 피킹지시';
COMMENT ON COLUMN pikng_acrst.pikng_qty     IS '이번 실행의 피킹 수량';

CREATE INDEX ix_pikng_acrst_task ON pikng_acrst (pikng_task_id);


-- =====================================================================
-- 6. 전략 STGY_* / INSP_* / PTAWY_* / WAV_* / ALOC_*  (관리자 정의 실행 정책)
--    - 로직·선택지·필드매핑은 코드 레지스트리가 소유하고, DB는 "무엇을 선택했고
--      파라미터가 무엇인가"만 저장한다. rule_cd/mthd_cd에 CHECK를 걸지 않는 이유 —
--      구현체 추가 시 DDL을 고치지 않기 위함이고, 존재 검증은 저장 서비스가 한다
--      (공통코드 성격 컬럼과 같은 방식). 전략 선택지를 code_detail에 넣지 않는다.
--    - 사용여부 컬럼 없음 (전 테이블 공통 원칙 유지 — D4). 실행 제외 = 물리삭제,
--      복원 근거 = stgy_rvsn 스냅샷.
--    - 파라미터·조건 목록은 JSONB — 저장 시 서비스가 ParamSpec/필드 레지스트리로
--      검증해 통과분만 담는다 (FK 0건과 같은 "검증은 애플리케이션" 철학).
--    - 웨이브(wav_stgy)는 2차에서 추가됐다. 할당 테이블(ALOC_*)은 3차.
-- =====================================================================

-- 전략 리비전. 저장(생성·수정·복원)마다 정의 전체를 스냅샷으로 남기는 append-only 이력.
-- 실행 기록(stgy_exec_log)의 rvsn_no와 조합해 "그때의 정의"를 재구성한다.
CREATE TABLE stgy_rvsn (
    stgy_rvsn_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_typ     VARCHAR(10)  NOT NULL,
    stgy_id      BIGINT       NOT NULL,
    rvsn_no      BIGINT       NOT NULL,
    snpsht       JSONB        NOT NULL,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_stgy_rvsn UNIQUE (stgy_typ, stgy_id, rvsn_no),
    -- 유형은 구조적 enum이다 (status 류와 같은 취급). WAV·ALOC은 2차 선반영
    CONSTRAINT ck_stgy_rvsn_typ CHECK (stgy_typ IN ('INSP', 'PTAWY', 'WAV', 'ALOC')),
    CONSTRAINT ck_stgy_rvsn_no CHECK (rvsn_no >= 1)
);

COMMENT ON TABLE  stgy_rvsn IS '전략 리비전 스냅샷 (append-only)';
COMMENT ON COLUMN stgy_rvsn.stgy_typ IS '전략 유형. StgyTyp enum';
COMMENT ON COLUMN stgy_rvsn.stgy_id  IS '유형별 헤더 PK';
COMMENT ON COLUMN stgy_rvsn.rvsn_no  IS '전략별 1부터 증가';
COMMENT ON COLUMN stgy_rvsn.snpsht   IS '정의 전체';

-- 전략 실행 로그. 실행·미리보기의 결과 요약 + 건별 판정 근거(dcsn_trc).
-- 검수는 결과 행이 없는 유형(산출물 = 차단 예외)이라 이 로그가 유일한 실행 흔적이다.
CREATE TABLE stgy_exec_log (
    stgy_exec_log_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_typ         VARCHAR(10) NOT NULL,
    stgy_id          BIGINT      NOT NULL,
    rvsn_no          BIGINT      NOT NULL,
    trgr_typ         VARCHAR(10) NOT NULL,
    tgt_ref          VARCHAR(30),
    rslt_smry        VARCHAR(200),
    dcsn_trc         JSONB,
    created_at       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by       VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at       TIMESTAMP,
    updated_by       VARCHAR(30),
    CONSTRAINT ck_stgy_exec_log_typ  CHECK (stgy_typ IN ('INSP', 'PTAWY', 'WAV', 'ALOC')),
    CONSTRAINT ck_stgy_exec_log_trgr CHECK (trgr_typ IN ('MANUAL', 'AUTO', 'PREVIEW'))
);

COMMENT ON TABLE  stgy_exec_log IS '전략 실행 로그';
COMMENT ON COLUMN stgy_exec_log.rvsn_no  IS '실행에 사용된 리비전. stgy_rvsn과 조합해 판정 당시의 정의를 재구성한다';
COMMENT ON COLUMN stgy_exec_log.trgr_typ IS 'MANUAL 화면 조작 / AUTO 스케줄 실행 / PREVIEW 결과를 반영하지 않은 산정 — 적치 일괄 추천만 기록한다(지시 생성 경로가 산정을 다시 돌리지 않아 근거가 거기밖에 없다). 조회 기본값은 MANUAL·AUTO';
COMMENT ON COLUMN stgy_exec_log.tgt_ref  IS '대상 문서 번호 (입고번호 IB-…). 가상 입력 미리보기는 NULL. inv_hist.rfn_doc_no와 같은 느슨한 참조 — 새 컬럼이라 ref 표기(사전 결정)';
COMMENT ON COLUMN stgy_exec_log.rslt_smry IS '사람용 한 줄 요약. 예: "라인 3건 중 위반 1건"';
COMMENT ON COLUMN stgy_exec_log.dcsn_trc IS '건별 판정 상세(라인×규칙 / 단계×후보). 관리 화면의 "왜 차단/배정됐나" 표의 원본이고, 구조는 판정 결과 DTO가 정의한다';

CREATE INDEX ix_stgy_exec_log_stgy ON stgy_exec_log (stgy_typ, stgy_id, created_at);
CREATE INDEX ix_stgy_exec_log_ref  ON stgy_exec_log (tgt_ref);

-- 검수 정책 헤더. 시스템 전역 1행 — DB 강제 없이 서비스가 검증한다 (D8).
-- prty가 없다: 검수는 "선택되는" 전략이 아니라 규칙 전부가 AND 실행되는 유형이라,
-- 선택 순서 컬럼이 있으면 스키마가 거짓말을 하게 된다 ("여러 개 만들면 하나가 골라진다"는 오해를 부른다).
CREATE TABLE insp_plcy (
    insp_plcy_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_nm      VARCHAR(100) NOT NULL,
    last_rvsn_no BIGINT       DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30)
);

COMMENT ON TABLE  insp_plcy IS '검수 정책 헤더';
COMMENT ON COLUMN insp_plcy.stgy_nm      IS '정책명';
COMMENT ON COLUMN insp_plcy.last_rvsn_no IS '마지막 저장 리비전';

-- 검수 규칙. 정책 1개 + 규칙 N개 — 실제 실행 의미(전부 AND)와 구조가 일치하는 모델.
CREATE TABLE insp_plcy_rule (
    insp_plcy_rule_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insp_plcy_id      BIGINT      NOT NULL,
    srt_seq           INTEGER     DEFAULT 0 NOT NULL,
    rule_cd           VARCHAR(30) NOT NULL,
    para              JSONB       DEFAULT '{}' NOT NULL,
    created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR(30),
    -- AND 실행이라 같은 규칙 2건은 더 엄격한 쪽 1건과 동일 — 의미 없는 중복을 DB가 거부
    CONSTRAINT uq_insp_plcy_rule UNIQUE (insp_plcy_id, rule_cd)
);

COMMENT ON TABLE  insp_plcy_rule IS '검수 규칙';
COMMENT ON COLUMN insp_plcy_rule.insp_plcy_id IS '소속 정책';
COMMENT ON COLUMN insp_plcy_rule.srt_seq IS '평가·표시 순서';
COMMENT ON COLUMN insp_plcy_rule.rule_cd IS '코드 레지스트리의 규칙 code';
COMMENT ON COLUMN insp_plcy_rule.para    IS '규칙 파라미터';

CREATE INDEX ix_insp_plcy_rule ON insp_plcy_rule (insp_plcy_id);

-- 적치 전략 헤더. 적치 추천 시 발주구분(odr_dvsn) 일치 전략 → 전체(NULL) 전략 순으로 선택 — 유형당 1개라 우선순위 컬럼이 없다.
-- 분할정책은 unt_splt_yn 하나만 둔다 — MAX 미설정 문제는 ck_loc_storage_capacity가,
-- 점유 계산 방식은 loc.max_qty 주석의 불변식이 이미 해결하기 때문이다.
CREATE TABLE ptawy_stgy (
    ptawy_stgy_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_nm       VARCHAR(100) NOT NULL,
    odr_dvsn      VARCHAR(10),
    unt_splt_yn   BOOLEAN      DEFAULT FALSE NOT NULL,
    loc_srt       JSONB        DEFAULT '[]' NOT NULL,
    last_rvsn_no  BIGINT       DEFAULT 1 NOT NULL,
    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(30),
    CONSTRAINT ck_ptawy_stgy_loc_srt  CHECK (jsonb_typeof(loc_srt) = 'array')
);

-- 유형당 전략 1개 (전체 = odr_dvsn NULL도 1개). 이 UNIQUE가 우선순위 컬럼을 대체한다 —
-- 선택 규칙이 "유형 일치 → 전체 → 수동 폴백"으로 숫자 없이 결정적이다.
CREATE UNIQUE INDEX ux_ptawy_stgy_odr_dvsn ON ptawy_stgy (COALESCE(odr_dvsn, 'ALL'));

COMMENT ON TABLE  ptawy_stgy IS '적치 전략 헤더';
COMMENT ON COLUMN ptawy_stgy.stgy_nm     IS '전략명';
COMMENT ON COLUMN ptawy_stgy.odr_dvsn    IS '적용대상 발주구분. NULL = 전체';
COMMENT ON COLUMN ptawy_stgy.unt_splt_yn IS '입수 단위 배수 절사';
COMMENT ON COLUMN ptawy_stgy.loc_srt     IS '후보 정렬 [{"field":…,"dir":ASC|DESC}]. 빈 배열 = 기본';
COMMENT ON COLUMN ptawy_stgy.last_rvsn_no IS '마지막 저장 리비전';

-- 적치 단계. "적치위치 × 추천방식"의 조합을 관리자가 순서를 직접 배열하는 단계 목록으로 표현한다 —
-- 표현력 손실 없이(조합은 단계를 그만큼 나열) 실행 순서가 화면에 그대로 보인다.
CREATE TABLE ptawy_stgy_stg (
    ptawy_stgy_stg_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ptawy_stgy_id     BIGINT      NOT NULL,
    srt_seq           INTEGER     NOT NULL,
    mthd_cd           VARCHAR(30) NOT NULL,
    mthd_para         JSONB       DEFAULT '{}' NOT NULL,
    line_cond         JSONB       DEFAULT '[]' NOT NULL,
    loc_cond          JSONB       DEFAULT '[]' NOT NULL,
    created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR(30),
    CONSTRAINT ck_ptawy_stg_line_cond CHECK (jsonb_typeof(line_cond) = 'array'),
    CONSTRAINT ck_ptawy_stg_loc_cond  CHECK (jsonb_typeof(loc_cond)  = 'array')
);

COMMENT ON TABLE  ptawy_stgy_stg IS '적치 전략 단계';
COMMENT ON COLUMN ptawy_stgy_stg.ptawy_stgy_id IS '소속 전략';
COMMENT ON COLUMN ptawy_stgy_stg.srt_seq   IS '실행 순서';
COMMENT ON COLUMN ptawy_stgy_stg.mthd_cd   IS '추천 방식 code';
COMMENT ON COLUMN ptawy_stgy_stg.mthd_para IS '방식 파라미터';
COMMENT ON COLUMN ptawy_stgy_stg.line_cond IS '조건 [{fld,op,vals}]';
COMMENT ON COLUMN ptawy_stgy_stg.loc_cond  IS '적치위치 지정 [{"fld","op","vals"}]. 빈 배열 = 전체 보관 로케이션';

CREATE INDEX ix_ptawy_stgy_stg ON ptawy_stgy_stg (ptawy_stgy_id);

-- 웨이브 전략. 미편성 출고 주문을 조건으로 걸러 웨이브에 편입하는 규칙 — 도메인이 테이블 1개로 끝난다.
-- 조건그룹은 개별 파라미터도 활성 플래그도 없이 항상 헤더와 통째로 저장되므로 하위 테이블이 아니라 JSONB다
-- (편집 단위 = 저장 단위 기준).
CREATE TABLE wav_stgy (
    wav_stgy_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_nm      VARCHAR(100) NOT NULL,
    prty         INTEGER      DEFAULT 0 NOT NULL,
    cond_grp     JSONB        NOT NULL,
    last_rvsn_no BIGINT       DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT ck_wav_stgy_prty CHECK (prty >= 0),
    -- 조건 0건 전략은 모든 주문을 쓸어담는다. 실행 시점이 아니라 저장 시점에 막는다.
    -- 그룹 안이 빈 배열인 경우([[]])는 CHECK로 표현할 수 없어 저장 서비스가 거부한다
    CONSTRAINT ck_wav_stgy_cond_grp CHECK (
        jsonb_typeof(cond_grp) = 'array' AND jsonb_array_length(cond_grp) > 0
    )
);

COMMENT ON TABLE  wav_stgy IS '웨이브 전략';
COMMENT ON COLUMN wav_stgy.stgy_nm      IS '전략명';
COMMENT ON COLUMN wav_stgy.prty         IS '실행 순서';
COMMENT ON COLUMN wav_stgy.cond_grp     IS '조건그룹 [[{fld,op,vals},…],…]. 그룹끼리 OR, 그룹 안 AND';
COMMENT ON COLUMN wav_stgy.last_rvsn_no IS '마지막 저장 리비전';


-- 할당 전략. 자동할당의 "어느 재고를, 어떤 순서로, 모자라면 누구에게"를 슬롯 단위로 정의한다.
-- 다른 세 유형과 다른 점: 할당에는 이미 코드에 박힌 기본 동작(FEFO + 점포 잔여수명 + 순차 소진)이
-- 있어서, 전략은 없던 판단을 만드는 게 아니라 그 기본값을 슬롯 단위로 덮어쓴다.
-- 그래서 필수 슬롯이 없고, 전략이 0건이면 기존 동작이 그대로 유지된다.
CREATE TABLE aloc_stgy (
    aloc_stgy_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_nm      VARCHAR(100) NOT NULL,
    prty         INTEGER      DEFAULT 0 NOT NULL,
    tgt_cond     JSONB        DEFAULT '[]' NOT NULL,
    last_rvsn_no BIGINT       DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT ck_aloc_stgy_prty     CHECK (prty >= 0),
    -- 웨이브(cond_grp)와 달리 길이 CHECK가 없다 — 할당의 조건 0건은 사고가 아니라
    -- "어느 전략도 매칭되지 않을 때 무엇을 쓸지"를 뜻하는 전체 매칭 폴백 전략이다
    CONSTRAINT ck_aloc_stgy_tgt_cond CHECK (jsonb_typeof(tgt_cond) = 'array')
);

COMMENT ON TABLE  aloc_stgy IS '할당 전략';
COMMENT ON COLUMN aloc_stgy.stgy_nm      IS '전략명';
COMMENT ON COLUMN aloc_stgy.prty         IS '선택 순서';
COMMENT ON COLUMN aloc_stgy.tgt_cond     IS '적용대상 조건 [{fld,op,vals},…]. 빈 배열 = 전체';
COMMENT ON COLUMN aloc_stgy.last_rvsn_no IS '마지막 저장 리비전';


-- 할당 슬롯. 적치 단계와 같은 판단으로 JSONB가 아니라 행이다 —
-- 개별로 추가·삭제·순서변경(drag&drop)하고 자기 파라미터·조건을 갖는 편집 단위이기 때문.
CREATE TABLE aloc_stgy_slot (
    aloc_stgy_slot_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aloc_stgy_id      BIGINT      NOT NULL,
    slot_typ          VARCHAR(15) NOT NULL,
    srt_seq           INTEGER     DEFAULT 0 NOT NULL,
    cmpnt_cd          VARCHAR(30),
    para              JSONB       DEFAULT '{}' NOT NULL,
    cond              JSONB       DEFAULT '[]' NOT NULL,
    created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR(30),
    CONSTRAINT ck_aloc_slot_typ CHECK (
        slot_typ IN ('INVN_FLTR','RSTRCT','INVN_SRT','ODR_SRT','DSTRB')
    ),
    -- 구현체 축이 있는 슬롯은 RSTRCT·DSTRB뿐이다. 필터 슬롯은 "무엇을 실행할지"가 아니라
    -- "어느 후보만"을 정하므로 정의 전체가 cond이고, 정렬 슬롯은 "기준을 순서대로 나열"
    -- 하나뿐이라 para.criteria가 정의 전부다 — 둘 다 고를 구현체가 없다.
    CONSTRAINT ck_aloc_slot_cmpnt CHECK (
        (slot_typ IN ('INVN_FLTR','INVN_SRT','ODR_SRT') AND cmpnt_cd IS NULL)
     OR (slot_typ IN ('RSTRCT','DSTRB')                 AND cmpnt_cd IS NOT NULL)
    ),
    CONSTRAINT ck_aloc_slot_srt_seq CHECK (srt_seq >= 0),
    CONSTRAINT ck_aloc_slot_para    CHECK (jsonb_typeof(para) = 'object'),
    CONSTRAINT ck_aloc_slot_cond    CHECK (jsonb_typeof(cond) = 'array')
);

CREATE INDEX ix_aloc_stgy_slot ON aloc_stgy_slot (aloc_stgy_id);
-- 단일 슬롯에 2건 등록을 DB가 거부한다. 다중 슬롯(INVN_FLTR·RSTRCT·DSTRB)은 대상이 아니다 —
-- 계층·순서를 표현하는 것이 그 슬롯들의 존재 이유이기 때문.
CREATE UNIQUE INDEX uq_aloc_stgy_slot_single ON aloc_stgy_slot (aloc_stgy_id, slot_typ)
    WHERE slot_typ IN ('INVN_SRT','ODR_SRT');

COMMENT ON TABLE  aloc_stgy_slot IS '할당 슬롯 (역할 5종)';
COMMENT ON COLUMN aloc_stgy_slot.aloc_stgy_id IS '할당 전략 헤더';
COMMENT ON COLUMN aloc_stgy_slot.slot_typ     IS '슬롯 유형. AlocSlotTyp enum';
COMMENT ON COLUMN aloc_stgy_slot.srt_seq      IS '다중 슬롯 안의 순서';
COMMENT ON COLUMN aloc_stgy_slot.cmpnt_cd     IS '구현체 code (enum name). 구현체 축이 없는 슬롯은 NULL';
COMMENT ON COLUMN aloc_stgy_slot.para         IS '슬롯 파라미터 [{"field","dir"},…]';
COMMENT ON COLUMN aloc_stgy_slot.cond         IS '슬롯 조건 [{fld,op,vals},…]';
