-- =====================================================================
-- WMS 스키마 DDL (PostgreSQL / Supabase) — 현행 기준 문서
--   스키마의 주인은 이 파일이다. 엔티티는 여기에 맞춰 작성한다.
--   신규 DB는 이 파일 전체를 적용하고, 기존 DB는 docs/migration-*.sql 증분만 적용한다.
--   (Oracle 시절 원본은 접었다 — 이력이 필요하면 커밋 히스토리를 본다)
--
-- 설계 근거: docs/design.md
--  - 재고 키: 상품 + Location + Lot
--  - 헤더 상태는 워크플로 단계만 표현, 부분 여부는 라인 수량에서 파생
--  - 재고 이력 합계 = 현재고 스냅샷 (불변식)
--  - 도메인: 식품/음료 유통센터 → 온도대 제약, 납품기한 출고 제한
--  - FK 제약은 걸지 않는다 — 참조 무결성은 애플리케이션이 보증. 서비스/DB 분리 시
--    스키마를 자유롭게 쪼갤 수 있어야 하고, 마이그레이션 순서 제약을 줄이기 위함
--
-- 네이밍 규칙
--  - 접두: 주문 OMS_* / 입고 IB_* / 출고 OUTB_* / 재고 INV* / 마스터는 무접두
--          전략은 유형별 도메인 접두(INSP_* 검수 / PTAWY_* 적치 / WAV_* 웨이브 / ALOC_* 할당) + 공용 STGY_*
--  - PK는 {테이블명}_id, FK는 참조 테이블 PK명 그대로
--  - 약어 사전의 주인은 docs/naming-dictionary.md 하나다. 아래는 이 파일에서 자주 보이는
--    것만 추린 발췌이며, 새 이름은 반드시 사전에서 단어를 찾아 조합한다:
--      expected→expct  received→rcvd  rejected→rjct  putaway→ptawy
--      allocated/allocation→aloc  location→loc  history→hist  zone→zon
--      code→cd  name→nm  vendor→vndr  priority→prty  temperature→tmp
--      date→de(일자)  datetime→dt(일시)   ← 둘을 구분한다
--  - 공통 감사 컬럼: 모든 테이블에 created_at/created_by/updated_at/updated_by.
--    작성자는 JPA Auditing(AuditorAware)이 채운다 (인증 도입 전까지 'admin' 고정)
--
-- 참고: ddl-auto=none이므로 Hibernate는 테이블을 만들지도, 엔티티와 대조하지도 않는다.
--       엔티티가 없는 컬럼을 가리켜도 기동 시점에는 조용하고 조회할 때 터진다.
--       스키마 변경은 항상 이 파일(+증분 마이그레이션)을 DB에 먼저 적용한 뒤 엔티티를 고친다.
-- =====================================================================


-- =====================================================================
-- 1. 마스터
-- =====================================================================

-- 계량단위(UOM)는 전용 마스터 테이블을 두지 않고 공통코드 UOM 그룹으로 관리한다.
-- 정의와 시드는 아래 「공통코드」 절에 있다 (code_group 'UOM' + code_detail).
-- 화면 콤보박스도 다른 코드성 컬럼과 똑같이 /master/codes/UOM 하나로 받는다.

-- 상품 마스터. 온도대/유통기한 정책 등 "상품이 갖는 규칙"을 보유한다.
CREATE TABLE prod (
    prod_id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_cd          VARCHAR(30)     NOT NULL,
    prod_nm          VARCHAR(100)    NOT NULL,
    tmp_zon       VARCHAR(10)     NOT NULL,
    inb_uom_cd      VARCHAR(20)     DEFAULT 'EA' NOT NULL,
    outb_uom_cd     VARCHAR(20)     DEFAULT 'EA' NOT NULL,
    shelf_life_days INTEGER,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT uq_prod_cd UNIQUE (prod_cd),
    CONSTRAINT ck_prod_tmp_zon CHECK (tmp_zon IN ('DRY', 'CHL', 'FRZ'))
    -- 환산수량 컬럼을 두지 않는다. 포장단위 → 낱개(EA) 환산은 prod_uom.ea_qty(낱개수량)로
    -- 파생시킨다 (아래 prod_uom 주석 참고). 두 벌로 두면 서로 어긋날 수 있는 값이 생긴다.
);

COMMENT ON TABLE  prod IS '상품 마스터. 보관 규칙(온도대)과 유통기한 정책을 상품 단위로 정의';
COMMENT ON COLUMN prod.prod_cd          IS '상품 코드 (업무 식별자, 예: PROD-0001)';
COMMENT ON COLUMN prod.tmp_zon       IS '보관 온도대 (DRY 상온 / CHL 냉장 / FRZ 냉동). 적치·이동 시 로케이션 온도대와 일치 검증';
COMMENT ON COLUMN prod.inb_uom_cd      IS '입고단위 (prod_uom에 있는 uom_cd여야 한다, FK 없음). 벤더에게 발주하고 납품받는 단위 (예: BOX). 이 단위를 쓰는 곳은 oms_ib_line.odr_qty 하나뿐이다. CHECK를 걸지 않는 이유는 값 목록의 주인이 공통코드 UOM 그룹이라서, CHECK가 있으면 단위를 추가할 때마다 DDL을 고쳐야 하기 때문 (zon.tmp_zon 등과 같은 형태)';
COMMENT ON COLUMN prod.outb_uom_cd     IS '출고단위 (prod_uom에 있는 uom_cd여야 한다, FK 없음). 출고주문서에 사람이 쓰는 단위 (oms_outb_line.odr_qty가 이 기준). 재고 저장 단위가 아니다 — 창고의 모든 수량 컬럼은 낱개(EA)다';
COMMENT ON COLUMN prod.shelf_life_days IS '제조일 기준 총 유통기한(일). NULL = 유통기한 미관리(공산품 등). 시더가 Lot 유통기한 생성 시 사용';

-- 상품 코드(PROD-0001)는 채번 모듈이 발급한다 — nbr_rule 'PROD_CD' + nbr_seq.
-- 전용 시퀀스(prod_cd_seq)를 두던 방식은 폐기했다. 규칙이 테이블 데이터라 화면에서 바꿀 수 있고,
-- 일자 리셋 같은 패턴도 DDL 없이 표현된다 (아래 「채번」 절 참고).

-- 상품 포장. (상품, 단위) 한 조합이 한 행이다 — 한 상품이 낱개·박스·파렛트를 동시에 갖고,
-- 낱개수량과 중량은 그 조합마다 다르다.
--
-- 환산수량 컬럼(prod.cnvr_qty) 대신 이 테이블을 두는 이유 —
--   ① 상품당 한 칸이면 "입고단위 → 출고단위" 한 쌍만 표현된다. 박스·파렛트를 함께 다루려면
--      쌍마다 컬럼이 늘어난다. 낱개수량을 단위마다 두면 어떤 두 단위든 낱개를 매개로 환산된다
--      (BOX→EA = ea_qty(BOX) / ea_qty(EA)).
--   ② 중량을 둘 자리가 여기 말고 없다. prod에 두면 그 값이 어느 포장 기준인지 이름에 드러나지 않고,
--      박스 중량을 「낱개중량 × 낱개수량」으로 파생하게 되어 포장재 무게(tare)가 사라진다.
--      파렛트처럼 tare가 큰 단위에서 무시할 수 없는 오차다.
--
-- PK는 규칙대로 prod_uom_id 대리키이고, 실제 grain은 uq_prod_uom이 강제한다.
-- prod_id는 FK가 아니다 (FK 0건 정책) — 상품 삭제 시 포장 정리는 ProdService(cascade)가 한다.
CREATE TABLE prod_uom (
    prod_uom_id BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_id     BIGINT          NOT NULL,
    uom_cd      VARCHAR(20)     NOT NULL,
    ea_qty      BIGINT          NOT NULL,
    wgt         NUMERIC(12, 3),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_prod_uom UNIQUE (prod_id, uom_cd),
    -- 0이나 음수면 환산이 수량을 0으로 만들거나 부호를 뒤집는다. 단위 관련 유일한 DB 방어선이다
    CONSTRAINT ck_prod_uom_ea_qty CHECK (ea_qty >= 1),
    -- NULL은 미측정. 값이 있는데 0 이하면 실측값일 수 없다
    CONSTRAINT ck_prod_uom_wgt CHECK (wgt IS NULL OR wgt > 0)
);

COMMENT ON TABLE  prod_uom IS '상품 포장. (상품, 단위) 한 조합이 한 행 — 낱개수량과 중량을 포장마다 갖는다. 어느 단위든 낱개(EA)를 매개로 환산되는 근거가 여기다';
COMMENT ON COLUMN prod_uom.uom_cd IS '단위 코드. 공통코드 UOM 그룹(code_detail) 참조, FK 없음 — 존재 검증은 ProdService';
COMMENT ON COLUMN prod_uom.ea_qty IS '이 단위 1개가 낱개 몇 개인가 (예: BOX 1개 = 24). 낱개 그 자체면 1. 환산(Prod.toEaQty = qty × ea_qty)은 OMS→WMS 경계 세 곳에서만 일어난다 — 발주→ASN(입고단위), 검수 입력(입고단위), 출고주문 확정(출고단위). 창고의 모든 수량 컬럼은 낱개(EA)다';
COMMENT ON COLUMN prod_uom.wgt    IS '이 단위 1개의 중량(kg). 포장재 무게(tare)를 포함한 실측값이며 미측정이면 NULL. 낱개중량 × 낱개수량으로 파생시키지 않는 이유가 tare다';

-- 존 마스터. 로케이션의 상위 그룹 (온도 · 보관형태 · 담당업무 단위).
-- tmp_zon은 loc.tmp_zon · prod.tmp_zon과 같은 값 도메인이다 (공통코드 TEMP_ZONE, Java TempZone enum 공용).
-- tmp_zon / strg_typ / biz_dvsn은 공통코드에서 관리하므로 CHECK를 걸지 않는다 —
-- 코드를 추가할 때마다 DDL을 고치지 않기 위함이고, 값 검증은 서비스단 enum이 맡는다.
-- (loc·prod는 CHECK를 갖고 있어 존만 방식이 다르다. 근거는 docs/design.md 「존 마스터」)
CREATE TABLE zon (
    zon_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    zon_cd      VARCHAR(20)     NOT NULL,
    zon_nm      VARCHAR(100)    NOT NULL,
    tmp_zon     VARCHAR(10)     NOT NULL,
    strg_typ    VARCHAR(10)     NOT NULL,
    biz_dvsn    VARCHAR(10)     NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_zon_cd UNIQUE (zon_cd)
);

COMMENT ON TABLE  zon IS '존 마스터. 로케이션의 상위 그룹 (loc.zon_cd가 zon.zon_cd를 느슨하게 참조)';
COMMENT ON COLUMN zon.zon_cd   IS '존 코드 (업무 식별자, 예: DRY, RCV-STAGE). 하위 로케이션이 문자열로 참조하므로 등록 후 변경 금지';
COMMENT ON COLUMN zon.zon_nm   IS '존 명 (화면 표시용)';
COMMENT ON COLUMN zon.tmp_zon  IS '온도구분. 공통코드 TEMP_ZONE (DRY 상온 / CHL 냉장 / FRZ 냉동). 보관 로케이션은 이 값과 loc.tmp_zon이 일치해야 한다';
COMMENT ON COLUMN zon.strg_typ IS '보관유형. 공통코드 STRG_TYP (RACK 랙 / FLAT 평치 / VRTL 가상)';
COMMENT ON COLUMN zon.biz_dvsn IS '업무구분. 공통코드 BIZ_DVSN (INB 입고작업 / OUTB 출고작업 / STRG 보관 / PIKNG 피킹 / RTNGS 반품 / WRK 작업)';

-- 로케이션 마스터. 존(zon)의 하위 물리 위치. 입고 스테이징(RCV-STAGE)과 온도대별 보관존으로 구성.
CREATE TABLE loc (
    loc_id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loc_cd          VARCHAR(30)     NOT NULL,
    zon_cd         VARCHAR(20)     NOT NULL,
    tmp_zon       VARCHAR(10)     NOT NULL,
    loc_typ        VARCHAR(10)     NOT NULL,
    pikng_prty       INTEGER         DEFAULT 0 NOT NULL,
    ptawy_prty      INTEGER         DEFAULT 0 NOT NULL,
    max_qty         BIGINT,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT uq_loc_cd UNIQUE (loc_cd),
    CONSTRAINT ck_loc_tmp_zon CHECK (tmp_zon IN ('DRY', 'CHL', 'FRZ')),
    CONSTRAINT ck_loc_typ CHECK (loc_typ IN ('STAGE', 'STORAGE')),
    CONSTRAINT ck_loc_max_qty CHECK (max_qty IS NULL OR max_qty > 0),
    -- 용량은 적치 전략의 전제다. 보관 로케이션에 상한이 없으면 후보가 "온도대 일치 전부"라
    -- 전략이 정렬 순서밖에 바꾸지 못한다 — 그래서 STORAGE에만 NOT NULL을 강제한다.
    CONSTRAINT ck_loc_storage_capacity CHECK (loc_typ <> 'STORAGE' OR max_qty IS NOT NULL)
);

COMMENT ON TABLE  loc IS '로케이션 마스터. 재고가 놓이는 물리 위치 (스테이징/보관존)';
COMMENT ON COLUMN loc.loc_cd    IS '로케이션 코드 (예: DRY-A-01-01, RCV-STAGE)';
COMMENT ON COLUMN loc.zon_cd   IS '존 코드. zon.zon_cd를 참조하지만 FK는 없다 — 존재 검증은 LocService가 한다';
COMMENT ON COLUMN loc.tmp_zon IS '존 온도대. 상품 온도대와 불일치하면 적치·이동 차단 (스테이징은 예외적으로 전 온도대 허용할지 서비스에서 판단)';
COMMENT ON COLUMN loc.loc_typ  IS 'STAGE: 스테이징(RCV-STAGE 적치 대기 / SHIP-STAGE 반출 대기) / STORAGE: 보관(할당 대상)';
COMMENT ON COLUMN loc.pikng_prty IS '할당 시 동일 유통기한(FEFO 동순위) 간 로케이션 우선순위. 낮을수록 먼저 할당. 적치 지시의 후보 순회 순서이기도 하다';
COMMENT ON COLUMN loc.ptawy_prty IS '적치 우선순위. 적치 전략의 후보 정렬 기준(PTAWY_PRTY) — 낮을수록 먼저 배정. 피킹 동선(pikng_prty)과 적치 동선이 다른 창고를 위해 분리한다';
COMMENT ON COLUMN loc.max_qty   IS '최대 적재 수량. 적재가능수량 = max_qty - 현재고 - 미완료 지시 잔량. NULL = 무제한(스테이징 전용), STORAGE는 NOT NULL 강제';

-- Lot. 입고 처리 시점에 생성되며 유통기한을 보유한다 (FEFO 기준값).
CREATE TABLE lot (
    lot_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_id      BIGINT          NOT NULL,
    lot_no      VARCHAR(30)     NOT NULL,
    receipt_dt  DATE,
    mfg_dt      DATE,
    expiry_dt   DATE,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_lot UNIQUE (prod_id, lot_no)
);

COMMENT ON TABLE  lot IS 'Lot(입고 단위 묶음). 입고 처리 시 생성. 유통기한이 FEFO 할당과 납품기한 필터의 기준';
COMMENT ON COLUMN lot.lot_no    IS 'Lot 번호 (상품 내 유일). 입고일 기준 상품별 일자 리셋 채번(LOT-YYMMDD-NNN). 유통기한 미관리 상품도 동일 형식이며 입고일자만으로 구분됨';
COMMENT ON COLUMN lot.receipt_dt IS '입고일자 (소급 등록 가능). 상품+입고일자+제조일자가 같으면 기존 Lot을 재사용 (증분 검수 시 배치 중복 생성 방지). 유통기한 미관리 상품은 제조일자가 항상 NULL이라 사실상 상품+입고일자로만 구분';
COMMENT ON COLUMN lot.mfg_dt    IS '제조일자. 유통기한 미관리 상품의 Lot은 NULL';
COMMENT ON COLUMN lot.expiry_dt IS '유통기한. 생성 시점의 prod.shelf_life_days로 계산해 저장한 스냅샷 (이후 상품 마스터 변경에 소급 영향 없음). NULL = 미관리 상품의 Lot (FEFO 맨 뒤 정렬, 잔여수명 필터 대상 아님)';

CREATE INDEX ix_lot_expiry ON lot (prod_id, expiry_dt);
-- Lot 재사용 조회(상품+입고일자+제조일자) 및 일자별 채번 카운트에 사용
CREATE INDEX ix_lot_prod_receipt ON lot (prod_id, receipt_dt);

-- Lot 번호는 더 이상 DB 시퀀스로 채번하지 않는다.
-- 상품 로우 락(SELECT ... FOR UPDATE) 하에 해당 상품+입고일자의 기존 Lot 건수를 세어 다음 번호를 매긴다 (상품별 일자 리셋).

-- 점포 마스터. 납품 기준(잔여수명 허용률)은 상품이 아니라 납품처가 정한다.
CREATE TABLE store (
    store_id        BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_cd        VARCHAR(30)     NOT NULL,
    store_nm        VARCHAR(100)    NOT NULL,
    store_grp       VARCHAR(10),
    store_typ       VARCHAR(10),
    outb_life_rate  SMALLINT        DEFAULT 40 NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT uq_store_cd UNIQUE (store_cd),
    CONSTRAINT ck_store_life_rate CHECK (outb_life_rate BETWEEN 0 AND 100)
);

COMMENT ON TABLE  store IS '점포(납품처) 마스터. 납품 허용 잔여수명 기준을 점포 단위로 관리';
COMMENT ON COLUMN store.store_cd       IS '점포 코드 (업무 식별자, 예: ST-0001)';
COMMENT ON COLUMN store.store_grp      IS '점포그룹 (공통코드 STORE_GRP — 체인·계열 묶음). NULL = 미지정. 웨이브 편성·할당 분배 조건의 기준값. CHECK 없음 — 값 목록은 공통코드가 소유하고 존재 검증은 하지 않는다(화면 콤보로만 들어온다)';
COMMENT ON COLUMN store.store_typ      IS '점포유형 (공통코드 STORE_TYP — 편의점·마트·급식). NULL = 미지정. 웨이브 편성·할당 분배 조건의 기준값';
COMMENT ON COLUMN store.outb_life_rate IS '납품 허용 잔여수명 비율(%). 이 점포 출고 시 잔여 유통기한이 이 비율 미만인 Lot은 할당 제외 (FEFO 앞단 필터)';

-- 벤더(납품처) 마스터. 입고주문·입고예정이 참조한다.
-- 점포(store)가 출고의 거래처이듯 벤더는 입고의 거래처 — 둘 다 마스터로 두어 대칭을 맞춘다.
-- 이름을 주문에 텍스트로 박지 않는 이유: 같은 벤더의 표기 흔들림("대한물류"/"(주)대한물류")을
-- 묶을 수 없고, 벤더 단위 기준정보(리드타임·검수기준 등)를 붙일 자리가 사라진다.
--
-- 사용여부(us_yn)를 두지 않는다 — 이 프로젝트의 어느 테이블에도 두지 않는다. 마스터는
-- 물리삭제로 운용한다. "지운 것도 아니고 쓰는 것도 아닌" 중간 상태를 만들면 모든 조회에
-- 그 필터가 따라붙어야 하고, 한 군데라도 빠지면 폐기한 값이 화면에 되살아난다.
CREATE TABLE vendor (
    vendor_id   BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vndr_cd     VARCHAR(30)     NOT NULL,
    vndr_nm     VARCHAR(100)    NOT NULL,
    pic_nm      VARCHAR(50),
    tel_no      VARCHAR(30),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_vndr_cd UNIQUE (vndr_cd)
);

COMMENT ON TABLE  vendor IS '벤더(납품처) 마스터. 입고주문·입고예정의 거래처. 거래 종료는 물리삭제';
COMMENT ON COLUMN vendor.vndr_cd IS '벤더 코드 (업무 식별자, 예: VD-0001). 서버가 시퀀스로 채번';

-- 공통코드 그룹. 관리 화면은 추후 추가 예정, 당분간 시드 데이터로만 운용.
-- 코드성 테이블이라 PK는 {테이블명}_id 규칙 대신 자연키를 쓴다 (조회가 항상 코드 기준).
CREATE TABLE code_group (
    grp_cd    VARCHAR(30)     NOT NULL,
    grp_nm    VARCHAR(100)    NOT NULL,
    dscr      VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT pk_code_group PRIMARY KEY (grp_cd)
);

COMMENT ON TABLE  code_group IS '공통코드 그룹. 로직 분기에 쓰이는 enum성 코드의 기준 목록 (표시 스타일은 프론트 상수가 보유)';
COMMENT ON COLUMN code_group.grp_cd IS '코드 그룹 코드 (예: TEMP_ZONE)';
COMMENT ON COLUMN code_group.dscr   IS '그룹 설명. 이 그룹을 어느 컬럼이 참조하는지와, ref1~ref3에 무엇을 담았는지를 적어 둔다';

-- 공통코드 상세. group_cd는 code_group 참조지만 FK는 걸지 않는다
-- (변경이 시드/관리화면으로만 일어나는 코드성 테이블 — 그룹 존재 검증은 관리 화면 추가 시 서비스에서).
CREATE TABLE code_detail (
    grp_cd    VARCHAR(30)     NOT NULL,
    code_cd     VARCHAR(30)     NOT NULL,
    code_nm     VARCHAR(100)    NOT NULL,
    srt_seq    INTEGER         DEFAULT 0 NOT NULL,
    ref1        VARCHAR(100),
    ref2        VARCHAR(100),
    ref3        VARCHAR(100),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT pk_code_detail PRIMARY KEY (grp_cd, code_cd)
);

-- 사용여부(us_yn)를 두지 않는다 (vendor와 같은 이유). 안 쓰는 코드는 지우고, 하위가 참조
-- 중이면 CodeService가 삭제를 거부한다 — UOM 그룹이 그 가드를 갖는 유일한 그룹이다.
COMMENT ON TABLE  code_detail IS '공통코드 상세. 그룹 내 개별 코드와 표시명/정렬 순서';
COMMENT ON COLUMN code_detail.code_cd  IS '코드 값 (예: DRY). 로직에서 리터럴로 참조하므로 변경 금지';
COMMENT ON COLUMN code_detail.srt_seq IS '화면 표시 정렬 순서';
-- 참조값 3칸. 코드마다 딸린 자잘한 속성을 새 컬럼 없이 얹는 자리다 (공통코드의 관행).
-- 뜻이 그룹마다 다르므로 컬럼 이름으로는 알 수 없다 — 무엇을 담았는지는 그 값을 읽는 쪽과
-- code_group.dscr 에 남긴다. 표시 스타일(뱃지 색 등)은 여기 담지 않는다:
-- 그건 프론트 상수가 갖기로 이미 정한 사항이다 (code_group 테이블 주석 참고).
COMMENT ON COLUMN code_detail.ref1    IS '참조값1. 뜻은 그룹마다 다르다 (해당 그룹의 dscr 참고)';
COMMENT ON COLUMN code_detail.ref2    IS '참조값2';
COMMENT ON COLUMN code_detail.ref3    IS '참조값3';

-- 채번 규칙. code_group과 같은 자연키 코드 테이블 — 항상 코드로 조회한다.
CREATE TABLE nbr_rule (
    rule_cd     VARCHAR(30)     NOT NULL,
    rule_nm     VARCHAR(100)    NOT NULL,
    prfx        VARCHAR(20)     NOT NULL,
    prfx_dlmt   VARCHAR(1)      NOT NULL,
    de_dlmt     VARCHAR(1)      NOT NULL,
    seq_dgt     SMALLINT        NOT NULL,
    dync_ky_typ VARCHAR(10)     NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT pk_nbr_rule PRIMARY KEY (rule_cd),
    CONSTRAINT ck_nbr_rule_prfx_dlmt CHECK (prfx_dlmt IN ('-', '_', '')),
    CONSTRAINT ck_nbr_rule_de_dlmt CHECK (de_dlmt IN ('-', '_', '')),
    CONSTRAINT ck_nbr_rule_seq_dgt CHECK (seq_dgt BETWEEN 1 AND 9),
    CONSTRAINT ck_nbr_rule_dync_ky_typ CHECK (dync_ky_typ IN ('NONE', 'YEAR', 'MONTH', 'DAY'))
);

COMMENT ON TABLE  nbr_rule IS '채번 규칙. 접두어+구분자+SEQ 자릿수+리셋단위로 형식을 정의 (예: prfx=PROD, prfx_dlmt=-, seq_dgt=4, dync_ky_typ=NONE → PROD-0001)';
COMMENT ON COLUMN nbr_rule.rule_cd     IS '채번 규칙 코드 (업무 식별자, 예: PROD_CD). 코드성 테이블이라 자연키를 PK로 쓴다 (code_group과 동일 패턴)';
COMMENT ON COLUMN nbr_rule.prfx        IS '접두어 리터럴 (예: IB, PROD)';
COMMENT ON COLUMN nbr_rule.prfx_dlmt   IS '접두어 뒤 구분자. NONE이면 접두어→SEQ 사이 유일한 경계로 쓰인다';
COMMENT ON COLUMN nbr_rule.de_dlmt     IS '날짜 뒤 구분자. NONE에서는 쓰이지 않음(화면에서 비활성화 처리)';
COMMENT ON COLUMN nbr_rule.seq_dgt     IS 'SEQ 자릿수 (zero-pad 폭), 1~9';
COMMENT ON COLUMN nbr_rule.dync_ky_typ IS '리셋 단위. NONE=카운터 전역 공유(dync_ky 고정값 -) / YEAR·MONTH·DAY=호출자가 넘긴 날짜를 해당 단위로 잘라 카운터 분리, 화면 날짜 조각 포맷(yyyy/yyyyMM/yyyyMMdd)도 여기서 파생';

-- 채번 카운터. rule_cd+dync_ky 조합별 현재 발급값. 관리자가 만들지 않고 최초 발급 시 자동 생성된다.
CREATE TABLE nbr_seq (
    rule_cd     VARCHAR(30)     NOT NULL,
    dync_ky     VARCHAR(30)     NOT NULL,
    seq         BIGINT          DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT pk_nbr_seq PRIMARY KEY (rule_cd, dync_ky)
);

COMMENT ON TABLE  nbr_seq IS '채번 카운터. rule_cd+dync_ky별 현재 발급값. FK 없음 — rule_cd는 nbr_rule.rule_cd를 느슨하게 참조';
COMMENT ON COLUMN nbr_seq.dync_ky IS '동적키 값. dync_ky_typ=NONE이면 고정값 "-", YEAR/MONTH/DAY면 각각 yyyy/yyyyMM/yyyyMMdd';
COMMENT ON COLUMN nbr_seq.seq     IS '현재 발급값. 발급마다 +1, updated_at이 곧 최종 발급 시각';

-- 공통코드 시드 (참조 데이터 — 테이블 정의와 한 몸이므로 여기서 함께 관리)
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('TEMP_ZONE', '온도대', '보관 온도 구분 (상품/로케이션 공용)');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('LOC_TYPE', '로케이션 유형', '스테이징/보관 구분');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('STRG_TYP', '보관유형', '존의 물리 보관 형태');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('BIZ_DVSN', '업무구분', '존이 담당하는 업무');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('ODR_DVSN', '발주구분', '입고주문의 성격 (oms_ib_order.odr_dvsn)');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('UOM', '계량단위', '상품 포장의 단위 (prod_uom.uom_cd · prod.inb_uom_cd · outb_uom_cd)');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('HLD_RSN', '보류사유', '재고 보류 등록 사유 (inv_hld.rsn_cd). ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('HLD_RLZ_RSN', '보류 해제사유', '재고 보류 해제 사유 (inv_hld_rlz_acrst.rsn_cd). 등록 사유와 별개 그룹 — 「왜 묶었나」와 「왜 풀었나」는 다른 질문이다. ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('ADJ_RSN', '재고조정 사유', '재고조사 확정 시 차이 라인의 조정 사유 (inv_stktk_ln.rsn_cd). 차이가 0이 아닌 라인만 필수이며, ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('LOT_ATTR_RSN', 'Lot 속성정정 사유', 'Lot 속성(제조일자·유통기한) 정정 사유 (lot_attr_chng.rsn_cd · inv_lot_chng.rsn_cd — 재고 로트변경도 사유 성격이 같아 그룹을 재사용한다). ETC(기타)일 때만 자유 텍스트 rsn_dscr를 받는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('OUTB_TYP', '출고유형', '출고주문의 성격 (oms_outb_order.outb_typ → outb_order.outb_typ). 주문 등록 시 정해져 확정 때 창고로 복사된다. 웨이브 편성 조건의 기준값');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('VHCL_FLTNO', '차량편수', '출고 배차 차수 (oms_outb_order.vhcl_fltno → outb_order.vhcl_fltno). 웨이브 편성 조건의 기준값 — 같은 차수에 실릴 주문만 함께 묶는다');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('STORE_GRP', '점포그룹', '점포의 체인·계열 묶음 (store.store_grp). 웨이브 편성 조건 「납품처그룹」과 할당 분배 대상 선별의 기준값');
INSERT INTO code_group (grp_cd, grp_nm, dscr) VALUES
    ('STORE_TYP', '점포유형', '점포의 업태 (store.store_typ — 편의점·마트·급식). 웨이브 편성 조건 「납품처유형」과 할당 분배 대상 선별의 기준값');

INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('TEMP_ZONE', 'DRY', '상온', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('TEMP_ZONE', 'CHL', '냉장', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('TEMP_ZONE', 'FRZ', '냉동', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOC_TYPE', 'STAGE', '스테이징', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOC_TYPE', 'STORAGE', '보관', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STRG_TYP', 'RACK', '랙', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STRG_TYP', 'FLAT', '평치', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STRG_TYP', 'VRTL', '가상', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'INB', '입고작업', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'OUTB', '출고작업', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'STRG', '보관', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'PIKNG', '피킹', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'RTNGS', '반품', 5);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('BIZ_DVSN', 'WRK', '작업', 6);
-- 계량단위. EA(낱개)는 prod.inb_uom_cd · outb_uom_cd의 DEFAULT이고 prod_uom.ea_qty가 세는 기준
-- 단위이기도 해서, 다른 코드와 달리 존재가 구조적 전제다 — 지우지 말 것.
--
-- 포장 단위만 둔다 (KG · L 같은 계량 단위는 넣지 않는다). prod_uom.ea_qty가 「이 단위 1개 =
-- 낱개 몇 개」인데 kg·리터에는 그 값이 성립하지 않아서, 목록에 있으면 채울 수 없는 칸이 생긴다.
-- 중량은 이미 prod_uom.wgt가 kg 고정으로 들고 있어 단위를 데이터로 둘 이유도 없다.
-- 중량 기반 재고(수량 컬럼이 BIGINT가 아니게 되는 변경)가 필요해지면 그때 단위에 유형 속성을
-- 붙여야 하고, 그건 공통코드로 표현할 수 없으므로 전용 마스터를 다시 세우는 결정이 선행한다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'EA', '낱개', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'BOX', '박스', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'PACK', '팩', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'CS', '케이스', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'PLT', '파렛트', 5);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'BAG', '봉지', 6);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'TRAY', '트레이', 7);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'SET', '세트', 8);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'DZ', '다스', 9);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'BDL', '번들', 10);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'CTN', '카톤', 11);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('UOM', 'ROLL', '롤', 12);

-- 발주구분. 기본값 NRML은 prod.inb_uom_cd의 'EA'처럼 컬럼 DEFAULT가 가리키는 값이라 지우면 안 된다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ODR_DVSN', 'NRML', '정상', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ODR_DVSN', 'URGT', '긴급', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ODR_DVSN', 'RTNGS', '반품입고', 3);

-- 출고유형. NRML은 outb_order.outb_typ의 컬럼 DEFAULT가 가리키는 값이라 지우면 안 된다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('OUTB_TYP', 'NRML', '일반출고', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('OUTB_TYP', 'RTNGS', '반품출고', 2);

-- 차량편수. 코드값이 곧 차수 숫자다. 편수가 늘면 코드관리 화면에서 추가하면 되고 컬럼·코드 변경은 없다.
-- 조건 비교가 문자열이라 대소 연산자는 허용하지 않는다(10편이 2편보다 앞서게 된다) — EQ/IN 계열만 쓴다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('VHCL_FLTNO', '1', '1편', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('VHCL_FLTNO', '2', '2편', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('VHCL_FLTNO', '3', '3편', 3);

-- 점포그룹·점포유형. 시드 점포 5건이 실제로 쓰는 값들 — 그룹은 체인 계열, 유형은 업태다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_GRP', 'CNU', '씨앤유', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_GRP', 'HANMAUM', '한마음', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_GRP', 'HAENGBOK', '행복', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_TYP', 'CVS', '편의점', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_TYP', 'MART', '마트', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('STORE_TYP', 'FDSVC', '급식', 3);

-- 보류사유·해제사유. ETC(기타)는 「코드가 기타면 자유 텍스트 입력」 규칙이 걸리는 값이라 지우면 안 된다.
-- 코드는 분류 축일 뿐 병존 단위가 아니다 — 같은 재고 행에 같은 사유의 미해제 보류가 여러 건 있을 수 있다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'QLTY', '품질이상', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'DAMG', '파손', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'EXPIRY', '유통기한', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RSN', 'ETC', '기타', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'NRML', '정상 확인', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'ERR_REG', '오등록', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('HLD_RLZ_RSN', 'ETC', '기타', 3);

-- 재고조정 사유 (재고조사 확정 시 차이 라인). 여기도 ETC가 자유 텍스트 규칙의 트리거라 지우면 안 된다.
-- 세트화·단위대체 같은 타 업무 사유는 넣지 않는다 — 조사 전용만 담아 화면이 거를 필요가 없게 한다.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'DAMG', '파손', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'LOSS', '분실', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'ERR_WRK', '작업오류', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'INIT', '기초재고', 4);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('ADJ_RSN', 'ETC', '기타', 5);

-- Lot 속성정정 사유 (재고 속성변경). 여기도 ETC가 자유 텍스트 규칙의 트리거라 지우면 안 된다.
-- 「왜 날짜가 틀렸나」의 출처를 나누는 값들이다 — 검수 입력 오류 / 실물 표기와 상이 / 거래처 통보.
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'ERR_REG', '검수 오등록', 1);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'LABEL', '실물표기 상이', 2);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'VNDR', '거래처 정정 통보', 3);
INSERT INTO code_detail (grp_cd, code_cd, code_nm, srt_seq) VALUES ('LOT_ATTR_RSN', 'ETC', '기타', 4);

-- 채번 규칙. 상품·벤더·점포 코드와 주문/입고/출고 번호를 여기서 발급한다 (전용 시퀀스 폐기).
-- STORE_CD의 접두어 ST는 STKTK_NO와 같지만 형식이 다르다(ST-0001 vs ST-20260814-001) —
-- prfx는 UNIQUE가 아니고, 시드가 이미 ST-0001 형식을 쓰고 있어 접두어를 바꿀 수 없다.
INSERT INTO nbr_rule (rule_cd, rule_nm, prfx, prfx_dlmt, de_dlmt, seq_dgt, dync_ky_typ) VALUES
    ('PROD_CD',     '상품 코드',        'PROD', '-', '-', 4, 'NONE'),
    ('VNDR_CD',     '벤더 코드',        'VD',   '-', '-', 4, 'NONE'),
    ('STORE_CD',    '점포 코드',        'ST',   '-', '-', 4, 'NONE'),
    ('OMS_IB_NO',   '입고주문 번호',    'PO',   '-', '-', 3, 'DAY'),
    ('OMS_OUTB_NO', '출고주문 번호',    'SO',   '-', '-', 3, 'DAY'),
    ('IB_NO',       '입고 번호',        'IB',   '-', '-', 3, 'DAY'),
    ('OUTB_NO',     '출고 번호',        'OB',   '-', '-', 3, 'DAY'),
    ('OUTB_WAV_NO', '출고 웨이브 번호', 'WV',   '-', '-', 3, 'DAY'),
    ('INV_MOV_NO',  '이동지시 번호',    'MV',   '-', '-', 3, 'DAY'),
    ('HLD_NO',      '보류 번호',        'HD',   '-', '-', 3, 'DAY'),
    ('STKTK_NO',    '재고조사 번호',    'ST',   '-', '-', 3, 'DAY'),
    ('LOT_CHNG_NO', '재고 로트변경 번호', 'LC', '-', '-', 3, 'DAY');
COMMIT;


-- =====================================================================
-- 2. OMS 주문 OMS_* (CREATED ↔ CONFIRMED)
--    주문 원장. WMS 작업문서(입고예정 ASN · 출고주문)의 유일한 발생지다.
--    확정(confirm) 시 같은 트랜잭션에서 ib_order / outb_order를 생성한다 —
--    WMS 쪽에 직접 등록 경로는 없다.
--    확정취소하면 작업문서는 삭제되고 주문은 CREATED로 돌아와 재확정할 수 있다.
--
--    취소 상태를 두지 않는다. 없앨 주문은 지운다 — 확정 전이면 바로, 확정 뒤면 확정취소로
--    되돌린 뒤에. "지운 것도 아니고 쓰는 것도 아닌" 상태를 두면 목록·집계마다 그 상태를 빼는
--    필터가 따라붙고, 화면에서 삭제와 취소 중 무엇을 눌러야 하는지가 매번 애매해진다.
--    (마스터에서 us_yn을 걷어낸 것과 같은 판단 — 위 「vendor」 참고)
--    ASN 쪽도 취소 상태를 두지 않는다: 확정취소는 ASN 행을 삭제한다 — 검수 전의 예정은
--    아직 아무 일도 안 한 문서라 흔적 가치가 없다 (재확정하면 새 번호로 새 행이 생긴다).
-- =====================================================================

-- 입고주문(벤더 발주) 헤더. 창고 작업 진행은 여기서 표현하지 않는다 (ASN의 status가 담당).
CREATE TABLE oms_ib_order (
    oms_ib_order_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_ib_no    VARCHAR(30)    NOT NULL,
    status       VARCHAR(15)    NOT NULL,
    vendor_id    BIGINT         NOT NULL,
    expct_de     DATE           NOT NULL,
    odr_dvsn     VARCHAR(10)    DEFAULT 'NRML' NOT NULL,
    pic_nm       VARCHAR(30),
    rmk          VARCHAR(200),
    cfm_dt       TIMESTAMP,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_oms_ib_no UNIQUE (oms_ib_no),
    CONSTRAINT ck_oms_ib_order_status CHECK (status IN ('CREATED', 'CONFIRMED'))
);

COMMENT ON TABLE  oms_ib_order IS '입고주문(벤더 발주) 헤더. 확정 시 ib_order(ASN)를 생성하는 상위 원장. ASN의 생성·취소는 전적으로 여기서 주관한다';
COMMENT ON COLUMN oms_ib_order.oms_ib_no    IS '입고주문 번호 (업무 식별자, 예: PO-20260723-001). 확정 후 생기는 입고번호(IB-)와는 별개의 채번';
COMMENT ON COLUMN oms_ib_order.status       IS 'CREATED 작성 / CONFIRMED 확정(=ASN 생성됨). 확정취소하면 CREATED로 돌아와 재확정할 수 있다. 취소 상태는 두지 않는다 — 없앨 주문은 삭제한다(확정 전만)';
COMMENT ON COLUMN oms_ib_order.vendor_id    IS '납품 벤더 (vendor 참조). 확정 시 ASN이 같은 벤더를 이어받는다. 이름은 조인으로 얻는다 — 주문에 텍스트를 중복 보관하지 않는다';
COMMENT ON COLUMN oms_ib_order.expct_de     IS '입고 예정일. ASN의 입고번호 채번(IB-YYYYMMDD-NNN) 기준일이기도 하다';
COMMENT ON COLUMN oms_ib_order.odr_dvsn     IS '발주구분. 공통코드 ODR_DVSN (NRML 정상 / URGT 긴급 / RTNGS 반품입고). 지금은 표시·분류용이며 창고 작업 흐름을 바꾸지 않는다 — 긴급을 적치·피킹 우선순위에 반영하려면 그때 ASN까지 전달해야 한다';
COMMENT ON COLUMN oms_ib_order.pic_nm       IS '발주 담당자명. 감사 컬럼 created_by(로그인 계정)와는 별개다 — 인증이 없어 created_by가 admin 고정이기도 하고, 대신 발주한 경우 실제 담당자가 다를 수 있다';
COMMENT ON COLUMN oms_ib_order.rmk          IS '비고. 벤더 전달사항 등 자유 입력. 확정 시 ASN으로 넘기지 않는다 — 발주 시점의 메모라 창고 작업 지시와 성격이 다르다';
COMMENT ON COLUMN oms_ib_order.cfm_dt       IS '확정(ASN 생성) 시각. 확정취소하면 다시 NULL이 된다';

-- 입고주문 라인. 발주 수량만 보유한다 (검수/적치 진행 수량은 ASN 라인이 갖는다).
CREATE TABLE oms_ib_line (
    oms_ib_line_id  BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_ib_order_id BIGINT      NOT NULL,
    prod_id          BIGINT      NOT NULL,
    odr_qty       BIGINT      NOT NULL,
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT ck_oms_ib_line_qty CHECK (odr_qty > 0)
);

COMMENT ON TABLE  oms_ib_line IS '입고주문 라인. 확정 시 ib_line으로 1:1 복사된다 (odr_qty를 낱개(EA)로 환산 → expct_qty)';
COMMENT ON COLUMN oms_ib_line.odr_qty IS '발주 수량. <<입고단위(prod.inb_uom_cd) 기준>> — 주문 원장은 사람이 쓰는 단위를 유지한다 (출고 쪽은 oms_outb_line.odr_qty가 출고단위). ASN 생성(주문확정) 시 prod_uom.ea_qty(입고단위)를 곱해 낱개(EA)로 환산된다';

CREATE INDEX ix_oms_ib_line_order ON oms_ib_line (oms_ib_order_id);
CREATE INDEX ix_oms_ib_order_vendor ON oms_ib_order (vendor_id);


-- 출고주문(점포 수주) 헤더. 창고 작업 진행은 여기서 표현하지 않는다 (outb_order의 status가 담당).
-- 입고주문과 같은 구조다 — 다른 것은 상대가 벤더가 아니라 납품처(점포)라는 점과,
-- 확정 시 넘기는 값이 하나가 아니라 셋(납품처 · 출고유형 · 편수)이라는 점뿐이다.
CREATE TABLE oms_outb_order (
    oms_outb_order_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_outb_no  VARCHAR(30)    NOT NULL,
    status       VARCHAR(15)    NOT NULL,
    store_id     BIGINT         NOT NULL,
    outb_typ     VARCHAR(10)    DEFAULT 'NRML' NOT NULL,
    vhcl_fltno   VARCHAR(10),
    expct_de     DATE           NOT NULL,
    pic_nm       VARCHAR(30),
    rmk          VARCHAR(200),
    cfm_dt       TIMESTAMP,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_oms_outb_no UNIQUE (oms_outb_no),
    CONSTRAINT ck_oms_outb_order_status CHECK (status IN ('CREATED', 'CONFIRMED'))
);

COMMENT ON TABLE  oms_outb_order IS '출고주문(점포 수주) 헤더. 확정 시 outb_order(WMS 출고주문)를 생성하는 상위 원장. WMS 출고주문의 생성·소멸은 전적으로 여기서 주관한다';
COMMENT ON COLUMN oms_outb_order.oms_outb_no IS '출고주문 번호 (업무 식별자, 예: SO-20260803-001). 확정 후 생기는 출고번호(OB-)와는 별개의 채번';
COMMENT ON COLUMN oms_outb_order.status      IS 'CREATED 작성 / CONFIRMED 확정(=WMS 출고주문 생성됨). 확정취소하면 CREATED로 돌아와 재확정할 수 있다. 취소 상태는 두지 않는다 — 없앨 주문은 삭제한다(확정 전만)';
COMMENT ON COLUMN oms_outb_order.store_id    IS '납품처 점포 (store 참조). 확정 시 WMS 출고주문이 같은 점포를 이어받는다 — 할당 때 이 점포의 잔여수명 허용률로 Lot을 거른다. 이름은 조인으로 얻는다';
COMMENT ON COLUMN oms_outb_order.outb_typ    IS '출고유형 (공통코드 OUTB_TYP — NRML 일반출고 / RTNGS 반품출고). 확정 시 그대로 복사된다 — 웨이브 편성 조건의 기준값이라 주문 시점에 정해져야 한다. CHECK 없음 — 값 목록은 공통코드가 소유하고 존재 검증은 서비스가 한다';
COMMENT ON COLUMN oms_outb_order.vhcl_fltno  IS '차량편수 (공통코드 VHCL_FLTNO — 1편·2편…). NULL = 배차 미정. 확정 시 그대로 복사된다 — 같은 차수에 실릴 주문만 함께 묶기 위한 웨이브 편성 조건';
COMMENT ON COLUMN oms_outb_order.expct_de    IS '출고 예정일. WMS 출고주문의 출고번호 채번(OB-YYYYMMDD-NNN) 기준일이자 웨이브 편성 대상 기간의 기준이다 — 「같은 날 나갈 주문을 묶는다」가 웨이브의 정의라서다';
COMMENT ON COLUMN oms_outb_order.pic_nm      IS '수주 담당자명. 감사 컬럼 created_by(로그인 계정)와는 별개다 — 인증이 없어 created_by가 admin 고정이기도 하고, 대신 등록한 경우 실제 담당자가 다를 수 있다';
COMMENT ON COLUMN oms_outb_order.rmk         IS '비고. 점포 전달사항 등 자유 입력. 확정 시 WMS로 넘기지 않는다 — 수주 시점의 메모라 창고 작업 지시와 성격이 다르다';
COMMENT ON COLUMN oms_outb_order.cfm_dt      IS '확정(WMS 출고주문 생성) 시각. 확정취소하면 다시 NULL이 된다';

-- 출고주문 라인. 주문 수량만 보유한다 (할당/피킹 진행은 WMS 쪽이 갖는다).
CREATE TABLE oms_outb_line (
    oms_outb_line_id  BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    oms_outb_order_id BIGINT    NOT NULL,
    prod_id           BIGINT    NOT NULL,
    odr_qty           BIGINT    NOT NULL,
    created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR(30),
    CONSTRAINT ck_oms_outb_line_qty CHECK (odr_qty > 0)
);

COMMENT ON TABLE  oms_outb_line IS '출고주문 라인. 확정 시 outb_line으로 복사되며, 그때 수량만 prod_uom.ea_qty(출고단위)를 곱해 낱개(EA)로 환산된다';
COMMENT ON COLUMN oms_outb_line.odr_qty IS '주문 수량. <<출고단위(prod.outb_uom_cd) 기준>> — 주문 원장은 사람이 쓰는 단위를 유지한다 (입고 쪽은 oms_ib_line.odr_qty가 입고단위). 확정 시 prod_uom.ea_qty(출고단위)를 곱해 낱개(EA)로 환산돼 outb_line.odr_qty가 된다';

CREATE INDEX ix_oms_outb_line_order ON oms_outb_line (oms_outb_order_id);
CREATE INDEX ix_oms_outb_order_store ON oms_outb_order (store_id);


-- =====================================================================
-- 3. 입고 IB_* (SCHEDULED → RECEIVING → CONFIRMED)
--    자동 전이 없음 — 종결은 입고확정 버튼뿐 (전제: 검수분 전량 적치).
--    검수·적치의 진행 단계(적치지시/적치완료)는 저장하지 않고 수량·지시에서 파생한다.
--    취소 상태 없음 — 확정취소는 행을 삭제한다 (검수 시작 전만 가능)
-- =====================================================================

-- 입고예정(ASN) 헤더. 상태는 워크플로 단계만 표현한다 (부분입고 상태 없음).
-- OMS 입고주문 확정으로만 생성된다 (등록·취소 엔드포인트가 WMS에 없다).
CREATE TABLE ib_order (
    ib_order_id BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ib_no       VARCHAR(30)     NOT NULL,
    oms_ib_order_id BIGINT      NOT NULL,
    status      VARCHAR(15)     NOT NULL,
    vendor_id   BIGINT          NOT NULL,
    expct_de    DATE            NOT NULL,
    odr_dvsn    VARCHAR(10)     DEFAULT 'NRML' NOT NULL,
    cfm_dt      TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_ib_no UNIQUE (ib_no),
    CONSTRAINT ck_ib_order_status CHECK (status IN ('SCHEDULED', 'RECEIVING', 'CONFIRMED'))
);

COMMENT ON TABLE  ib_order IS '입고예정(ASN) 헤더. 부분입고 여부는 상태가 아니라 라인 수량(expct vs rcvd)에서 파생';
COMMENT ON COLUMN ib_order.ib_no     IS '입고 번호 (업무 식별자, 예: IB-20260714-001)';
COMMENT ON COLUMN ib_order.oms_ib_order_id IS '이 ASN을 발생시킨 입고주문. NOT NULL — 주문 없는 입고예정은 존재할 수 없다(무결성은 애플리케이션이 보증, FK 없음). JPA는 연관관계가 아닌 스칼라로 매핑한다(패키지 의존을 omsback → wmsback 한 방향으로 유지)';
COMMENT ON COLUMN ib_order.status    IS 'SCHEDULED 예정 / RECEIVING 입고중 / CONFIRMED 입고확정. 자동 전이 없음 — CONFIRMED는 입고확정 버튼만이 만든다(전제: 검수분 전량 적치). 적치지시/적치완료 등 진행 단계는 저장하지 않고 파생(IbPrgr). 취소 상태 없음 — 확정취소는 행을 삭제한다(검수 시작 전만)';
COMMENT ON COLUMN ib_order.vendor_id IS '납품 벤더 (vendor 참조). 주문에서 그대로 이어받는다 — 확정 시점의 스냅샷이 아니라 같은 마스터를 가리킨다';
COMMENT ON COLUMN ib_order.expct_de  IS '입고 예정일';
COMMENT ON COLUMN ib_order.odr_dvsn  IS '발주구분 (공통코드 ODR_DVSN: NRML/URGT/RTNGS). 확정 시 oms_ib_order.odr_dvsn에서 복사 — wmsback이 omsback을 import할 수 없어 조회 대신 복사. 적치 전략 선택의 기준';
COMMENT ON COLUMN ib_order.cfm_dt   IS '입고확정 시각 — 사람이 입고확정 버튼을 누른 시각(IbOrder.confirm만 채운다). 이 시점에 결품(예정-검수)이 못박힌다. oms_ib_order.cfm_dt(발주 확정 = ASN 생성)와는 다른 사건이다';

-- 입고 라인. 부분입고/검수/적치 진행률을 수량으로만 표현한다.
CREATE TABLE ib_line (
    ib_line_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ib_order_id BIGINT          NOT NULL,
    prod_id      BIGINT          NOT NULL,
    expct_qty   BIGINT          NOT NULL,
    rcvd_qty    BIGINT          DEFAULT 0 NOT NULL,
    ptawy_qty    BIGINT          DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT ck_ib_line_qty CHECK (
        expct_qty > 0 AND rcvd_qty >= 0
        AND ptawy_qty >= 0 AND ptawy_qty <= rcvd_qty
    )
);

COMMENT ON TABLE  ib_line IS '입고 라인. Lot은 라인이 아니라 입고 처리(재고 이력) 단위로 기록되므로 여기엔 두지 않는다';
COMMENT ON COLUMN ib_line.expct_qty IS '입고 예정 수량. 낱개(EA) 기준 — oms_ib_line.odr_qty(입고단위)에 prod_uom.ea_qty(입고단위)를 곱한 값이다. 창고의 모든 수량 컬럼이 같은 단위(EA)다';
COMMENT ON COLUMN ib_line.rcvd_qty  IS '검수(개수 확인) 완료된 실제 입고(스테이징 입) 수량 누계. 실무 검수는 개수 대조 수준이라 불합격 수량은 관리하지 않는다';
COMMENT ON COLUMN ib_line.ptawy_qty  IS '적치 완료 수량 누계 (스테이징 → 보관 MOVE 반영분)';

CREATE INDEX ix_ib_line_order ON ib_line (ib_order_id);
-- 주문 → ASN 역추적 (입고주문 관리 화면이 주문별 ASN 진행상태를 붙여 보여준다)
CREATE INDEX ix_ib_order_oms ON ib_order (oms_ib_order_id);
-- 주문 하나가 붙들 수 있는 ASN은 하나. 확정취소가 행을 삭제하므로 평범한 유니크로 충분하다
-- (예전에는 CANCELLED를 남겨 부분 유니크였다 — migration-drop-asn-cancelled.sql로 전환).
-- 동시 확정 요청 시 두 트랜잭션이 모두 CREATED를 읽고 통과하는 구간을 DB가 막는 최후 방어선.
CREATE UNIQUE INDEX uq_ib_order_oms_active ON ib_order (oms_ib_order_id);
CREATE INDEX ix_ib_order_vendor ON ib_order (vendor_id);

-- 적치 지시. 전략이 정한 배정 결과(어느 Lot을 어느 로케이션에 몇 개)를 담는다.
-- 지시 생성(전략 적용)과 지시 실행(실물 MOVE)을 분리해 지시 대비 실적을 추적한다.
-- 실적의 실체는 inv_hist의 MOVE 2행이므로 실적 테이블을 따로 두지 않고 cmpl_qty로 갈음한다.
CREATE TABLE putaway_task (
    putaway_task_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ib_line_id      BIGINT      NOT NULL,
    lot_id          BIGINT      NOT NULL,
    to_loc_id       BIGINT      NOT NULL,
    drct_qty        BIGINT      NOT NULL,
    cmpl_qty        BIGINT      DEFAULT 0 NOT NULL,
    status          VARCHAR(15) NOT NULL,
    cmpl_dt    TIMESTAMP,
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT ck_ptawy_task_status CHECK (status IN ('DIRECTED', 'DONE', 'CANCELLED')),
    -- 지시 초과 실행을 DB가 거부한다 (로케이션 적재가능수량 계산의 전제)
    CONSTRAINT ck_ptawy_task_qty CHECK (drct_qty > 0 AND cmpl_qty >= 0 AND cmpl_qty <= drct_qty)
);

COMMENT ON TABLE  putaway_task IS '적치 지시. 전략이 정한 (라인, Lot, 대상 로케이션, 수량) 배정 결과. 지시는 권고가 아니라 명령이며, 다른 로케이션에 두려면 취소 후 재지시한다';
COMMENT ON COLUMN putaway_task.ib_line_id   IS '적치 대상 입고 라인. 지시 단위가 (라인, Lot) 배치인 이유는 한 라인의 검수분이 여러 Lot에 걸칠 수 있기 때문';
COMMENT ON COLUMN putaway_task.lot_id       IS '적치 대상 Lot. 이 Lot의 스테이징 잔량이 지시 수량의 상한';
COMMENT ON COLUMN putaway_task.to_loc_id    IS '지시된 보관 로케이션. 출발지는 항상 RCV-STAGE라 컬럼으로 두지 않는다. 용량이 모자라면 한 배치가 여러 로케이션으로 1:N 분할된다';
COMMENT ON COLUMN putaway_task.drct_qty     IS '지시 수량';
COMMENT ON COLUMN putaway_task.cmpl_qty     IS '실행(실물 MOVE) 완료 수량 누계. 부분 실행 허용 — drct_qty에 도달하면 DONE';
COMMENT ON COLUMN putaway_task.status       IS 'DIRECTED 지시(부분 실행 포함) / DONE 완료 / CANCELLED 취소(cmpl_qty=0일 때만 가능)';
COMMENT ON COLUMN putaway_task.cmpl_dt IS '지시 완료 시각 (DONE 전이 시점)';

CREATE INDEX ix_ptawy_task_line ON putaway_task (ib_line_id);
-- 적재가능수량 계산: 로케이션별 미완료 지시 잔량 SUM(drct_qty - cmpl_qty).
-- 지시는 대부분 금방 DONE이 되므로 DIRECTED만 담는 부분 인덱스로 좁게 유지한다.
CREATE INDEX ix_ptawy_task_open_loc ON putaway_task (to_loc_id) WHERE status = 'DIRECTED';


-- =====================================================================
-- 4. 재고 INV*
-- =====================================================================

-- 현재고 스냅샷. 할당 시 락을 거는 지점 (비관적/낙관적 락 비교 대상).
CREATE TABLE inv (
    inv_id      BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prod_id      BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    on_hand_qty BIGINT          DEFAULT 0 NOT NULL,
    aloc_qty   BIGINT          DEFAULT 0 NOT NULL,
    hld_qty     BIGINT          DEFAULT 0 NOT NULL,
    version     BIGINT          DEFAULT 0 NOT NULL,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_inv UNIQUE (prod_id, loc_id, lot_id),
    -- 동시성 실험의 최후 방어선: 애플리케이션 락이 실패해도 DB가 음수/과할당/과보류를 거부.
    -- 예약과 보류는 배타(각각 가용에서만 잡는다)라 합산 상한 하나로 표현된다.
    CONSTRAINT ck_inv_qty CHECK (on_hand_qty >= 0 AND aloc_qty >= 0 AND hld_qty >= 0 AND aloc_qty + hld_qty <= on_hand_qty)
);

COMMENT ON TABLE  inv IS '현재고 스냅샷. 키: 상품+Loc+Lot. 재고수량(on_hand) = 가용 + 예약(aloc) + 보류(hld). 가용재고 = on_hand - aloc - hld (파생값, 컬럼 아님)';
COMMENT ON COLUMN inv.on_hand_qty IS '실물 보유 수량. 물리 변동(RECEIVE/MOVE/ADJUST/PICK 등) 시에만 증감';
COMMENT ON COLUMN inv.aloc_qty   IS '예약 수량 — 출고 할당 전용이 아니라 예약수량 일반. 출고 할당(outb_alloc)과 이동지시(inv_mov_task)가 같은 컬럼으로 선점하고, 실행(피킹/이동확정)이 on_hand와 함께 소진. 물리 이동이 아니므로 이력에 기록하지 않음. 항등식: aloc_qty = 원천별 미소진 잔량 합 (대사 대상)';
COMMENT ON COLUMN inv.hld_qty     IS '보류 수량 — 가용재고에서 뺀다(예약과 배타: 가용에서만 잡고, 예약분은 보류 불가). 물리 이동이 아니므로 이력에 기록하지 않고, 원장은 inv_hld/inv_hld_acrst/inv_hld_rlz_acrst가 담당. 항등식: hld_qty = SUM(HELD 건의 hld_qty - rlz_qty) (대사 대상)';
COMMENT ON COLUMN inv.version     IS '낙관적 락 버전 (@Version). 비관적 락과의 비교 실험 대상';

CREATE INDEX ix_inv_prod ON inv (prod_id);
CREATE INDEX ix_inv_loc ON inv (loc_id);

-- 재고 이력 (append-only 원장). 이력 합계 = 스냅샷 불변식의 근거 데이터.
CREATE TABLE inv_hist (
    inv_hist_id  BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tx_typ      VARCHAR(10)    NOT NULL,
    prod_id       BIGINT         NOT NULL,
    loc_id       BIGINT         NOT NULL,
    lot_id       BIGINT         NOT NULL,
    qty          BIGINT         NOT NULL,
    rfn_doc_typ VARCHAR(10),
    rfn_doc_no   VARCHAR(30),
    ib_line_id   BIGINT,
    from_loc_id  BIGINT,
    to_loc_id    BIGINT,
    cncl_inv_hist_id BIGINT,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT ck_invh_tx_typ CHECK (tx_typ IN ('RECEIVE', 'MOVE', 'ADJUST', 'PICK', 'SHIP')),
    CONSTRAINT ck_invh_qty CHECK (qty <> 0)
);

COMMENT ON TABLE  inv_hist IS '재고 이력 (append-only 원장). 모든 물리 변동을 ±수량으로 기록. 스냅샷과 한 트랜잭션에서 갱신. MOVE는 출발지(-)/도착지(+) 2건으로 기록';
COMMENT ON COLUMN inv_hist.tx_typ      IS 'RECEIVE 입고 / MOVE 이동(적치 포함) / ADJUST 조정 / PICK 피킹 / SHIP 출고확정';
COMMENT ON COLUMN inv_hist.qty          IS '변동 수량 (증가 +, 감소 -). 0 금지';
COMMENT ON COLUMN inv_hist.rfn_doc_typ IS '참조 문서 유형 (INBOUND / OUTBOUND / INV_MOV 이동지시 / INV_STKTK 재고조사 / LOT_CHNG 재고 로트변경 / 수동조정 시 NULL)';
COMMENT ON COLUMN inv_hist.rfn_doc_no   IS '참조 문서 번호 (입고번호/출고번호). 이력 → 원인 문서 추적용';
COMMENT ON COLUMN inv_hist.ib_line_id   IS '입고 라인 ID. RECEIVE(및 그 취소 ADJUST) 건에만 채워짐. rfn_doc_no(주문 단위)와 달리 라인 단위 역추적용 (적치 시 FEFO 소진 대상 Lot 조회, 검수 취소 대상 조회). ib_line 테이블 FK는 걸지 않는다 — ref_doc_no와 같은 느슨한 참조 컬럼';
COMMENT ON COLUMN inv_hist.from_loc_id  IS 'MOVE의 출발지. 도착지(+)/출발지(-) 두 행 모두 동일한 값을 가져서, 한 행만 봐도 상대 조인 없이 "출발지→도착지"를 알 수 있다. 재고 키/불변식은 loc_id·qty가 그대로 담당하고 이건 표시 전용. MOVE가 아니면 NULL. loc 테이블 FK는 걸지 않는다 — ib_line_id/ref_doc_no와 같은 느슨한 참조 컬럼';
COMMENT ON COLUMN inv_hist.to_loc_id    IS 'MOVE의 도착지. from_loc_id와 동일한 성격 — 표시 전용, FK 없음, MOVE가 아니면 NULL';
COMMENT ON COLUMN inv_hist.cncl_inv_hist_id IS '검수 취소(ADJUST) 건이 되돌리는 원본 RECEIVE 건의 inv_hist_id. 이게 있어야 화면이 "이미 취소된 RECEIVE"를 구분해 취소 버튼을 다시 못 누르게 막을 수 있다. FK 없음. ADJUST가 아니면 NULL';

CREATE INDEX ix_invh_prod_created ON inv_hist (prod_id, created_at);
CREATE INDEX ix_invh_rfn_doc ON inv_hist (rfn_doc_no);
CREATE INDEX ix_invh_ib_line ON inv_hist (ib_line_id);
-- 대사(reconciliation) 배치: 키별 SUM(qty) vs inv.on_hand_qty 비교용
CREATE INDEX ix_invh_inv_key ON inv_hist (prod_id, loc_id, lot_id);

-- 이동지시 (보관 ↔ 보관 2단계 이동: 지시=예약 → 확정=실물 MOVE).
-- 등록 시 FROM 재고의 aloc_qty를 선점하고, 확정이 inv_hist MOVE 2행을 남기며 예약을 소진한다.
-- 실적 테이블은 따로 없다 — 실적의 실체는 inv_hist의 MOVE 2행이고, 분할확정은 확정 횟수만큼
-- 2행이 쌓이는 것이다 (putaway_task가 지시/실적 분리를 접은 것과 같은 판단).
CREATE TABLE inv_mov_task (
    inv_mov_task_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_mov_no      VARCHAR(30) NOT NULL,
    mov_dvsn        VARCHAR(10) NOT NULL,
    prod_id         BIGINT      NOT NULL,
    lot_id          BIGINT      NOT NULL,
    from_loc_id     BIGINT      NOT NULL,
    to_loc_id       BIGINT      NOT NULL,
    drct_qty        BIGINT      NOT NULL,
    cmpl_qty        BIGINT      DEFAULT 0 NOT NULL,
    status          VARCHAR(15) NOT NULL,
    cmpl_dt         TIMESTAMP,
    created_at      TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by      VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at      TIMESTAMP,
    updated_by      VARCHAR(30),
    CONSTRAINT uq_inv_mov_no UNIQUE (inv_mov_no),
    CONSTRAINT ck_inv_mov_dvsn CHECK (mov_dvsn IN ('INV_MOV', 'PTAWY', 'PIKNG')),
    CONSTRAINT ck_inv_mov_status CHECK (status IN ('DIRECTED', 'DONE', 'CANCELLED')),
    -- 지시 초과 확정을 DB가 거부한다 (putaway_task의 ck_ptawy_task_qty와 같은 방어)
    CONSTRAINT ck_inv_mov_qty CHECK (drct_qty > 0 AND cmpl_qty >= 0 AND cmpl_qty <= drct_qty),
    CONSTRAINT ck_inv_mov_loc CHECK (from_loc_id <> to_loc_id)
);

COMMENT ON TABLE  inv_mov_task IS '이동지시 (보관↔보관 2단계: 지시=예약 → 확정=실물 MOVE). 지시는 권고가 아니라 명령 — 지시 TO와 다른 로케이션으로 확정할 수 없고, 다른 곳에 두려면 잔량 취소 후 재지시한다. 실적은 별도 테이블 없이 inv_hist의 MOVE 2행(rfn_doc_no = inv_mov_no)';
COMMENT ON COLUMN inv_mov_task.inv_mov_no  IS '이동지시 번호 (건당 유일 — 라인 구조 없음). inv_hist 실적이 rfn_doc_no만으로 지시와 정확히 매칭되게 하는 전제. nbr_rule INV_MOV_NO 채번';
COMMENT ON COLUMN inv_mov_task.mov_dvsn    IS '이동구분 — INV_MOV 재고이동 / PTAWY 적치 / PIKNG 피킹. 재고이동 화면의 등록은 INV_MOV 고정이고, 그 화면의 확정·취소도 INV_MOV만 허용한다(적치·피킹 유형은 각자의 화면 경로 전용). 적치는 별도 putaway_task 유지로 확정(FROM이 항상 스테이징이라 컬럼이 남고, ib_line_id 같은 입고 전용 컬럼이 이 테이블로 새어 나온다). 피킹 지시는 구현 시 결정';
COMMENT ON COLUMN inv_mov_task.prod_id     IS '이동 대상 상품. Lot이 상품을 함의하지만 재고 키(상품+Loc+Lot) 그대로 담아 단독 조회를 가능하게 한다 (inv_hist와 같은 형태)';
COMMENT ON COLUMN inv_mov_task.from_loc_id IS '출발 보관 로케이션. 등록 시 이 로케이션 재고의 aloc_qty를 잔여수량만큼 선점(예약)한다';
COMMENT ON COLUMN inv_mov_task.to_loc_id   IS '도착 보관 로케이션. 온도대 일치 + 적재가능수량(max_qty − 현재고 − 미완료 지시 유입 잔량) 검증 대상';
COMMENT ON COLUMN inv_mov_task.drct_qty    IS '지시 수량. 부분확정 후 잔량 취소 시 완료수량으로 차감된다';
COMMENT ON COLUMN inv_mov_task.cmpl_qty    IS '확정(실물 MOVE) 완료 수량 누계. 부분확정 허용 — drct_qty에 도달하면 DONE';
COMMENT ON COLUMN inv_mov_task.status      IS 'DIRECTED 지시(부분확정 포함) / DONE 완료 / CANCELLED 취소(cmpl_qty=0 전량 취소 시. 부분확정 후 잔량 취소는 drct_qty 차감 후 DONE). 「진행」 같은 부분 상태는 두지 않는다 — 진행도는 수량 파생';
COMMENT ON COLUMN inv_mov_task.cmpl_dt     IS '지시 완료 시각 (DONE 전이 시점)';

CREATE INDEX ix_inv_mov_prod ON inv_mov_task (prod_id);
-- 적재가능수량 계산: TO 로케이션별 미완료 지시 유입 잔량 SUM(drct_qty - cmpl_qty).
-- putaway_task의 ix_ptawy_task_open_loc와 같은 이유로 DIRECTED만 담는 부분 인덱스.
CREATE INDEX ix_inv_mov_open_to ON inv_mov_task (to_loc_id) WHERE status = 'DIRECTED';

-- 재고 보류 (수량 방식: 등록이 inv.hld_qty를 늘려 가용재고에서 뺀다. 재고상태 컬럼 없음).
-- 보류/해제는 물리 이동이 아니라 inv_hist(수량 원장)에 실을 수 없는데 등록·해제 각각의
-- 사유 히스토리를 보존해야 하므로, 「물리 변동 실적 테이블 없음」 원칙의 유일한 예외로
-- 전용 실적 테이블 2벌(inv_hld_acrst / inv_hld_rlz_acrst)을 둔다.
-- v1 보류 대상은 보관(STORAGE) 로케이션 재고만 — 스테이징 허용은 적치·출고확정 파급을 수반.
CREATE TABLE inv_hld (
    inv_hld_id  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hld_no      VARCHAR(30)     NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    hld_qty     BIGINT          NOT NULL,
    rlz_qty     BIGINT          DEFAULT 0 NOT NULL,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    status      VARCHAR(15)     NOT NULL,
    rlz_dt      TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_inv_hld_no UNIQUE (hld_no),
    CONSTRAINT ck_inv_hld_status CHECK (status IN ('HELD', 'RELEASED')),
    -- 과해제를 DB가 거부한다 (inv_mov_task의 ck_inv_mov_qty와 같은 방어)
    CONSTRAINT ck_inv_hld_qty CHECK (hld_qty > 0 AND rlz_qty >= 0 AND rlz_qty <= hld_qty)
);

COMMENT ON TABLE  inv_hld IS '재고 보류 건. 등록 즉시 발효(지시→확정 2단계 아님) — inv.hld_qty 증가와 한 트랜잭션. 잔량 = hld_qty - rlz_qty 파생. 전량 해제돼도 행 보존(RELEASED 전이) — putaway_task 선례. 항등식: inv.hld_qty = SUM(HELD 건의 잔량)';
COMMENT ON COLUMN inv_hld.hld_no   IS '보류 번호 (건당 유일 — 라인 구조 없음). nbr_rule HLD_NO 채번';
COMMENT ON COLUMN inv_hld.prod_id  IS '보류 대상 상품. 재고 키(상품+Loc+Lot) 그대로 담는다 (inv_mov_task와 같은 형태)';
COMMENT ON COLUMN inv_hld.hld_qty  IS '보류 수량. 등록 시점 가용재고(on_hand - aloc - hld) 이내 — 예약분은 보류 불가(배타)';
COMMENT ON COLUMN inv_hld.rlz_qty  IS '해제 완료 수량 누계. 부분 해제 허용 — hld_qty에 도달하면 RELEASED';
COMMENT ON COLUMN inv_hld.rsn_cd   IS '보류 사유 코드 (공통코드 HLD_RSN). ETC(기타)일 때만 rsn_dscr 필수';
COMMENT ON COLUMN inv_hld.rsn_dscr IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';
COMMENT ON COLUMN inv_hld.status   IS 'HELD 보류중(부분 해제 포함) / RELEASED 전량 해제. 취소 상태 없음 — 오등록도 해제(사유: 오등록)로 흡수한다(등록 즉시 발효라 실행 전 취소 구간이 없다)';
COMMENT ON COLUMN inv_hld.rlz_dt   IS '전량 해제 시각 (RELEASED 전이 시점)';

-- 항등식 대사(재고 키별 HELD 잔량 SUM vs inv.hld_qty) + 재고 행의 미해제 보류 조회.
-- 유니크가 아니다 — 같은 재고 행에는 사유가 같든 다르든 미해제 보류가 여러 건 병존한다.
CREATE INDEX ix_inv_hld_open ON inv_hld (prod_id, loc_id, lot_id) WHERE status = 'HELD';
-- 상태를 가리지 않는 상품별 조회 (위 부분 인덱스는 HELD만 담아 대신하지 못한다)
CREATE INDEX ix_inv_hld_prod ON inv_hld (prod_id);

-- 보류 실적 (등록의 append-only 로그). 보류 건과 1:1이지만 자기완결로 둔다 —
-- 건이 갱신(해제누계·상태 전이)돼도 등록 시점의 기록이 그대로 보존된다. 실적 시각 = created_at.
CREATE TABLE inv_hld_acrst (
    inv_hld_acrst_id BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hld_no      VARCHAR(30)     NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    hld_qty     BIGINT          NOT NULL,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT ck_inv_hld_acrst_qty CHECK (hld_qty > 0)
);

COMMENT ON TABLE  inv_hld_acrst IS '보류 실적 (등록 append-only 로그). 수정·삭제하지 않는다. hld_no는 inv_hld를 느슨하게 참조 (FK 없음)';

CREATE INDEX ix_inv_hld_acrst_no ON inv_hld_acrst (hld_no);

-- 해제 실적 (해제의 append-only 로그). 부분 해제가 N번이면 N행. 해제 사유는 등록 사유와
-- 별개의 코드 그룹(HLD_RLZ_RSN)이다 — 「왜 묶었나」와 「왜 풀었나」는 다른 질문이다.
CREATE TABLE inv_hld_rlz_acrst (
    inv_hld_rlz_acrst_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hld_no      VARCHAR(30)     NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    rlz_qty     BIGINT          NOT NULL,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT ck_inv_hld_rlz_acrst_qty CHECK (rlz_qty > 0)
);

COMMENT ON TABLE  inv_hld_rlz_acrst IS '보류 해제 실적 (append-only 로그). 해제는 특정 보류 건(hld_no)을 지목하며 부분 해제 허용 — N번 해제면 N행. rsn_cd는 공통코드 HLD_RLZ_RSN, ETC일 때만 rsn_dscr 필수';

CREATE INDEX ix_inv_hld_rlz_acrst_no ON inv_hld_rlz_acrst (hld_no);

-- 재고조사(실사). 조사 범위를 잡아 라인을 만들고(전산수량 스냅샷), 실사수량을 입력한 뒤
-- 확정 시점에 차이를 ADJUST로 보정한다. 건별 수동 조정 화면을 따로 두지 않는다 —
-- 특정 재고 하나의 정정도 범위를 좁게 잡은 조사로 수행한다(입고 확정 후 수량 정정 포함).
-- 실적 테이블은 없다 — 실적의 실체는 inv_hist의 ADJUST 행(rfn_doc_no = 조사번호)이다
-- (inv_mov_task와 같은 판단. 보류만이 「실적 테이블 없음」의 예외다).
CREATE TABLE inv_stktk (
    inv_stktk_id BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stktk_no    VARCHAR(30)     NOT NULL,
    zon_cd      VARCHAR(20),
    loc_id      BIGINT,
    prod_id     BIGINT,
    status      VARCHAR(15)     NOT NULL,
    cfm_dt      TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_inv_stktk_no UNIQUE (stktk_no),
    CONSTRAINT ck_inv_stktk_status CHECK (status IN ('CREATED', 'CONFIRMED', 'CANCELLED'))
);

COMMENT ON TABLE  inv_stktk IS '재고조사(실사) 헤더. 상태는 워크플로 단계만(작성 → 확정) — 「부분확정」은 두지 않는다. 확정 후 재정정은 조사를 되열지 않고 새 조사를 만든다(append-only). 확정이 남기는 것은 inv_hist의 ADJUST 행(rfn_doc_typ=INV_STKTK, rfn_doc_no=stktk_no)';
COMMENT ON COLUMN inv_stktk.stktk_no IS '재고조사 번호 (건당 유일 — 라인은 inv_stktk_ln). nbr_rule STKTK_NO 채번. inv_hist.rfn_doc_no로 실려 조사 ↔ 조정 이력이 매칭된다';
COMMENT ON COLUMN inv_stktk.zon_cd   IS '조사 범위 — 존 코드. NULL이면 존 조건 없음. 라인 생성에 쓴 조건을 그대로 보존해 「무엇을 조사했나」를 남긴다';
COMMENT ON COLUMN inv_stktk.loc_id   IS '조사 범위 — 로케이션. NULL이면 로케이션 조건 없음. 범위 3필드가 모두 NULL이면 전 보관 로케이션 조사';
COMMENT ON COLUMN inv_stktk.prod_id  IS '조사 범위 — 상품. NULL이면 상품 조건 없음';
COMMENT ON COLUMN inv_stktk.status   IS 'CREATED 작성(실사수량 입력 중) / CONFIRMED 확정(ADJUST 반영 완료) / CANCELLED 취소(확정 전 폐기 — 라인 보존, putaway_task 선례)';
COMMENT ON COLUMN inv_stktk.cfm_dt   IS '확정 시각 (CONFIRMED 전이 시점)';

CREATE INDEX ix_inv_stktk_status ON inv_stktk (status);

-- 재고조사 라인. 재고 키(상품+Loc+Lot) 단위로 전산수량과 실사수량을 나란히 든다.
-- 조정수량(차이)은 stktk_qty - cfm_sys_qty 파생이라 컬럼을 두지 않는다.
CREATE TABLE inv_stktk_ln (
    inv_stktk_ln_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_stktk_id BIGINT         NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    lot_id      BIGINT          NOT NULL,
    sys_qty     BIGINT          NOT NULL,
    stktk_qty   BIGINT,
    cfm_sys_qty BIGINT,
    rsn_cd      VARCHAR(10),
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    -- 한 조사 안에서 같은 재고를 두 번 세지 않는다 (서비스 검증이 아니라 DB가 막는다)
    CONSTRAINT uq_inv_stktk_ln UNIQUE (inv_stktk_id, prod_id, loc_id, lot_id),
    CONSTRAINT ck_inv_stktk_ln_qty CHECK (
        sys_qty >= 0
        AND (stktk_qty IS NULL OR stktk_qty >= 0)
        AND (cfm_sys_qty IS NULL OR cfm_sys_qty >= 0)
    )
);

COMMENT ON TABLE  inv_stktk_ln IS '재고조사 라인. 재고 키 단위. 조정수량 = stktk_qty - cfm_sys_qty (파생, 컬럼 아님). 실사수량 미입력(NULL) 라인은 「미조사」로 확정에서 건너뛴다 — 0(실물 없음)과 구분된다';
COMMENT ON COLUMN inv_stktk_ln.sys_qty     IS '조사 생성 시점의 전산수량 스냅샷 (on_hand_qty). 조정 계산의 기준이 아니라 「조사 시작 때는 얼마였나」의 기록 — 확정 기준은 cfm_sys_qty다';
COMMENT ON COLUMN inv_stktk_ln.stktk_qty   IS '실사수량 (실물을 센 값). NULL = 미조사(확정 시 건너뜀), 0 = 실물 없음(전량 차감). 낱개(EA) 기준';
COMMENT ON COLUMN inv_stktk_ln.cfm_sys_qty IS '확정 시점에 재고 행 락을 걸고 다시 읽은 전산수량(= 조정전수량). 조정수량 = stktk_qty - cfm_sys_qty이므로 확정 후 on_hand_qty는 실사수량과 정확히 일치한다. 조사 중 다른 업무로 재고가 변해도 실사값이 이긴다 (2026-08-03 결정 — 확정시점 기준). 확정 전에는 NULL';
COMMENT ON COLUMN inv_stktk_ln.rsn_cd      IS '조정사유 코드 (공통코드 ADJ_RSN). 차이가 0이 아닌 라인만 필수 — 차이 0 라인은 ADJUST 자체가 없으므로 사유도 없다. ETC(기타)일 때만 rsn_dscr 필수';
COMMENT ON COLUMN inv_stktk_ln.rsn_dscr    IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';

CREATE INDEX ix_inv_stktk_ln_stktk ON inv_stktk_ln (inv_stktk_id);
CREATE INDEX ix_inv_stktk_ln_prod ON inv_stktk_ln (prod_id);

-- Lot 속성 정정 이력 (재고 속성변경 화면). 대상은 lot 행이라 INV* 접두를 쓰지 않지만,
-- 이 정정을 수행하는 업무가 재고 화면군이라 재고 절에 둔다 (Lot 생성이 검수의 소관인 것과 같은 갈래).
-- 이 화면은 재고를 한 톨도 움직이지 않는다 — inv·inv_hist 모두 무변경이고, 정정의 원장은 이 테이블 하나다.
-- 채번하지 않는다: 어디서도 참조되지 않는 append-only 로그라 문서번호가 필요 없다
-- (보류의 hld_no는 해제가 지목해야 해서, 조사의 stktk_no는 inv_hist.rfn_doc_no가 물어서 있는 것이다).
CREATE TABLE lot_attr_chng (
    lot_attr_chng_id BIGINT     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_id      BIGINT          NOT NULL,
    prod_id     BIGINT          NOT NULL,
    lot_no      VARCHAR(30)     NOT NULL,
    bfr_mfg_dt  DATE,
    aft_mfg_dt  DATE,
    bfr_expiry_dt DATE,
    aft_expiry_dt DATE,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    -- 변동 0 금지. ck_invh_qty(수량 변동 0 금지)와 같은 성격의 최후 방어 —
    -- 두 필드가 모두 그대로인 「정정」은 로그만 늘린다.
    CONSTRAINT ck_lot_attr_chng_diff CHECK (
        bfr_mfg_dt IS DISTINCT FROM aft_mfg_dt OR bfr_expiry_dt IS DISTINCT FROM aft_expiry_dt
    ),
    CONSTRAINT ck_lot_attr_chng_dt CHECK (
        aft_mfg_dt IS NULL OR aft_expiry_dt IS NULL OR aft_expiry_dt >= aft_mfg_dt
    )
);

COMMENT ON TABLE  lot_attr_chng IS 'Lot 속성 정정 이력 (append-only 자기완결 로그). 재고 속성변경 화면이 남기는 유일한 원장 — 수량 변동이 없어 inv_hist에 실을 수 없다(보류 실적 테이블과 같은 예외 성격). 변경 이벤트당 1행이고 바뀌지 않은 필드도 전/후에 같은 값이 들어간다. 되돌리는 정정도 새 행이다(취소 경로 없음)';
COMMENT ON COLUMN lot_attr_chng.lot_id        IS '정정 대상 Lot. lot 테이블 FK는 걸지 않는다 — inv_hist.ib_line_id와 같은 느슨한 참조';
COMMENT ON COLUMN lot_attr_chng.prod_id       IS '대상 Lot의 상품. Lot이 상품을 함의하지만 단독 조회를 가능하게 담는다 (inv_hld·inv_mov_task와 같은 형태)';
COMMENT ON COLUMN lot_attr_chng.lot_no        IS 'Lot 번호 스냅샷. lot_no는 정정 대상이 아니라 지금은 lot과 항상 같지만, 로그를 자기완결로 두는 원칙(보류 실적 선례)을 따른다';
COMMENT ON COLUMN lot_attr_chng.bfr_mfg_dt    IS '제조일자 변경 전 값. 배치 재사용 키(상품+입고일자+제조일자)의 일부라 정정 시 다른 Lot과의 키 충돌을 서비스가 막는다 — uq_lot은 (prod_id, lot_no)에만 걸려 DB가 잡아주지 않는다';
COMMENT ON COLUMN lot_attr_chng.aft_mfg_dt    IS '제조일자 변경 후 값. mfg_dt <= lot.receipt_dt 검증 대상 (검수의 「제조일자가 입고일자보다 미래일 수 없다」와 같은 규칙)';
COMMENT ON COLUMN lot_attr_chng.bfr_expiry_dt IS '유통기한 변경 전 값';
COMMENT ON COLUMN lot_attr_chng.aft_expiry_dt IS '유통기한 변경 후 값. 제조일자+shelf_life_days와 일치할 필요는 없다 — 벤더 인쇄값과 계산값이 다른 것이 이 화면의 주 사용처다. 정정 즉시 FEFO 정렬과 점포 잔여수명 필터에 반영되지만 이미 생성된 할당은 건드리지 않는다';
COMMENT ON COLUMN lot_attr_chng.rsn_cd        IS '정정 사유 코드 (공통코드 LOT_ATTR_RSN). ETC(기타)일 때만 rsn_dscr 필수';
COMMENT ON COLUMN lot_attr_chng.rsn_dscr      IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';

CREATE INDEX ix_lot_attr_chng_lot ON lot_attr_chng (lot_id);
CREATE INDEX ix_lot_attr_chng_prod_created ON lot_attr_chng (prod_id, created_at);

-- 재고 로트변경 (수량을 지정한 Lot 속성정정) 원장. lot_attr_chng(전량·무이동 정정)와 별개 테이블 —
-- 그쪽은 「한 Lot의 변경 전/후」(bfr_*/aft_*)이고 여기는 「두 Lot 사이」(from_*/to_*)라 모양이 다르고
-- (로트변경에서 원 Lot의 속성은 바뀌지 않는다), 무채번(그쪽) vs 채번 필수(여기)로 정책도 정면 충돌한다.
-- 재고 실체는 inv_hist의 ADJUST 2행(원 Lot −N / 새 Lot +N, rfn_doc_typ=LOT_CHNG, rfn_doc_no=lot_chng_no) —
-- 「이력 합계 = 스냅샷」 불변식은 Lot별로 그대로 유지된다. 이 테이블은 조작 단위의 자기완결 로그다(보류 실적 선례).
-- 대상은 보관(STORAGE) 로케이션의 유통기한 관리 상품 재고만 — 스테이징은 적치 잔량 집계(ib_line_id 기반)가
-- 깨져 제외한다(적치 전 제조일자 오류는 검수 취소 후 재검수가 정답).
CREATE TABLE inv_lot_chng (
    inv_lot_chng_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lot_chng_no VARCHAR(30)     NOT NULL,
    prod_id     BIGINT          NOT NULL,
    loc_id      BIGINT          NOT NULL,
    from_lot_id BIGINT          NOT NULL,
    from_lot_no VARCHAR(30)     NOT NULL,
    from_mfg_dt DATE            NOT NULL,
    from_expiry_dt DATE         NOT NULL,
    to_lot_id   BIGINT          NOT NULL,
    to_lot_no   VARCHAR(30)     NOT NULL,
    to_mfg_dt   DATE            NOT NULL,
    to_expiry_dt DATE           NOT NULL,
    chng_qty    BIGINT          NOT NULL,
    to_lot_new_yn BOOLEAN       DEFAULT FALSE NOT NULL,
    rsn_cd      VARCHAR(10)     NOT NULL,
    rsn_dscr    VARCHAR(200),
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_inv_lot_chng_no UNIQUE (lot_chng_no),
    CONSTRAINT ck_inv_lot_chng_qty CHECK (chng_qty >= 1),
    -- 같은 Lot으로의 「변경」 금지 — 제조일자가 같으면 목적지 = 원 Lot이라 조작 자체가 무의미하다
    CONSTRAINT ck_inv_lot_chng_lot CHECK (from_lot_id <> to_lot_id),
    -- 날짜 4컬럼이 NOT NULL이라(대상이 관리 상품뿐) lot_attr_chng의 null 분기 없이 곧장 비교한다
    CONSTRAINT ck_inv_lot_chng_dt  CHECK (to_expiry_dt >= to_mfg_dt)
);

COMMENT ON TABLE  inv_lot_chng IS '재고 로트변경 원장 (append-only 자기완결 로그). 「이 로케이션의 이 재고 중 N개는 제조일자가 X였다」 — 원 Lot에서 N개를 빼 (상품+입고일자+X) 배치의 Lot으로 넣는다(그 키의 Lot이 있으면 병합, 없으면 채번=분할). 취소 경로 없음 — 되돌리는 것도 새 로트변경 1건. 재고 실체는 inv_hist의 ADJUST 2행(rfn_doc_typ=LOT_CHNG, rfn_doc_no=lot_chng_no)';
COMMENT ON COLUMN inv_lot_chng.lot_chng_no    IS '로트변경 번호 (건당 유일 — 라인 구조 없음). nbr_rule LOT_CHNG_NO 채번. inv_hist.rfn_doc_no로 실려 실적 ↔ 이력이 매칭된다 — lot_attr_chng가 무채번인 것과 갈리는 지점(그쪽은 아무도 참조하지 않는 로그다)';
COMMENT ON COLUMN inv_lot_chng.prod_id        IS '대상 상품. 재고 키(상품+Loc+Lot) 그대로 담는다 (inv_hld·inv_mov_task와 같은 형태)';
COMMENT ON COLUMN inv_lot_chng.loc_id         IS '대상 보관 로케이션. 로케이션은 바뀌지 않는다 — 같은 로케이션 안에서 Lot만 바뀌는 장부 이동이라 inv_hist의 from/to_loc_id도 NULL';
COMMENT ON COLUMN inv_lot_chng.from_lot_id    IS '원 Lot. lot 테이블 FK는 걸지 않는다 — lot_attr_chng.lot_id와 같은 느슨한 참조';
COMMENT ON COLUMN inv_lot_chng.from_lot_no    IS '원 Lot 번호 스냅샷 — 자기완결 로그 원칙 (lot_attr_chng.lot_no·보류 실적 선례)';
COMMENT ON COLUMN inv_lot_chng.from_mfg_dt    IS '원 Lot 제조일자 스냅샷. NOT NULL — 대상이 유통기한 관리 상품뿐이라 값이 항상 있다 (lot_attr_chng이 nullable로 둔 것을 따르지 않는 이유: 새 테이블에서 같은 느슨함을 복제할 이유가 없다)';
COMMENT ON COLUMN inv_lot_chng.from_expiry_dt IS '원 Lot 유통기한 스냅샷';
COMMENT ON COLUMN inv_lot_chng.to_lot_id      IS '목적지 Lot — (원 Lot의 상품+입고일자, 요청 제조일자) 배치 키의 findOrCreate 결과. 있으면 재사용(병합), 없으면 채번(분할) — 배치 키 충돌이 구조적으로 없다';
COMMENT ON COLUMN inv_lot_chng.to_lot_no      IS '목적지 Lot 번호 스냅샷. 새 번호가 발생하므로 현품 라벨은 재출력 대상 — 라벨을 유지해야 하는 정정은 기존 재고 속성변경(전량)이 맡는다';
COMMENT ON COLUMN inv_lot_chng.to_mfg_dt      IS '정정된 제조일자. 원 Lot과 반드시 다르다(같으면 목적지 = 원 Lot이라 무의미 — 서비스 검증) — 그래서 목적지 배치 키가 원 Lot과 언제나 다르다';
COMMENT ON COLUMN inv_lot_chng.to_expiry_dt   IS '정정된 유통기한 — 화면 입력값(벤더 인쇄값 정정이 주 사용처, 계산 강제 없음). 목적지 Lot이 기존이고 그 유통기한이 이 값과 다르면 거부한다(작업자 입력과 다른 값의 조용한 저장 금지)';
COMMENT ON COLUMN inv_lot_chng.chng_qty       IS '변경 수량. 원 재고 행의 가용수량(on_hand - aloc - hld) 이내 — 예약(outb_alloc·inv_mov_task)·보류(inv_hld)가 가리키는 재고를 침범할 수 없다';
COMMENT ON COLUMN inv_lot_chng.to_lot_new_yn  IS '목적지 Lot을 이번에 채번했는가 — true 분할(새 Lot) / false 병합(기존 Lot 합류). 실적 조회에서 둘을 구분할 유일한 근거';
COMMENT ON COLUMN inv_lot_chng.rsn_cd         IS '변경 사유 코드 (공통코드 LOT_ATTR_RSN 재사용 — 사유 성격이 속성 정정과 같다). ETC(기타)일 때만 rsn_dscr 필수';
COMMENT ON COLUMN inv_lot_chng.rsn_dscr       IS '기타 사유 텍스트. rsn_cd = ETC일 때만 사용';

CREATE INDEX ix_inv_lot_chng_from_lot     ON inv_lot_chng (from_lot_id);
CREATE INDEX ix_inv_lot_chng_prod_created ON inv_lot_chng (prod_id, created_at);


-- =====================================================================
-- 5. 출고 OUTB_* (CREATED → ALLOCATED → PICKING → PICKED → SHIPPED)
--    취소 상태 없음 — 확정취소(OMS 출고주문)가 행을 삭제한다 (웨이브 편성 전만). ASN과 같은 방식
--    할당은 웨이브를 대상으로 실행하되 계산·결과는 출고주문 라인 단위다 (outb_alloc).
--    웨이브 상태는 할당으로 바뀌지 않는다 — 「릴리즈(=웨이브가 할당 상태를 갖는 것)」는 없다.
--    피킹/확정도 주문 단위.
--    물리 재고는 2단계: PICK(보관→SHIP-STAGE) → SHIP(SHIP-STAGE 반출). 입고의 거울상.
-- =====================================================================

-- 출고 웨이브. 피킹지시의 발행 단위이자 할당의 실행 단위 (동시성 실험의 경합 지점).
CREATE TABLE outb_wave (
    outb_wave_id BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wav_no      VARCHAR(30)    NOT NULL,
    status       VARCHAR(15)    NOT NULL,
    issued_dt    TIMESTAMP,
    wav_stgy_id  BIGINT,
    rvsn_no      BIGINT,
    created_at   TIMESTAMP      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)    DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_wav_no UNIQUE (wav_no),
    CONSTRAINT ck_outb_wave_status CHECK (status IN ('PLANNED', 'ISSUED')),
    -- 전략 컬럼은 전략이 실제로 실행해 만든 행에만 채운다 — "전략 id 있음 = 전략이 실행함"이 성립해야 한다
    CONSTRAINT ck_outb_wave_stgy CHECK ((wav_stgy_id IS NULL) = (rvsn_no IS NULL))
);

COMMENT ON TABLE  outb_wave IS '출고 웨이브. 피킹지시의 발행 단위 — 여러 주문의 집품을 한 번에 지시하기 위한 그룹. 발행 이후 진행(피킹/확정)은 주문 단위라 웨이브는 여기서 역할이 끝난다. 할당도 이 단위로 실행하지만(2026-08-03 번복 — 피킹지시가 웨이브 단위라 할당만 주문 단위면 흐름 중간에서 단위가 어긋난다) 계산·결과는 라인 단위이고 웨이브 상태는 할당으로 바뀌지 않는다';
COMMENT ON COLUMN outb_wave.wav_no     IS '웨이브 번호 (업무 식별자, 예: WV-20260718-001)';
COMMENT ON COLUMN outb_wave.status      IS 'PLANNED 편성중(주문 담기 가능) / ISSUED 피킹지시 발행 완료. RELEASED를 쓰지 않는 것은 inv_hld의 RELEASED(보류 해제)와 한 토큰이 두 뜻이 되기 때문';
COMMENT ON COLUMN outb_wave.issued_dt   IS '피킹지시 발행 시각. 미발행이면 NULL';
COMMENT ON COLUMN outb_wave.wav_stgy_id IS '이 웨이브를 만든 웨이브 전략 (느슨한 참조, FK 없음). NULL = 화면에서 수동 생성';
COMMENT ON COLUMN outb_wave.rvsn_no     IS '생성에 사용된 전략 리비전. stgy_rvsn과 조합해 "그때의 조건"을 재구성한다 (P5)';

-- 출고 주문 헤더. 부분할당 여부는 상태가 아니라 라인/할당 수량에서 파생.
-- OMS 출고주문 확정으로만 생성된다 (등록·취소 엔드포인트가 WMS에 없다 — ASN과 같은 구조).
CREATE TABLE outb_order (
    outb_order_id BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outb_no     VARCHAR(30)     NOT NULL,
    oms_outb_order_id BIGINT    NOT NULL,
    status      VARCHAR(15)     NOT NULL,
    outb_typ    VARCHAR(10)     DEFAULT 'NRML' NOT NULL,
    vhcl_fltno  VARCHAR(10),
    store_id    BIGINT          NOT NULL,
    wav_id     BIGINT,
    wav_reg_typ VARCHAR(10),
    odr_de    DATE            NOT NULL,
    expct_de  DATE            NOT NULL,
    shmt_dt  TIMESTAMP,
    created_at  TIMESTAMP       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  VARCHAR(30)     DEFAULT 'admin' NOT NULL,
    updated_at  TIMESTAMP,
    updated_by  VARCHAR(30),
    CONSTRAINT uq_outb_no UNIQUE (outb_no),
    CONSTRAINT ck_outb_order_status CHECK (status IN ('CREATED', 'ALLOCATED', 'PICKING', 'PICKED', 'SHIPPED')),
    -- 편성 출처는 편성돼 있을 때만 존재한다. 편성 해제·주문 취소는 wav_id와 함께 이 컬럼도 비워야 한다
    CONSTRAINT ck_outb_order_wav_reg CHECK (
        (wav_id IS NULL AND wav_reg_typ IS NULL)
        OR (wav_id IS NOT NULL AND wav_reg_typ IN ('STGY', 'MANUAL'))
    )
);

COMMENT ON TABLE  outb_order IS '출고 주문 헤더 (B2B 점포 출고). OMS 출고주문 확정으로만 생성되고 확정취소로만 삭제된다. 피킹 시작 이후 취소는 v1 미지원';
COMMENT ON COLUMN outb_order.outb_no  IS '출고 번호 (업무 식별자, 예: OB-20260714-001)';
COMMENT ON COLUMN outb_order.oms_outb_order_id IS '이 출고주문을 발생시킨 OMS 출고주문. NOT NULL — 주문 없는 창고 출고주문은 존재할 수 없다(무결성은 애플리케이션이 보증, FK 없음). JPA는 연관관계가 아닌 스칼라로 매핑한다(패키지 의존을 omsback → wmsback 한 방향으로 유지)';
COMMENT ON COLUMN outb_order.status   IS 'CREATED 생성 / ALLOCATED 할당 / PICKING 피킹중 / PICKED 피킹완료 / SHIPPED 출고확정. 취소 상태 없음 — 없앨 주문은 OMS 확정취소가 행을 삭제한다(웨이브 편성 전만). 같은 「없앤다」를 두 조작이 다르게 처리하던 겹침을 정리한 것이다 — migration-drop-outb-cancelled.sql';
COMMENT ON COLUMN outb_order.outb_typ   IS '출고유형 (공통코드 OUTB_TYP — NRML 일반출고 / RTNGS 반품출고). 웨이브 편성 조건의 기준값. CHECK 없음 — 값 목록은 공통코드가 소유하고 존재 검증은 서비스가 한다';
COMMENT ON COLUMN outb_order.vhcl_fltno IS '차량편수 (공통코드 VHCL_FLTNO — 1편·2편…). NULL = 배차 미정. 같은 차수에 실릴 주문만 함께 묶기 위한 웨이브 편성 조건';
COMMENT ON COLUMN outb_order.store_id IS '출고처 점포. 할당 시 이 점포의 잔여수명 허용률로 Lot 필터';
COMMENT ON COLUMN outb_order.wav_id  IS '편성된 출고 웨이브. NULL = 아직 미편성. 주문은 웨이브에 편성돼야 피킹지시를 받는다(주문 1건짜리 웨이브도 허용)';
COMMENT ON COLUMN outb_order.wav_reg_typ IS '웨이브 편입 출처. STGY 전략 실행 / MANUAL 화면 수동 편성. NULL = 미편성. 수동 편성을 금지하지 않고 가시화한다 — 전략 조건과 안 맞는 주문이 웨이브에 있는 상황을 화면이 구분 표시';
COMMENT ON COLUMN outb_order.odr_de IS '주문일 = 상위 OMS 출고주문이 등록된 날. 확정 시 복사되며 이후 바뀌지 않는다 — 「언제 들어온 주문인가」를 보는 값이다';
COMMENT ON COLUMN outb_order.expct_de IS '출고 예정일. 출고번호 채번(OB-YYYYMMDD-NNN) 기준일이자 웨이브 편성 대상 기간의 기준이다 — 웨이브는 「같은 날 나갈 주문」을 묶는 단위라 주문일이 아니라 이쪽을 본다';

CREATE INDEX ix_outb_order_wav ON outb_order (wav_id);
-- 주문 → WMS 출고주문 역추적 (출고주문 관리 화면이 주문별 창고 진행상태를 붙여 보여준다)
CREATE INDEX ix_outb_order_oms ON outb_order (oms_outb_order_id);
-- 주문 하나가 붙들 수 있는 WMS 출고주문은 하나. 확정취소가 행을 삭제하므로 평범한 유니크로 충분하다.
-- 동시 확정 요청 시 두 트랜잭션이 모두 CREATED를 읽고 통과하는 구간을 DB가 막는 최후 방어선
-- (ib_order의 uq_ib_order_oms_active와 같은 역할).
CREATE UNIQUE INDEX uq_outb_order_oms ON outb_order (oms_outb_order_id);

-- 출고 라인. 주문 수량만 보유하고, 할당/피킹 진행은 outb_alloc에서 집계 파생.
CREATE TABLE outb_line (
    outb_line_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outb_order_id BIGINT        NOT NULL,
    prod_id        BIGINT        NOT NULL,
    odr_qty     BIGINT        NOT NULL,
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    VARCHAR(30)   DEFAULT 'admin' NOT NULL,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(30),
    CONSTRAINT ck_outb_line_qty CHECK (odr_qty > 0)
);

COMMENT ON TABLE  outb_line IS '출고 주문 라인. 할당/피킹 수량은 컬럼으로 두지 않고 outb_alloc 집계로 파생 (수량-상태 불일치 원천 차단)';
COMMENT ON COLUMN outb_line.odr_qty IS '주문 수량. 낱개(EA) 기준 — oms_outb_line.odr_qty(출고단위)에 prod_uom.ea_qty(출고단위)를 곱한 값이다. 창고의 모든 수량 컬럼이 같은 단위(EA)다 (입고 쪽 대응은 ib_line.expct_qty)';

CREATE INDEX ix_outb_line_order ON outb_line (outb_order_id);

-- 할당. 주문라인 ↔ 재고(상품+Loc+Lot) 매핑. FEFO(+ 납품기한 필터) 결과가 기록된다.
CREATE TABLE outb_alloc (
    outb_alloc_id BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outb_line_id  BIGINT        NOT NULL,
    inv_id        BIGINT        NOT NULL,
    aloc_qty     BIGINT        NOT NULL,
    pikng_qty    BIGINT        DEFAULT 0 NOT NULL,
    -- 이 할당을 만든 전략·리비전. 전략이 실제로 실행해 만든 행에만 채운다 —
    -- 수동할당분에까지 채우면 "전략 id 있음 ≠ 전략 실행됨"이 되어 추적이 무의미해진다
    aloc_stgy_id  BIGINT,
    rvsn_no       BIGINT,
    created_at    TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    VARCHAR(30)   DEFAULT 'admin' NOT NULL,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(30),
    CONSTRAINT ck_aloc_qty CHECK (aloc_qty > 0 AND pikng_qty >= 0 AND pikng_qty <= aloc_qty),
    CONSTRAINT ck_outb_alloc_stgy CHECK ((aloc_stgy_id IS NULL) = (rvsn_no IS NULL))
);

COMMENT ON TABLE  outb_alloc IS '재고 할당 레코드. 어떤 주문라인이 어떤 재고(상품+Loc+Lot)를 몇 개 예약했는지. 할당 취소 시 삭제 + inv.aloc_qty 복원';
COMMENT ON COLUMN outb_alloc.aloc_qty  IS '할당 수량 (부분할당 허용: 라인 order_qty보다 합계가 작을 수 있음)';
COMMENT ON COLUMN outb_alloc.aloc_stgy_id IS '이 할당을 만든 할당 전략 (느슨한 참조, FK 없음). NULL = 수동할당 또는 전략 미설정 기간의 기본 동작 할당. 같은 (라인,재고)에 합산될 때는 처음 값을 유지한다 — 나중 실행의 전략으로 덮어쓰면 이미 기록된 수량의 근거가 바뀐다';
COMMENT ON COLUMN outb_alloc.rvsn_no      IS '할당에 사용된 전략 리비전. stgy_rvsn과 조합해 "그때의 정의"를 재구성한다 (P5)';
COMMENT ON COLUMN outb_alloc.pikng_qty IS '피킹 완료 수량. 피킹 리스트는 outb_alloc을 loc.pikng_prty 순으로 정렬한 뷰. 피킹 시 보관→SHIP-STAGE MOVE(tx PICK)와 함께 누적되고, 이때 보관 inv.alloc_qty도 소진된다(실물 반출)';

CREATE INDEX ix_alloc_line ON outb_alloc (outb_line_id);
CREATE INDEX ix_alloc_inv ON outb_alloc (inv_id);


-- =====================================================================
-- 6. 전략 STGY_* / INSP_* / PTAWY_* / WAV_* / ALOC_*  (관리자 정의 실행 정책)
--    - 로직·선택지·필드매핑은 코드 레지스트리가 소유하고, DB는 "무엇을 선택했고
--      파라미터가 무엇인가"만 저장한다. rule_cd/mthd_cd에 CHECK를 걸지 않는 이유 —
--      구현체 추가 시 DDL을 고치지 않기 위함이고, 존재 검증은 저장 서비스가 한다
--      (공통코드 성격 컬럼과 같은 방식). 전략 선택지를 code_detail에 넣지 않는다.
--    - 사용여부 컬럼 없음 (전 테이블 공통 원칙 유지 — D4). 실행 제외 = 물리삭제,
--      복원 근거 = stgy_rvsn 스냅샷.
--    - 파라미터·조건 목록은 JSONB — 저장 시 서비스가 ParamSpec/필드 레지스트리로
--      검증해 통과분만 담는다 (FK 0건과 같은 "검증은 애플리케이션" 철학).
--    - 웨이브(wav_stgy)는 2차에서 추가됐다. 할당 테이블(ALOC_*)은 3차.
-- =====================================================================

-- 전략 리비전. 저장(생성·수정·복원)마다 정의 전체를 스냅샷으로 남기는 append-only 이력.
-- 실행 기록(stgy_exec_log)의 rvsn_no와 조합해 "그때의 정의"를 재구성한다.
CREATE TABLE stgy_rvsn (
    stgy_rvsn_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_typ     VARCHAR(10)  NOT NULL,
    stgy_id      BIGINT       NOT NULL,
    rvsn_no      BIGINT       NOT NULL,
    snpsht       JSONB        NOT NULL,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT uq_stgy_rvsn UNIQUE (stgy_typ, stgy_id, rvsn_no),
    -- 유형은 구조적 enum이다 (status 류와 같은 취급). WAV·ALOC은 2차 선반영
    CONSTRAINT ck_stgy_rvsn_typ CHECK (stgy_typ IN ('INSP', 'PTAWY', 'WAV', 'ALOC')),
    CONSTRAINT ck_stgy_rvsn_no CHECK (rvsn_no >= 1)
);

COMMENT ON TABLE  stgy_rvsn IS '전략 리비전 스냅샷 (append-only). 전략 저장마다 1행 — created_*가 곧 저장 시각/저장자. 전략이 삭제돼도 남아 복원·감사의 근거가 된다';
COMMENT ON COLUMN stgy_rvsn.stgy_typ IS 'INSP 검수 / PTAWY 적치 (2차: WAV 웨이브 / ALOC 할당)';
COMMENT ON COLUMN stgy_rvsn.stgy_id  IS '유형별 헤더 PK (insp_plcy_id 또는 ptawy_stgy_id). FK 없음 — 원본 삭제 후에도 남는 느슨한 참조';
COMMENT ON COLUMN stgy_rvsn.rvsn_no  IS '전략별 1부터 증가. 헤더 행 잠금 하에 last_rvsn_no+1로 부여, uq_stgy_rvsn이 최후 방어선';
COMMENT ON COLUMN stgy_rvsn.snpsht   IS '정의 전체(헤더+하위 구성)의 JSON 직렬화. 직렬화 형태의 주인은 저장 서비스이고, 읽을 때도 같은 DTO로 역직렬화한다';

-- 전략 실행 로그. 실행·미리보기의 결과 요약 + 건별 판정 근거(dcsn_trc).
-- 검수는 결과 행이 없는 유형(산출물 = 차단 예외)이라 이 로그가 유일한 실행 흔적이다.
CREATE TABLE stgy_exec_log (
    stgy_exec_log_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_typ         VARCHAR(10) NOT NULL,
    stgy_id          BIGINT      NOT NULL,
    rvsn_no          BIGINT      NOT NULL,
    trgr_typ         VARCHAR(10) NOT NULL,
    tgt_ref          VARCHAR(30),
    rslt_smry        VARCHAR(200),
    dcsn_trc         JSONB,
    created_at       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by       VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at       TIMESTAMP,
    updated_by       VARCHAR(30),
    CONSTRAINT ck_stgy_exec_log_typ  CHECK (stgy_typ IN ('INSP', 'PTAWY', 'WAV', 'ALOC')),
    CONSTRAINT ck_stgy_exec_log_trgr CHECK (trgr_typ IN ('MANUAL', 'AUTO', 'PREVIEW'))
);

COMMENT ON TABLE  stgy_exec_log IS '전략 실행 로그. 검수 위반(=검수 저장 롤백) 시에도 남아야 하므로 기록은 REQUIRES_NEW 별도 트랜잭션. created_at = 실행 시각';
COMMENT ON COLUMN stgy_exec_log.rvsn_no  IS '실행에 사용된 리비전. stgy_rvsn과 조합해 판정 당시의 정의를 재구성한다';
COMMENT ON COLUMN stgy_exec_log.trgr_typ IS 'MANUAL 화면 조작 / AUTO 자동 실행(2차 웨이브용 선반영) / PREVIEW 결과를 반영하지 않은 산정 — 적치 일괄 추천만 기록한다(지시 생성 경로가 산정을 다시 돌리지 않아 근거가 거기밖에 없다). 조회 기본값은 MANUAL·AUTO';
COMMENT ON COLUMN stgy_exec_log.tgt_ref  IS '대상 문서 번호 (입고번호 IB-…). 가상 입력 미리보기는 NULL. inv_hist.rfn_doc_no와 같은 느슨한 참조 — 새 컬럼이라 ref 표기(사전 결정)';
COMMENT ON COLUMN stgy_exec_log.rslt_smry IS '사람용 한 줄 요약. 예: "라인 3건 중 위반 1건"';
COMMENT ON COLUMN stgy_exec_log.dcsn_trc IS '건별 판정 상세(라인×규칙 / 단계×후보). 관리 화면의 "왜 차단/배정됐나" 표의 원본이고, 구조는 판정 결과 DTO가 정의한다';

CREATE INDEX ix_stgy_exec_log_stgy ON stgy_exec_log (stgy_typ, stgy_id, created_at);
CREATE INDEX ix_stgy_exec_log_ref  ON stgy_exec_log (tgt_ref);

-- 검수 정책 헤더. 시스템 전역 1행 — DB 강제 없이 서비스가 검증한다 (D8).
-- prty가 없다: 검수는 "선택되는" 전략이 아니라 규칙 전부가 AND 실행되는 유형이라,
-- 선택 순서 컬럼이 있으면 스키마가 거짓말을 하게 된다 ("여러 개 만들면 하나가 골라진다"는 오해를 부른다).
CREATE TABLE insp_plcy (
    insp_plcy_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_nm      VARCHAR(100) NOT NULL,
    last_rvsn_no BIGINT       DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30)
);

COMMENT ON TABLE  insp_plcy IS '검수 정책 헤더 (전역 1행 — 서비스 검증). 검수 저장 직전 규칙 전부를 AND 평가, 위반 시 저장 전체 거부';
COMMENT ON COLUMN insp_plcy.stgy_nm      IS '정책명. 표시용 — 실행에 사용하지 않는다 (이름/동작 불일치는 미리보기가 보완)';
COMMENT ON COLUMN insp_plcy.last_rvsn_no IS '마지막 저장 리비전 (stgy_rvsn.rvsn_no 최신값)';

-- 검수 규칙. 정책 1개 + 규칙 N개 — 실제 실행 의미(전부 AND)와 구조가 일치하는 모델.
CREATE TABLE insp_plcy_rule (
    insp_plcy_rule_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insp_plcy_id      BIGINT      NOT NULL,
    srt_seq           INTEGER     DEFAULT 0 NOT NULL,
    rule_cd           VARCHAR(30) NOT NULL,
    para              JSONB       DEFAULT '{}' NOT NULL,
    created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR(30),
    -- AND 실행이라 같은 규칙 2건은 더 엄격한 쪽 1건과 동일 — 의미 없는 중복을 DB가 거부
    CONSTRAINT uq_insp_plcy_rule UNIQUE (insp_plcy_id, rule_cd)
);

COMMENT ON TABLE  insp_plcy_rule IS '검수 규칙. 규칙 끄기 = 행 삭제 (D4 — 사용여부 컬럼 없음). 삭제 전 구성은 정책 리비전 스냅샷이 보유';
COMMENT ON COLUMN insp_plcy_rule.insp_plcy_id IS '소속 정책. FK 없음 — 정책 삭제 시 규칙 정리는 서비스(cascade)가 한다';
COMMENT ON COLUMN insp_plcy_rule.srt_seq IS '평가·표시 순서. 전 규칙이 실행되므로 결과에는 영향 없고 위반 목록 정렬에 쓰인다';
COMMENT ON COLUMN insp_plcy_rule.rule_cd IS '코드 레지스트리의 규칙 code (1차: LOT_DATE_REVERSE 역순제한 / SHELF_LIFE_PCT 유통기한 잔여비율). CHECK 없음 — 값 목록의 주인은 코드 레지스트리';
COMMENT ON COLUMN insp_plcy_rule.para    IS '규칙 파라미터. 저장 시 ParamSpec으로 검증된 값만 담는다. 예: {"minPercent": 30}, {"excludeSameDay": true}';

CREATE INDEX ix_insp_plcy_rule ON insp_plcy_rule (insp_plcy_id);

-- 적치 전략 헤더. 적치 추천 시 발주구분(odr_dvsn) 일치 전략 → 전체(NULL) 전략 순으로 선택 — 유형당 1개라 우선순위 컬럼이 없다.
-- 분할정책은 unt_splt_yn 하나만 둔다 — MAX 미설정 문제는 ck_loc_storage_capacity가,
-- 점유 계산 방식은 loc.max_qty 주석의 불변식이 이미 해결하기 때문이다.
CREATE TABLE ptawy_stgy (
    ptawy_stgy_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_nm       VARCHAR(100) NOT NULL,
    odr_dvsn      VARCHAR(10),
    unt_splt_yn   BOOLEAN      DEFAULT FALSE NOT NULL,
    loc_srt       JSONB        DEFAULT '[]' NOT NULL,
    last_rvsn_no  BIGINT       DEFAULT 1 NOT NULL,
    created_at    TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(30),
    CONSTRAINT ck_ptawy_stgy_loc_srt  CHECK (jsonb_typeof(loc_srt) = 'array')
);

-- 유형당 전략 1개 (전체 = odr_dvsn NULL도 1개). 이 UNIQUE가 우선순위 컬럼을 대체한다 —
-- 선택 규칙이 "유형 일치 → 전체 → 수동 폴백"으로 숫자 없이 결정적이다.
CREATE UNIQUE INDEX ux_ptawy_stgy_odr_dvsn ON ptawy_stgy (COALESCE(odr_dvsn, 'ALL'));

COMMENT ON TABLE  ptawy_stgy IS '적치 전략 헤더. 선택 기준은 발주구분 하나(유형당 1개 — ux_ptawy_stgy_odr_dvsn). 1차에서 전략은 추천만 한다 — 실행은 기존 즉시 MOVE 흐름 유지';
COMMENT ON COLUMN ptawy_stgy.stgy_nm     IS '전략명. 표시용 — 실행에 사용하지 않는다';
COMMENT ON COLUMN ptawy_stgy.odr_dvsn    IS '적용대상 발주구분 (공통코드 ODR_DVSN — NRML/URGT). NULL = 전체. 반품(RTNGS)은 스코프 아웃이라 저장 검증이 거부한다';
COMMENT ON COLUMN ptawy_stgy.unt_splt_yn IS '입수 단위 배수 절사. 입수 = ea_qty(입고단위) — 재고가 낱개(EA)라 입고단위 낱개수량이 곧 배수다. true면 로케이션별 배정수량을 입수 배수로 내림(낱개 혼적 방지), 몫 0인 로케이션은 스킵';
COMMENT ON COLUMN ptawy_stgy.loc_srt     IS '후보 정렬 [{"field":PIKNG_PRTY|PTAWY_PRTY|LOC_CD,"dir":ASC|DESC}]. 빈 배열 = 기본(피킹순위 ASC → 로케이션코드 ASC)';
COMMENT ON COLUMN ptawy_stgy.last_rvsn_no IS '마지막 저장 리비전';

-- 적치 단계. "적치위치 × 추천방식"의 조합을 관리자가 순서를 직접 배열하는 단계 목록으로 표현한다 —
-- 표현력 손실 없이(조합은 단계를 그만큼 나열) 실행 순서가 화면에 그대로 보인다.
CREATE TABLE ptawy_stgy_stg (
    ptawy_stgy_stg_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ptawy_stgy_id     BIGINT      NOT NULL,
    srt_seq           INTEGER     NOT NULL,
    mthd_cd           VARCHAR(30) NOT NULL,
    mthd_para         JSONB       DEFAULT '{}' NOT NULL,
    line_cond         JSONB       DEFAULT '[]' NOT NULL,
    loc_cond          JSONB       DEFAULT '[]' NOT NULL,
    created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR(30),
    CONSTRAINT ck_ptawy_stg_line_cond CHECK (jsonb_typeof(line_cond) = 'array'),
    CONSTRAINT ck_ptawy_stg_loc_cond  CHECK (jsonb_typeof(loc_cond)  = 'array')
);

COMMENT ON TABLE  ptawy_stgy_stg IS '적치 단계. srt_seq 순으로 시도, 잔여수량이 0이 되면 종료. "단계 0건 전략" 저장 거부는 서비스 검증(자식 행 존재는 CHECK 범위 밖)';
COMMENT ON COLUMN ptawy_stgy_stg.ptawy_stgy_id IS '소속 전략. FK 없음 — 삭제 연쇄는 서비스가 수행';
COMMENT ON COLUMN ptawy_stgy_stg.srt_seq   IS '실행 순서 (화면 drag&drop 순서 그대로)';
COMMENT ON COLUMN ptawy_stgy_stg.mthd_cd   IS '추천 방식 code (1차: SAME_PROD_LOC 적재 / EMPTY_LOC 빈 / ANY_LOC 전체 보관). 고정로케이션 방식은 고정상품 마스터가 없어 제외. CHECK 없음 — PutawayMethod enum이 소유';
COMMENT ON COLUMN ptawy_stgy_stg.mthd_para IS '방식 파라미터 (1차 방식들은 빈 객체 — 확장 대비)';
COMMENT ON COLUMN ptawy_stgy_stg.line_cond IS '조건 — 이 조건일 때만 이 단계를 적용 [{fld,op,vals}]. 빈 배열 = 항상 시도';
COMMENT ON COLUMN ptawy_stgy_stg.loc_cond  IS '적치위치 지정 — 존 업무유형 IN 최대 1건 [{"fld":"BIZ_DVSN","op":"IN","vals":[...]}]. 조건이 아니라 적용기준값(여기에 둔다). 빈 배열 = 전체 보관 로케이션. 온도대 일치 + STORAGE는 불변 전제라 저장하지 않는다';

CREATE INDEX ix_ptawy_stgy_stg ON ptawy_stgy_stg (ptawy_stgy_id);

-- 웨이브 전략. 미편성 출고 주문을 조건으로 걸러 웨이브에 편입하는 규칙 — 도메인이 테이블 1개로 끝난다.
-- 조건그룹은 개별 파라미터도 활성 플래그도 없이 항상 헤더와 통째로 저장되므로 하위 테이블이 아니라 JSONB다
-- (편집 단위 = 저장 단위 기준).
CREATE TABLE wav_stgy (
    wav_stgy_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_nm      VARCHAR(100) NOT NULL,
    prty         INTEGER      DEFAULT 0 NOT NULL,
    cond_grp     JSONB        NOT NULL,
    last_rvsn_no BIGINT       DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT ck_wav_stgy_prty CHECK (prty >= 0),
    -- 조건 0건 전략은 모든 주문을 쓸어담는다. 실행 시점이 아니라 저장 시점에 막는다.
    -- 그룹 안이 빈 배열인 경우([[]])는 CHECK로 표현할 수 없어 저장 서비스가 거부한다
    CONSTRAINT ck_wav_stgy_cond_grp CHECK (
        jsonb_typeof(cond_grp) = 'array' AND jsonb_array_length(cond_grp) > 0
    )
);

COMMENT ON TABLE  wav_stgy IS '웨이브 전략. 실행 시 전략마다 웨이브를 1개 만들고 조건에 맞는 미편성 주문을 편입한다. 적치와 달리 "적용대상 1개 선택"이 아니라 전 전략을 prty 순으로 순회하는 유형이라 우선순위 컬럼이 있다';
COMMENT ON COLUMN wav_stgy.stgy_nm      IS '전략명. 표시용 — 실행에 사용하지 않는다 (이름/조건 불일치는 미리보기가 보완)';
COMMENT ON COLUMN wav_stgy.prty         IS '실행 순서. 낮을수록 먼저 — 주문은 먼저 실행된 전략이 선점한다(한 주문은 웨이브 1개). 동률은 wav_stgy_id 순으로 결정적이게 처리';
COMMENT ON COLUMN wav_stgy.cond_grp     IS '조건그룹 [[{fld,op,vals},…],…]. 그룹끼리 OR, 그룹 안 AND. 필드: WaveOrderField enum — OUTB_TYP 출고유형 · VHCL_FLTNO 차량편수 (둘 다 값 목록의 주인은 공통코드다)';
COMMENT ON COLUMN wav_stgy.last_rvsn_no IS '마지막 저장 리비전';


-- 할당 전략. 자동할당의 "어느 재고를, 어떤 순서로, 모자라면 누구에게"를 슬롯 단위로 정의한다.
-- 다른 세 유형과 다른 점: 할당에는 이미 코드에 박힌 기본 동작(FEFO + 점포 잔여수명 + 순차 소진)이
-- 있어서, 전략은 없던 판단을 만드는 게 아니라 그 기본값을 슬롯 단위로 덮어쓴다.
-- 그래서 필수 슬롯이 없고, 전략이 0건이면 기존 동작이 그대로 유지된다.
CREATE TABLE aloc_stgy (
    aloc_stgy_id BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stgy_nm      VARCHAR(100) NOT NULL,
    prty         INTEGER      DEFAULT 0 NOT NULL,
    tgt_cond     JSONB        DEFAULT '[]' NOT NULL,
    last_rvsn_no BIGINT       DEFAULT 1 NOT NULL,
    created_at   TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by   VARCHAR(30)  DEFAULT 'admin' NOT NULL,
    updated_at   TIMESTAMP,
    updated_by   VARCHAR(30),
    CONSTRAINT ck_aloc_stgy_prty     CHECK (prty >= 0),
    -- 웨이브(cond_grp)와 달리 길이 CHECK가 없다 — 할당의 조건 0건은 사고가 아니라
    -- "어느 전략도 매칭되지 않을 때 무엇을 쓸지"를 뜻하는 전체 매칭 폴백 전략이다
    CONSTRAINT ck_aloc_stgy_tgt_cond CHECK (jsonb_typeof(tgt_cond) = 'array')
);

COMMENT ON TABLE  aloc_stgy IS '할당 전략. 자동할당이 어느 재고를 어떤 순서로 쓰고 모자라면 어떻게 나눌지를 정한다. 전략은 코드의 기본 동작을 슬롯 단위로 덮어쓰므로 필수 슬롯이 없고, 전략 0건이면 기본 동작(FEFO·점포 잔여수명·순차 소진)이 그대로 실행된다';
COMMENT ON COLUMN aloc_stgy.stgy_nm      IS '전략명. 표시용 — 실행에 사용하지 않는다 (이름/정의 불일치는 미리보기가 보완)';
COMMENT ON COLUMN aloc_stgy.prty         IS '선택 순서. 낮을수록 먼저 매칭 판정 — 실행 1회당 전략 1건이 확정된다. 동률은 aloc_stgy_id 순';
COMMENT ON COLUMN aloc_stgy.tgt_cond     IS '적용대상 조건 [{fld,op,vals},…]. 원소끼리 AND, 빈 배열 = 전체 매칭 폴백. 대상 주문 "전부"가 만족해야 매칭이다. 필드: AlocTgtField enum — OUTB_TYP 출고유형 · VHCL_FLTNO 차량편수 (점포는 없다 — 한 웨이브에 여러 점포가 섞이는 것이 정상이라 전부-만족이 성립하지 않는다)';
COMMENT ON COLUMN aloc_stgy.last_rvsn_no IS '마지막 저장 리비전';


-- 할당 슬롯. 적치 단계와 같은 판단으로 JSONB가 아니라 행이다 —
-- 개별로 추가·삭제·순서변경(drag&drop)하고 자기 파라미터·조건을 갖는 편집 단위이기 때문.
CREATE TABLE aloc_stgy_slot (
    aloc_stgy_slot_id BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aloc_stgy_id      BIGINT      NOT NULL,
    slot_typ          VARCHAR(15) NOT NULL,
    srt_seq           INTEGER     DEFAULT 0 NOT NULL,
    cmpnt_cd          VARCHAR(30),
    para              JSONB       DEFAULT '{}' NOT NULL,
    cond              JSONB       DEFAULT '[]' NOT NULL,
    created_at        TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by        VARCHAR(30) DEFAULT 'admin' NOT NULL,
    updated_at        TIMESTAMP,
    updated_by        VARCHAR(30),
    CONSTRAINT ck_aloc_slot_typ CHECK (
        slot_typ IN ('INVN_FLTR','RSTRCT','INVN_SRT','ODR_SRT','DSTRB')
    ),
    -- 구현체 축이 있는 슬롯은 RSTRCT·DSTRB뿐이다. 필터 슬롯은 "무엇을 실행할지"가 아니라
    -- "어느 후보만"을 정하므로 정의 전체가 cond이고, 정렬 슬롯은 "기준을 순서대로 나열"
    -- 하나뿐이라 para.criteria가 정의 전부다 — 둘 다 고를 구현체가 없다.
    CONSTRAINT ck_aloc_slot_cmpnt CHECK (
        (slot_typ IN ('INVN_FLTR','INVN_SRT','ODR_SRT') AND cmpnt_cd IS NULL)
     OR (slot_typ IN ('RSTRCT','DSTRB')                 AND cmpnt_cd IS NOT NULL)
    ),
    CONSTRAINT ck_aloc_slot_srt_seq CHECK (srt_seq >= 0),
    CONSTRAINT ck_aloc_slot_para    CHECK (jsonb_typeof(para) = 'object'),
    CONSTRAINT ck_aloc_slot_cond    CHECK (jsonb_typeof(cond) = 'array')
);

CREATE INDEX ix_aloc_stgy_slot ON aloc_stgy_slot (aloc_stgy_id);
-- 단일 슬롯에 2건 등록을 DB가 거부한다. 다중 슬롯(INVN_FLTR·RSTRCT·DSTRB)은 대상이 아니다 —
-- 계층·순서를 표현하는 것이 그 슬롯들의 존재 이유이기 때문.
CREATE UNIQUE INDEX uq_aloc_stgy_slot_single ON aloc_stgy_slot (aloc_stgy_id, slot_typ)
    WHERE slot_typ IN ('INVN_SRT','ODR_SRT');

COMMENT ON TABLE  aloc_stgy_slot IS '할당 슬롯. 할당이 하는 일을 역할로 쪼갠 5종 — INVN_FLTR 재고위치(다중=계층) · RSTRCT 출고제약(다중) · INVN_SRT 재고정렬(단일) · ODR_SRT 주문순서(단일) · DSTRB 분배(다중=실행순서)';
COMMENT ON COLUMN aloc_stgy_slot.aloc_stgy_id IS '할당 전략 헤더 (느슨한 참조, FK 없음)';
COMMENT ON COLUMN aloc_stgy_slot.slot_typ     IS '슬롯 타입. 값 목록이 코드 구조 그 자체(AlocSlotTyp enum)라 공통코드가 아니라 CHECK로 고정한다 — status류와 같은 취급';
COMMENT ON COLUMN aloc_stgy_slot.srt_seq      IS '다중 슬롯 안의 순서. INVN_FLTR은 후보 계층 순서(앞 계층부터 소진), DSTRB는 분배 실행 순서. 단일 슬롯에서는 무의미';
COMMENT ON COLUMN aloc_stgy_slot.cmpnt_cd     IS '구현체 code (enum name — SHELF_LIFE_PCT · SEQUENTIAL · RATIO · EQUAL). CHECK 없음: 구현체 추가로 DDL을 고치지 않기 위함이고 존재 검증은 저장 서비스가 한다. 구현체 축이 없는 INVN_FLTR·INVN_SRT·ODR_SRT는 NULL';
COMMENT ON COLUMN aloc_stgy_slot.para         IS '슬롯 파라미터. 정렬 슬롯(INVN_SRT·ODR_SRT)은 {"criteria":[{"field","dir"},…]}, SHELF_LIFE_PCT는 {"basis":"STORE"} 또는 {"basis":"FIXED","minPct":40}';
COMMENT ON COLUMN aloc_stgy_slot.cond         IS '조건 [{fld,op,vals},…] — 원소끼리 AND. INVN_FLTR은 계층 지정(존 업무유형 IN), DSTRB는 배분 대상 선별. 정렬·제약 슬롯은 쓰지 않는다. 마지막 DSTRB 슬롯의 조건이 비어 있어야 하는 검증은 저장 서비스 몫 — 조건 있는 슬롯으로 끝나면 어느 조건에도 안 걸린 라인이 재고를 두고도 0을 받는다';
